// AUTO-GENERATED by gruntz.analysis.gen_attributed_stubs - do not hand-edit.
// Proximity-attributed class memberships (static RVA bracketing, ~91% exact;
// see docs/tu-spatial-structure.md): each `<Class>_<rva>()` is a __thiscall
// method attributed to <Class>, defined as an RVA stub in src/Stub/Attributed.cpp.
// Minimal decls; real classes are fully modelled in their own TUs (separate
// translation unit, so this is conflict-free).
#ifndef GRUNTZ_STUB_ATTRIBUTED_H
#define GRUNTZ_STUB_ATTRIBUTED_H

class CNetMgr {
public:
    void CNetMgr_0b86c0();
    void CNetMgr_0b8fc0();
    void CNetMgr_0bbc90();
    void CNetMgr_0bbec0();
    void CNetMgr_0bbf80();
    void CNetMgr_0bc750();
    void CNetMgr_0bccd0();
};
class CTriggerMgr {
public:
    void CTriggerMgr_07abc0();
};
class CBattlezSpawnMgr_or_CGruntSpawnMgr {
public:
    void UnknownClassArrays_02b950();
};
class istream {
public:
    void istream_16a490();
};
class streambuf {
public:
    void streambuf_16b340();
    void streambuf_16b360();
};
class strstreambuf {
public:
    void strstreambuf_1692c0();
    void strstreambuf_1693f0();
    void strstreambuf_169400();
};

#endif
