// AUTO-GENERATED by gruntz.analysis.gen_attributed_stubs - do not hand-edit.
// Proximity-attributed class memberships (static RVA bracketing, ~91% exact;
// see docs/tu-spatial-structure.md): each `<Class>_<rva>()` is a __thiscall
// method attributed to <Class>, defined as an RVA stub in src/Stub/Attributed.cpp.
// Minimal decls; real classes are fully modelled in their own TUs (separate
// translation unit, so this is conflict-free).
#ifndef GRUNTZ_STUB_ATTRIBUTED_H
#define GRUNTZ_STUB_ATTRIBUTED_H

class CAttract { public: void CAttract_014520(); void CAttract_014630(); };
class CBattlezDlg { public: void CBattlezDlg_014c90(); void CBattlezDlg_015de0(); void CBattlezDlg_015e60(); void CBattlezDlg_015ee0(); void CBattlezDlg_015f60(); void CBattlezDlg_016410(); void CBattlezDlg_016500(); void CBattlezDlg_017140(); void CBattlezDlg_017340(); };
class CBehindCandyAni { public: void CBehindCandyAni_0ad7d0(); void CBehindCandyAni_0ad9b0(); };
class CBootyState { public: void CBootyState_01ce30(); void CBootyState_01d420(); };
class CButeMgrHelper { public: void CButeMgrHelper_1697e0(); void CButeMgrHelper_1699a0(); void CButeMgrHelper_1699e0(); void CButeMgrHelper_169bc0(); void CButeMgrHelper_169d10(); };
class CChatBox { public: void CChatBox_1831d0(); void CChatBox_1831f0(); };
class CChatBoxOwner { public: void CChatBoxOwner_0205c0(); void CChatBoxOwner_020ef0(); };
class CCreditsState { public: void CCreditsState_0393b0(); };
class CDDPalette { public: void CDDPalette_147410(); void CDDPalette_147590(); void CDDPalette_147710(); void CDDPalette_147840(); void CDDPalette_1478c0(); void CDDPalette_147aa0(); void CDDPalette_147c80(); };
class CDDSurface { public: void CDDSurface_13e9a0(); };
class CDDrawShadeBlit { public: void CDDrawShadeBlit_149950(); void CDDrawShadeBlit_149d00(); void CDDrawShadeBlit_14b770(); };
class CDDrawSubMgrAni { public: void CDDrawSubMgrAni_1529b0(); };
class CDDrawSubMgrLeaf { public: void CDDrawSubMgrLeaf_152660(); };
class CDDrawSubMgrLeafScan { public: void CDDrawSubMgrLeafScan_157e00(); void CDDrawSubMgrLeafScan_1580b0(); void CDDrawSubMgrLeafScan_158210(); void CDDrawSubMgrLeafScan_1584a0(); };
class CDDrawSurfaceMgr { public: void CDDrawSurfaceMgr_156530(); };
class CDDrawSurfacePair { public: void CDDrawSurfacePair_163f00(); };
class CDDrawWorkerB { public: void CDDrawWorkerB_1572b0(); };
class CDDrawWorkerMgr { public: void CDDrawWorkerMgr_158b90(); void CDDrawWorkerMgr_158bc0(); void CDDrawWorkerMgr_158bf0(); void CDDrawWorkerMgr_158cb0(); void CDDrawWorkerMgr_158d50(); };
class CDDrawWorkerRegistry { public: void CDDrawWorkerRegistry_155460(); };
class CDataBuffer { public: void CDataBuffer_1501f0(); void CDataBuffer_150250(); void CDataBuffer_150330(); };
class CFaderMgr { public: void CFaderMgr_17d980(); void CFaderMgr_17e160(); };
class CFileImage { public: void CFileImage_13ebb0(); void CFileImage_141280(); void CFileImage_1443b0(); void CFileImage_144900(); void CFileImage_144b30(); void CFileImage_144d80(); };
class CFileMem { public: void CFileMem_165f00(); };
class CFontConfig { public: void CFontConfig_021e20(); void CFontConfig_021ef0(); void CFontConfig_0220f0(); };
class CGameApp { public: void CGameApp_13dbc0(); };
class CGameLevel { public: void CGameLevel_15ff20(); void CGameLevel_15ffe0(); void CGameLevel_160980(); void CGameLevel_160a40(); };
class CGameObject { public: void CGameObject_150f90(); void CGameObject_151070(); };
class CGrunt { public: void CGrunt_051c00(); void CGrunt_05b050(); void CGrunt_05b570(); void CGrunt_061940(); void CGrunt_061bc0(); void CGrunt_062b70(); void CGrunt_067b00(); void CGrunt_0692f0(); void CGrunt_069fd0(); };
class CGruntHealthSprite { public: void CGruntHealthSprite_07ecf0(); void CGruntHealthSprite_07eed0(); };
class CGruntPowerupSprite { public: void CGruntPowerupSprite_07ffa0(); void CGruntPowerupSprite_080180(); };
class CGruntSelectedSprite { public: void CGruntSelectedSprite_07e5e0(); void CGruntSelectedSprite_07e7c0(); };
class CGruntSpawnConfig { public: void CGruntSpawnConfig_11c7f0(); };
class CGruntToySprite { public: void CGruntToySprite_07f540(); void CGruntToySprite_07f720(); };
class CGruntVoice { public: void CGruntVoice_119dc0(); };
class CGruntzCmdMgr { public: void CGruntzCmdMgr_023b40(); };
class CGruntzCommand { public: void CGruntzCommand_024050(); void CGruntzCommand_0240d0(); };
class CGruntzMgr { public: void CGruntzMgr_0901d0(); void CGruntzMgr_090ac0(); void CGruntzMgr_0910d0(); void CGruntzMgr_091170(); void CGruntzMgr_091a40(); void CGruntzMgr_091e20(); void CGruntzMgr_092000(); void CGruntzMgr_092030(); void CGruntzMgr_0923b0(); void CGruntzMgr_092500(); void CGruntzMgr_092530(); void CGruntzMgr_0929e0(); void CGruntzMgr_092d50(); void CGruntzMgr_092e30(); void CGruntzMgr_092e80(); };
class CGruntzSoundZ { public: void CGruntzSoundZ_1385e0(); void CGruntzSoundZ_138780(); void CGruntzSoundZ_1387e0(); void CGruntzSoundZ_1388c0(); };
class CHashBase { public: void CHashBase_184a70(); };
class CImage { public: void CImage_1530e0(); void CImage_1532b0(); void CImage_153380(); void CImage_175a00(); void CImage_175b80(); void CImage_175ce0(); void CImage_175d50(); };
class CImageOwned { public: void CImageOwned_148d40(); void CImageOwned_148fc0(); };
class CImageSet { public: void CImageSet_1524d0(); };
class CInGameIcon { public: void CInGameIcon_097800(); void CInGameIcon_0979e0(); void CInGameIcon_097d60(); void CInGameIcon_097f40(); void CInGameIcon_098340(); };
class CInGameText { public: void CInGameText_0995c0(); };
class CInputDevice { public: void CInputDevice_134f70(); };
class CKitchenSlime { public: void CKitchenSlime_0b2aa0(); void CKitchenSlime_0b2ff0(); };
class CMenuItem { public: void CMenuItem_1845d0(); void CMenuItem_1845f0(); };
class CMulti { public: void CMulti_0b6220(); void CMulti_0b62a0(); void CMulti_0b6580(); void CMulti_0b67f0(); void CMulti_0b6890(); void CMulti_0b72c0(); void CMulti_0bc2d0(); void CMulti_0bc3f0(); };
class CMultiStartDlg { public: void CMultiStartDlg_0c1e60(); void CMultiStartDlg_0c1fd0(); };
class CNetMgr { public: void CNetMgr_0b86c0(); void CNetMgr_0b8960(); void CNetMgr_0b8fc0(); void CNetMgr_0ba590(); void CNetMgr_0ba7d0(); void CNetMgr_0ba810(); void CNetMgr_0ba980(); void CNetMgr_0baa90(); void CNetMgr_0baac0(); void CNetMgr_0bac40(); void CNetMgr_0bac90(); void CNetMgr_0bad00(); void CNetMgr_0baf00(); void CNetMgr_0baff0(); void CNetMgr_0bb0b0(); void CNetMgr_0bb120(); void CNetMgr_0bb190(); void CNetMgr_0bb510(); void CNetMgr_0bb5e0(); void CNetMgr_0bbc90(); void CNetMgr_0bbec0(); void CNetMgr_0bbf80(); void CNetMgr_0bc750(); void CNetMgr_0bcc10(); void CNetMgr_0bccd0(); void CNetMgr_0bce80(); void CNetMgr_178170(); void CNetMgr_1786d0(); void CNetMgr_178790(); void CNetMgr_1789e0(); void CNetMgr_178a40(); void CNetMgr_178a80(); void CNetMgr_178b30(); void CNetMgr_178cb0(); void CNetMgr_178d40(); };
class CParticlez { public: void CParticlez_046cb0(); };
class CPathHazard { public: void CPathHazard_013280(); void CPathHazard_0b43f0(); };
class CPlay { public: void CPlay_0d8dc0(); void CPlay_0d8ed0(); void CPlay_0d9050(); };
class CProjectile { public: void CProjectile_0df920(); void CProjectile_0dfb00(); };
class CRandomAmbientSound { public: void CRandomAmbientSound_00c4b0(); void CRandomAmbientSound_00c530(); void CRandomAmbientSound_00c5b0(); void CRandomAmbientSound_00c9d0(); void CRandomAmbientSound_00ca00(); };
class CRezItm { public: void CRezItm_13c6c0(); };
class CSBI_RectOnly { public: void CSBI_RectOnly_0fe3e0(); void CSBI_RectOnly_0fe670(); void CSBI_RectOnly_0fe860(); void CSBI_RectOnly_0fe8a0(); void CSBI_RectOnly_108410(); void CSBI_RectOnly_109520(); void CSBI_RectOnly_10bb50(); };
class CSaveGame { public: void CSaveGame_0e52c0(); };
class CSecretLevelTrigger { public: void CSecretLevelTrigger_0426e0(); void CSecretLevelTrigger_0428c0(); };
class CSecretTeleporterTrigger { public: void CSecretTeleporterTrigger_0420d0(); };
class CShadeTableCache { public: void CShadeTableCache_14df40(); void CShadeTableCache_14e540(); void CShadeTableCache_14e830(); void CShadeTableCache_14e9f0(); void CShadeTableCache_14ec00(); void CShadeTableCache_14ede0(); void CShadeTableCache_14f6c0(); void CShadeTableCache_14f8b0(); void CShadeTableCache_14fa60(); };
class CSimpleAnimation { public: void CSimpleAnimation_0abb90(); void CSimpleAnimation_0abd70(); };
class CSymTab { public: void CSymTab_13bca0(); };
class CTileTriggerSwitchLogic { public: void CTileTriggerSwitchLogic_117e70(); };
class CTileTriggerTransition { public: void CTileTriggerTransition_10fc90(); void CTileTriggerTransition_10fe70(); };
class CTimer { public: void CTimer_09c090(); };
class CToobSpikez { public: void CToobSpikez_1147e0(); };
class CTriggerMgr { public: void CTriggerMgr_06da60(); void CTriggerMgr_06daa0(); void CTriggerMgr_079d90(); void CTriggerMgr_079ea0(); void CTriggerMgr_07abc0(); };
class CUserLogic { public: void CUserLogic_0646b0(); };
class CWarlord { public: void CWarlord_0447a0(); };
class CWormhole { public: void CWormhole_03ffd0(); void CWormhole_0401b0(); };
class CWwdGameObject { public: void CWwdGameObject_150c30(); void CWwdGameObject_151780(); };
class CWwdObjMgr { public: void CWwdObjMgr_15ab30(); void CWwdObjMgr_15ad30(); void CWwdObjMgr_15b0e0(); };
class DirectInputMgr2 { public: void DirectInputMgr2_132ee0(); };
class DirectSoundMgr { public: void DirectSoundMgr_135300(); void DirectSoundMgr_135340(); void DirectSoundMgr_135c20(); void DirectSoundMgr_136260(); void DirectSoundMgr_136300(); void DirectSoundMgr_1365e0(); };
class Font { public: void Font_1799f0(); };
class FontRenderer { public: void FontRenderer_17b120(); };
class GruntzPlayer { public: void GruntzPlayer_0da9e0(); };
class LeafElementObj { public: void LeafElementObj_1586e0(); void LeafElementObj_158720(); };
class SoundDevice { public: void SoundDevice_136860(); void SoundDevice_136ab0(); void SoundDevice_136bd0(); };
class UnknownClassArrays { public: void UnknownClassArrays_02ad40(); void UnknownClassArrays_02b950(); void UnknownClassArrays_02c080(); void UnknownClassArrays_0302c0(); void UnknownClassArrays_0343f0(); void UnknownClassArrays_034960(); void UnknownClassArrays_034c70(); };
class istream { public: void istream_16a490(); };
class streambuf { public: void streambuf_16b340(); void streambuf_16b360(); };
class strstreambuf { public: void strstreambuf_1692c0(); void strstreambuf_1693f0(); void strstreambuf_169400(); };

#endif
