// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.
// Trace-discovered class memberships (docs/this-pointer-classes.csv): each
// `<Class>_<rva>()` is a recovered __thiscall method, defined as an RVA stub in
// src/Stub/Discovered.cpp. Minimal decls; real classes are fully modelled in
// their own TUs (separate translation unit, so this is conflict-free).
#ifndef GRUNTZ_STUB_DISCOVERED_H
#define GRUNTZ_STUB_DISCOVERED_H

class CActionOptionsMenuBar {
public:
    void CActionOptionsMenuBar_009090();
    void CActionOptionsMenuBar_009220();
    void CActionOptionsMenuBar_0092e0();
    void CActionOptionsMenuBar_009300();
    void CActionOptionsMenuBar_009330();
    void CActionOptionsMenuBar_0094c0();
    void CActionOptionsMenuBar_009650();
    void CActionOptionsMenuBar_009760();
    void CActionOptionsMenuBar_0097f0();
    void CActionOptionsMenuBar_009810();
};
class CBattlezDlgColors {
public:
    void CBattlezDlgColors_017ac0();
};
class CBehindCandy {
public:
    void CBehindCandy_00fb70();
    void CBehindCandy_00fc30();
};
class CBehindCandyAni {
public:
    void CBehindCandyAni_0100f0();
    void CBehindCandyAni_0adbb0();
};
class CBootyState {
public:
    void CBootyState_0196c0();
    void CBootyState_019b90();
    void CBootyState_01c0f0();
    void CBootyState_01e520();
    void CBootyState_01e570();
    void CBootyState_01ecf0();
    void CBootyState_08d510();
};
class CBrickz {
public:
    void CBrickz_0113c0();
    void CBrickz_077790();
    void CBrickz_081e10();
    void CBrickz_082030();
    void CBrickz_082430();
    void CBrickz_085480();
    void CBrickz_09356c();
    void CBrickz_09eca0();
    void CBrickz_09f010();
    void CBrickz_09f370();
    void CBrickz_09f430();
    void CBrickz_09f470();
    void CBrickz_09f500();
    void CBrickz_09f590();
    void CBrickz_09f5d0();
    void CBrickz_09f690();
    void CBrickz_09f710();
    void CBrickz_09f7f0();
    void CBrickz_0ec230();
};
// CButeMgr lexer cluster migrated to src/Bute/ButeMgr.cpp (its real class TU);
// only the EH-frame scalar destructor stays here, deferred to the final sweep.
class CButeMgr {
public:
    void CButeMgr_0213c0();
};
class CButeMgrHelper {
public:
    void CButeMgrHelper_1697c0();
    void CButeMgrHelper_1699c0();
    void CButeMgrHelper_169c00();
    void CButeMgrHelper_169dd0();
    void CButeMgrHelper_16b650();
    void CButeMgrHelper_16c0c0();
};
class CButeTree {
public:
    void CButeTree_16e070();
};
class CCheckpointDlg {
public:
    void CCheckpointDlg_023570();
};
class CCheckpointTrigger {
public:
    void CCheckpointTrigger_011480();
};
class CCreditsState {
public:
    void CCreditsState_038f00();
    void CCreditsState_039c40();
    void CCreditsState_039c60();
    void CCreditsState_039d00();
};
class CCursorSnapSprite {
public:
    void CCursorSnapSprite_011880();
    void CCursorSnapSprite_011920();
};
class CDDPalette {
public:
    void CDDPalette_1474d0();
    void CDDPalette_147530();
};
class CDDSurface {
public:
    void CDDSurface_142a40();
};
class CDDrawSubMgr {
public:
    void CDDrawSubMgr_031250();
    void CDDrawSubMgr_158b40();
    void CDDrawSubMgr_158c70();
    void CDDrawSubMgr_158d20();
    void CDDrawSubMgr_158dc0();
    void CDDrawSubMgr_158e40();
    void CDDrawSubMgr_158e90();
    void CDDrawSubMgr_158ee0();
    void CDDrawSubMgr_159600();
    void CDDrawSubMgr_159e40();
    void CDDrawSubMgr_159ef0();
    void CDDrawSubMgr_15aa90();
    void CDDrawSubMgr_15ab70();
    void CDDrawSubMgr_15aba0();
    void CDDrawSubMgr_15abc0();
    void CDDrawSubMgr_15ac20();
    void CDDrawSubMgr_15acb0();
    void CDDrawSubMgr_15b020();
    void CDDrawSubMgr_15b1d0();
    void CDDrawSubMgr_15c290();
    void CDDrawSubMgr_15c2c0();
    void CDDrawSubMgr_15c2d0();
    void CDDrawSubMgr_15c360();
    void CDDrawSubMgr_15c900();
    void CDDrawSubMgr_15c970();
};
class CDDrawSubMgrLeaf {
public:
    void CDDrawSubMgrLeaf_05b7e0();
    void CDDrawSubMgrLeaf_114120();
    void CDDrawSubMgrLeaf_157570();
    void CDDrawSubMgrLeaf_157c70();
    void CDDrawSubMgrLeaf_157d70();
    void CDDrawSubMgrLeaf_157ee0();
    void CDDrawSubMgrLeaf_1583c0();
    void CDDrawSubMgrLeaf_1584f0();
    void CDDrawSubMgrLeaf_158570();
};
class CDDrawSurfaceMgr {
public:
    void CDDrawSurfaceMgr_1558b0();
    void CDDrawSurfaceMgr_155e20();
    void CDDrawSurfaceMgr_156020();
};
class CDDrawWorkerList {
public:
    void CDDrawWorkerList_163bc0();
};
class CDDrawWorkerMapSmall {
public:
    void CDDrawWorkerMapSmall_156d20();
    void CDDrawWorkerMapSmall_165810();
};
class CDDrawWorkerRegistry {
public:
    void CDDrawWorkerRegistry_151f00();
    void CDDrawWorkerRegistry_155360();
    void CDDrawWorkerRegistry_155550();
    void CDDrawWorkerRegistry_155630();
    void CDDrawWorkerRegistry_15cc30();
    void CDDrawWorkerRegistry_165360();
};
class CDoNothing {
public:
    void CDoNothing_00f6b0();
    void CDoNothing_00f770();
};
class CDroppedObject {
public:
    void CDroppedObject_0125b0();
    void CDroppedObject_0c6bd0();
};
class CDroppedObjectShadow {
public:
    void CDroppedObjectShadow_012670();
};
class CExitTrigger {
public:
    void CExitTrigger_010870();
    void CExitTrigger_0108c0();
};
class CExplosion {
public:
    void CExplosion_012ec0();
};
class CEyeCandy {
public:
    void CEyeCandy_00fca0();
    void CEyeCandy_00fd60();
};
class CFileIO {
public:
    void CFileIO_085b50();
    void CFileIO_0e4d20();
    void CFileIO_0e4d50();
    void CFileIO_0e4d90();
    void CFileIO_0e4ea0();
    void CFileIO_0e50a0();
    void CFileIO_0e50f0();
    void CFileIO_0e5130();
    void CFileIO_0e51d0();
    void CFileIO_0e5240();
    void CFileIO_0e5390();
    void CFileIO_0e5410();
    void CFileIO_0e5460();
    void CFileIO_0e54b0();
    void CFileIO_0e54e0();
    void CFileIO_0e5620();
    void CFileIO_0e5660();
    void CFileIO_0e5690();
};
class CFileImage {
public:
    void CFileImage_13e550();
    void CFileImage_13e760();
    void CFileImage_141350();
    void CFileImage_148890();
};
class CFontConfig {
public:
    void CFontConfig_021b60();
    void CFontConfig_021bd0();
    void CFontConfig_021c60();
    void CFontConfig_021d80();
    void CFontConfig_085f40();
};
class CFortressFlag {
public:
    void CFortressFlag_010e90();
    void CFortressFlag_046410();
};
class CGameLevel {
public:
    void CGameLevel_06b330();
    void CGameLevel_082600();
    void CGameLevel_0cedf0();
    void CGameLevel_0cee10();
    void CGameLevel_15da80();
    void CGameLevel_15dc90();
    void CGameLevel_15dde0();
    void CGameLevel_15de40();
    void CGameLevel_15dfb0();
    void CGameLevel_160ee0();
    void CGameLevel_160f40();
    void CGameLevel_160f70();
    void CGameLevel_167130();
};
class CGrunt {
public:
    void CGrunt_057c40();
};
class CGruntAnimPlayer {
public:
    void CGruntAnimPlayer_150610();
};
class CGruntCreationPoint {
public:
    void CGruntCreationPoint_010730();
    void CGruntCreationPoint_03ecc0();
};
class CGruntHealthSprite {
public:
    void CGruntHealthSprite_011fb0();
    void CGruntHealthSprite_07f0d0();
};
class CGruntPowerupSprite {
public:
    void CGruntPowerupSprite_012370();
    void CGruntPowerupSprite_080380();
    void CGruntPowerupSprite_080410();
};
class CGruntPuddle {
public:
    void CGruntPuddle_010d10();
    void CGruntPuddle_040c30();
    void CGruntPuddle_040d20();
    void CGruntPuddle_07d810();
};
class CGruntSelectedSprite {
public:
    void CGruntSelectedSprite_011e80();
    void CGruntSelectedSprite_07e9c0();
    void CGruntSelectedSprite_07e9f0();
};
class CGruntStartingPoint {
public:
    void CGruntStartingPoint_010670();
};
class CGruntToySprite {
public:
    void CGruntToySprite_0122b0();
    void CGruntToySprite_07f920();
    void CGruntToySprite_07f960();
};
class CGruntToyTimeSprite {
public:
    void CGruntToyTimeSprite_012130();
};
class CGruntVoice {
public:
    void CGruntVoice_119ae0();
    void CGruntVoice_119e40();
    void CGruntVoice_11a7e0();
    void CGruntVoice_11a870();
};
class CGruntzCommand {
public:
    void CGruntzCommand_023e20();
    void CGruntzCommand_023e60();
    void CGruntzCommand_023ed0();
    void CGruntzCommand_024140();
    void CGruntzCommand_024190();
    void CGruntzCommand_024490();
};
class CGruntzMgr {
public:
    void CGruntzMgr_0860b0();
    void CGruntzMgr_08b960();
    void CGruntzMgr_08d6a0();
    void CGruntzMgr_08d780();
    void CGruntzMgr_08d9d0();
    void CGruntzMgr_08da00();
    void CGruntzMgr_08da30();
    void CGruntzMgr_08da60();
    void CGruntzMgr_08daa0();
    void CGruntzMgr_08dae0();
    void CGruntzMgr_08db20();
    void CGruntzMgr_08db60();
    void CGruntzMgr_08dba0();
    void CGruntzMgr_08dbe0();
    void CGruntzMgr_08de70();
    void CGruntzMgr_08e980();
    void CGruntzMgr_08ef10();
    void CGruntzMgr_08f4f0();
    void CGruntzMgr_08f740();
    void CGruntzMgr_08f7b0();
    void CGruntzMgr_08f7f0();
    void CGruntzMgr_08fab0();
    void CGruntzMgr_090200();
    void CGruntzMgr_0903f0();
    void CGruntzMgr_090980();
    void CGruntzMgr_0909b0();
    void CGruntzMgr_0909e0();
    void CGruntzMgr_090a50();
    void CGruntzMgr_090aa0();
    void CGruntzMgr_091500();
    void CGruntzMgr_0919d0();
    void CGruntzMgr_091a10();
    void CGruntzMgr_0920b0();
    void CGruntzMgr_0927b0();
    void CGruntzMgr_0928c0();
    void CGruntzMgr_092900();
    void CGruntzMgr_092990();
    void CGruntzMgr_0929b0();
    void CGruntzMgr_092ec0();
    void CGruntzMgr_093170();
    void CGruntzMgr_0933e0();
    void CGruntzMgr_093460();
    void CGruntzMgr_093620();
    void CGruntzMgr_111ec0();
};
class CGruntzSoundZ {
public:
    void CGruntzSoundZ_086040();
    void CGruntzSoundZ_138530();
    void CGruntzSoundZ_138670();
    void CGruntzSoundZ_138700();
    void CGruntzSoundZ_138730();
    void CGruntzSoundZ_138840();
    void CGruntzSoundZ_1388a0();
    void CGruntzSoundZ_138920();
};
class CGuardPoint {
public:
    void CGuardPoint_010410();
};
class CInGameIcon {
public:
    void CInGameIcon_011d00();
    void CInGameIcon_097680();
    void CInGameIcon_0986b0();
    void CInGameIcon_098c90();
    void CInGameIcon_099b10();
};
class CInGameText {
public:
    void CInGameText_011dc0();
    void CInGameText_099460();
    void CInGameText_099a30();
};
class CInputDevice {
public:
    void CInputDevice_133300();
    void CInputDevice_133b50();
    void CInputDevice_133bf0();
    void CInputDevice_133c30();
    void CInputDevice_133d00();
    void CInputDevice_134260();
    void CInputDevice_134d50();
    void CInputDevice_134fe0();
};
class CKitchenSlime {
public:
    void CKitchenSlime_013100();
    void CKitchenSlime_0b2940();
    void CKitchenSlime_0b2ca0();
};
class CLightFx {
public:
    void CLightFx_012430();
    void CLightFx_09d520();
    void CLightFx_09d770();
};
class CMapArrayA {
public:
    void CMapArrayA_09e740();
};
class CMapArrayB {
public:
    void CMapArrayB_09e860();
};
class CMenuState {
public:
    void CMenuState_0a0d40();
};
class NetUnattributed {
public:
    void NetUnattributed_007c20();
    void NetUnattributed_024450();
    void NetUnattributed_099d10();
    void NetUnattributed_0b89e0();
    void NetUnattributed_0f93b0();
    void NetUnattributed_11f618();
    void NetUnattributed_18c022();
};
class CObjectDropper {
public:
    void CObjectDropper_0124f0();
};
class CParticlez {
public:
    void CParticlez_012d90();
    void CParticlez_046d30();
};
class CPlay {
public:
    void CPlay_08d270();
    void CPlay_0b6110();
    void CPlay_0b76c0();
    void CPlay_0b7730();
    void CPlay_0b7a90();
    void CPlay_0b7ad0();
    void CPlay_0b7e30();
    void CPlay_0b7f60();
    void CPlay_0b7fe0();
    void CPlay_0bc250();
    void CPlay_0bc420();
    void CPlay_0c9c20();
    void CPlay_0c9cc0();
    void CPlay_0ce530();
    void CPlay_0d0920();
    void CPlay_0d0a60();
    void CPlay_0d0db0();
    void CPlay_0d1b60();
    void CPlay_0d5f00();
    void CPlay_0d72c0();
    void CPlay_0d9160();
};
class CProjectile {
public:
    void CProjectile_013c70();
    void CProjectile_0def60();
    void CProjectile_0e05e0();
    void CProjectile_0e08b0();
    void CProjectile_0e0b10();
    void CProjectile_0e2190();
};
class CRandomAmbientSound {
public:
    void CRandomAmbientSound_00b5e0();
    void CRandomAmbientSound_00b660();
    void CRandomAmbientSound_00bc30();
    void CRandomAmbientSound_00bc80();
    void CRandomAmbientSound_00bcf0();
    void CRandomAmbientSound_00bd60();
    void CRandomAmbientSound_085ed0();
};
class CRollingBall {
public:
    void CRollingBall_012f80();
    void CRollingBall_0b0fe0();
};
class CSBI_RectOnly {
public:
    void CSBI_RectOnly_0c8980();
    void CSBI_RectOnly_0e72f0();
    void CSBI_RectOnly_0e7400();
    void CSBI_RectOnly_0ebd70();
    void CSBI_RectOnly_0fe350();
    void CSBI_RectOnly_0ff850();
    void CSBI_RectOnly_0ff9f0();
    void CSBI_RectOnly_0ffcb0();
    void CSBI_RectOnly_100930();
    void CSBI_RectOnly_100b00();
    void CSBI_RectOnly_100cb0();
    void CSBI_RectOnly_100d70();
    void CSBI_RectOnly_101420();
    void CSBI_RectOnly_102000();
    void CSBI_RectOnly_1020a0();
    void CSBI_RectOnly_104d60();
    void CSBI_RectOnly_104f90();
    void CSBI_RectOnly_105280();
    void CSBI_RectOnly_105480();
    void CSBI_RectOnly_105520();
    void CSBI_RectOnly_105560();
    void CSBI_RectOnly_105710();
    void CSBI_RectOnly_105750();
    void CSBI_RectOnly_1057d0();
    void CSBI_RectOnly_105800();
    void CSBI_RectOnly_1058d0();
    void CSBI_RectOnly_105920();
    void CSBI_RectOnly_106610();
    void CSBI_RectOnly_1066f0();
    void CSBI_RectOnly_106740();
    void CSBI_RectOnly_106790();
    void CSBI_RectOnly_106820();
    void CSBI_RectOnly_106900();
    void CSBI_RectOnly_1069c0();
    void CSBI_RectOnly_106a00();
    void CSBI_RectOnly_106b40();
    void CSBI_RectOnly_107920();
    void CSBI_RectOnly_107aa0();
    void CSBI_RectOnly_1084d0();
    void CSBI_RectOnly_1090a0();
    void CSBI_RectOnly_109a90();
    void CSBI_RectOnly_109ad0();
    void CSBI_RectOnly_10b210();
    void CSBI_RectOnly_10b5d0();
    void CSBI_RectOnly_10b6f0();
    void CSBI_RectOnly_10b810();
    void CSBI_RectOnly_10b930();
    void CSBI_RectOnly_10bb90();
};
class CSecretLevelTrigger {
public:
    void CSecretLevelTrigger_010c50();
    void CSecretLevelTrigger_042ac0();
};
class CSecretTeleporterTrigger {
public:
    void CSecretTeleporterTrigger_010a10();
    void CSecretTeleporterTrigger_010ab0();
    void CSecretTeleporterTrigger_042150();
    void CSecretTeleporterTrigger_042b80();
};
class CSimpleAnimation {
public:
    void CSimpleAnimation_00f9d0();
    void CSimpleAnimation_0abf70();
};
class CSingleAnimation {
public:
    void CSingleAnimation_010540();
};
class CState {
public:
    void CState_018c90();
    void CState_019cd0();
    void CState_01af70();
    void CState_08ce60();
    void CState_08d440();
    void CState_0a02c0();
    void CState_0a05a0();
    void CState_0a0640();
    void CState_0a06d0();
};
class CStaticHazard {
public:
    void CStaticHazard_012b30();
    void CStaticHazard_0fbbf0();
};
class CStatusBarItem {
public:
    void CStatusBarItem_0e6d90();
    void CStatusBarItem_0e6e40();
    void CStatusBarItem_0e80e0();
    void CStatusBarItem_0e81a0();
    void CStatusBarItem_0e81e0();
    void CStatusBarItem_0e82a0();
    void CStatusBarItem_0e8310();
    void CStatusBarItem_0e8480();
    void CStatusBarItem_0e84f0();
    void CStatusBarItem_0e8520();
    void CStatusBarItem_1005b0();
    void CStatusBarItem_1007d0();
    void CStatusBarItem_10bfc0();
};
class CTeleporter {
public:
    void CTeleporter_010dd0();
    void CTeleporter_0419e0();
};
class CTileTrigger {
public:
    void CTileTrigger_011290();
    void CTileTrigger_011540();
    void CTileTrigger_011600();
    void CTileTrigger_0116c0();
};
class CTileTriggerSwitch {
public:
    void CTileTriggerSwitch_0110f0();
};
class CTileTriggerSwitchLogic {
public:
    void CTileTriggerSwitchLogic_0c8640();
    void CTileTriggerSwitchLogic_112590();
    void CTileTriggerSwitchLogic_112880();
    void CTileTriggerSwitchLogic_112970();
    void CTileTriggerSwitchLogic_112b70();
    void CTileTriggerSwitchLogic_112c70();
    void CTileTriggerSwitchLogic_113a90();
    void CTileTriggerSwitchLogic_113ae0();
    void CTileTriggerSwitchLogic_113d40();
    void CTileTriggerSwitchLogic_113dd0();
    void CTileTriggerSwitchLogic_115f00();
    void CTileTriggerSwitchLogic_115f30();
    void CTileTriggerSwitchLogic_116a40();
    void CTileTriggerSwitchLogic_116cf0();
    void CTileTriggerSwitchLogic_116e60();
    void CTileTriggerSwitchLogic_116ee0();
    void CTileTriggerSwitchLogic_116f20();
    void CTileTriggerSwitchLogic_116fa0();
    void CTileTriggerSwitchLogic_1170b0();
    void CTileTriggerSwitchLogic_117150();
    void CTileTriggerSwitchLogic_1171d0();
    void CTileTriggerSwitchLogic_117200();
    void CTileTriggerSwitchLogic_117280();
    void CTileTriggerSwitchLogic_117630();
    void CTileTriggerSwitchLogic_117710();
    void CTileTriggerSwitchLogic_117e20();
    void CTileTriggerSwitchLogic_117ec0();
    void CTileTriggerSwitchLogic_117f60();
};
class CTileTriggerTransition {
public:
    void CTileTriggerTransition_011730();
    void CTileTriggerTransition_0117f0();
    void CTileTriggerTransition_110070();
};
class CTimer {
public:
    void CTimer_09bab0();
    void CTimer_09bc70();
    void CTimer_09bca0();
    void CTimer_09bfa0();
    void CTimer_09c0e0();
    void CTimer_09c1c0();
    void CTimer_09c2e0();
};
class CToobSpikez {
public:
    void CToobSpikez_012c60();
    void CToobSpikez_114860();
};
class CUserLogic {
public:
    void CUserLogic_00f2f0();
    void CUserLogic_029a50();
    void CUserLogic_03c7f0();
    void CUserLogic_048360();
    void CUserLogic_049c60();
    void CUserLogic_04ac10();
    void CUserLogic_04b130();
    void CUserLogic_04b240();
    void CUserLogic_04b320();
    void CUserLogic_04b370();
    void CUserLogic_04c170();
    void CUserLogic_04d060();
    void CUserLogic_0511b0();
    void CUserLogic_0514a0();
    void CUserLogic_051850();
    void CUserLogic_051a20();
    void CUserLogic_052fb0();
    void CUserLogic_053b80();
    void CUserLogic_053f90();
    void CUserLogic_057060();
    void CUserLogic_057c10();
    void CUserLogic_057ce0();
    void CUserLogic_057d80();
    void CUserLogic_0588f0();
    void CUserLogic_059230();
    void CUserLogic_05b6f0();
    void CUserLogic_05caa0();
    void CUserLogic_05f310();
    void CUserLogic_0616e0();
    void CUserLogic_0617c0();
    void CUserLogic_062110();
    void CUserLogic_0637a0();
    void CUserLogic_067850();
    void CUserLogic_068370();
    void CUserLogic_06a6d0();
    void CUserLogic_06b260();
    void CUserLogic_0f26f0();
    void CUserLogic_16e7f0();
    void CUserLogic_16ea90();
};
class CVoiceTrigger {
public:
    void CVoiceTrigger_0135a0();
    void CVoiceTrigger_11a700();
};
class CWarlord {
public:
    void CWarlord_0107f0();
    void CWarlord_044640();
    void CWarlord_044bb0();
};
class CWayPoint {
public:
    void CWayPoint_0102e0();
};
class CWormhole {
public:
    void CWormhole_010980();
    void CWormhole_0403b0();
};
class ClassUnknown_1 {
public:
    void ClassUnknown_1_134be0();
    void ClassUnknown_1_134c60();
    void ClassUnknown_1_134c80();
};
class ClassUnknown_10 {
public:
    void ClassUnknown_10_0e2250();
    void ClassUnknown_10_0e2290();
    void ClassUnknown_10_0e22d0();
    void ClassUnknown_10_0e2360();
    void ClassUnknown_10_0e2390();
    void ClassUnknown_10_0e23c0();
    void ClassUnknown_10_0e2890();
};
class ClassUnknown_100 {
public:
    void ClassUnknown_100_109bb0();
    void ClassUnknown_100_10a0f0();
    void ClassUnknown_100_10a2f0();
};
class ClassUnknown_101 {
public:
    void ClassUnknown_101_11f6b9();
};
class ClassUnknown_102 {
public:
    void ClassUnknown_102_06b2e0();
};
class ClassUnknown_103 {
public:
    void ClassUnknown_103_148d10();
};
class ClassUnknown_104 {
public:
    void ClassUnknown_104_152e30();
    void ClassUnknown_104_165730();
};
class ClassUnknown_105 {
public:
    void ClassUnknown_105_1657a0();
};
class ClassUnknown_106 {
public:
    void ClassUnknown_106_0af0a0();
};
class ClassUnknown_107 {
public:
    void ClassUnknown_107_10d3d0();
};
class ClassUnknown_108 {
public:
    void ClassUnknown_108_112d80();
    void ClassUnknown_108_112da0();
    void ClassUnknown_108_112ee0();
    void ClassUnknown_108_113f10();
    void ClassUnknown_108_113f60();
};
class ClassUnknown_109 {
public:
    void ClassUnknown_109_0aa960();
};
class ClassUnknown_11 {
public:
    void ClassUnknown_11_13abc0();
    void ClassUnknown_11_13b850();
    void ClassUnknown_11_13bff0();
    void ClassUnknown_11_13c030();
    void ClassUnknown_11_13c210();
};
class ClassUnknown_110 {
public:
    void ClassUnknown_110_0fb660();
};
class ClassUnknown_111 {
public:
    void ClassUnknown_111_029a80();
};
class ClassUnknown_112 {
public:
    void ClassUnknown_112_021c40();
};
class ClassUnknown_113 {
public:
    void ClassUnknown_113_114480();
};
class ClassUnknown_114 {
public:
    void ClassUnknown_114_0e6380();
    void ClassUnknown_114_104bb0();
};
class ClassUnknown_115 {
public:
    void ClassUnknown_115_0e8c70();
    void ClassUnknown_115_0e8cb0();
    void ClassUnknown_115_0e8dc0();
    void ClassUnknown_115_104ce0();
};
class ClassUnknown_116 {
public:
    void ClassUnknown_116_0e7980();
    void ClassUnknown_116_0e7b00();
    void ClassUnknown_116_0ea0f0();
    void ClassUnknown_116_1047f0();
    void ClassUnknown_116_1048f0();
};
class ClassUnknown_117 {
public:
    void ClassUnknown_117_0ea470();
    void ClassUnknown_117_0ea4b0();
    void ClassUnknown_117_0ea6c0();
    void ClassUnknown_117_104b00();
};
class ClassUnknown_118 {
public:
    void ClassUnknown_118_0eb6b0();
    void ClassUnknown_118_0eb740();
    void ClassUnknown_118_0eb830();
    void ClassUnknown_118_0eb880();
    void ClassUnknown_118_104a00();
};
class ClassUnknown_119 {
public:
    void ClassUnknown_119_1591b0();
};
class ClassUnknown_12 {
public:
    void ClassUnknown_12_139ee0();
    void ClassUnknown_12_13a230();
    void ClassUnknown_12_13bae0();
    void ClassUnknown_12_13be40();
};
class ClassUnknown_120 {
public:
    void ClassUnknown_120_1852e0();
};
class ClassUnknown_121 {
public:
    void ClassUnknown_121_139cf0();
};
class ClassUnknown_122 {
public:
    void ClassUnknown_122_1397a0();
};
class ClassUnknown_123 {
public:
    void ClassUnknown_123_16dfc0();
};
class ClassUnknown_124 {
public:
    void ClassUnknown_124_11eaf5();
};
class ClassUnknown_125 {
public:
    void ClassUnknown_125_11eaa8();
};
class ClassUnknown_126 {
public:
    void ClassUnknown_126_11cf30();
};
class ClassUnknown_127 {
public:
    void ClassUnknown_127_11cee3();
};
class ClassUnknown_128 {
public:
    void ClassUnknown_128_174d70();
};
class ClassUnknown_129 {
public:
    void ClassUnknown_129_016460();
};
class ClassUnknown_13 {
public:
    void ClassUnknown_13_13c240();
    void ClassUnknown_13_13c270();
    void ClassUnknown_13_13c350();
    void ClassUnknown_13_13c360();
    void ClassUnknown_13_13c3c0();
    void ClassUnknown_13_13c3f0();
    void ClassUnknown_13_184a40();
    void ClassUnknown_13_184ab0();
    void ClassUnknown_13_184b40();
};
class ClassUnknown_14 {
public:
    void ClassUnknown_14_13a000();
};
class ClassUnknown_15 {
public:
    void ClassUnknown_15_13c520();
    void ClassUnknown_15_13c590();
    void ClassUnknown_15_13c600();
    void ClassUnknown_15_13c830();
};
class ClassUnknown_16 {
public:
    void ClassUnknown_16_021280();
    void ClassUnknown_16_169160();
    void ClassUnknown_16_169220();
    void ClassUnknown_16_1692b0();
    void ClassUnknown_16_169490();
    void ClassUnknown_16_16b070();
    void ClassUnknown_16_16b150();
    void ClassUnknown_16_16b1d0();
    void ClassUnknown_16_16b320();
    void ClassUnknown_16_16b3a0();
    void ClassUnknown_16_16cd00();
};
class ClassUnknown_17 {
public:
    void ClassUnknown_17_16f6c0();
    void ClassUnknown_17_16f760();
    void ClassUnknown_17_170100();
};
class ClassUnknown_18 {
public:
    void ClassUnknown_18_16f7f0();
};
class ClassUnknown_19 {
public:
    void ClassUnknown_19_16fc70();
};
class ClassUnknown_2 {
public:
    void ClassUnknown_2_14de30();
    void ClassUnknown_2_14de50();
    void ClassUnknown_2_14dec0();
    void ClassUnknown_2_14ded0();
    void ClassUnknown_2_14eef0();
    void ClassUnknown_2_14f080();
    void ClassUnknown_2_14f310();
    void ClassUnknown_2_14f5b0();
    void ClassUnknown_2_14fb80();
};
class ClassUnknown_20 {
public:
    void ClassUnknown_20_16df70();
};
class ClassUnknown_21 {
public:
    void ClassUnknown_21_16e480();
};
class ClassUnknown_22 {
public:
    void ClassUnknown_22_022b00();
    void ClassUnknown_22_022be0();
    void ClassUnknown_22_022c80();
    void ClassUnknown_22_085e60();
};
class ClassUnknown_23 {
public:
    void ClassUnknown_23_06b640();
    void ClassUnknown_23_06b680();
    void ClassUnknown_23_06b6d0();
    void ClassUnknown_23_06bcb0();
    void ClassUnknown_23_06bd40();
    void ClassUnknown_23_06be30();
    void ClassUnknown_23_06bea0();
    void ClassUnknown_23_06bfd0();
    void ClassUnknown_23_06d300();
    void ClassUnknown_23_06dae0();
    void ClassUnknown_23_06e120();
    void ClassUnknown_23_06e800();
    void ClassUnknown_23_06ea00();
    void ClassUnknown_23_075af0();
    void ClassUnknown_23_078260();
    void ClassUnknown_23_078430();
    void ClassUnknown_23_0784d0();
    void ClassUnknown_23_078520();
    void ClassUnknown_23_078680();
    void ClassUnknown_23_078880();
    void ClassUnknown_23_078a30();
    void ClassUnknown_23_078a50();
    void ClassUnknown_23_079520();
    void ClassUnknown_23_0798d0();
    void ClassUnknown_23_079b00();
    void ClassUnknown_23_079b30();
    void ClassUnknown_23_079b80();
    void ClassUnknown_23_079fb0();
    void ClassUnknown_23_07a180();
    void ClassUnknown_23_07a240();
    void ClassUnknown_23_07a510();
    void ClassUnknown_23_07a5e0();
    void ClassUnknown_23_07a760();
    void ClassUnknown_23_07b1b0();
    void ClassUnknown_23_07be10();
    void ClassUnknown_23_07c110();
    void ClassUnknown_23_07d0c0();
    void ClassUnknown_23_07d140();
    void ClassUnknown_23_07d1d0();
    void ClassUnknown_23_07d2a0();
    void ClassUnknown_23_07d330();
    void ClassUnknown_23_085c50();
};
class ClassUnknown_24 {
public:
    void ClassUnknown_24_085df0();
    void ClassUnknown_24_11adc0();
    void ClassUnknown_24_11ae30();
    void ClassUnknown_24_11af00();
    void ClassUnknown_24_11af90();
    void ClassUnknown_24_11bba0();
    void ClassUnknown_24_11bee0();
    void ClassUnknown_24_11c1a0();
    void ClassUnknown_24_11c7b0();
    void ClassUnknown_24_11c830();
};
class ClassUnknown_25 {
public:
    void ClassUnknown_25_099ca0();
    void ClassUnknown_25_09a450();
    void ClassUnknown_25_11c560();
};
class ClassUnknown_26 {
public:
    void ClassUnknown_26_11c630();
};
class ClassUnknown_27 {
public:
    void ClassUnknown_27_13a260();
    void ClassUnknown_27_13a280();
    void ClassUnknown_27_13a2b0();
    void ClassUnknown_27_13a2d0();
    void ClassUnknown_27_13a2f0();
    void ClassUnknown_27_13a310();
};
class ClassUnknown_28 {
public:
    void ClassUnknown_28_01f940();
    void ClassUnknown_28_158760();
};
class ClassUnknown_29 {
public:
    void ClassUnknown_29_137110();
};
class ClassUnknown_3 {
public:
    void ClassUnknown_3_09dad0();
    void ClassUnknown_3_09dc80();
    void ClassUnknown_3_09dcb0();
};
class ClassUnknown_30 {
public:
    void ClassUnknown_30_136f60();
    void ClassUnknown_30_1390e0();
    void ClassUnknown_30_139110();
    void ClassUnknown_30_1391e0();
};
class ClassUnknown_31 {
public:
    void ClassUnknown_31_152f20();
    void ClassUnknown_31_152fb0();
    void ClassUnknown_31_153810();
};
class ClassUnknown_32 {
public:
    void ClassUnknown_32_141d50();
    void ClassUnknown_32_142060();
    void ClassUnknown_32_142100();
    void ClassUnknown_32_142120();
    void ClassUnknown_32_142160();
    void ClassUnknown_32_142260();
    void ClassUnknown_32_1423c0();
    void ClassUnknown_32_142e60();
    void ClassUnknown_32_142eb0();
    void ClassUnknown_32_142ed0();
    void ClassUnknown_32_142f10();
    void ClassUnknown_32_142fc0();
};
class ClassUnknown_33 {
public:
    void ClassUnknown_33_153180();
};
class ClassUnknown_34 {
public:
    void ClassUnknown_34_148ce0();
    void ClassUnknown_34_1490d0();
};
class ClassUnknown_35 {
public:
    void ClassUnknown_35_151eb0();
    void ClassUnknown_35_1557a0();
};
class ClassUnknown_36 {
public:
    void ClassUnknown_36_14dd90();
};
class ClassUnknown_37 {
public:
    void ClassUnknown_37_06b2a0();
    void ClassUnknown_37_152720();
    void ClassUnknown_37_1527d0();
    void ClassUnknown_37_1528d0();
    void ClassUnknown_37_152ad0();
    void ClassUnknown_37_152c50();
    void ClassUnknown_37_152d30();
    void ClassUnknown_37_1577e0();
};
class ClassUnknown_38 {
public:
    void ClassUnknown_38_06b270();
    void ClassUnknown_38_165460();
    void ClassUnknown_38_1655c0();
};
class ClassUnknown_39 {
public:
    void ClassUnknown_39_168c60();
    void ClassUnknown_39_168e50();
};
class ClassUnknown_4 {
public:
    void ClassUnknown_4_150180();
    void ClassUnknown_4_150190();
    void ClassUnknown_4_1501a0();
    void ClassUnknown_4_1503c0();
};
class ClassUnknown_40 {
public:
    void ClassUnknown_40_168d00();
};
class ClassUnknown_41 {
public:
    void ClassUnknown_41_165dd0();
    void ClassUnknown_41_168ee0();
    void ClassUnknown_41_168fb0();
};
class ClassUnknown_42 {
public:
    void ClassUnknown_42_0e2df0();
    void ClassUnknown_42_0e32e0();
};
class ClassUnknown_43 {
public:
    void ClassUnknown_43_13e4d0();
    void ClassUnknown_43_13edb0();
    void ClassUnknown_43_13f910();
    void ClassUnknown_43_142360();
    void ClassUnknown_43_144350();
    void ClassUnknown_43_144640();
    void ClassUnknown_43_148840();
};
class ClassUnknown_44 {
public:
    void ClassUnknown_44_158680();
    void ClassUnknown_44_1587c0();
};
class ClassUnknown_45 {
public:
    void ClassUnknown_45_183250();
    void ClassUnknown_45_1832d0();
    void ClassUnknown_45_1832f0();
    void ClassUnknown_45_1833a0();
    void ClassUnknown_45_1833c0();
    void ClassUnknown_45_183430();
    void ClassUnknown_45_183460();
    void ClassUnknown_45_1835a0();
    void ClassUnknown_45_183990();
    void ClassUnknown_45_1839d0();
    void ClassUnknown_45_183ad0();
    void ClassUnknown_45_183b30();
    void ClassUnknown_45_183b60();
    void ClassUnknown_45_183c50();
    void ClassUnknown_45_183d10();
    void ClassUnknown_45_183dd0();
    void ClassUnknown_45_184070();
    void ClassUnknown_45_1840a0();
    void ClassUnknown_45_184100();
    void ClassUnknown_45_184150();
    void ClassUnknown_45_1843f0();
    void ClassUnknown_45_1844d0();
};
class ClassUnknown_46 {
public:
    void ClassUnknown_46_1845b0();
    void ClassUnknown_46_184610();
    void ClassUnknown_46_184630();
    void ClassUnknown_46_184690();
    void ClassUnknown_46_184730();
    void ClassUnknown_46_185460();
    void ClassUnknown_46_185510();
    void ClassUnknown_46_185580();
    void ClassUnknown_46_1855f0();
    void ClassUnknown_46_1856d0();
    void ClassUnknown_46_185700();
};
class ClassUnknown_47 {
public:
    void ClassUnknown_47_0f9280();
    void ClassUnknown_47_17e7b0();
    void ClassUnknown_47_17e880();
};
class ClassUnknown_48 {
public:
    void ClassUnknown_48_17d910();
    void ClassUnknown_48_17d9a0();
    void ClassUnknown_48_17d9c0();
    void ClassUnknown_48_17e170();
    void ClassUnknown_48_17e1d0();
};
class ClassUnknown_49 {
public:
    void ClassUnknown_49_182940();
    void ClassUnknown_49_182a80();
};
class ClassUnknown_5 {
public:
    void ClassUnknown_5_150040();
};
class ClassUnknown_50 {
public:
    void ClassUnknown_50_0d5e80();
    void ClassUnknown_50_153260();
    void ClassUnknown_50_153790();
};
class ClassUnknown_51 {
public:
    void ClassUnknown_51_1154b0();
};
class ClassUnknown_52 {
public:
    void ClassUnknown_52_179c30();
    void ClassUnknown_52_179d10();
    void ClassUnknown_52_17a460();
    void ClassUnknown_52_17ac50();
    void ClassUnknown_52_17ad10();
};
class ClassUnknown_53 {
public:
    void ClassUnknown_53_029ac0();
};
class ClassUnknown_54 {
public:
    void ClassUnknown_54_135110();
};
class ClassUnknown_55 {
public:
    void ClassUnknown_55_137060();
    void ClassUnknown_55_1370d0();
};
class ClassUnknown_56 {
public:
    void ClassUnknown_56_08c3b0();
};
class ClassUnknown_57 {
public:
    void ClassUnknown_57_03a1d0();
    void ClassUnknown_57_1590f0();
    void ClassUnknown_57_163e20();
    void ClassUnknown_57_163f40();
};
class ClassUnknown_58 {
public:
    void ClassUnknown_58_0204e0();
    void ClassUnknown_58_020510();
    void ClassUnknown_58_020530();
    void ClassUnknown_58_021140();
};
class ClassUnknown_59 {
public:
    void ClassUnknown_59_0e6c80();
    void ClassUnknown_59_0e74f0();
    void ClassUnknown_59_0e86e0();
    void ClassUnknown_59_0e9800();
    void ClassUnknown_59_0e9820();
    void ClassUnknown_59_0e99c0();
    void ClassUnknown_59_100700();
    void ClassUnknown_59_100870();
    void ClassUnknown_59_105200();
};
class ClassUnknown_6 {
public:
    void ClassUnknown_6_14dcf0();
};
class ClassUnknown_60 {
public:
    void ClassUnknown_60_0ebd30();
};
class ClassUnknown_61 {
public:
    void ClassUnknown_61_120120();
    void ClassUnknown_61_17b500();
};
class ClassUnknown_62 {
public:
    void ClassUnknown_62_099c20();
    void ClassUnknown_62_099d40();
    void ClassUnknown_62_09a0b0();
    void ClassUnknown_62_09b430();
};
class ClassUnknown_63 {
public:
    void ClassUnknown_63_1682f0();
    void ClassUnknown_63_168340();
    void ClassUnknown_63_168430();
    void ClassUnknown_63_168460();
    void ClassUnknown_63_168500();
    void ClassUnknown_63_1688b0();
    void ClassUnknown_63_1688f0();
};
class ClassUnknown_64 {
public:
    void ClassUnknown_64_1682a0();
    void ClassUnknown_64_1915c0();
    void ClassUnknown_64_191800();
    void ClassUnknown_64_191840();
    void ClassUnknown_64_191890();
    void ClassUnknown_64_1918c0();
    void ClassUnknown_64_191a70();
};
class ClassUnknown_65 {
public:
    void ClassUnknown_65_095750();
    void ClassUnknown_65_095890();
    void ClassUnknown_65_0aa6e0();
    void ClassUnknown_65_151da0();
    void ClassUnknown_65_151e20();
    void ClassUnknown_65_15b340();
    void ClassUnknown_65_164830();
    void ClassUnknown_65_164960();
};
class ClassUnknown_66 {
public:
    void ClassUnknown_66_161370();
    void ClassUnknown_66_166d40();
};
class ClassUnknown_67 {
public:
    void ClassUnknown_67_191ad0();
    void ClassUnknown_67_191b10();
    void ClassUnknown_67_191c30();
};
class ClassUnknown_68 {
public:
    void ClassUnknown_68_0a32c0();
    void ClassUnknown_68_0a3360();
    void ClassUnknown_68_0a33a0();
    void ClassUnknown_68_0a33e0();
    void ClassUnknown_68_0a3460();
    void ClassUnknown_68_0a3820();
    void ClassUnknown_68_0a3b50();
    void ClassUnknown_68_0a3c90();
    void ClassUnknown_68_0a3dc0();
    void ClassUnknown_68_0a4840();
    void ClassUnknown_68_0a5310();
    void ClassUnknown_68_0a5d90();
    void ClassUnknown_68_0a7260();
    void ClassUnknown_68_0a9480();
    void ClassUnknown_68_0a9500();
    void ClassUnknown_68_0a9550();
    void ClassUnknown_68_0a95d0();
    void ClassUnknown_68_0a9660();
};
class ClassUnknown_69 {
public:
    void ClassUnknown_69_058b60();
    void ClassUnknown_69_10d150();
    void ClassUnknown_69_1504d0();
    void ClassUnknown_69_15b2c0();
};
class ClassUnknown_7 {
public:
    void ClassUnknown_7_0fc9c0();
    void ClassUnknown_7_0fca10();
    void ClassUnknown_7_0fcad0();
    void ClassUnknown_7_0fcb50();
    void ClassUnknown_7_0fcb90();
    void ClassUnknown_7_0fcbc0();
    void ClassUnknown_7_0fcc10();
    void ClassUnknown_7_0fcc50();
    void ClassUnknown_7_0fcc90();
    void ClassUnknown_7_0fccb0();
    void ClassUnknown_7_0fcd70();
    void ClassUnknown_7_0fced0();
    void ClassUnknown_7_0fd330();
    void ClassUnknown_7_0fd3f0();
};
class ClassUnknown_70 {
public:
    void ClassUnknown_70_15b2b0();
};
class ClassUnknown_71 {
public:
    void ClassUnknown_71_15b270();
};
class ClassUnknown_72 {
public:
    void ClassUnknown_72_03d670();
    void ClassUnknown_72_07db20();
    void ClassUnknown_72_07dda0();
    void ClassUnknown_72_15b300();
};
class ClassUnknown_73 {
public:
    void ClassUnknown_73_15b730();
};
class ClassUnknown_74 {
public:
    void ClassUnknown_74_16e360();
};
class ClassUnknown_75 {
public:
    void ClassUnknown_75_0a9cc0();
};
class ClassUnknown_76 {
public:
    void ClassUnknown_76_0aa5a0();
};
class ClassUnknown_77 {
public:
    void ClassUnknown_77_0136d0();
    void ClassUnknown_77_058bc0();
    void ClassUnknown_77_058ca0();
    void ClassUnknown_77_16ecd0();
};
class ClassUnknown_78 {
public:
    void ClassUnknown_78_008750();
    void ClassUnknown_78_0310f0();
    void ClassUnknown_78_0312a0();
    void ClassUnknown_78_16da80();
    void ClassUnknown_78_16df40();
};
class ClassUnknown_8 {
public:
    void ClassUnknown_8_0382c0();
    void ClassUnknown_8_038340();
    void ClassUnknown_8_0383b0();
    void ClassUnknown_8_0385e0();
    void ClassUnknown_8_0386b0();
};
class ClassUnknown_81 {
public:
    void ClassUnknown_81_00b790();
    void ClassUnknown_81_00c090();
    void ClassUnknown_81_00c200();
};
class ClassUnknown_82 {
public:
    void ClassUnknown_82_115520();
};
class ClassUnknown_83 {
public:
    void ClassUnknown_83_029a30();
};
class ClassUnknown_84 {
public:
    void ClassUnknown_84_09a260();
};
class ClassUnknown_85 {
public:
    void ClassUnknown_85_139ae0();
    void ClassUnknown_85_139af0();
};
class ClassUnknown_86 {
public:
    void ClassUnknown_86_1497f0();
    void ClassUnknown_86_14a200();
};
class ClassUnknown_87 {
public:
    void ClassUnknown_87_152480();
    void ClassUnknown_87_152520();
    void ClassUnknown_87_1525c0();
};
class ClassUnknown_88 {
public:
    void ClassUnknown_88_0311b0();
};
class ClassUnknown_89 {
public:
    void ClassUnknown_89_14c9f0();
};
class ClassUnknown_9 {
public:
    void ClassUnknown_9_0239d0();
    void ClassUnknown_9_0239f0();
    void ClassUnknown_9_023a10();
    void ClassUnknown_9_023bc0();
    void ClassUnknown_9_023c00();
    void ClassUnknown_9_023c30();
    void ClassUnknown_9_023ca0();
    void ClassUnknown_9_023d10();
    void ClassUnknown_9_024890();
    void ClassUnknown_9_024a90();
    void ClassUnknown_9_085bd0();
};
class ClassUnknown_90 {
public:
    void ClassUnknown_90_1d38a1();
};
class ClassUnknown_91 {
public:
    void ClassUnknown_91_1d496b();
};
class ClassUnknown_92 {
public:
    void ClassUnknown_92_0e3c60();
};
class ClassUnknown_93 {
public:
    void ClassUnknown_93_00d170();
};
class ClassUnknown_94 {
public:
    void ClassUnknown_94_157850();
    void ClassUnknown_94_157980();
    void ClassUnknown_94_157a40();
    void ClassUnknown_94_157a50();
    void ClassUnknown_94_165e30();
    void ClassUnknown_94_165e60();
    void ClassUnknown_94_165ef0();
    void ClassUnknown_94_165f50();
};
class ClassUnknown_95 {
public:
    void ClassUnknown_95_008c00();
};
class ClassUnknown_96 {
public:
    void ClassUnknown_96_03c8f0();
};
class ClassUnknown_97 {
public:
    void ClassUnknown_97_058ee0();
};
class ClassUnknown_98 {
public:
    void ClassUnknown_98_056da0();
};
class ClassUnknown_99 {
public:
    void ClassUnknown_99_046850();
};
class CmdHost_0953f0 {
public:
    void CmdHost_0953f0_08cf30();
    void CmdHost_0953f0_095140();
};
class EngStr {
public:
    void EngStr_115440();
    void EngStr_16da60();
    void EngStr_16e100();
    void EngStr_193080();
};
class HelperHost {
public:
    void HelperHost_1549d0();
    void HelperHost_154a50();
    void HelperHost_1647e0();
};
class InterfaceObject {
public:
    void InterfaceObject_179300();
    void InterfaceObject_179340();
};
class MallocCtor_136230 {
public:
    void MallocCtor_136230_1359a0();
};
class MallocCtor_1375b0 {
public:
    void MallocCtor_1375b0_136370();
    void MallocCtor_1375b0_1374c0();
    void MallocCtor_1375b0_137520();
    void MallocCtor_1375b0_137590();
    void MallocCtor_1375b0_137650();
};
class MallocCtor_15b390 {
public:
    void MallocCtor_15b390_150a70();
    void MallocCtor_15b390_150b00();
    void MallocCtor_15b390_150d60();
    void MallocCtor_15b390_151150();
    void MallocCtor_15b390_151320();
    void MallocCtor_15b390_151c00();
    void MallocCtor_15b390_15b940();
};
class MallocCtor_1615a0 {
public:
    void MallocCtor_1615a0_0311e0();
};
class MallocCtor_16b510 {
public:
    void MallocCtor_16b510_16a410();
    void MallocCtor_16b510_16a510();
    void MallocCtor_16b510_16b720();
};
class MallocCtor_16bfa0 {
public:
    void MallocCtor_16bfa0_16ab20();
    void MallocCtor_16bfa0_16bd10();
    void MallocCtor_16bfa0_16bd90();
    void MallocCtor_16bfa0_192060();
};
class MallocCtor_17fdb0 {
public:
    void MallocCtor_17fdb0_17e450();
    void MallocCtor_17fdb0_17e4a0();
    void MallocCtor_17fdb0_17e510();
    void MallocCtor_17fdb0_17e760();
    void MallocCtor_17fdb0_17e780();
    void MallocCtor_17fdb0_17fdf0();
};
class MinervaInner {
public:
    void MinervaInner_136500();
    void MinervaInner_136690();
    void MinervaInner_1366f0();
    void MinervaInner_136910();
    void MinervaInner_136d80();
    void MinervaInner_136de0();
    void MinervaInner_136ed0();
    void MinervaInner_1371a0();
    void MinervaInner_137710();
    void MinervaInner_137780();
    void MinervaInner_137900();
    void MinervaInner_1379d0();
    void MinervaInner_137b70();
};
class PaintHost_0fac70 {
public:
    void PaintHost_0fac70_0140d0();
    void PaintHost_0fac70_014340();
    void PaintHost_0fac70_0147b0();
    void PaintHost_0fac70_08c610();
    void PaintHost_0fac70_08cd90();
    void PaintHost_0fac70_0fa300();
};
class Region_182ab0 {
public:
    void Region_182ab0_0a0280();
    void Region_182ab0_0a0360();
    void Region_182ab0_182b30();
    void Region_182ab0_182b60();
    void Region_182ab0_182ba0();
    void Region_182ab0_182be0();
    void Region_182ab0_182da0();
    void Region_182ab0_182dd0();
    void Region_182ab0_182df0();
    void Region_182ab0_182e60();
    void Region_182ab0_182ed0();
    void Region_182ab0_182f90();
    void Region_182ab0_183030();
    void Region_182ab0_1830b0();
    void Region_182ab0_1831a0();
    void Region_182ab0_183210();
    void Region_182ab0_183230();
};
class RegistryHelper {
public:
    void RegistryHelper_114fa0();
};
class RemusParseSource {
public:
    void RemusParseSource_139800();
};
class RngBox_00cd70 {
public:
    void RngBox_00cd70_00bb40();
    void RngBox_00cd70_00be50();
    void RngBox_00cd70_00c2a0();
    void RngBox_00cd70_00cb30();
};
class StatusBarItem {
public:
    void StatusBarItem_0d1b30();
    void StatusBarItem_0d6560();
    void StatusBarItem_0d9290();
    void StatusBarItem_0da030();
};
class Timer_1380d0 {
public:
    void Timer_1380d0_137340();
    void Timer_1380d0_137380();
    void Timer_1380d0_137cd0();
    void Timer_1380d0_137cf0();
    void Timer_1380d0_137d10();
    void Timer_1380d0_137dc0();
    void Timer_1380d0_137ed0();
    void Timer_1380d0_137f00();
    void Timer_1380d0_137f30();
};
class UnknownClassArrays {
public:
    void UnknownClassArrays_025c20();
    void UnknownClassArrays_025d90();
    void UnknownClassArrays_026470();
    void UnknownClassArrays_029b40();
    void UnknownClassArrays_02ade0();
    void UnknownClassArrays_02b420();
    void UnknownClassArrays_02bfc0();
    void UnknownClassArrays_02c0a0();
    void UnknownClassArrays_02d800();
    void UnknownClassArrays_02ed90();
    void UnknownClassArrays_02edb0();
    void UnknownClassArrays_02f620();
    void UnknownClassArrays_0300c0();
    void UnknownClassArrays_030530();
    void UnknownClassArrays_0305b0();
    void UnknownClassArrays_030730();
    void UnknownClassArrays_030b20();
    void UnknownClassArrays_030f20();
    void UnknownClassArrays_034460();
};
class UnknownClassInCGruntzMgr {
public:
    void UnknownClassInCGruntzMgr_01f450();
    void UnknownClassInCGruntzMgr_0da870();
    void UnknownClassInCGruntzMgr_0da960();
    void UnknownClassInCGruntzMgr_0dace0();
    void UnknownClassInCGruntzMgr_0dafb0();
};
class WndHolder_13d4c0 {
public:
    void WndHolder_13d4c0_0946a0();
    void WndHolder_13d4c0_094920();
    void WndHolder_13d4c0_094a20();
    void WndHolder_13d4c0_094a60();
    void WndHolder_13d4c0_094ae0();
    void WndHolder_13d4c0_094b20();
    void WndHolder_13d4c0_094b90();
    void WndHolder_13d4c0_13d470();
    void WndHolder_13d4c0_13d4e0();
};
class WwdFile {
public:
    void WwdFile_00a000();
    void WwdFile_162010();
    void WwdFile_163300();
    void WwdFile_163370();
};

#endif
