// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.
// Trace-discovered class memberships (docs/this-pointer-classes.csv): each
// `<Class>_<rva>()` is a recovered __thiscall method, defined as an RVA stub in
// src/Stub/Discovered.cpp. Minimal decls; real classes are fully modelled in
// their own TUs (separate translation unit, so this is conflict-free).
#ifndef GRUNTZ_STUB_DISCOVERED_H
#define GRUNTZ_STUB_DISCOVERED_H

class CBattlezDlgColors {
public:
    void CBattlezDlgColors_017ac0();
};
class CBehindCandy {
public:
    void CBehindCandy_00fb70();
    void CBehindCandy_00fc30();
};
class CBehindCandyAni {
public:
    void CBehindCandyAni_0100f0();
    void CBehindCandyAni_0adbb0();
};
// CBrickz's four terrain-grid methods (0x077790/0x081e10/0x082030/0x09356c) were
// reconstructed into src/Gruntz/Brickz.cpp (the real CBrickz TU); no stubs remain.
// CButeMgr lexer cluster migrated to src/Bute/ButeMgr.cpp (its real class TU);
// only the EH-frame scalar destructor stays here, deferred to the final sweep.
class CButeMgr {
public:
    void CButeMgr_0213c0();
};
class CButeTree {
public:
    void CButeTree_16e070();
};
class CCheckpointDlg {
public:
    void CCheckpointDlg_023570();
};
class CCheckpointTrigger {
public:
    void CCheckpointTrigger_011480();
};
class CCreditsState {
public:
    void CCreditsState_038f00();
    void CCreditsState_039c40();
    void CCreditsState_039c60();
    void CCreditsState_039d00();
};
class CCursorSnapSprite {
public:
    void CCursorSnapSprite_011880();
    void CCursorSnapSprite_011920();
};
class CDDPalette {
public:
    void CDDPalette_1474d0();
    void CDDPalette_147530();
};
class CDDSurface {
public:
    void CDDSurface_142a40();
};
class CDDrawSubMgr {
public:
    void CDDrawSubMgr_031250();
    void CDDrawSubMgr_159600();
    void CDDrawSubMgr_15c360();
};
class CDDrawSubMgrLeaf {
public:
    void CDDrawSubMgrLeaf_114120();
    void CDDrawSubMgrLeaf_157d70();
    void CDDrawSubMgrLeaf_157ee0();
};
class CDDrawSurfaceMgr {
public:
    void CDDrawSurfaceMgr_156020();
};
class CDDrawWorkerList {
public:
    void CDDrawWorkerList_163bc0();
};
class CDDrawWorkerMapSmall {
public:
    void CDDrawWorkerMapSmall_156d20();
    void CDDrawWorkerMapSmall_165810();
};
// 0x151f00 / 0x15cc30 are worker-object methods (g_severusWorkerVtbl), not
// registry methods; the four map-holder methods were reconstructed in the TU.
class CSeverusWorker {
public:
    void CSeverusWorker_151f00();
    void CSeverusWorker_15cc30();
};
class CDoNothing {
public:
    void CDoNothing_00f6b0();
    void CDoNothing_00f770();
};
class CDroppedObject {
public:
    void CDroppedObject_0125b0();
    void CDroppedObject_0c6bd0();
};
class CDroppedObjectShadow {
public:
    void CDroppedObjectShadow_012670();
};
class CExitTrigger {
public:
    void CExitTrigger_010870();
    void CExitTrigger_0108c0();
};
class CExplosion {
public:
    void CExplosion_012ec0();
};
class CEyeCandy {
public:
    void CEyeCandy_00fca0();
    void CEyeCandy_00fd60();
};
class CFortressFlag {
public:
    void CFortressFlag_010e90();
    void CFortressFlag_046410();
};
class CGrunt {
public:
    void CGrunt_057c40();
};
class CGruntAnimPlayer {
public:
    void CGruntAnimPlayer_150610();
};
class CGruntCreationPoint {
public:
    void CGruntCreationPoint_010730();
    void CGruntCreationPoint_03ecc0();
};
class CGruntHealthSprite {
public:
    void CGruntHealthSprite_011fb0();
    void CGruntHealthSprite_07f0d0();
};
class CGruntPowerupSprite {
public:
    void CGruntPowerupSprite_012370();
    void CGruntPowerupSprite_080380();
    void CGruntPowerupSprite_080410();
};
class CGruntSelectedSprite {
public:
    void CGruntSelectedSprite_011e80();
    void CGruntSelectedSprite_07e9c0();
    void CGruntSelectedSprite_07e9f0();
};
class CGruntStartingPoint {
public:
    void CGruntStartingPoint_010670();
};
class CGruntToySprite {
public:
    void CGruntToySprite_0122b0();
    void CGruntToySprite_07f920();
    void CGruntToySprite_07f960();
};
class CGruntToyTimeSprite {
public:
    void CGruntToyTimeSprite_012130();
};
class CGruntzMgr {
public:
    void CGruntzMgr_08b960();
};
class CGuardPoint {
public:
    void CGuardPoint_010410();
};
class CInGameText {
public:
    void CInGameText_011dc0();
    void CInGameText_099460();
    void CInGameText_099a30();
};
class CKitchenSlime {
public:
    void CKitchenSlime_013100();
    void CKitchenSlime_0b2940();
};
class CLightFx {
public:
    void CLightFx_012430();
    void CLightFx_09d520();
    void CLightFx_09d770();
};
class CMapArrayA {
public:
    void CMapArrayA_09e740();
};
class CMapArrayB {
public:
    void CMapArrayB_09e860();
};
class CMenuState {
public:
    void CMenuState_0a0d40();
};
class NetUnattributed {
public:
    void NetUnattributed_007c20();
    void NetUnattributed_099d10();
    void NetUnattributed_0b89e0();
    void NetUnattributed_0f93b0();
    void NetUnattributed_11f618();
    void NetUnattributed_18c022();
};
class CObjectDropper {
public:
    void CObjectDropper_0124f0();
};
class CParticlez {
public:
    void CParticlez_012d90();
    void CParticlez_046d30();
};
class CPlay {
public:
    void CPlay_0d1b60();
};
class CRollingBall {
public:
    void CRollingBall_012f80();
    void CRollingBall_0b0fe0();
};
class CSBI_RectOnly {
public:
    void CSBI_RectOnly_0c8980();
    void CSBI_RectOnly_0ebd70();
    void CSBI_RectOnly_105800();
    void CSBI_RectOnly_1084d0();
};
class CSecretLevelTrigger {
public:
    void CSecretLevelTrigger_010c50();
    void CSecretLevelTrigger_042ac0();
};
class CSimpleAnimation {
public:
    void CSimpleAnimation_00f9d0();
    void CSimpleAnimation_0abf70();
};
class CSingleAnimation {
public:
    void CSingleAnimation_010540();
};
// CState migrated to src/Gruntz/GameMode.cpp (CMenuState/CBootyState methods).
class CStaticHazard {
public:
    void CStaticHazard_012b30();
    void CStaticHazard_0fbbf0();
};
// CStatusBarItem's discovered methods were recovered as CSBI_MenuItem and moved
// to src/Gruntz/SBI_MenuItem.cpp (see the note in Discovered.cpp).
class CTeleporter {
public:
    void CTeleporter_010dd0();
    void CTeleporter_0419e0();
};
class CTileTriggerSwitch {
public:
    void CTileTriggerSwitch_0110f0();
};
class CTileTriggerSwitchLogic {
public:
    void CTileTriggerSwitchLogic_112c70();
    void CTileTriggerSwitchLogic_117280();
};
class CTileTriggerTransition {
public:
    void CTileTriggerTransition_011730();
    void CTileTriggerTransition_0117f0();
    void CTileTriggerTransition_110070();
};
class CToobSpikez {
public:
    void CToobSpikez_012c60();
    void CToobSpikez_114860();
};
class CUserLogic {
public:
    void CUserLogic_00f2f0();
    void CUserLogic_04ac10();
    // 0x04b370/0x04c170 -> CGrunt::StepArrivalDrop/StepGruntMovement (Grunt.cpp)
    void CUserLogic_051850();
    void CUserLogic_051a20();
    // 0x052fb0 -> CGrunt::StepAnimDispatchA (Grunt.cpp)
    void CUserLogic_053b80();
    void CUserLogic_059230();
    void CUserLogic_05caa0();
    // 0x05f310 -> CGrunt::StepCoordResolve (Grunt.cpp)
    void CUserLogic_062110();
    void CUserLogic_0637a0();
    void CUserLogic_067850();
    // 0x06a6d0 -> CGrunt::StepAnimDispatchB (Grunt.cpp)
    void CUserLogic_16e7f0();
    void CUserLogic_16ea90();
};
class CVoiceTrigger {
public:
    void CVoiceTrigger_0135a0();
    void CVoiceTrigger_11a700();
};
class CWayPoint {
public:
    void CWayPoint_0102e0();
};
class CWormhole {
public:
    void CWormhole_010980();
    void CWormhole_0403b0();
};
class ClassUnknown_1 {
public:
    void ClassUnknown_1_134be0();
    void ClassUnknown_1_134c60();
    void ClassUnknown_1_134c80();
};
class ClassUnknown_10 {
public:
    void ClassUnknown_10_0e2250();
    void ClassUnknown_10_0e2290();
    void ClassUnknown_10_0e22d0();
    void ClassUnknown_10_0e2360();
    void ClassUnknown_10_0e2390();
    void ClassUnknown_10_0e23c0();
    void ClassUnknown_10_0e2890();
};
class ClassUnknown_100 {
public:
    void ClassUnknown_100_109bb0();
    void ClassUnknown_100_10a0f0();
    void ClassUnknown_100_10a2f0();
};
class ClassUnknown_101 {
public:
    void ClassUnknown_101_11f6b9();
};
class ClassUnknown_102 {
public:
    void ClassUnknown_102_06b2e0();
};
class ClassUnknown_103 {
public:
    void ClassUnknown_103_148d10();
};
class ClassUnknown_104 {
public:
    void ClassUnknown_104_152e30();
    void ClassUnknown_104_165730();
};
class ClassUnknown_105 {
public:
    void ClassUnknown_105_1657a0();
};
class ClassUnknown_106 {
public:
    void ClassUnknown_106_0af0a0();
};
class ClassUnknown_107 {
public:
    void ClassUnknown_107_10d3d0();
};
class ClassUnknown_109 {
public:
    void ClassUnknown_109_0aa960();
};
class ClassUnknown_11 {
public:
    void ClassUnknown_11_13abc0();
    void ClassUnknown_11_13b850();
    void ClassUnknown_11_13bff0();
    void ClassUnknown_11_13c030();
    void ClassUnknown_11_13c210();
};
class ClassUnknown_110 {
public:
    void ClassUnknown_110_0fb660();
};
class ClassUnknown_111 {
public:
    void ClassUnknown_111_029a80();
};
class ClassUnknown_112 {
public:
    void ClassUnknown_112_021c40();
};
class ClassUnknown_113 {
public:
    void ClassUnknown_113_114480();
};
class ClassUnknown_114 {
public:
    void ClassUnknown_114_0e6380();
    void ClassUnknown_114_104bb0();
};
class ClassUnknown_115 {
public:
    void ClassUnknown_115_0e8c70();
    void ClassUnknown_115_0e8cb0();
    void ClassUnknown_115_0e8dc0();
    void ClassUnknown_115_104ce0();
};
class ClassUnknown_116 {
public:
    void ClassUnknown_116_0e7980();
    void ClassUnknown_116_0e7b00();
    void ClassUnknown_116_0ea0f0();
    void ClassUnknown_116_1047f0();
    void ClassUnknown_116_1048f0();
};
class ClassUnknown_117 {
public:
    void ClassUnknown_117_0ea470();
    void ClassUnknown_117_0ea4b0();
    void ClassUnknown_117_0ea6c0();
    void ClassUnknown_117_104b00();
};
class ClassUnknown_118 {
public:
    void ClassUnknown_118_0eb6b0();
    void ClassUnknown_118_0eb740();
    void ClassUnknown_118_0eb830();
    void ClassUnknown_118_0eb880();
    void ClassUnknown_118_104a00();
};
class ClassUnknown_119 {
public:
    void ClassUnknown_119_1591b0();
};
class ClassUnknown_120 {
public:
    void ClassUnknown_120_1852e0();
};
class ClassUnknown_121 {
public:
    void ClassUnknown_121_139cf0();
};
class ClassUnknown_122 {
public:
    void ClassUnknown_122_1397a0();
};
class ClassUnknown_123 {
public:
    void ClassUnknown_123_16dfc0();
};
class ClassUnknown_124 {
public:
    void ClassUnknown_124_11eaf5();
};
class ClassUnknown_125 {
public:
    void ClassUnknown_125_11eaa8();
};
class ClassUnknown_126 {
public:
    void ClassUnknown_126_11cf30();
};
class ClassUnknown_127 {
public:
    void ClassUnknown_127_11cee3();
};
class ClassUnknown_128 {
public:
    void ClassUnknown_128_174d70();
};
class ClassUnknown_129 {
public:
    void ClassUnknown_129_016460();
};
class ClassUnknown_14 {
public:
    void ClassUnknown_14_13a000();
};
class ClassUnknown_15 {
public:
    void ClassUnknown_15_13c520();
    void ClassUnknown_15_13c590();
    void ClassUnknown_15_13c600();
    void ClassUnknown_15_13c830();
};
class ClassUnknown_17 {
public:
    void ClassUnknown_17_16f6c0();
    void ClassUnknown_17_16f760();
    void ClassUnknown_17_170100();
};
class ClassUnknown_18 {
public:
    void ClassUnknown_18_16f7f0();
};
class ClassUnknown_19 {
public:
    void ClassUnknown_19_16fc70();
};
class ClassUnknown_2 {
public:
    void ClassUnknown_2_14f080();
    void ClassUnknown_2_14f310();
};
class ClassUnknown_20 {
public:
    void ClassUnknown_20_16df70();
};
class ClassUnknown_21 {
public:
    void ClassUnknown_21_16e480();
};
class ClassUnknown_22 {
public:
    void ClassUnknown_22_022b00();
    void ClassUnknown_22_022be0();
    void ClassUnknown_22_022c80();
    void ClassUnknown_22_085e60();
};
// ClassUnknown_24 -> CGruntSpawnConfig (all 10 graduated to
// src/Gruntz/CGruntSpawnConfig.cpp).
class ClassUnknown_25 {
public:
    void ClassUnknown_25_099ca0();
    void ClassUnknown_25_09a450();
    void ClassUnknown_25_11c560();
};
class ClassUnknown_26 {
public:
    void ClassUnknown_26_11c630();
};
class ClassUnknown_27 {
public:
    void ClassUnknown_27_13a260();
    void ClassUnknown_27_13a280();
    void ClassUnknown_27_13a2b0();
    void ClassUnknown_27_13a2d0();
    void ClassUnknown_27_13a2f0();
    void ClassUnknown_27_13a310();
};
class ClassUnknown_28 {
public:
    void ClassUnknown_28_01f940();
    void ClassUnknown_28_158760();
};
class ClassUnknown_29 {
public:
    void ClassUnknown_29_137110();
};
class ClassUnknown_3 {
public:
    void ClassUnknown_3_09dad0();
    void ClassUnknown_3_09dc80();
    void ClassUnknown_3_09dcb0();
};
class ClassUnknown_30 {
public:
    void ClassUnknown_30_136f60();
    void ClassUnknown_30_1390e0();
    void ClassUnknown_30_139110();
    void ClassUnknown_30_1391e0();
};
class ClassUnknown_31 {
public:
    void ClassUnknown_31_152f20();
    void ClassUnknown_31_152fb0();
    void ClassUnknown_31_153810();
};
// ClassUnknown_32 reconstructed as CDDrawPtrCollections in
// src/Gruntz/CDDrawPtrCollections.cpp.
class ClassUnknown_33 {
public:
    void ClassUnknown_33_153180();
};
class ClassUnknown_34 {
public:
    void ClassUnknown_34_148ce0();
    void ClassUnknown_34_1490d0();
};
class ClassUnknown_35 {
public:
    void ClassUnknown_35_151eb0();
    void ClassUnknown_35_1557a0();
};
class ClassUnknown_36 {
public:
    void ClassUnknown_36_14dd90();
};
// ClassUnknown_37 == tomalla CDDrawSubMgrLeaf (reconstructed in
// src/Gruntz/CDDrawSubMgrLeaf.cpp). Only the two large /GX builders remain
// stubbed here (factory 0x1528d0, recursive directory walker 0x152ad0).
class ClassUnknown_37 {
public:
    void ClassUnknown_37_1528d0();
    void ClassUnknown_37_152ad0();
};
class ClassUnknown_38 {
public:
    void ClassUnknown_38_06b270();
    void ClassUnknown_38_165460();
    void ClassUnknown_38_1655c0();
};
class ClassUnknown_39 {
public:
    void ClassUnknown_39_168c60();
    void ClassUnknown_39_168e50();
};
class ClassUnknown_4 {
public:
    void ClassUnknown_4_150180();
    void ClassUnknown_4_150190();
    void ClassUnknown_4_1501a0();
    void ClassUnknown_4_1503c0();
};
class ClassUnknown_40 {
public:
    void ClassUnknown_40_168d00();
};
class ClassUnknown_41 {
public:
    void ClassUnknown_41_165dd0();
    void ClassUnknown_41_168ee0();
    void ClassUnknown_41_168fb0();
};
class ClassUnknown_42 {
public:
    void ClassUnknown_42_0e2df0();
    void ClassUnknown_42_0e32e0();
};
class ClassUnknown_43 {
public:
    void ClassUnknown_43_142360(); // CFileImage 2nd destructor copy (deferred, see Discovered.cpp)
    void ClassUnknown_43_144640(); // CFileImage::SaveRle16 (deferred, see Discovered.cpp)
};
class ClassUnknown_44 {
public:
    void ClassUnknown_44_158680();
    void ClassUnknown_44_1587c0();
};
// ClassUnknown_45 fully recovered -> CMenuPage (src/Gruntz/MenuPage.cpp).
// ClassUnknown_46 fully recovered -> CMenuItem (src/Gruntz/MenuItem.cpp).
class ClassUnknown_47 {
public:
    void ClassUnknown_47_0f9280();
    void ClassUnknown_47_17e7b0();
    void ClassUnknown_47_17e880();
};
class ClassUnknown_49 {
public:
    void ClassUnknown_49_182940();
    void ClassUnknown_49_182a80();
};
class ClassUnknown_5 {
public:
    void ClassUnknown_5_150040();
};
class ClassUnknown_50 {
public:
    void ClassUnknown_50_0d5e80();
    void ClassUnknown_50_153260();
    void ClassUnknown_50_153790();
};
class ClassUnknown_51 {
public:
    void ClassUnknown_51_1154b0();
};
class ClassUnknown_53 {
public:
    void ClassUnknown_53_029ac0();
};
class ClassUnknown_54 {
public:
    void ClassUnknown_54_135110();
};
class ClassUnknown_55 {
public:
    void ClassUnknown_55_137060();
    void ClassUnknown_55_1370d0();
};
class ClassUnknown_56 {
public:
    void ClassUnknown_56_08c3b0();
};
class ClassUnknown_57 {
public:
    void ClassUnknown_57_03a1d0();
    void ClassUnknown_57_1590f0();
    void ClassUnknown_57_163e20();
    void ClassUnknown_57_163f40();
};
class ClassUnknown_58 {
public:
    void ClassUnknown_58_0204e0();
    void ClassUnknown_58_020510();
    void ClassUnknown_58_020530();
    void ClassUnknown_58_021140();
};
class ClassUnknown_59 {
public:
    void ClassUnknown_59_0e6c80();
    void ClassUnknown_59_0e74f0();
    void ClassUnknown_59_0e86e0();
    void ClassUnknown_59_0e9800();
    void ClassUnknown_59_0e9820();
    void ClassUnknown_59_0e99c0();
    void ClassUnknown_59_100700();
    void ClassUnknown_59_100870();
    void ClassUnknown_59_105200();
};
class ClassUnknown_6 {
public:
    void ClassUnknown_6_14dcf0();
};
class ClassUnknown_60 {
public:
    void ClassUnknown_60_0ebd30();
};
class ClassUnknown_61 {
public:
    void ClassUnknown_61_120120();
    void ClassUnknown_61_17b500();
};
class ClassUnknown_62 {
public:
    void ClassUnknown_62_099c20();
    void ClassUnknown_62_099d40();
    void ClassUnknown_62_09a0b0();
    void ClassUnknown_62_09b430();
};
class ClassUnknown_64 {
public:
    void ClassUnknown_64_1682a0();
    void ClassUnknown_64_1915c0();
    void ClassUnknown_64_191800();
    void ClassUnknown_64_191840();
    void ClassUnknown_64_191890();
    void ClassUnknown_64_1918c0();
    void ClassUnknown_64_191a70();
};
// NOTE: the five real members (151da0/151e20/15b340/164830/164960) of this
// trace-cluster are reconstructed as CLogicRecord (src/Gruntz/LogicRecord.cpp).
// The three remaining handlers are __cdecl free functions (no ecx use) that
// were trace-attributed here by ecx-leftover coincidence - NOT members; they
// dispatch on arg->m_7c->m_1c and `new` a sub-record. Kept stubbed pending
// their own (message-handler) cluster.
class ClassUnknown_65 {
public:
    void ClassUnknown_65_095750();
    void ClassUnknown_65_095890();
    void ClassUnknown_65_0aa6e0();
};
class ClassUnknown_66 {
public:
    void ClassUnknown_66_161370();
    void ClassUnknown_66_166d40();
};
class ClassUnknown_67 {
public:
    void ClassUnknown_67_191ad0();
    void ClassUnknown_67_191b10();
    void ClassUnknown_67_191c30();
};
class ClassUnknown_68 {
public:
    void ClassUnknown_68_0a3460();
    void ClassUnknown_68_0a3820();
};
class ClassUnknown_69 {
public:
    void ClassUnknown_69_058b60();
    void ClassUnknown_69_10d150();
    void ClassUnknown_69_1504d0();
    void ClassUnknown_69_15b2c0();
};
class ClassUnknown_70 {
public:
    void ClassUnknown_70_15b2b0();
};
class ClassUnknown_71 {
public:
    void ClassUnknown_71_15b270();
};
class ClassUnknown_72 {
public:
    void ClassUnknown_72_03d670();
    void ClassUnknown_72_07db20();
    void ClassUnknown_72_07dda0();
    void ClassUnknown_72_15b300();
};
class ClassUnknown_73 {
public:
    void ClassUnknown_73_15b730();
};
class ClassUnknown_74 {
public:
    void ClassUnknown_74_16e360();
};
class ClassUnknown_75 {
public:
    void ClassUnknown_75_0a9cc0();
};
class ClassUnknown_76 {
public:
    void ClassUnknown_76_0aa5a0();
};
class ClassUnknown_77 {
public:
    void ClassUnknown_77_16ecd0();
};
class ClassUnknown_78 {
public:
    void ClassUnknown_78_008750();
    void ClassUnknown_78_0310f0();
    void ClassUnknown_78_0312a0();
    void ClassUnknown_78_16da80();
    void ClassUnknown_78_16df40();
};
class ClassUnknown_8 {
public:
    void ClassUnknown_8_0382c0();
    void ClassUnknown_8_038340();
    void ClassUnknown_8_0383b0();
    void ClassUnknown_8_0385e0();
    void ClassUnknown_8_0386b0();
};
class ClassUnknown_81 {
public:
    void ClassUnknown_81_00b790();
    void ClassUnknown_81_00c090();
    void ClassUnknown_81_00c200();
};
class ClassUnknown_82 {
public:
    void ClassUnknown_82_115520();
};
class ClassUnknown_83 {
public:
    void ClassUnknown_83_029a30();
};
class ClassUnknown_84 {
public:
    void ClassUnknown_84_09a260();
};
class ClassUnknown_85 {
public:
    void ClassUnknown_85_139ae0();
    void ClassUnknown_85_139af0();
};
class ClassUnknown_87 {
public:
    void ClassUnknown_87_152480();
    void ClassUnknown_87_152520();
    void ClassUnknown_87_1525c0();
};
class ClassUnknown_88 {
public:
    void ClassUnknown_88_0311b0();
};
class ClassUnknown_89 {
public:
    void ClassUnknown_89_14c9f0();
};
class ClassUnknown_90 {
public:
    void ClassUnknown_90_1d38a1();
};
class ClassUnknown_91 {
public:
    void ClassUnknown_91_1d496b();
};
class ClassUnknown_92 {
public:
    void ClassUnknown_92_0e3c60();
};
class ClassUnknown_93 {
public:
    void ClassUnknown_93_00d170();
};
class ClassUnknown_94 {
public:
    void ClassUnknown_94_157850();
    void ClassUnknown_94_157980();
    void ClassUnknown_94_157a40();
    void ClassUnknown_94_157a50();
    void ClassUnknown_94_165e30();
    void ClassUnknown_94_165e60();
    void ClassUnknown_94_165ef0();
    void ClassUnknown_94_165f50();
};
class ClassUnknown_95 {
public:
    void ClassUnknown_95_008c00();
};
class ClassUnknown_96 {
public:
    void ClassUnknown_96_03c8f0();
};
class ClassUnknown_97 {
public:
    void ClassUnknown_97_058ee0();
};
class ClassUnknown_98 {
public:
    void ClassUnknown_98_056da0();
};
class ClassUnknown_99 {
public:
    void ClassUnknown_99_046850();
};
class CmdHost_0953f0 {
public:
    void CmdHost_0953f0_08cf30();
    void CmdHost_0953f0_095140();
};
class EngStr {
public:
    void EngStr_115440();
    void EngStr_16da60();
    void EngStr_16e100();
    void EngStr_193080();
};
class HelperHost {
public:
    void HelperHost_1549d0();
    void HelperHost_154a50();
    void HelperHost_1647e0();
};
class InterfaceObject {
public:
    void InterfaceObject_179300();
    void InterfaceObject_179340();
};
class MallocCtor_136230 {
public:
    void MallocCtor_136230_1359a0();
};
class MallocCtor_1375b0 {
public:
    void MallocCtor_1375b0_136370();
    void MallocCtor_1375b0_1374c0();
    void MallocCtor_1375b0_137520();
    void MallocCtor_1375b0_137590();
    void MallocCtor_1375b0_137650();
};
class MallocCtor_1615a0 {
public:
    void MallocCtor_1615a0_0311e0();
};
class MallocCtor_16b510 {
public:
    void MallocCtor_16b510_16a410();
    void MallocCtor_16b510_16a510();
    void MallocCtor_16b510_16b720();
};
class MallocCtor_16bfa0 {
public:
    void MallocCtor_16bfa0_16ab20();
    void MallocCtor_16bfa0_16bd10();
    void MallocCtor_16bfa0_16bd90();
    void MallocCtor_16bfa0_192060();
};
class MallocCtor_17fdb0 {
public:
    void MallocCtor_17fdb0_17e450();
    void MallocCtor_17fdb0_17e4a0();
    void MallocCtor_17fdb0_17e510();
    void MallocCtor_17fdb0_17e760();
    void MallocCtor_17fdb0_17e780();
    void MallocCtor_17fdb0_17fdf0();
};
class MinervaInner {
public:
    void MinervaInner_1366f0();
    void MinervaInner_136910();
};
class PaintHost_0fac70 {
public:
    void PaintHost_0fac70_0140d0();
    void PaintHost_0fac70_014340();
    void PaintHost_0fac70_0147b0();
    void PaintHost_0fac70_08c610();
    void PaintHost_0fac70_08cd90();
    void PaintHost_0fac70_0fa300();
};
class RegistryHelper {
public:
    void RegistryHelper_114fa0();
};
class RemusParseSource {
public:
    void RemusParseSource_139800();
};
class RngBox_00cd70 {
public:
    void RngBox_00cd70_00bb40();
    void RngBox_00cd70_00be50();
    void RngBox_00cd70_00c2a0();
    void RngBox_00cd70_00cb30();
};
class StatusBarItem {
public:
    void StatusBarItem_0d1b30();
    void StatusBarItem_0d6560();
    void StatusBarItem_0d9290();
    void StatusBarItem_0da030();
};
class UnknownClassInCGruntzMgr {
public:
    void UnknownClassInCGruntzMgr_01f450();
    void UnknownClassInCGruntzMgr_0da870();
    void UnknownClassInCGruntzMgr_0da960();
    void UnknownClassInCGruntzMgr_0dace0();
    void UnknownClassInCGruntzMgr_0dafb0();
};
class WndHolder_13d4c0 {
public:
    void WndHolder_13d4c0_0946a0();
    void WndHolder_13d4c0_094920();
    void WndHolder_13d4c0_094a20();
    void WndHolder_13d4c0_094a60();
    void WndHolder_13d4c0_094ae0();
    void WndHolder_13d4c0_094b20();
    void WndHolder_13d4c0_094b90();
    void WndHolder_13d4c0_13d470();
    void WndHolder_13d4c0_13d4e0();
};

#endif
