// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.
// Trace-discovered class memberships (from the dynamic this/ecx trace): each
// `<Class>_<rva>()` is a recovered __thiscall method, defined as an RVA stub in
// src/Stub/Discovered.cpp. Minimal decls; real classes are fully modelled in
// their own TUs (separate translation unit, so this is conflict-free).
#ifndef GRUNTZ_STUB_DISCOVERED_H
#define GRUNTZ_STUB_DISCOVERED_H

class CAniRecord {
public:
    void CAniRecord_1657a0();
};
class CButeStore {
public:
    void CButeStore_174d70();
};
class CCheckpointTrigger {
public:
    void CCheckpointTrigger_011480();
};
class CDDSurface {
public:
    void CDDSurface_142a40();
};
class CGrunt {
public:
    void CGrunt_0ec670();
    void CGrunt_0ef6b0();
};
class CGruntToyTimeSprite {
public:
    void CGruntToyTimeSprite_012130();
};
class CGruntzMgr {
public:
    void CGruntzMgr_08b960();
};
class CGruntzSingleCommand {
public:
    void CGruntzSingleCommand_0ec1c0();
    void CGruntzSingleCommand_11f618();
    void CGruntzSingleCommand_135110();
    void CGruntzSingleCommand_18c022();
};
class CLogicRecord {
public:
    void CLogicRecord_0fb660();
    void CLogicRecord_10d3d0();
};
class CPlay {
public:
    void CPlay_0cb480();
    void CPlay_0d53d0();
    void CPlay_0d9290();
};
class CSpotLight {
public:
    void CSpotLight_0b1ee0();
};
class CUserLogic {
public:
    void CUserLogic_16ea90();
};
class ClassUnknown_1 {
public:
    void ClassUnknown_1_150040();
};
class ClassUnknown_11 {
public:
    void ClassUnknown_11_14dd90();
};
class ClassUnknown_13 {
public:
    void ClassUnknown_13_1154b0();
    void ClassUnknown_13_115520();
};
class ClassUnknown_14 {
public:
    void ClassUnknown_14_029ac0();
};
class ClassUnknown_15 {
public:
    void ClassUnknown_15_1d38a1();
};
class ClassUnknown_16 {
public:
    void ClassUnknown_16_1d496b();
};
class ClassUnknown_17 {
public:
    void ClassUnknown_17_0ebd30();
};
class ClassUnknown_2 {
public:
    void ClassUnknown_2_14dcf0();
};
class ClassUnknown_21 {
public:
    void ClassUnknown_21_15b2b0();
};
class ClassUnknown_22 {
public:
    void ClassUnknown_22_15b270();
};
class ClassUnknown_23 {
public:
    void ClassUnknown_23_16e360();
};
class ClassUnknown_28 {
public:
    void ClassUnknown_28_0311b0();
};
class ClassUnknown_29 {
public:
    void ClassUnknown_29_029a30();
};
class ClassUnknown_30 {
public:
    void ClassUnknown_30_09a260();
};
class ClassUnknown_33 {
public:
    void ClassUnknown_33_11f6b9();
};
class ClassUnknown_34 {
public:
    void ClassUnknown_34_046850();
};
class ClassUnknown_35 {
public:
    void ClassUnknown_35_021c40();
};
class ClassUnknown_37 {
public:
    void ClassUnknown_37_0deb20();
};
class ClassUnknown_39 {
public:
    void ClassUnknown_39_148d10();
};
class ClassUnknown_4 {
public:
    void ClassUnknown_4_16f760();
};
class ClassUnknown_42 {
public:
    void ClassUnknown_42_0f1c70();
};
class ClassUnknown_43 {
public:
    void ClassUnknown_43_0f7d90();
};
class ClassUnknown_45 {
public:
    void ClassUnknown_45_08c3b0();
};
class ClassUnknown_46 {
public:
    void ClassUnknown_46_1591b0();
};
class ClassUnknown_48 {
public:
    void ClassUnknown_48_139cf0();
};
class ClassUnknown_49 {
public:
    void ClassUnknown_49_1397a0();
};
class ClassUnknown_50 {
public:
    void ClassUnknown_50_16dfc0();
};
class ClassUnknown_51 {
public:
    void ClassUnknown_51_11eaf5();
};
class ClassUnknown_52 {
public:
    void ClassUnknown_52_11eaa8();
};
class ClassUnknown_53 {
public:
    void ClassUnknown_53_11cf30();
};
class ClassUnknown_54 {
public:
    void ClassUnknown_54_11cee3();
};
class ClassUnknown_55 {
public:
    void ClassUnknown_55_016460();
};
class ClassUnknown_8 {
public:
    void ClassUnknown_8_16e480();
};
class ClassUnknown_9 {
public:
    void ClassUnknown_9_11c630();
};

#endif
