"""activate.py - emit activate.ps1 / activate.bat (the flake shellHook, for Windows).

A Python process cannot mutate its parent shell's environment, so - exactly like
vcvarsall.bat - we WRITE shell scripts the user dot-sources/runs to enter the dev
environment. Both set the same variables env.py computes (no wine vars), prepend
the tool dirs to PATH, enable the repo's pre-commit hook, and print a banner.
"""

from __future__ import annotations

from pathlib import Path

from .env import compute, win_toolchain_root

_BANNER = [
    ("target EXE", "%GRUNTZ_EXE%"),
    ("MSVC 5.0  ", "%MSVC_DIR%\\bin\\CL.EXE (native - no wine)"),
    ("tools     ", "objdiff(-cli), vostok-delinker, ghidra, llvm-pdbutil, ninja, rg, jq"),
    ("clang     ", "%GRUNTZ_CLANG%"),
    ("cli       ", "gruntz <cmd>  (init/build/clangd/format/status/...)"),
]


def _ps1(env: dict, path_prepend, repo: Path) -> str:
    L = ["# gruntz Windows dev environment - generated by bootstrap_windows.py.",
         "# Dot-source me:  . .\\build\\win-toolchain\\activate.ps1", ""]
    for k, v in env.items():
        if k.startswith("_"):
            continue
        L.append(f'$env:{k} = "{v}"')
    paths = ";".join(str(p) for p in path_prepend)
    L.append(f'$env:PATH = "{paths};" + $env:PATH')
    L.append(f'$env:INCLUDE = "{env["_INCLUDE_PREPEND"]}" + $(if ($env:INCLUDE) {{ ";" + $env:INCLUDE }} else {{ "" }})')
    L.append(f'$env:LIB = "{env["_LIB_PREPEND"]}" + $(if ($env:LIB) {{ ";" + $env:LIB }} else {{ "" }})')
    L.append(f'$env:PYTHONPATH = "{env["_PYTHONPATH_PREPEND"]}" + $(if ($env:PYTHONPATH) {{ ";" + $env:PYTHONPATH }} else {{ "" }})')
    L.append('git -C "$env:GRUNTZ_DIR" config --local core.hooksPath .githooks 2>$null')
    L.append('Write-Host "[gruntz] Windows dev environment active (native MSVC 5.0, no wine)."')
    for label, val in _BANNER:
        v = val.replace("%GRUNTZ_EXE%", "$env:GRUNTZ_EXE").replace("%MSVC_DIR%", "$env:MSVC_DIR").replace("%GRUNTZ_CLANG%", "$env:GRUNTZ_CLANG")
        L.append(f'Write-Host "[gruntz] {label}: {v}"')
    return "\n".join(L) + "\n"


def _bat(env: dict, path_prepend, repo: Path) -> str:
    L = ["@echo off",
         "rem gruntz Windows dev environment - generated by bootstrap_windows.py.",
         "rem Run me:  build\\win-toolchain\\activate.bat", ""]
    for k, v in env.items():
        if k.startswith("_"):
            continue
        L.append(f'set "{k}={v}"')
    paths = ";".join(str(p) for p in path_prepend)
    L.append(f'set "PATH={paths};%PATH%"')
    L.append(f'set "INCLUDE={env["_INCLUDE_PREPEND"]};%INCLUDE%"')
    L.append(f'set "LIB={env["_LIB_PREPEND"]};%LIB%"')
    L.append(f'set "PYTHONPATH={env["_PYTHONPATH_PREPEND"]};%PYTHONPATH%"')
    L.append('git -C "%GRUNTZ_DIR%" config --local core.hooksPath .githooks >nul 2>&1')
    L.append('echo [gruntz] Windows dev environment active (native MSVC 5.0, no wine).')
    for label, val in _BANNER:
        L.append(f'echo [gruntz] {label}: {val}')
    return "\r\n".join(L) + "\r\n"


def write_scripts(repo: Path) -> tuple[Path, Path]:
    env, path_prepend = compute(repo)
    root = win_toolchain_root(repo)
    root.mkdir(parents=True, exist_ok=True)
    ps1 = root / "activate.ps1"
    bat = root / "activate.bat"
    ps1.write_text(_ps1(env, path_prepend, repo), encoding="utf-8")
    bat.write_text(_bat(env, path_prepend, repo), encoding="utf-8", newline="")
    return ps1, bat
