[package]
name = "gruntz-oracle"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "gruntz-oracle"
path = "src/main.rs"

[[bin]]
name = "fntdump"
path = "src/bin/fntdump.rs"

[dependencies]
gruntz-rez = { workspace = true }
gruntz-codec = { workspace = true }
gruntz-cast = { workspace = true }
clap = { workspace = true }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
png = "0.17"
