#ifndef GRUNTZ_BUTE_BUTELEXACTION_H
#define GRUNTZ_BUTE_BUTELEXACTION_H

#include <Enums.h>

GZ_ENUM_BEGIN(ButeLexAction)
    LEXACT_ERROR = 0,
    LEXACT_TAKE = 1,
    LEXACT_SKIP = 2,
    LEXACT_ACCEPT_TAKE = 3,
    LEXACT_ACCEPT_SKIP = 4,
    LEXACT_ACCEPT_PUSHBACK = 5
GZ_ENUM_END(ButeLexAction)

GZ_ENUM_CONST_BEGIN(ButeLexSlot)
    LEXSLOT_ACTION = 0,
    LEXSLOT_TARGET = 1,
    LEXSLOT_STATE = 2
GZ_ENUM_CONST_END(ButeLexSlot)

#endif // GRUNTZ_BUTE_BUTELEXACTION_H
