#ifndef GRUNTZ_BUTE_BUTETOKEN_H
#define GRUNTZ_BUTE_BUTETOKEN_H

#include <Enums.h>

GZ_ENUM_BEGIN_SPLIT(ButeToken, i16)
    BUTETOK_NONE = 0,
    BUTETOK_END = 1,
    BUTETOK_TAG_OPEN = 2,
    BUTETOK_TAG_CLOSE = 3,
    BUTETOK_NAME = 4,
    BUTETOK_ASSIGN = 5,
    BUTETOK_INT = 6,
    BUTETOK_INT_SIGNED = 7,
    BUTETOK_DOUBLE = 8,
    BUTETOK_STRING = 9,
    BUTETOK_RECT = 10,
    BUTETOK_POINT = 11,
    BUTETOK_VECTOR = 12,
    BUTETOK_RANGE = 13,
    BUTETOK_KEYWORD_DWORD = 14,
    BUTETOK_KEYWORD_FLOAT = 15,
    BUTETOK_FLOAT_SUFFIX = 16
GZ_ENUM_END_SPLIT(ButeToken, i16)

#endif // GRUNTZ_BUTE_BUTETOKEN_H
