#!/usr/bin/env python3
"""configure.py - generate the Gruntz matching build from the units manifest.

Single source of truth: config/units.toml (per-TU). This script reads it and
emits, from one manifest:

  * build.ninja            - the native incremental build graph (Linux ninja
                             driving `wine cl` via scripts/gruntz/build/cc_wrap.py).
  * build/objdiff/objdiff.json - the objdiff project pairing each recompiled
                             base obj against its delinked target obj BY SYMBOL
                             NAME.

(The clang compile DB lives in build/clangd/, generated by scripts/gruntz/init/clangd.py
- the build itself needs no compdb; ninja tracks deps.)

Two graph phases (see docs/build-system.md):
  1. compile -> .obj   - IMPLEMENTED. Each manifest unit's source compiles to
                         build/objdiff/base/<unit>.obj via the `cl` rule.
  2. link -> .EXE      - DEFERRED. A clearly-marked placeholder (emit_link_phase)
                         marks where whole-binary verification will go later.

The TARGET (delink) half is orchestrated as a ninja `delink` rule that runs
scripts/gruntz/build/delink.py (synth_pdb -> vostok-delinker -> collect <unit>.c.obj).

Run inside `nix develop .#build`:
    python3 configure.py        # regenerate build.ninja + objdiff.json
    ninja                       # build the base objs + delink the target
    objdiff-cli report generate -p build/objdiff -o build/objdiff/report.json

Add a TU: add an [[unit]] block to config/units.toml and annotate each function
in its src/ file with a `// @address:` comment (build/gen/symbol_names.csv is
regenerated from those), then re-run configure.py and ninja.
"""

import argparse
import json
import re
import struct
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent
MANIFEST = REPO / "config" / "units.toml"

# Local includes - both quoted (`"All-aggregated.cpp"`, same-dir) and angle-bracket
# (`<Module/Foo.h>`, resolved against the include/ tree). System `<string.h>` etc.
# resolve to nothing under the repo and are skipped (the MSVC headers don't change).
_INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*[<"]([^>"]+)[>"]', re.M)


def local_headers(source: str) -> list:
    """Transitive set of repo-local headers a TU `#include "..."`s (repo-relative).

    ninja's `cl` rule lists only the .cpp as input, so without these as implicit
    deps a header-only edit (e.g. a struct-offset fix in a shared .h) does NOT
    rebuild the dependent .obj - the matcher then diffs STALE code (a real trap;
    see docs/match-learnings.md). We resolve quoted includes relative to each
    file's own dir and emit the dependents so ninja rebuilds exactly the affected
    units (not a coarse all-units rebuild)."""
    seen: set[str] = set()
    stack = [Path(source)]
    while stack:
        rel = stack.pop()
        path = REPO / rel
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for inc in _INCLUDE_RE.findall(text):
            # quoted same-dir first (e.g. All.cpp's `"CFoo.cpp"`), then the include/ tree
            for base in (path.parent, REPO / "include"):
                try:
                    hrel = (base / inc).resolve().relative_to(REPO)
                except ValueError:
                    continue  # outside the repo (e.g. ../../usr) - skip
                if (REPO / hrel).exists():
                    key = str(hrel)
                    if key not in seen:
                        seen.add(key)
                        stack.append(hrel)
                    break
    return sorted(seen)

# scripts/gruntz/build/ holds the build-pipeline modules incl. the vendored
# ninja_syntax helper; make it importable whether configure.py is run from the
# repo root or elsewhere.
sys.path.insert(0, str(REPO / "scripts" / "gruntz" / "build"))
import ninja_syntax  # noqa: E402

# --- paths (all relative to the repo root, which is the ninja build root) ----
PY = "python3"
CC_WRAP = "scripts/gruntz/build/cc_wrap.py"
DELINK = "scripts/gruntz/build/delink.py"
GEN_LABELS = "scripts/gruntz/build/labels.py"
# The rva->name,unit map is GENERATED from src `// @address:` annotations joined
# to the base objs (clang mangledName INTERSECT nm) - no hand-written CSV. See
# docs/source-consolidation-investigation.md.
GEN_NAMES = "build/gen/symbol_names.csv"
# clangd compile DB (per-TU MS/include flags); labels.py uses it so the IR emit's
# system-header lookup succeeds. Optional - labels.py degrades to bare MS flags.
COMPDB = "build/clangd/compile_commands.json"

# Target (delink) inputs.
EXE = "build/exe/GRUNTZ.EXE"
FUNCTIONS = "build/ghidra-enrich/exports/functions.csv"
SYMBOLS = "build/ghidra-enrich/exports/symbols.csv"

# Out-dir layout (under build/, git-ignored).
OBJDIFF_DIR = "build/objdiff"
BASE_DIR = "build/objdiff/base"      # recompiled base objs (phase 1 outputs)
TARGET_DIR = "build/objdiff/target"  # collected delinked target objs
DELINK_RAW = "build/delink/named"    # raw vostok-delinker output
PDB_DIR = "build/pdb"                # synth PDB/YAML


# --- manifest ---------------------------------------------------------------
def load_manifest(path: Path) -> dict:
    with path.open("rb") as f:
        data = tomllib.load(f)
    # Named flag profiles ([flags] table): EVERY [[unit]] selects one with
    # `flags = "<name>"`. The profiles ARE the full flag sets - there is no
    # separate global default to inherit, so each TU's flag choice is explicit.
    profiles = data.get("flags", {})
    if not profiles:
        raise SystemExit(f"{path}: [flags] must define at least one profile")
    units = data.get("unit", [])
    if not units:
        raise SystemExit(f"{path}: no [[unit]] entries")
    seen = set()
    for u in units:
        for key in ("unit", "source", "flags"):
            if key not in u:
                raise SystemExit(f"{path}: a [[unit]] is missing '{key}'")
        if u["unit"] in seen:
            raise SystemExit(f"{path}: duplicate unit '{u['unit']}'")
        seen.add(u["unit"])
        if u["flags"] not in profiles:
            raise SystemExit(f"{path}: unit '{u['unit']}' references unknown "
                             f"flags profile '{u['flags']}' "
                             f"(defined: {sorted(profiles)})")
        u["cflags"] = profiles[u["flags"]]
    return data


# --- build.ninja ------------------------------------------------------------
def emit_link_phase(w: ninja_syntax.Writer) -> None:
    """PLACEHOLDER for graph phase 2 (link -> candidate .EXE).

    NOT IMPLEMENTED YET. Whole-binary verification (link every base .obj into a
    candidate GRUNTZ.EXE and byte-compare against the retail binary) goes here.
    When implemented this will add:
      * a `link` rule running `wine link.exe` via a wrapper, fed a RESPONSE FILE
        (@objs.rsp) - VC5's link has a short command-line limit under wine, so
        the obj list + flags must go through a response file, not argv.
      * link flags pinned by matching: /OPT:REF /OPT:ICF plus the exact link
        ORDER (COMDAT order, not source order - see docs/zlib-matching.md).
      * inputs = every base <unit>.obj; output = build/exe/GRUNTZ.candidate.EXE
        plus a verify step diffing it against the retail EXE.
    See docs/build-system.md "Deferred: the link phase".
    """
    w.comment("=== PHASE 2 (DEFERRED): link -> candidate .EXE ===")
    w.comment("Not implemented. Whole-binary verification will add a `link` "
              "rule (wine link.exe via a @response file - VC5 link has a short "
              "cmdline limit under wine), /OPT:REF /OPT:ICF + the matched link "
              "order, fed every base <unit>.obj. See configure.py:emit_link_phase "
              "and docs/build-system.md.")
    w.newline()


def emit_ninja(manifest: dict, out: Path) -> None:
    build = manifest["build"]
    units = manifest["unit"]
    # build.ninja's global $cflags default = the first [flags] profile; a unit's
    # edge overrides it only when its resolved flags differ. Generation detail -
    # every unit names its profile explicitly in the manifest.
    global_cflags = next(iter(manifest["flags"].values()))

    with out.open("w", encoding="utf-8") as f:
        w = ninja_syntax.Writer(f)
        w.comment("GENERATED by configure.py from config/units.toml - do not edit.")
        w.comment("Regenerate: python3 configure.py")
        w.newline()

        w.variable("ninja_required_version", "1.7")
        w.variable("py", PY)
        w.variable("cflags", " ".join(global_cflags))
        w.newline()

        # Regenerate build.ninja when the manifest or configure.py changes.
        w.rule("configure",
               command=f"{PY} configure.py",
               description="configure.py (regenerate build.ninja)",
               generator=True)
        w.build("build.ninja", "configure",
                implicit=["configure.py", "config/units.toml",
                          "scripts/gruntz/build/ninja_syntax.py"])
        w.newline()

        # PHASE 1: compile each TU's source -> base .obj via the wine-cl wrapper.
        w.comment("=== PHASE 1: compile -> base .obj (cl /O2 /MT under wine) ===")
        w.rule("cl",
               command=f"{PY} {CC_WRAP} --out $out --src $in -- $cflags",
               description="cl $unit")
        w.newline()

        base_objs = []
        for u in units:
            obj = f"{BASE_DIR}/{u['unit']}.obj"
            base_objs.append(obj)
            variables = {"unit": u["unit"]}
            # The unit's resolved [flags] profile; emit a per-edge override only
            # when it differs from build.ninja's global $cflags default.
            if u["cflags"] != global_cflags:
                variables["cflags"] = " ".join(u["cflags"])
            w.build(obj, "cl", inputs=u["source"],
                    implicit=[CC_WRAP] + local_headers(u["source"]),
                    variables=variables)
        w.newline()

        # LABELS: regenerate build/gen/symbol_names.csv from the src @address
        # annotations + the base objs (clang mangledName INTERSECT nm). The IR
        # emit needs the clangd compdb's per-TU include flags so system headers
        # resolve (-emit-llvm stops at a fatal error, unlike -ast-dump); it is an
        # optional input (labels.py falls back to bare MS flags if absent).
        w.comment("=== LABELS: src RVA() macros + base objs -> symbol_names.csv ===")
        labels_args = " ".join(
            f"--tu {u['source']} --obj {BASE_DIR}/{u['unit']}.obj" for u in units)
        w.rule("gen_labels",
               command=f"{PY} {GEN_LABELS} {labels_args} "
                       f"--compdb {COMPDB} --out {GEN_NAMES}",
               description="gen_labels (src RVA() macros -> symbol_names.csv)")
        compdb_dep = [COMPDB] if (REPO / COMPDB).exists() else []
        w.build(GEN_NAMES, "gen_labels",
                inputs=[u["source"] for u in units] + base_objs,
                implicit=[GEN_LABELS, "config/units.toml"] + compdb_dep)
        w.newline()

        # TARGET (delink) half: one rule produces all in-scope <unit>.c.obj.
        w.comment("=== TARGET: delink GRUNTZ.EXE -> named per-unit .c.obj ===")
        unit_args = " ".join(f"--unit {u['unit']}" for u in units)
        w.rule("delink",
               command=(f"{PY} {DELINK} --exe {EXE} --functions {FUNCTIONS} "
                        f"--symbols {SYMBOLS} --names-map {GEN_NAMES} "
                        f"--pdb-dir {PDB_DIR} --delink-dir {DELINK_RAW} "
                        f"--target-dir {TARGET_DIR} {unit_args}"),
               description="delink GRUNTZ.EXE -> target objs")
        target_objs = [f"{TARGET_DIR}/{u['unit']}.c.obj" for u in units]
        w.build(target_objs, "delink",
                inputs=[EXE, FUNCTIONS, SYMBOLS, GEN_NAMES],
                implicit=[DELINK, "scripts/gruntz/build/synth_pdb.py"])
        w.newline()

        # OBJDIFF MANIFEST: objdiff.json pairs each base obj with its target obj.
        # Whether a unit pairs with its real <unit>.c.obj or the empty dummy.obj is
        # decided from symbol_names.csv, which gen_labels regenerates ABOVE - so the
        # manifest must be (re)built AFTER it, in-graph, not at configure time (when
        # the csv can still be stale for a unit added this build). gen_labels ->
        # gen_objdiff is the ordering that makes a new unit pair correctly in ONE
        # build instead of two.
        objdiff_json = f"{OBJDIFF_DIR}/objdiff.json"
        w.comment("=== OBJDIFF: symbol_names.csv -> objdiff.json (post-labels) ===")
        w.rule("gen_objdiff",
               command=f"{PY} configure.py --emit-objdiff",
               description="gen_objdiff (symbol_names.csv -> objdiff.json)")
        w.build(objdiff_json, "gen_objdiff",
                inputs=[GEN_NAMES],
                implicit=["configure.py", "config/units.toml"])
        w.newline()

        # Convenience aliases.
        w.comment("=== aliases ===")
        w.build("base", "phony", inputs=base_objs)
        w.build("target", "phony", inputs=target_objs)
        w.build("all", "phony", inputs=base_objs + target_objs + [objdiff_json])
        w.default(["all"])
        w.newline()

        emit_link_phase(w)


# --- objdiff project (absorbs scripts/generate_objdiff_config.py) -----------
def write_dummy(path: Path) -> None:
    """A minimal valid empty i386 COFF (.text, no symbols) for units whose
    target side has no named functions yet, so objdiff still lists them."""
    symbol_table_offset = 20 + 40  # header + 1 section header
    header = struct.pack(
        "<HHIIIHH",
        0x14C,                 # Machine: IMAGE_FILE_MACHINE_I386
        1,                     # NumberOfSections
        0,                     # TimeDateStamp
        symbol_table_offset,   # PointerToSymbolTable
        0,                     # NumberOfSymbols
        0,                     # SizeOfOptionalHeader
        0,                     # Characteristics
    )
    section = struct.pack(
        "<8sIIIIIIHHI",
        b".text\0\0\0",
        0, 0, 0, 0, 0, 0, 0, 0,
        0x60000020,            # CODE | EXECUTE | READ
    )
    string_table = struct.pack("<I", 4)  # empty string table (size field only)
    path.write_bytes(header + section + string_table)


def units_with_named_functions(names_csv: Path) -> set:
    """Units that have >=1 row in symbol_names.csv (so the delinker emits a
    <unit>.c.obj for them). This is the INTENT that decides objdiff's
    target_path - we cannot probe the filesystem because configure.py runs
    BEFORE ninja builds the objs."""
    units = set()
    if not names_csv.exists():
        return units
    import csv
    with names_csv.open(newline="") as f:
        rows = [ln for ln in f if not ln.lstrip().startswith("#")]
    for row in csv.DictReader(rows):
        unit = (row.get("unit") or "").strip()
        if unit:
            units.add(unit)
    return units


def emit_objdiff(manifest: dict, objdiff_dir: Path) -> None:
    """Write build/objdiff/objdiff.json pairing base <-> target BY NAME.

    base   : ./base/<unit>.obj      (cl /O2 /MT vendor/zlib-1.0.4/<unit>.c)
    target : ./target/<unit>.c.obj  (delinked, named per symbol_names.csv)

    Symbols are pre-named on both sides (cdecl `_<name>`), so objdiff pairs them
    directly with no `symbol_mappings` overlay. Paths reflect build INTENT, not
    the current filesystem: configure.py runs before ninja, so probing for the
    objs would (wrongly) point everything at the dummy. ninja always builds a
    base obj for every manifest unit; the delinker emits a <unit>.c.obj only for
    units that have rows in symbol_names.csv, so a unit with no named target
    functions yet is paired against the empty dummy.obj (lists at 0%).

    The pairing is read from symbol_names.csv. At configure time that csv can be
    stale (gen_labels regenerates it during ninja), so the `gen_objdiff` ninja rule
    re-runs this AFTER gen_labels - that in-graph re-emit is what makes a unit added
    this build pair correctly in one pass. See emit_ninja's gen_objdiff edge.
    """
    build = manifest["build"]
    objdiff_dir.mkdir(parents=True, exist_ok=True)
    write_dummy(objdiff_dir / "dummy.obj")
    # GEN_NAMES is a BUILD output (ninja's gen_labels), so it may not exist at
    # configure time. When absent (fresh tree), assume every manifest unit will be
    # named once gen_labels runs; when present, use it for accurate dummy pairing.
    named = (units_with_named_functions(REPO / GEN_NAMES)
             if (REPO / GEN_NAMES).exists()
             else {u["unit"] for u in manifest["unit"]})
    units = []
    for u in manifest["unit"]:
        base_path = f"./base/{u['unit']}.obj"   # ninja always builds this
        target_path = (f"./target/{u['unit']}.c.obj"
                       if u["unit"] in named else "./dummy.obj")
        units.append({
            "name": u["unit"],
            "target_path": target_path,
            "base_path": base_path,
            "scratch": {
                "platform": build.get("platform", "win32"),
                "compiler": build.get("compiler", "msvc5.0"),
            },
        })
    obj = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "build_base": False,
        "build_target": False,
        "watch_patterns": ["*.obj"],
        "units": units,
    }
    with (objdiff_dir / "objdiff.json").open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default=MANIFEST, type=Path)
    ap.add_argument("--emit-objdiff", action="store_true",
                    help="(re)write ONLY build/objdiff/objdiff.json from the "
                         "current symbol_names.csv. Run by the `gen_objdiff` ninja "
                         "rule AFTER gen_labels, so a unit added this build pairs "
                         "with its real delinked obj in one pass.")
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)

    if args.emit_objdiff:
        emit_objdiff(manifest, REPO / OBJDIFF_DIR)
        print(f"[configure] wrote {OBJDIFF_DIR}/objdiff.json")
        return

    n = len(manifest["unit"])
    emit_ninja(manifest, REPO / "build.ninja")
    # objdiff.json is NOT written here: the `gen_objdiff` ninja edge owns it and
    # rebuilds it after gen_labels, so it always reflects the fresh symbol_names.csv
    # (a unit added this build pairs with its real obj in one pass). Single owner =
    # no churn. ninja creates it on the first build.

    print(f"[configure] wrote build.ninja ({n} units); "
          "objdiff.json is built in-graph by the gen_objdiff edge")
    print("[configure] next: ninja   (then objdiff-cli report generate "
          f"-p {OBJDIFF_DIR} -o {OBJDIFF_DIR}/report.json)")


if __name__ == "__main__":
    main()
