#!/usr/bin/env python3
"""configure.py - generate the Gruntz matching build from the units manifest.

Single source of truth: config/units.toml (per-TU). This script reads it and
emits, from one manifest:

  * build.ninja            - the native incremental build graph (Linux ninja
                             driving `wine cl` via scripts/gruntz/core/cc_wrap.py).
  * build/objdiff/objdiff.json - the objdiff project pairing each recompiled
                             base obj against its delinked target obj BY SYMBOL
                             NAME.

(The clang compile DB lives in build/clangd/, generated by scripts/gruntz/init/clangd.py
- the build itself needs no compdb; ninja tracks deps.)

Two graph phases (see docs/build-system.md):
  1. compile -> .obj   - IMPLEMENTED. Each manifest unit's source compiles to
                         build/objdiff/base/<unit>.obj via the `cl` rule.
  2. link -> .EXE      - IMPLEMENTED but OPT-IN. emit_link_phase() emits a `link`
                         rule + `candidate` phony, kept OUT of the default `all`
                         (build only via `ninja candidate` / `gruntz link`). It
                         links the base objs into a non-runnable candidate EXE +
                         .map for the link-order study (intra-TU order = source
                         order, cross-TU = object order); a normal build never
                         links. See docs/link-order-investigation.md.

The TARGET (delink) half is orchestrated as a ninja `delink` rule that runs
scripts/gruntz/build/delink.py (synth_pdb -> vostok-delinker -> collect <unit>.c.obj).

Run inside `nix develop`:
    python3 configure.py        # regenerate build.ninja + objdiff.json
    ninja                       # build the base objs + delink the target
    objdiff-cli report generate -p build/objdiff -o build/objdiff/report.json

Add a TU: add an [[unit]] block to config/units.toml and annotate each function
in its src/ file with a `// @address:` comment (build/gen/symbol_names.csv is
regenerated from those), then re-run configure.py and ninja.
"""

import argparse
import json
import os
import re
import struct
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent
MANIFEST = REPO / "config" / "units.toml"

# Local includes - both quoted (`"All-aggregated.cpp"`, same-dir) and angle-bracket
# (`<Module/Foo.h>`, resolved against the include/ tree). System `<string.h>` etc.
# resolve to nothing under the repo and are skipped (the MSVC headers don't change).
_INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*[<"]([^>"]+)[>"]', re.M)


_direct_cache: dict = {}
# Every repo-local file the include scan has READ, across all units. It is the
# exact set whose CONTENT decides the dep lists below, so it is what the
# build.ninja generator edge must depend on - see emit_ninja().
scanned_files: set = set()


def _direct_includes(rel: str) -> list:
    """The repo-local files `rel` includes directly, repo-relative, memoized.

    `Path.resolve()` is a syscall per component and the old code paid it once per
    include-line per *unit* - 180k calls, ~13 s of a 13 s configure - because the
    walk restarted from scratch for all 344 TUs and re-read every shared header.
    Resolving is unnecessary anyway: the repo has no symlinked headers and the
    include paths are already repo-relative, so normpath over strings is both
    correct and ~40x cheaper."""
    hit = _direct_cache.get(rel)
    if hit is not None:
        return hit
    out: list = []
    _direct_cache[rel] = out          # cycle guard: self-referential includes
    scanned_files.add(rel)
    try:
        text = (REPO / rel).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return out
    parent = os.path.dirname(rel)
    for inc in _INCLUDE_RE.findall(text):
        # quoted same-dir first (e.g. All.cpp's `"CFoo.cpp"`), then the include/ tree
        for base in (parent, "include"):
            hrel = os.path.normpath(os.path.join(base, inc))
            if hrel.startswith(".."):
                continue              # outside the repo (e.g. ../../usr) - skip
            if (REPO / hrel).exists():
                out.append(hrel)
                break
    return out


def local_headers(source: str) -> list:
    """Transitive set of repo-local headers a TU `#include "..."`s (repo-relative).

    ninja's `cl` rule lists only the .cpp as input, so without these as implicit
    deps a header-only edit (e.g. a struct-offset fix in a shared .h) does NOT
    rebuild the dependent .obj - the matcher then diffs STALE code (a real trap;
    see docs/match-learnings.md). We resolve quoted includes relative to each
    file's own dir and emit the dependents so ninja rebuilds exactly the affected
    units (not a coarse all-units rebuild)."""
    seen: set = set()
    stack = [source]
    while stack:
        for hrel in _direct_includes(stack.pop()):
            if hrel not in seen:
                seen.add(hrel)
                stack.append(hrel)
    return sorted(seen)

# scripts/gruntz/build/ holds the build-pipeline modules incl. the vendored
# ninja_syntax helper; make it importable whether configure.py is run from the
# repo root or elsewhere.
sys.path.insert(0, str(REPO / "scripts" / "gruntz" / "build"))
import ninja_syntax  # noqa: E402

# --- paths (all relative to the repo root, which is the ninja build root) ----
PY = "python3"
CC_WRAP = "scripts/gruntz/core/cc_wrap.py"
DELINK = "scripts/gruntz/build/delink.py"
LINK = "scripts/gruntz/build/link.py"
RESCOMP = "scripts/gruntz/build/rescomp.py"
# Data-symbol normalization: rewrite compiler-private ($SG/$T/$S) data names +
# jump-table DIR32 labels of base AND target into a content-addressed, disposable
# comparison copy so objdiff pairs them BY NAME (matching-neutral; the real objs
# are untouched). See scripts/gruntz/build/canonicalize_data_symbols.py.
NORMALIZE = "scripts/gruntz/build/normalize_objs.py"
NORMALIZE_MOD = "scripts/gruntz/build/canonicalize_data_symbols.py"
GEN_LABELS = "scripts/gruntz/build/labels.py"
# The rva->name,unit map is GENERATED from src `// @address:` annotations joined
# to the base objs (clang mangledName INTERSECT nm) - no hand-written CSV. See
# docs/build-system.md.
GEN_NAMES = "build/gen/symbol_names.csv"
# Source-derived Ghidra enrichment metadata (labels.py), merged from per-TU
# fragments alongside symbol_names.csv; consumed by apply.py during ghidra-refresh.
FUNCTIONS_JSON = "build/gen/functions.json"
GLOBALS_JSON = "build/gen/globals.json"
# clangd compile DB (per-TU MS/include flags); labels.py uses it so the IR emit's
# system-header lookup succeeds. Optional - labels.py degrades to bare MS flags.
COMPDB = "build/clangd/compile_commands.json"

# Target (delink) inputs.
EXE = "build/exe/GRUNTZ.EXE"
FUNCTIONS = "config/retail/functions.tsv"
RELOC_ALIASES = "config/retail/reloc-aliases.tsv"

# Out-dir layout (under build/, git-ignored).
OBJDIFF_DIR = "build/objdiff"
BASE_DIR = "build/objdiff/base"      # recompiled base objs (phase 1 outputs)
TARGET_DIR = "build/objdiff/target"  # collected delinked target objs
NORM_DIR = "build/objdiff/normalized"  # disposable normalized objdiff comparison copies
DELINK_RAW = "build/delink/named"    # raw vostok-delinker output
PDB_DIR = "build/pdb"                # synth PDB/YAML
LABELS_DIR = "build/gen/labels"      # per-TU symbol_names.csv fragments
# The delinker's holding unit for library DATA (see gruntz.core.vtable_catalog):
# deliberately NOT in units.toml, so it is not an orphan - see
# prune_orphan_artifacts(). Spelled out here to keep configure.py import-free.
LIBRARY_HOLDING_UNIT = "library_data"


# --- manifest ---------------------------------------------------------------
def load_manifest(path: Path) -> dict:
    with path.open("rb") as f:
        data = tomllib.load(f)
    # Named flag profiles ([flags] table): EVERY [[unit]] selects one with
    # `flags = "<name>"`. The profiles ARE the full flag sets - there is no
    # separate global default to inherit and no per-TU append, so each TU's flag
    # choice is one explicit, greppable name. /GX and /GR are profile choices
    # (cpp, cpp-o1, cpp-rtti), never bolt-ons: a stray `extra` key is a hard error.
    profiles = data.get("flags", {})
    if not profiles:
        raise SystemExit(f"{path}: [flags] must define at least one profile")
    units = data.get("unit", [])
    if not units:
        raise SystemExit(f"{path}: no [[unit]] entries")
    seen = set()
    for u in units:
        for key in ("unit", "source", "flags"):
            if key not in u:
                raise SystemExit(f"{path}: a [[unit]] is missing '{key}'")
        if u["unit"] in seen:
            raise SystemExit(f"{path}: duplicate unit '{u['unit']}'")
        seen.add(u["unit"])
        if u["flags"] not in profiles:
            raise SystemExit(f"{path}: unit '{u['unit']}' references unknown "
                             f"flags profile '{u['flags']}' "
                             f"(defined: {sorted(profiles)})")
        if "extra" in u:
            raise SystemExit(
                f"{path}: unit '{u['unit']}' sets 'extra' - per-TU flag bolt-ons "
                f"are not supported. Add (or reuse) a [flags] profile carrying the "
                f"FULL set instead; /GR lives in the `cpp-rtti` profile.")
        # Copy the profile - never mutate the shared list.
        u["cflags"] = list(profiles[u["flags"]])
    return data


# --- build.ninja ------------------------------------------------------------
def emit_link_phase(w: ninja_syntax.Writer, base_objs: list) -> None:
    """Graph phase 2: link the base objs -> candidate (non-runnable) .EXE + .map.

    Runs the genuine VC5 link.exe (5.10.7303) under wine via
    scripts/gruntz/build/link.py over a @response file (VC5 link has a short argv
    limit under wine), against the retail library set - static CRT + MFC via the
    objs' own -defaultlib: directives, DX6, version/winmm, and the mss32/smackw32
    import libs synthesised by gruntz.build.import_lib. The reconstruction is still
    PARTIAL, so /FORCE stays on; the deliverable is the `.map`, which gives each
    function's link-assigned RVA + source object. That, cross-referenced with the
    retail RVAs, is what recovers the build order for matching (intra-TU order =
    source-definition order; cross-TU order = object link order). See
    docs/link-order-investigation.md and `gruntz link`.

    This is an OPT-IN target (`ninja candidate`), kept OUT of the default `all` so
    a normal `gruntz build` is unaffected. link.py manages its own wineserver.

    The `.rsrc` section comes from `gruntz.build.rescomp`, the project's resource
    compiler (the toolchain tarball ships `cvtres.exe` but no `rc.exe`): it parses
    src/Gruntz/Gruntz.rc - real, tracked rc grammar covering all 57 authorable
    resources - and writes the Win32 `.RES` container itself. Only the 18
    ICON/CURSOR art resources are carried bytes (config/retail/rsrc/data/); the
    `rescomp check` build gate byte-proves both halves against retail's own image.
    """
    w.comment("=== PHASE 2: link -> candidate .EXE + .map (opt-in: `ninja candidate`) ===")
    cand = "build/exe/GRUNTZ.candidate.EXE"
    res = "build/gen/gruntz.res"
    w.rule("rescomp", command=f"{PY} {RESCOMP} build --out $out",
           description=".rc + art blobs -> .RES")
    w.build(res, "rescomp",
            inputs=["config/retail/rsrc/manifest.tsv", "src/Gruntz/Gruntz.rc"],
            implicit=[RESCOMP])
    w.rule("link",
           command=f"{PY} {LINK} --out {cand} --objs-dir {BASE_DIR} --res {res}",
           description="link base objs -> candidate EXE + map")
    w.build([cand, "build/exe/GRUNTZ.candidate.map"], "link",
            inputs=base_objs, implicit=[LINK, res,
                                        "scripts/gruntz/build/msdis_stub.py",
                                        "scripts/gruntz/build/import_lib.py"])
    # The README's link-status block is refreshed HERE and nowhere else in the
    # build: `gruntz build` does not link, so the block is only as fresh as the
    # last `ninja candidate`. It states the candidate's digest and link time so a
    # stale block is visible rather than silent.
    #
    # It carries a per-section BYTE-similarity column from gruntz.audit.image_diff,
    # which reads build/gen/delink_data_manifest.tsv - and prune_orphan_artifacts()
    # deletes that file whenever it prunes, so the delink stamp is an input here or
    # `ninja candidate` would score the image against a manifest that is not there.
    w.rule("linkscore",
           command=f"{PY} -m gruntz.audit.link_sections --write-readme && "
                   f"touch $out",
           description="candidate EXE -> README link status")
    w.build("build/gen/.link_score.stamp", "linkscore", inputs=[cand],
            implicit=["scripts/gruntz/audit/link_sections.py",
                      "scripts/gruntz/audit/image_diff.py",
                      "build/objdiff/.delink.stamp"])
    w.build("candidate", "phony",
            inputs=[cand, "build/gen/.link_score.stamp"])
    w.newline()


def emit_ninja(manifest: dict, out: Path) -> None:
    build = manifest["build"]
    units = manifest["unit"]
    # build.ninja's global $cflags default = the first [flags] profile; a unit's
    # edge overrides it only when its resolved flags differ. Generation detail -
    # every unit names its profile explicitly in the manifest.
    global_cflags = next(iter(manifest["flags"].values()))

    with out.open("w", encoding="utf-8") as f:
        w = ninja_syntax.Writer(f)
        w.comment("GENERATED by configure.py from config/units.toml - do not edit.")
        w.comment("Regenerate: python3 configure.py")
        w.newline()

        w.variable("ninja_required_version", "1.7")
        w.variable("py", PY)
        w.variable("cflags", " ".join(global_cflags))
        w.newline()

        # PHASE 1: compile each TU's source -> base .obj via the wine-cl wrapper.
        # Emitted BEFORE the generator edge only so the include scan has run and
        # `scanned_files` is complete; ninja does not care about edge order.
        cl_edges = []
        for u in units:
            obj = f"{BASE_DIR}/{u['unit']}.obj"
            variables = {"unit": u["unit"]}
            # The unit's resolved [flags] profile; emit a per-edge override only
            # when it differs from build.ninja's global $cflags default.
            if u["cflags"] != global_cflags:
                variables["cflags"] = " ".join(u["cflags"])
            cl_edges.append((obj, u["source"], [CC_WRAP] + local_headers(u["source"]),
                             variables))

        # Regenerate build.ninja when the manifest, configure.py, or ANY file the
        # include scan read changes.
        #
        # The dep lists on the `cl` edges below are baked HERE, at configure time,
        # from the #include graph as it stood. So an edit that changes that graph -
        # adding an #include, adding/renaming/deleting a header - invalidates them,
        # and without the scanned set on this edge nothing notices: ninja keeps
        # using the stale list and a later edit to a newly-included header does not
        # rebuild its TU. That is silent, and it is exactly the failure mode a
        # byte-neutrality claim from a header-only edit depends on not happening.
        # /showIncludes would let cl emit real depfiles, but MSVC 5.0 rejects it
        # (D4002), so the scan is what we have - make it self-invalidating.
        w.rule("configure",
               command=f"{PY} configure.py",
               description="configure.py (regenerate build.ninja)",
               generator=True)
        w.build("build.ninja", "configure",
                implicit=["configure.py", "config/units.toml",
                          "scripts/gruntz/build/ninja_syntax.py",
                          *sorted(scanned_files)])
        w.newline()

        w.comment("=== PHASE 1: compile -> base .obj (cl /O2 /MT under wine) ===")
        w.rule("cl",
               command=f"{PY} {CC_WRAP} --out $out --src $in -- $cflags",
               description="cl $unit")
        w.newline()

        base_objs = []
        for obj, src, implicit, variables in cl_edges:
            base_objs.append(obj)
            w.build(obj, "cl", inputs=src, implicit=implicit, variables=variables)
        w.newline()

        # LABELS: per-TU fragment, then a cheap merge -> symbol_names.csv.
        # Each fragment is one TU's clang-IR pass (the expensive step), so a single
        # edit re-emits only THAT unit's IR instead of all ~23. Both edges carry
        # `restat` so an unchanged symbol set (a pure code edit) stops here and does
        # NOT cascade into delink/objdiff. The IR emit needs the clangd compdb's
        # per-TU include flags (labels.py falls back to bare MS flags if absent).
        # Each TU also emits functions.json/globals.json fragments (per-RVA
        # signatures + declared global types for apply.py's Ghidra enrichment);
        # merge_labels combines all three so apply.py sees EVERY unit, not just the
        # last TU built.
        w.comment("=== LABELS: per-TU fragments -> merge -> symbol_names.csv ===")
        w.rule("gen_labels_one",
               command=f"{PY} {GEN_LABELS} --tu $src --obj $obj --unit $unit "
                       f"--compdb {COMPDB} --out $csvfrag "
                       f"--functions-out $funcfrag --globals-out $globfrag",
               description="gen_labels $unit",
               restat=True)
        compdb_dep = [COMPDB] if (REPO / COMPDB).exists() else []
        zlib_dep = [p for p in ("config/retail/functions_zlib.tsv",
                                "config/retail/data_zlib.tsv")
                    if (REPO / p).exists()]
        # DATA extents come directly from pylibclang's Type.get_size() in this
        # per-TU edge.  structs.json is a separate whole-tree audit cache and must
        # never make label correctness depend on when that cache was refreshed.
        frags, func_frags, glob_frags = [], [], []
        for u in units:
            frag = f"{LABELS_DIR}/{u['unit']}.csv"
            funcfrag = f"{LABELS_DIR}/{u['unit']}.functions.json"
            globfrag = f"{LABELS_DIR}/{u['unit']}.globals.json"
            obj = f"{BASE_DIR}/{u['unit']}.obj"
            frags.append(frag)
            func_frags.append(funcfrag)
            glob_frags.append(globfrag)
            w.build([frag, funcfrag, globfrag], "gen_labels_one",
                    inputs=u["source"],
                    implicit=[obj, GEN_LABELS, "config/units.toml"]
                             + compdb_dep + zlib_dep,
                    variables={"src": u["source"], "obj": obj, "unit": u["unit"],
                               "csvfrag": frag,
                               "funcfrag": funcfrag, "globfrag": globfrag})
        w.rule("merge_labels",
               command=f"{PY} {GEN_LABELS} --merge $csvfrags --out {GEN_NAMES} "
                       f"--merge-functions $funcfrags --functions-out {FUNCTIONS_JSON} "
                       f"--merge-globals $globfrags --globals-out {GLOBALS_JSON}",
               description="merge_labels -> symbol_names.csv + functions/globals.json",
               restat=True)
        # Vtable catalogs are consumed only by the cheap merge. Catalog edits
        # must not rerun clang IR over every translation unit.
        vtbl_dep = ["config/retail/vtables_game.csv", "config/retail/vtables_library.csv"]
        # Reviewed per-TU static-copy pins are folded in at merge time too.
        copies_dep = [str(p.relative_to(REPO))
                      for p in [REPO / "config/static_data_copies.tsv"] if p.exists()]
        w.build([GEN_NAMES, FUNCTIONS_JSON, GLOBALS_JSON], "merge_labels",
                inputs=frags + func_frags + glob_frags,
                implicit=[GEN_LABELS] + vtbl_dep + copies_dep,
                variables={"csvfrags": " ".join(frags),
                           "funcfrags": " ".join(func_frags),
                           "globfrags": " ".join(glob_frags)})
        w.newline()

        # TARGET (delink) half: one rule produces all in-scope <unit>.c.obj.
        w.comment("=== TARGET: delink GRUNTZ.EXE -> named per-unit .c.obj ===")
        unit_args = " ".join(f"--unit {u['unit']}" for u in units)
        # The declared output is a single STAMP, NOT the ~500 per-unit .c.obj. Some
        # units have no named symbol yet (they pair with dummy.obj below), so
        # declaring every <unit>.c.obj as an output made ninja treat delink as
        # perpetually unbuilt - re-running the full ~24s delink on EVERY build,
        # including no-ops. Keyed on GEN_NAMES (symbol_names.csv, written
        # content-idempotently by labels.py), delink now fires ONLY when a symbol
        # changes (name / RVA / size / kind) - never on a pure code-body edit.
        # `gruntz build --force-delink` removes the stamp to force a re-delink.
        delink_stamp = f"{OBJDIFF_DIR}/.delink.stamp"
        w.rule("delink",
               command=(f"{PY} {DELINK} --exe {EXE} --functions {FUNCTIONS} "
                        f"--names-map {GEN_NAMES} "
                        f"--reloc-alias-manifest {RELOC_ALIASES} "
                        f"--pdb-dir {PDB_DIR} --delink-dir {DELINK_RAW} "
                        f"--target-dir {TARGET_DIR} --stamp {delink_stamp} {unit_args}"),
               description="delink GRUNTZ.EXE -> target objs")
        target_objs = [f"{TARGET_DIR}/{u['unit']}.c.obj" for u in units]
        w.build(delink_stamp, "delink",
                inputs=[EXE, FUNCTIONS, GEN_NAMES],
                # data_manifest.py (+ the data_audit PE classifier it imports):
                # delink.py regenerates the data/section manifests in-process on every
                # run, so editing either must re-delink too - otherwise objdiff keeps
                # scoring the previous manifest.
                implicit=[DELINK, "scripts/gruntz/build/synth_pdb.py",
                          "scripts/gruntz/build/data_manifest.py",
                          "scripts/gruntz/core/data_audit.py",
                          RELOC_ALIASES,
                          # synth_pdb carries the tracked FID library labels into
                          # the fake PDB, so the delinked target speaks the same
                          # CRT/MFC symbol names our base objs reference. Editing
                          # a row must re-delink or objdiff keeps the old name.
                          "config/retail/functions_static_libs.tsv",
                          # vtable_rows() reads the RTTI slot map through
                          # vtable_hierarchy -> vtable_scan; both decide vtable extents.
                          "scripts/gruntz/core/vtable_hierarchy.py",
                          "scripts/gruntz/core/vtable_scan.py"])
        w.newline()

        # NORMALIZE: rewrite compiler-private data names + jump-table labels of
        # every base/target obj into content-addressed comparison copies under
        # build/objdiff/normalized/ (objdiff pairs BY NAME; the real objs are
        # untouched, so this is matching-neutral and can only sharpen the diff).
        # One stamped edge drives the whole set (mirrors delink); the driver
        # mtime-skips unchanged objs, so a single base recompile only re-normalizes
        # that one obj. Keyed on the base objs + the delink stamp so it re-runs when
        # either side changes. See docs/build-system.md (data-symbol normalization).
        w.comment("=== NORMALIZE: base/target -> content-addressed comparison copies ===")
        normalize_stamp = f"{OBJDIFF_DIR}/.normalize.stamp"
        unit_norm_args = " ".join(f"--unit {u['unit']}" for u in units)
        w.rule("normalize",
               command=(f"{PY} {NORMALIZE} --base-dir {BASE_DIR} "
                        f"--target-dir {TARGET_DIR} --out-dir {NORM_DIR} "
                        f"--stamp {normalize_stamp} {unit_norm_args}"),
               description="normalize base/target objs")
        w.build(normalize_stamp, "normalize",
                inputs=base_objs + [delink_stamp],
                implicit=[NORMALIZE, NORMALIZE_MOD])
        w.newline()

        # OBJDIFF MANIFEST: objdiff.json pairs each base obj with its target obj.
        # Whether a unit pairs with its real <unit>.c.obj or the empty dummy.obj is
        # read off the DELINK OUTPUT, so this edge runs after the delink stamp (and
        # therefore after gen_labels, which delink itself depends on). That is what
        # makes a unit added this build pair correctly in ONE build - and what stops
        # a unit whose only contribution is data from being left on the dummy, which
        # objdiff scores 100.00% with zero totals.
        objdiff_json = f"{OBJDIFF_DIR}/objdiff.json"
        w.comment("=== OBJDIFF: symbol_names.csv -> objdiff.json (post-labels) ===")
        w.rule("gen_objdiff",
               command=f"{PY} configure.py --emit-objdiff",
               description="gen_objdiff (symbol_names.csv -> objdiff.json)",
               restat=True)
        w.build(objdiff_json, "gen_objdiff",
                # AFTER the delink: the pairing is read off the target objs the
                # delinker actually wrote, not predicted from symbol_names.csv.
                inputs=[GEN_NAMES, delink_stamp],
                implicit=["configure.py", "config/units.toml"])
        w.newline()

        # REPORT: the objdiff summary, in-graph so it regenerates ONLY when an obj
        # (or the pairing) changes - not via an unconditional call every build. A
        # pure code edit changes the edited unit's base obj -> report.json updates;
        # a no-op build leaves it untouched, so `gruntz build` can skip its feedback
        # tail (nothing rebuilt -> nothing to report).
        report_json = f"{OBJDIFF_DIR}/report.json"
        w.comment("=== REPORT: objs + pairing -> report.json (objdiff-cli) ===")
        w.rule("report",
               command=f"objdiff-cli report generate -p {OBJDIFF_DIR} -o {report_json}",
               description="objdiff report -> report.json")
        # Reads the NORMALIZED comparison copies (objdiff.json points at them); the
        # normalize stamp transitively carries the base-obj + delink dependencies.
        w.build(report_json, "report",
                inputs=[normalize_stamp, objdiff_json])
        w.newline()

        # Convenience aliases.
        w.comment("=== aliases ===")
        w.build("base", "phony", inputs=base_objs)
        w.build("target", "phony", inputs=[delink_stamp])
        w.build("all", "phony",
                inputs=base_objs + [delink_stamp, objdiff_json, report_json])
        w.default(["all"])
        w.newline()

        emit_link_phase(w, base_objs)


# --- objdiff project (absorbs scripts/generate_objdiff_config.py) -----------
def write_dummy(path: Path) -> None:
    """A minimal valid empty i386 COFF (.text, no symbols) for units whose
    target side has no named functions yet, so objdiff still lists them."""
    symbol_table_offset = 20 + 40  # header + 1 section header
    header = struct.pack(
        "<HHIIIHH",
        0x14C,                 # Machine: IMAGE_FILE_MACHINE_I386
        1,                     # NumberOfSections
        0,                     # TimeDateStamp
        symbol_table_offset,   # PointerToSymbolTable
        0,                     # NumberOfSymbols
        0,                     # SizeOfOptionalHeader
        0,                     # Characteristics
    )
    section = struct.pack(
        "<8sIIIIIIHHI",
        b".text\0\0\0",
        0, 0, 0, 0, 0, 0, 0, 0,
        0x60000020,            # CODE | EXECUTE | READ
    )
    string_table = struct.pack("<I", 4)  # empty string table (size field only)
    path.write_bytes(header + section + string_table)


def units_with_a_target(names_csv: Path, target_dir: Path) -> set:
    """Units the delinker produces a `<unit>.c.obj` for, so objdiff can open one.

    THE DELINKED OBJS ON DISK ARE THE ANSWER, and this runs after the delink edge
    (see emit_ninja's gen_objdiff), so it reads them rather than predicting. It
    used to predict, from FUNCTION rows only, on the grounds that "the delinker
    routes ALL data symbols into one synthetic module". That stopped being true
    when the data manifest arrived: a data-only unit gets a real per-object
    contribution now. Two units were still pointed at the empty dummy.obj on
    2026-08-09 while their real target objs sat unopened beside it -
    `logicdispatchinit` (one `.bss` template static) and `stringstaticpool` (one
    `CString`). objdiff scores an empty pairing 100.00% on EVERY measure with zero
    totals, so both reported MATCHING while being entirely unscored.

    The csv is still the fallback for the first configure of a fresh tree, where
    nothing is delinked yet; ninja re-emits post-delink in the same build.
    """
    units = {p.name[:-len(".c.obj")]
             for p in target_dir.glob("*.c.obj")} if target_dir.is_dir() else set()
    if units:
        return units
    if not names_csv.exists():
        return units
    import csv
    with names_csv.open(newline="") as f:
        rows = [ln for ln in f if not ln.lstrip().startswith("#")]
    for row in csv.DictReader(rows):
        unit = (row.get("unit") or "").strip()
        if unit:
            units.add(unit)
    return units


def emit_objdiff(manifest: dict, objdiff_dir: Path) -> None:
    """Write build/objdiff/objdiff.json pairing base <-> target BY NAME.

    base   : ./normalized/base/<unit>.obj      (cl /O2 /MT, then data-name normalized)
    target : ./normalized/target/<unit>.c.obj  (delinked per symbol_names.csv, normalized)

    Symbols are pre-named on both sides (cdecl `_<name>`), so objdiff pairs them
    directly with no `symbol_mappings` overlay. ninja always builds a base obj for
    every manifest unit; the delinker emits a <unit>.c.obj only for units it has a
    contribution for, and a unit with no delinked target pairs against the empty
    dummy.obj (lists at 0%).

    Which units those are is READ OFF THE DELINK OUTPUT, not predicted: the
    `gen_objdiff` ninja edge runs after the delink stamp for exactly that reason.
    Predicting it from symbol_names.csv is what let two data-only units keep
    pairing with the dummy after the delinker started emitting objects for them -
    a pairing objdiff scores 100.00% with zero totals. See units_with_a_target.
    """
    build = manifest["build"]
    objdiff_dir.mkdir(parents=True, exist_ok=True)
    write_dummy(objdiff_dir / "dummy.obj")
    # The delinked objs are a BUILD output, so on the first configure of a fresh
    # tree there are none; units_with_a_target falls back to symbol_names.csv, and
    # failing that to every manifest unit. ninja re-emits after the delink in the
    # same build, which is where the pairing becomes exact.
    named = units_with_a_target(REPO / GEN_NAMES, REPO / TARGET_DIR)
    if not named:
        named = {u["unit"] for u in manifest["unit"]}
    units = []
    for u in manifest["unit"]:
        # Pair the NORMALIZED comparison copies (compiler-private data names +
        # jump-table labels content-addressed on both sides). ninja's `normalize`
        # edge produces base/<unit>.obj for every unit and target/<unit>.c.obj for
        # named units; an unnamed unit has no delinked target, so it pairs against
        # the empty dummy (which has no data symbols to normalize).
        base_path = f"./normalized/base/{u['unit']}.obj"
        target_path = (f"./normalized/target/{u['unit']}.c.obj"
                       if u["unit"] in named else "./dummy.obj")
        units.append({
            "name": u["unit"],
            "target_path": target_path,
            "base_path": base_path,
            "scratch": {
                "platform": build.get("platform", "win32"),
                "compiler": build.get("compiler", "msvc5.0"),
            },
        })
    obj = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "build_base": False,
        "build_target": False,
        # Strict relocation scoring: require name/address identity AND the
        # pointed-to data value.  This makes REL32 callee identity visible and
        # keeps the DATA-level check; our pinned objdiff also compares absolute
        # DIR32 addends.
        "options": {"functionRelocDiffs": "all"},
        "watch_patterns": ["*.obj"],
        "units": units,
    }
    with (objdiff_dir / "objdiff.json").open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def prune_orphan_artifacts(manifest: dict) -> int:
    """Delete build artifacts of units that are no longer in config/units.toml.

    Ninja has no concept of an output whose EDGE disappeared, so dropping a unit
    (a source deleted, a TU folded, a branch switched in a shared worktree) leaves
    its `.obj`, label fragments and normalized copies behind - and the downstream
    readers that GLOB rather than follow the graph keep consuming them. That is not
    cosmetic: a stale `build/objdiff/base/<gone>.obj` re-enrols its vtables and RTTI
    into `build/gen/delink_data_manifest.tsv`, and `gruntz.audit.data_relocs` then
    FATALs the build with "enrolled datum carved into an object objdiff never opens"
    for a unit that has no source in the tree. Prune at configure time, where the
    live unit set is known.

    The delinker's LIBRARY HOLDING UNIT is live-by-design and must be exempt. It
    carries library DATA no cl output can re-emit (CDialog's messageMap,
    type_info's vtable), deliberately absent from config/units.toml so objdiff
    never opens it - which made every configure see `library_data.c.obj` as an
    orphan, prune it, and take `delink_data_manifest.tsv` with it (the manifests
    are dropped whenever ANY orphan is found, since they are rebuilt from the
    surviving objs). Net effect before this exemption: entering `nix develop`
    deleted the data manifest every single time, so `data_coverage` /
    `data_denominator` / `data_relocs` reported "run `gruntz build` first" on a
    tree that had just been built.
    """
    live = {u["unit"] for u in manifest["unit"]} | {LIBRARY_HOLDING_UNIT}
    patterns = [
        (REPO / BASE_DIR, "{}.obj"),
        (REPO / OBJDIFF_DIR / "normalized/base", "{}.obj"),
        (REPO / OBJDIFF_DIR / "normalized/base", "{}.symbols.tsv"),
        (REPO / OBJDIFF_DIR / "normalized/target", "{}.c.obj"),
        (REPO / OBJDIFF_DIR / "normalized/target", "{}.symbols.tsv"),
        (REPO / TARGET_DIR, "{}.c.obj"),
        (REPO / DELINK_RAW, "{}.c.obj"),
        (REPO / "build/gen/labels", "{}.csv"),
        (REPO / "build/gen/labels", "{}.functions.json"),
        (REPO / "build/gen/labels", "{}.globals.json"),
    ]
    stems = set()
    for d, pat in patterns:
        if not d.is_dir():
            continue
        head, tail = pat.split("{}")
        for p in d.iterdir():
            if p.name.startswith(head) and p.name.endswith(tail):
                stem = p.name[len(head):len(p.name) - len(tail)] if tail else p.name
                if stem and stem not in live:
                    stems.add(stem)
    if not stems:
        return 0
    n = 0
    for d, pat in patterns:
        for stem in stems:
            p = d / pat.format(stem)
            if p.exists():
                p.unlink()
                n += 1
    # The data manifests are regenerated in-process by delink.py from whatever objs
    # are present, so they must be rebuilt once an orphan obj is gone.
    for f in ("delink_data_manifest.tsv", "delink_data_section_manifest.tsv"):
        p = REPO / "build/gen" / f
        if p.exists():
            p.unlink()
            n += 1
    stamp = REPO / OBJDIFF_DIR / ".delink.stamp"
    if stamp.exists():
        stamp.unlink()
        n += 1
    return n


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default=MANIFEST, type=Path)
    ap.add_argument("--emit-objdiff", action="store_true",
                    help="(re)write ONLY build/objdiff/objdiff.json from the "
                         "current symbol_names.csv. Run by the `gen_objdiff` ninja "
                         "rule AFTER gen_labels, so a unit added this build pairs "
                         "with its real delinked obj in one pass.")
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)

    if args.emit_objdiff:
        emit_objdiff(manifest, REPO / OBJDIFF_DIR)
        print(f"[configure] wrote {OBJDIFF_DIR}/objdiff.json")
        return

    n = len(manifest["unit"])
    pruned = prune_orphan_artifacts(manifest)
    if pruned:
        print(f"[configure] pruned {pruned} artifact(s) of unit(s) no longer in "
              "config/units.toml")
    emit_ninja(manifest, REPO / "build.ninja")
    # objdiff.json is NOT written here: the `gen_objdiff` ninja edge owns it and
    # rebuilds it after gen_labels, so it always reflects the fresh symbol_names.csv
    # (a unit added this build pairs with its real obj in one pass). Single owner =
    # no churn. ninja creates it on the first build.

    print(f"[configure] wrote build.ninja ({n} units); "
          "objdiff.json is built in-graph by the gen_objdiff edge")
    print("[configure] next: ninja   (then objdiff-cli report generate "
          f"-p {OBJDIFF_DIR} -o {OBJDIFF_DIR}/report.json)")


if __name__ == "__main__":
    main()
