#ifndef IMAGE_BYTERUNENCODING_H
#define IMAGE_BYTERUNENCODING_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(ByteRunEncoding)
    BYTE_RUN_CONTROL_MASK = 0xc0,
    BYTE_RUN_MARKER = 0xc0,
    BYTE_RUN_LENGTH_MASK = 0x3f
GZ_ENUM_CONST_END(ByteRunEncoding)

#endif // IMAGE_BYTERUNENCODING_H
