#ifndef GRUNTZ_IMAGE_POLYGONWINDING_H
#define GRUNTZ_IMAGE_POLYGONWINDING_H

#include <Enums.h>

GZ_ENUM_BEGIN(PolygonWinding)
    POLYGON_WINDING_UNSET = 0,
    POLYGON_WINDING_COUNTERCLOCKWISE = 1,
    POLYGON_WINDING_CLOCKWISE = 2
GZ_ENUM_END(PolygonWinding)

#endif // GRUNTZ_IMAGE_POLYGONWINDING_H
