#!/usr/bin/env python3
"""merge_state.py - resolve the generated-state files a lane merge always conflicts on.

Two files conflict on essentially every lane integration, and each has exactly one
correct resolution that is NOT "take a side":

  config/cleanliness-baseline.tsv
                                take the LOWER value, per metric row, THEN RE-MEASURE.
                                These are RATCHETS: the gate FATALs when the measured
                                count exceeds the baseline. Taking the higher side blesses
                                a ratchet upward, which is explicitly forbidden - it would
                                let real regressions through unnoticed forever.

                                But the lower side is a FLOOR, not the answer. Each side's
                                count was measured in ITS OWN tree, and the merged tree
                                holds both sides' work, so its honest count can exceed
                                both. Merging a lane that cut `m_<hex>` 7483 -> 7461 with
                                one that added 98 new-body fields measures 7554: lower
                                than main's pre-merge 7581 (so still a tightening) but
                                above the 7461 min, and pinning 7461 sets a floor nothing
                                can reach. So: take the min provisionally, build, and if
                                the gate fires, set the row to the MEASURED count and
                                compare it against what MAIN had BEFORE the merge.
                                Below main = tightening, keep it. Above main = a real
                                regression - fix the source, never the baseline.

  README.md                     neither side. The stats block is regenerated by
                                `gruntz build`, and a lane's copy is computed against
                                ITS build, not the merged tree. Take ours and rebuild.

Everything else must be resolved by hand - especially source files, where the rule is
COMBINE both lanes' models and notes rather than take a side (two lanes reaching the
same conclusion from different evidence is worth more than either alone).

    python -m gruntz.audit.merge_state          # resolve, report what it did
    python -m gruntz.audit.merge_state --check  # report only, change nothing
"""
import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]


def stage(path, index):
    """The :N: version of a conflicted path, or None when that stage is absent."""
    r = subprocess.run(["git", "show", ":%d:%s" % (index, path)],
                       cwd=REPO, capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else None


def conflicted():
    r = subprocess.run(["git", "diff", "--name-only", "--diff-filter=U"],
                       cwd=REPO, capture_output=True, text=True, check=True)
    return [p for p in r.stdout.split("\n") if p]


def pick_min_rows(ours, theirs):
    """`<metric>\t<count>` rows. Keep the LOWER count per metric, union of rows."""
    def rows(t):
        out = {}
        for line in t.split("\n"):
            if "\t" in line:
                k, v = line.rsplit("\t", 1)
                out[k] = int(v)
        return out
    a, b = rows(ours), rows(theirs)
    merged = dict(a)
    for k, v in b.items():
        merged[k] = min(merged[k], v) if k in merged else v
    order = [l.rsplit("\t", 1)[0] for l in ours.split("\n") if "\t" in l]
    order += [k for k in merged if k not in order]
    return "".join("%s\t%d\n" % (k, merged[k]) for k in order)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="report only")
    a = ap.parse_args()

    files = conflicted()
    if not files:
        print("[merge-state] no conflicts")
        return 0

    handled, left = [], []
    for path in files:
        ours, theirs = stage(path, 2), stage(path, 3)
        if ours is None or theirs is None:
            left.append(path)
            continue
        if path == "config/cleanliness-baseline.tsv":
            text, why = pick_min_rows(ours, theirs), "LOWER per row (ratchet)"
        elif path == "README.md":
            text, why = ours, "ours; regenerate with `gruntz build`"
        else:
            left.append(path)
            continue
        if not a.check:
            (REPO / path).write_text(text)
            subprocess.run(["git", "add", path], cwd=REPO, check=True)
        handled.append((path, why, text.split("\n")[0][:48]))

    for path, why, first in handled:
        print("   %-34s %-28s %s" % (path, why, first))
    if left:
        print("\nSTILL CONFLICTED - resolve by hand, COMBINING both sides' models "
              "and notes rather than taking a side:")
        for path in left:
            print("   %s" % path)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
