#!/usr/bin/env python3
"""gruntz.analysis.gen_boundary_stubs - name the unnamed FUN_ bodies that sit at a
CLASS BOUNDARY and record the two classes they are between.

Sibling of gen_attributed_stubs. That tool handles functions INSIDE a class block
(matched same-class neighbours on both sides -> ~91% exact). This one handles the
functions AT a boundary: the two matched neighbours are DIFFERENT classes, so the
both-sides rule abstains. Picking the nearer class is only ~58% exact (a near
coin-flip - see docs/tu-spatial-structure.md), so instead of committing to one class
we give each a neutral name and document BOTH candidate classes in a comment.

Emits src/Stub/Boundary.cpp: `RVA(rva,size) void Boundary_<rva>() {}` free-function
stubs (the `engine_boundary` unit), each trailed by
`// proximity: <below>@-0xN | <above>@+0xM` so a matcher sees the two neighbours and
which side each is on. No header (free functions need no class decl).

Run: python -m gruntz.analysis.gen_boundary_stubs [--near 0x800]
"""
import argparse
import csv
import re
from pathlib import Path

from gruntz.analysis import tu_layout as T

REPO = next((p for p in Path(__file__).resolve().parents if (p / "flake.nix").exists()),
            Path(__file__).resolve().parents[3])
FUNCS = REPO / "build" / "ghidra-enrich" / "exports" / "functions.csv"
SRC = REPO / "src" / "Stub" / "Boundary.cpp"

MACRO = re.compile(r"\b(?:RVA|RVAU|DATA|SYMBOL)\s*\(\s*(0x[0-9a-fA-F]+)"
                   r"|@rva-symbol:\s*\S+\s+(0x[0-9a-fA-F]+)")


def load_labeled():
    """Every RVA already claimed anywhere in src/ (except our own output) + label CSVs,
    so labels.py's duplicate-RVA guard never fires."""
    lab = set()
    for f in (REPO / "src").rglob("*.cpp"):
        if f.resolve() == SRC.resolve():
            continue
        try:
            for a, b in MACRO.findall(f.read_text(errors="ignore")):
                lab.add(int(a or b, 16))
        except OSError:
            pass
    for c in ("library_labels.csv", "zlib_labels.csv"):
        p = REPO / "config" / c
        if p.exists():
            for r in csv.reader(open(p)):
                try:
                    lab.add(int(r[0], 16))
                except (ValueError, IndexError):
                    pass
    return lab


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--near", type=lambda s: int(s, 0), default=0x800,
                    help="max distance to the nearer matched neighbour (default 0x800)")
    args = ap.parse_args()

    funcs = T.load_funcs()
    boundaries = T.load_boundaries(FUNCS)
    sizes = {rva: size for rva, size, _ in boundaries}
    unnamed = [b[0] for b in boundaries
               if b[2].startswith("FUN_") and not T.is_thunk(b[2], b[1])]
    bnd = T.boundary_targets(funcs, unnamed, near=args.near)

    labeled = load_labeled()
    rows = [(rva, *bnd[rva]) for rva in sorted(bnd) if rva not in labeled]

    sl = ["// AUTO-GENERATED by gruntz.analysis.gen_boundary_stubs - do not hand-edit.",
          "// Unnamed FUN_ bodies that sit AT a class boundary: the two matched neighbours",
          "// are different classes, so single-class proximity abstains (~58% exact). Each",
          "// stub is named neutrally; the trailing comment records the two candidate",
          "// classes (below | above) a matcher should pick between. The `engine_boundary`",
          "// unit; delinked + objdiff'd like any backlog stub.",
          "#include <rva.h>", ""]
    for rva, lo_c, lo_d, hi_c, hi_d in rows:
        sl.append("RVA(0x%08x, 0x%x) void Boundary_%06x() {}  // proximity: %s@-0x%x | %s@+0x%x"
                  % (rva, sizes.get(rva, 1), rva, lo_c, lo_d, hi_c, hi_d))
    sl.append("")
    SRC.parent.mkdir(parents=True, exist_ok=True)
    SRC.write_text("\n".join(sl))
    print("wrote %s (%d boundary stubs; near<=%#x; skipped %d already-labeled)"
          % (SRC, len(rows), args.near, len(bnd) - len(rows)))


if __name__ == "__main__":
    main()
