#!/usr/bin/env python3
"""gruntz.analysis.gen_attributed_stubs - tie proximity-attributed functions to
their class as header decls + RVA stub definitions.

Sibling of gruntz.analysis.gen_class_stubs (which integrates the runtime this/ecx
trace). Where that uses dynamic call observations, this uses the STATIC layout fact
from gruntz.analysis.tu_layout: an unnamed FUN_ body flanked on both sides - within
--gap - by the same class C, where C sits in a contiguous run of >=3 of its own
matched methods (and not in a special-member pool), is C. Leave-one-out on the
matched methods puts this HIGH-confidence rule at ~91% exact / 94% same-family
(see docs/tu-spatial-structure.md). The two signals are complementary: the trace
reaches runtime-called functions, proximity reaches functions bracketed by matched
siblings - in practice a disjoint set.

For every HIGH-confidence attribution NOT already labeled anywhere it emits:
  - include/Stub/attributed.h : minimal class decls with the recovered methods
    (`<Class>_<rva>()`), grouped by class.
  - src/Stub/Attributed.cpp   : `RVA(rva,size) void <Class>::<Class>_<rva>() {}`
    empty __thiscall stubs (own TU; the `engine_attributed` unit).

So each attribution becomes a real, binary-verified backlog stub: the delinker
carves the retail bytes at the RVA and objdiff tracks it like any stub. A matcher
later reconstructs it and, if the proximity class was off, moves it to the right TU.

Run: python -m gruntz.analysis.gen_attributed_stubs [--include-med]
"""
import argparse
import collections
import csv
import re
from pathlib import Path

from gruntz.analysis import tu_layout as T

REPO = next((p for p in Path(__file__).resolve().parents if (p / "flake.nix").exists()),
            Path(__file__).resolve().parents[3])
FUNCS = REPO / "build" / "ghidra-enrich" / "exports" / "functions.csv"
HDR = REPO / "include" / "Stub" / "attributed.h"
SRC = REPO / "src" / "Stub" / "Attributed.cpp"

IDENT = re.compile(r"^[A-Za-z_]\w*$")
# the build's duplicate-RVA guard label forms (scripts/gruntz/build/labels.py).
MACRO = re.compile(r"\b(?:RVA|RVAU|DATA|SYMBOL)\s*\(\s*(0x[0-9a-fA-F]+)"
                   r"|@rva-symbol:\s*\S+\s+(0x[0-9a-fA-F]+)")


def load_labeled():
    """Every RVA already claimed by a src macro / label CSV - skip them so labels.py's
    duplicate-RVA guard never fires. Scans ALL of src/ (incl. the trace's
    Discovered.cpp) EXCEPT our own output, so the proximity set is deduped against
    every matched function and trace stub."""
    lab = set()
    for f in (REPO / "src").rglob("*.cpp"):
        if f.resolve() == SRC.resolve():
            continue
        try:
            for a, b in MACRO.findall(f.read_text(errors="ignore")):
                lab.add(int(a or b, 16))
        except OSError:
            pass
    for c in ("library_labels.csv", "zlib_labels.csv"):
        p = REPO / "config" / c
        if p.exists():
            for r in csv.reader(open(p)):
                try:
                    lab.add(int(r[0], 16))
                except (ValueError, IndexError):
                    pass
    return lab


def valid_class(name):
    parts = name.split("::")
    return bool(parts) and all(IDENT.match(p) for p in parts)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--gap", type=lambda s: int(s, 0), default=T.DEFAULT_GAP)
    ap.add_argument("--include-med", action="store_true",
                    help="also emit MED-confidence attributions (right family, not "
                         "always the exact class)")
    args = ap.parse_args()

    funcs = T.load_funcs()
    boundaries = T.load_boundaries(FUNCS)
    sizes = {rva: size for rva, size, _ in boundaries}
    attr, _ = T.attribute(funcs, boundaries, args.gap)
    keep = {"HIGH", "MED"} if args.include_med else {"HIGH"}

    labeled = load_labeled()
    by_class = collections.defaultdict(list)   # class -> [(rva, size, conf)]
    skipped_labeled = skipped_bad = 0
    for rva in sorted(attr):
        cls, conf = attr[rva]
        if conf not in keep:
            continue
        if not valid_class(cls):
            skipped_bad += 1
            continue
        if rva in labeled:
            skipped_labeled += 1            # already named elsewhere - don't re-stub
            continue
        by_class[cls].append((rva, sizes.get(rva, 1), conf))

    # ---- header: minimal class decls -----------------------------------------
    HDR.parent.mkdir(parents=True, exist_ok=True)
    hl = ["// AUTO-GENERATED by gruntz.analysis.gen_attributed_stubs - do not hand-edit.",
          "// Proximity-attributed class memberships (static RVA bracketing, ~91% exact;",
          "// see docs/tu-spatial-structure.md): each `<Class>_<rva>()` is a __thiscall",
          "// method attributed to <Class>, defined as an RVA stub in src/Stub/Attributed.cpp.",
          "// Minimal decls; real classes are fully modelled in their own TUs (separate",
          "// translation unit, so this is conflict-free).",
          "#ifndef GRUNTZ_STUB_ATTRIBUTED_H", "#define GRUNTZ_STUB_ATTRIBUTED_H", ""]
    for klass in sorted(by_class):
        *ns, leaf = klass.split("::")
        methods = "".join(" void %s_%06x();" % (leaf, rva)
                          for rva, _, _ in sorted(by_class[klass]))
        decl = "class %s { public:%s };" % (leaf, methods)
        for n in reversed(ns):
            decl = "namespace %s { %s }" % (n, decl)
        hl.append(decl)
    hl += ["", "#endif", ""]
    HDR.write_text("\n".join(hl))

    # ---- source: RVA stub definitions ----------------------------------------
    sl = ["// AUTO-GENERATED by gruntz.analysis.gen_attributed_stubs - do not hand-edit.",
          "// Empty __thiscall stubs at each proximity-attributed RVA; the class is the",
          "// static-layout bracket assignment (conf in the trailing comment). @stub",
          "// backlog -> reconstruct from objdiff; a matcher moves it if the class was off.",
          "#include <rva.h>", "#include <Stub/attributed.h>", ""]
    nstub = 0
    for klass in sorted(by_class):
        leaf = klass.split("::")[-1]
        sl.append("// ---- %s ----" % klass)
        for rva, size, conf in sorted(by_class[klass]):
            sl.append("RVA(0x%08x, 0x%x) void %s::%s_%06x() {}  // %s"
                      % (rva, size, klass, leaf, rva, conf.lower()))
            nstub += 1
        sl.append("")
    SRC.parent.mkdir(parents=True, exist_ok=True)
    SRC.write_text("\n".join(sl))

    print("wrote %s (%d classes) + %s (%d RVA stubs)" % (HDR, len(by_class), SRC, nstub))
    print("  confidence kept: %s; skipped %d already-labeled, %d invalid-class"
          % ("+".join(sorted(keep)), skipped_labeled, skipped_bad))


if __name__ == "__main__":
    main()
