#!/usr/bin/env python3
"""gruntz.analysis.gen_frida_script - emit the frida-gadget JS for this/ecx tracing.

Frida (loaded into GRUNTZ.EXE under wine as SFMAN32.DLL via the gadget) hooks every
game __thiscall entry with an inline trampoline, reads ecx (`this`) on entry, dedups
on (rva,ecx), retires a hook once saturated, and streams (rva,ecx,seq) edges to a
CSV. Unlike gdb breakpoints this is in-process and does NOT stop the world, so the
game keeps rendering and stays playable while it traces.

Run: python -m gruntz.analysis.gen_frida_script [funcs.csv] [out.js] [edges_name]
  funcs.csv   : rva[,name] list (default build/trace/thiscall_game.csv)
  out.js      : output script   (default build/game/retail/gruntz_trace.js)
  edges_name  : edges file written by the gadget, relative to the game cwd
                (default gruntz_edges.csv -> build/game/retail/gruntz_edges.csv)
"""
import csv
import sys
from pathlib import Path

REPO = next((p for p in Path(__file__).resolve().parents if (p / "flake.nix").exists()),
            Path(__file__).resolve().parents[3])

# K   : retire a hook after this many distinct ecx (objects) seen
# MAX : retire after this many total hits. Kept low so HOT functions (tight loops,
#       math helpers) drop their inline hook after a few calls instead of paying the
#       per-hit JS callback thousands of times -> lets us hook the full ~7k-fn set
#       while the game stays playable. Overridable via env GRUNTZ_TRACE_K / _MAX.
import os as _os
K = int(_os.environ.get("GRUNTZ_TRACE_K", "24"))
MAX = int(_os.environ.get("GRUNTZ_TRACE_MAX", "64"))
# PATCH: neutralize _free so each ecx is a unique object (best identity) but the
# 32-bit heap leaks and eventually OOMs -> good for SHORT sessions. Set
# GRUNTZ_TRACE_PATCH=0 for LONG/stable sessions (no leak; clustering tolerates the
# occasional address reuse via majority-vote purity).
PATCH = _os.environ.get("GRUNTZ_TRACE_PATCH", "1") == "1"
FREE_RVA = 0x120c30   # _free

TEMPLATE = """// AUTO-GENERATED by gruntz.analysis.gen_frida_script - do not hand-edit.
'use strict';
var BASE = ptr('0x400000');
var K = %(K)d, MAXHITS = %(MAX)d;
var RVAS = [%(rvas)s];

var OUT = new File('%(edges)s', 'w');
OUT.write('rva,ecx,seq\\n'); OUT.flush();
var seq = 0;

// crash diagnostics: on a fault, log the faulting pc + the stack return addresses
// (resolved to GRUNTZ RVAs) so a hook-induced crash points at the culprit function.
Process.setExceptionHandler(function (d) {
  var f = new File('frida_crash.log', 'w');
  try {
    var c = d.context;
    f.write('type=' + d.type + ' faultAddr=' + d.address + ' pc=' + c.pc + ' sp=' + c.sp + '\\n');
    f.write('eax=' + c.eax + ' ecx=' + c.ecx + ' edx=' + c.edx + ' ebx=' + c.ebx +
            ' esi=' + c.esi + ' edi=' + c.edi + ' ebp=' + c.ebp + '\\n');
    var pcr = c.pc.toUInt32() - 0x400000;
    if (pcr > 0 && pcr < 0x300000) f.write('pc in GRUNTZ +0x' + pcr.toString(16) + '\\n');
    var sp = c.sp;
    for (var i = 0; i < 20; i++) {
      var v = null; try { v = sp.add(i * 4).readPointer(); } catch (e) {}
      if (v) {
        var r = v.toUInt32() - 0x400000;
        f.write('  [sp+' + (i * 4) + '] = ' + v +
                (r > 0 && r < 0x300000 ? '  (GRUNTZ +0x' + r.toString(16) + ')' : '') + '\\n');
      }
    }
  } catch (e) { f.write('handler err ' + e + '\\n'); }
  f.flush();
  return false;
});

// neutralize _free -> `ret` so nothing is ever deallocated; with no address reuse
// every distinct ecx is a globally-unique object identity for the whole run.
if (%(dopatch)s) {
  try {
    var freeAddr = BASE.add(0x%(free)x);
    Memory.protect(freeAddr, 16, 'rwx');
    freeAddr.writeU8(0xC3);
  } catch (e) {}
}

function attachOne(rva) {
  var addr = BASE.add(rva);
  var rvaHex = '0x' + rva.toString(16);
  var seen = Object.create(null);
  var nseen = 0, hits = 0;
  var listener = Interceptor.attach(addr, {
    onEnter: function () {
      hits++;
      var ecx = this.context.ecx.toString();   // "0x...."
      if (!(ecx in seen)) {
        seen[ecx] = 1; nseen++; seq++;
        OUT.write(rvaHex + ',' + ecx + ',' + seq + '\\n'); OUT.flush();
      }
      if (nseen >= K || hits >= MAXHITS) { listener.detach(); }
    }
  });
}

// Attach in chunks across event-loop ticks: each Interceptor.attach commit briefly
// pauses the target, so committing all ~7k at once stalls the game for a long time.
// Chunking yields between batches so the game is playable from t=0 and hook
// coverage ramps up in the background.
var idx = 0;
var CHUNK = 150;
function attachChunk() {
  var end = Math.min(idx + CHUNK, RVAS.length);
  for (; idx < end; idx++) { try { attachOne(RVAS[idx]); } catch (e) {} }
  var prog = new File('frida_trace.log', 'w');
  prog.write('hooked ' + idx + '/' + RVAS.length + ' fns; free-patch=%(dopatch)s; K=' + K
             + ' MAX=' + MAXHITS + (idx >= RVAS.length ? ' (DONE)' : ' (attaching...)') + '\\n');
  prog.flush();
  if (idx < RVAS.length) { setTimeout(attachChunk, 1); }
}
attachChunk();
"""


def load_rvas(path):
    rvas = []
    with open(path) as f:
        for row in csv.reader(f):
            if not row:
                continue
            c0 = row[0].strip().strip('"')
            if not c0 or c0.lower() == "rva":
                continue
            try:
                rvas.append(int(c0, 16))
            except ValueError:
                pass
    return rvas


def load_text(exe):
    """Return (.text raw bytes, rva_lo, rva_hi) of the PE at `exe`."""
    import struct
    d = open(exe, "rb").read()
    e = struct.unpack_from("<I", d, 0x3c)[0]
    nsec = struct.unpack_from("<H", d, e + 6)[0]
    opt = struct.unpack_from("<H", d, e + 20)[0]
    off = e + 24 + opt
    for _ in range(nsec):
        name = d[off:off + 8].rstrip(b"\x00")
        vs = struct.unpack_from("<I", d, off + 8)[0]
        va = struct.unpack_from("<I", d, off + 12)[0]
        rs = struct.unpack_from("<I", d, off + 16)[0]
        raw = struct.unpack_from("<I", d, off + 20)[0]
        if name == b".text":
            n = min(vs, rs) if rs else vs
            return d[raw:raw + n], va, va + n
        off += 40
    return b"", 0, 0


# First bytes that are NOT real hookable function bodies:
#   e9/eb = jmp (ILT thunk), ff25 = jmp [iat] thunk, cc/90/00 = padding/data,
#   c3/c2 = a bare `ret` (0-size fn). Hooking these corrupts code/vtables under
#   Frida; their real targets are separate entries, so coverage is unaffected.
_SKIP_FIRST = {0xE9, 0xEB, 0xCC, 0x90, 0x00, 0xC3, 0xC2}

# RVA ranges to skip entirely. The MFC window/dialog cluster (NAFXCW) holds a
# function whose Frida inline trampoline corrupts a stack object's vtable -> a
# NULL virtual call (in HandleSetFont, via WM_SETFONT) when the save/checkpoint
# dialog opens. It's MFC, not engine, so skipping the band costs no engine
# coverage. (Found via the edge ordering: last fns hit before the crash were here.)
_SKIP_RANGES = [(0x1b9000, 0x1c2000)]

def is_real_body(tb, lo, hi, rva):
    if not (lo <= rva < hi):
        return False
    for r0, r1 in _SKIP_RANGES:
        if r0 <= rva < r1:
            return False
    i = rva - lo
    if i >= len(tb):
        return False
    b = tb[i]
    if b in _SKIP_FIRST:
        return False
    if b == 0xFF and i + 1 < len(tb) and tb[i + 1] == 0x25:   # jmp dword [iat]
        return False
    return True


def main():
    funcs = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "build/trace/thiscall_game.csv"
    out_js = Path(sys.argv[2]) if len(sys.argv) > 2 else REPO / "build/game/retail/gruntz_trace.js"
    edges = sys.argv[3] if len(sys.argv) > 3 else "gruntz_edges.csv"
    rvas = load_rvas(funcs)
    # drop thunks/padding/data so Frida only patches real function bodies
    exe = REPO / "build/game/retail/GRUNTZ.EXE"
    if not exe.exists():
        exe = REPO / "build/exe/GRUNTZ.EXE"
    if exe.exists():
        tb, lo, hi = load_text(str(exe))
        before = len(rvas)
        rvas = [r for r in rvas if is_real_body(tb, lo, hi, r)]
        print("filtered thunks/padding: %d -> %d (dropped %d)" % (before, len(rvas), before - len(rvas)))
    js = TEMPLATE % {
        "K": K, "MAX": MAX, "free": FREE_RVA, "edges": edges,
        "dopatch": "true" if PATCH else "false",
        "rvas": ",".join("0x%x" % r for r in rvas),
    }
    out_js.write_text(js)
    print("wrote %s: %d hooks (free-patch=%s, edges -> %s)"
          % (out_js, len(rvas), PATCH, edges))


if __name__ == "__main__":
    main()
