#!/usr/bin/env python3
"""gruntz.analysis.gen_class_stubs - integrate the trace's function->class ties
into the codebase as header decls + RVA stub definitions.

Reads docs/this-pointer-classes.csv (from tie_classes.py) and, for every
trace-discovered function (not yet labeled), emits:
  - include/Stub/discovered.h : minimal class decls with the recovered methods
    (`<Class>_<rva>()`), grouped by class incl. the synthetic ClassUnknown_<n>.
  - src/Stub/Discovered.cpp    : `RVA(rva,size) void <Class>::<Class>_<rva>() {}`
    empty stubs (own TU; aggregated as the `engine_discovered` unit).

These are __thiscall member stubs (ecx=this), so the delinker carves the retail
bytes at each RVA and objdiff tracks them like any backlog stub - i.e. the trace's
class assignment becomes a real, binary-verified worklist entry.

Run: python -m gruntz.analysis.gen_class_stubs
"""
import collections
import csv
import re
from pathlib import Path

REPO = next((p for p in Path(__file__).resolve().parents if (p / "flake.nix").exists()),
            Path(__file__).resolve().parents[3])
TABLE = REPO / "docs" / "this-pointer-classes.csv"
FUNCS = REPO / "build" / "ghidra-enrich" / "exports" / "functions.csv"
HDR = REPO / "include" / "Stub" / "discovered.h"
SRC = REPO / "src" / "Stub" / "Discovered.cpp"

IDENT = re.compile(r"^[A-Za-z_]\w*$")


def load_sizes():
    sz = {}
    if FUNCS.exists():
        with open(FUNCS) as f:
            for r in csv.DictReader(f):
                sz[int(r["entry_rva"], 16)] = int(r["byte_size"])
    return sz


def load_labeled():
    """RVAs already labeled elsewhere (src RVA/RVAU/DATA macros + `@rva-symbol:` comments
    + label CSVs) - skip them, or labels.py's duplicate-RVA guard fails when main has
    since claimed them (e.g. compiler-emitted `??_G` deleting-dtors use @rva-symbol)."""
    lab = set()
    # mirror the build's dup-guard label forms (scripts/gruntz/build/labels.py): RVA/DATA/
    # SYMBOL macros (whitespace-tolerant) + RVAU + `@rva-symbol:` comments (?_G dtors etc.)
    macro = re.compile(r"\b(?:RVA|RVAU|DATA|SYMBOL)\s*\(\s*(0x[0-9a-fA-F]+)"
                       r"|@rva-symbol:\s*\S+\s+(0x[0-9a-fA-F]+)")
    for f in (REPO / "src").rglob("*.cpp"):
        if f.name == "Discovered.cpp":
            continue
        try:
            for a, b in macro.findall(f.read_text(errors="ignore")):
                lab.add(int(a or b, 16))
        except OSError:
            pass
    for c in ("library_labels.csv", "zlib_labels.csv"):
        p = REPO / "config" / c
        if p.exists():
            for r in csv.reader(open(p)):
                try:
                    lab.add(int(r[0], 16))
                except (ValueError, IndexError):
                    pass
    return lab


def valid_class(name):
    parts = name.split("::")
    return parts and all(IDENT.match(p) for p in parts)


def main():
    sizes = load_sizes()
    labeled = load_labeled()
    by_class = collections.defaultdict(list)   # class -> [(rva, size)]
    seen = set()
    skipped_labeled = 0
    with open(TABLE) as f:
        for r in csv.DictReader(f):
            if r["source"] not in ("trace", "trace-new"):
                continue
            klass = r["class"].strip()
            if not valid_class(klass):
                continue                       # e.g. "(ambiguous)"
            rva = int(r["rva"], 16)
            if rva in seen:
                continue
            seen.add(rva)
            if rva in labeled:
                skipped_labeled += 1           # already named elsewhere - don't re-stub
                continue
            by_class[klass].append((rva, sizes.get(rva, 1)))

    # ---- header: minimal class decls (namespaces handled) ----------------------
    HDR.parent.mkdir(parents=True, exist_ok=True)
    hl = ["// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.",
          "// Trace-discovered class memberships (docs/this-pointer-classes.csv): each",
          "// `<Class>_<rva>()` is a recovered __thiscall method, defined as an RVA stub in",
          "// src/Stub/Discovered.cpp. Minimal decls; real classes are fully modelled in",
          "// their own TUs (separate translation unit, so this is conflict-free).",
          "#ifndef GRUNTZ_STUB_DISCOVERED_H", "#define GRUNTZ_STUB_DISCOVERED_H", ""]
    for klass in sorted(by_class):
        *ns, leaf = klass.split("::")
        methods = "".join(" void %s_%06x();" % (leaf, rva) for rva, _ in sorted(by_class[klass]))
        decl = "class %s { public:%s };" % (leaf, methods)
        for n in reversed(ns):
            decl = "namespace %s { %s }" % (n, decl)
        hl.append(decl)
    hl += ["", "#endif", ""]
    HDR.write_text("\n".join(hl))

    # ---- source: RVA stub definitions -----------------------------------------
    sl = ["// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.",
          "// Empty __thiscall stubs at each trace-discovered RVA; the class is the trace's",
          "// (inheritance-aware) assignment. @stub backlog -> reconstruct from objdiff.",
          "#include <rva.h>", "#include <Stub/discovered.h>", ""]
    nstub = 0
    for klass in sorted(by_class):
        leaf = klass.split("::")[-1]
        sl.append("// ---- %s ----" % klass)
        for rva, size in sorted(by_class[klass]):
            sl.append("RVA(0x%08x, 0x%x) void %s::%s_%06x() {}" % (rva, size, klass, leaf, rva))
            nstub += 1
        sl.append("")
    SRC.parent.mkdir(parents=True, exist_ok=True)
    SRC.write_text("\n".join(sl))

    nunknown = sum(1 for k in by_class if k.startswith("ClassUnknown"))
    print("wrote %s (%d classes) + %s (%d RVA stubs)" % (HDR, len(by_class), SRC, nstub))
    print("  %d real classes + %d ClassUnknown groups; skipped %d already-labeled in main"
          % (len(by_class) - nunknown, nunknown, skipped_labeled))


if __name__ == "__main__":
    main()
