#ifndef GRUNTZ_GRUNTZ_ACTIONAREAOWNER_H
#define GRUNTZ_GRUNTZ_ACTIONAREAOWNER_H

#include <Enums.h>

GZ_ENUM_BEGIN(ActionAreaOwner)
    ACTION_AREA_BLUE_OWNER = 1,
    ACTION_AREA_RED_OWNER = 2
GZ_ENUM_END(ActionAreaOwner)

#endif // GRUNTZ_GRUNTZ_ACTIONAREAOWNER_H
