#ifndef GRUNTZ_GRUNTZ_ARRIVALFLAGSPRESET_H
#define GRUNTZ_GRUNTZ_ARRIVALFLAGSPRESET_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(ArrivalFlagsPreset)
    ARRIVAL_FLAGS_PLAYER = 0x4000901,
    ARRIVAL_FLAGS_PLAYER_SINGLE = 0x4000911,
    ARRIVAL_FLAGS_BATTLEZ = 0x4000983,
    ARRIVAL_FLAGS_ENEMY = 0x1c000d83
GZ_ENUM_CONST_END(ArrivalFlagsPreset)

#endif // GRUNTZ_GRUNTZ_ARRIVALFLAGSPRESET_H
