#ifndef GRUNTZ_GRUNTZ_BATTLESTATROW_H
#define GRUNTZ_GRUNTZ_BATTLESTATROW_H

#include <Enums.h>

GZ_ENUM_BEGIN(BattleStatRow)
    BATTLEROW_FORTZ = 0,
    BATTLEROW_KILLZ = 1,
    BATTLEROW_GRUNTZ = 2,
    BATTLEROW_TOOLZ = 3,
    BATTLEROW_TOYZ = 4,
    BATTLEROW_POWERUPZ = 5,
    BATTLEROW_CURSEZ = 6,
    BATTLEROW_COUNT = 7
GZ_ENUM_END(BattleStatRow)

#endif // GRUNTZ_GRUNTZ_BATTLESTATROW_H
