#ifndef GRUNTZ_GRUNTZ_BATTLEZINTERVALMS_H
#define GRUNTZ_GRUNTZ_BATTLEZINTERVALMS_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(BattlezIntervalMs)
    BLOCKED_VOICE_INTERVAL_MS = 0x1388
GZ_ENUM_CONST_END(BattlezIntervalMs)

#endif // GRUNTZ_GRUNTZ_BATTLEZINTERVALMS_H
