#ifndef GRUNTZ_GRUNTZ_BATTLEZUNITKIND_H
#define GRUNTZ_GRUNTZ_BATTLEZUNITKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(BattlezUnitKind)
    BZUNIT_BOMB = 1,
    BZUNIT_GUNHAT = 2,
    BZUNIT_GAUNTLETZ = 3,
    BZUNIT_CLUB = 4,
    BZUNIT_SHIELD = 5,
    BZUNIT_GLOVEZ = 6,
    BZUNIT_BRICK = 7,
    BZUNIT_GRAVITYBOOTZ = 8,
    BZUNIT_BOOMERANG = 9,
    BZUNIT_SPY = 10,
    BZUNIT_NERFGUN = 11,
    BZUNIT_ROCK = 12,
    BZUNIT_GOOBER = 13,
    BZUNIT_SWORD = 14,
    BZUNIT_SHOVEL = 15,
    BZUNIT_SHOVEL_MOUNTED = 16
GZ_ENUM_END(BattlezUnitKind)

#endif // GRUNTZ_GRUNTZ_BATTLEZUNITKIND_H
