#ifndef GRUNTZ_GRUNTZ_BOOTYSTATROW_H
#define GRUNTZ_GRUNTZ_BOOTYSTATROW_H

#include <Enums.h>

GZ_ENUM_BEGIN(BootyStatRow)
    BOOTYSTAT_TIME = 0,
    BOOTYSTAT_GRUNTZ_EXITED = 1,
    BOOTYSTAT_GRUNTZ_LOST = 2,
    BOOTYSTAT_TOOLZ = 3,
    BOOTYSTAT_TOYZ = 4,
    BOOTYSTAT_POWERUPZ = 5,
    BOOTYSTAT_COINZ = 6,
    BOOTYSTAT_SECRETZ = 7,
    BOOTYSTAT_COUNT = 8
GZ_ENUM_END(BootyStatRow)

#endif // GRUNTZ_GRUNTZ_BOOTYSTATROW_H
