#ifndef GRUNTZ_GRUNTZ_BOOTYSEQPHASE_H
#define GRUNTZ_GRUNTZ_BOOTYSEQPHASE_H

#include <Enums.h>

GZ_ENUM_BEGIN(BootySeqPhase)
    BOOTYSEQ_SECRET_PENDING = -2,
    BOOTYSEQ_WARP_CUE = 100,
    BOOTYSEQ_GLITTER = 101,
    BOOTYSEQ_LETTERS = 102,
    BOOTYSEQ_WALK = 103,
    BOOTYSEQ_PERFECT_BONUS = 199,
    BOOTYSEQ_DONE = 200
GZ_ENUM_END(BootySeqPhase)

#endif // GRUNTZ_GRUNTZ_BOOTYSEQPHASE_H
