#ifndef GRUNTZ_GRUNTZ_CARDINALDIR_H
#define GRUNTZ_GRUNTZ_CARDINALDIR_H

#include <Enums.h>

GZ_ENUM_BEGIN(CardinalDir)
    CARDINAL_NORTH = 1,
    CARDINAL_EAST = 2,
    CARDINAL_SOUTH = 3,
    CARDINAL_WEST = 4,
    CARDINAL_FIRST = CARDINAL_NORTH,
    CARDINAL_LAST = CARDINAL_WEST,
    CARDINAL_COUNT = 4
GZ_ENUM_END(CardinalDir)

#endif // GRUNTZ_GRUNTZ_CARDINALDIR_H
