#ifndef GRUNTZ_GRUNTZ_CUSTOMMAPSELECTION_H
#define GRUNTZ_GRUNTZ_CUSTOMMAPSELECTION_H

#include <Enums.h>

GZ_ENUM_BEGIN(CustomMapSelection)
    CUSTOM_MAP_STANDARD = 0,
    CUSTOM_MAP_SELECTED = 1,
    CUSTOM_MAP_UNINITIALIZED = 2
GZ_ENUM_END(CustomMapSelection)

#endif // GRUNTZ_GRUNTZ_CUSTOMMAPSELECTION_H
