#ifndef GRUNTZ_GRUNTZ_DEBUGDISPLAYFLAGS_H
#define GRUNTZ_GRUNTZ_DEBUGDISPLAYFLAGS_H

#include <Enums.h>

GZ_ENUM_FLAGS_BEGIN(DebugDisplayFlags, i32)
    DEBUG_DISPLAY_NONE = 0,
    DEBUG_DISPLAY_OBJECT_COUNT = 0x1,
    DEBUG_DISPLAY_NETWORK_COUNTERS = 0x2,
    DEBUG_DISPLAY_WORLD_POSITION = 0x4,
    DEBUG_DISPLAY_PROFILE_TEXT = 0x8,
    DEBUG_DISPLAY_FRAME_RATE = 0x10,
    DEBUG_DISPLAY_SUPPRESS = 0x20,
    DEBUG_DISPLAY_TIMING = 0x40,
    DEBUG_DISPLAY_ELAPSED_TIME = 0x80,
    DEBUG_DISPLAY_TIMING_ALTERNATE = 0x100,
    DEBUG_DISPLAY_FRAME_RATE_LIMIT = 0x200,
    DEBUG_DISPLAY_BUILD_INFO = 0x400,
GZ_ENUM_FLAGS_END(DebugDisplayFlags, i32)
GZ_ENUM_FLAGS_OPS(DebugDisplayFlags)

#endif // GRUNTZ_GRUNTZ_DEBUGDISPLAYFLAGS_H
