#ifndef GRUNTZ_GRUNTZ_DEMOMOVERSTATE_H
#define GRUNTZ_GRUNTZ_DEMOMOVERSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(DemoMoverState)
    DEMO_MOVER_CHOOSE_TARGET = 0,
    DEMO_MOVER_SCROLL_TO_TARGET = 1
GZ_ENUM_END(DemoMoverState)

#endif // GRUNTZ_GRUNTZ_DEMOMOVERSTATE_H
