#ifndef GRUNTZ_GRUNTZ_DESTRUCTWARNINGSTATE_H
#define GRUNTZ_GRUNTZ_DESTRUCTWARNINGSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(DestructWarningState)
    DESTRUCT_WARNING_INACTIVE = 0,
    DESTRUCT_WARNING_FORWARD = 1,
    DESTRUCT_WARNING_REVERSE = 2
GZ_ENUM_END(DestructWarningState)

GZ_ENUM_BEGIN(DestructButtonFrame)
    DESTRUCT_FRAME_IDLE = 1,
    DESTRUCT_FRAME_WARNING_FIRST = 2,
    DESTRUCT_FRAME_WARNING_LAST = 6,
    DESTRUCT_FRAME_DISABLED = 7
GZ_ENUM_END(DestructButtonFrame)
GZ_ENUM_STEPPED(DestructButtonFrame)

#endif // GRUNTZ_GRUNTZ_DESTRUCTWARNINGSTATE_H
