#ifndef GRUNTZ_GRUNTZ_ENEMYAITYPE_H
#define GRUNTZ_GRUNTZ_ENEMYAITYPE_H

#include <Enums.h>

GZ_ENUM_BEGIN(EnemyAiType)
    AI_NONE = 0,
    AI_DUMBCHASER = 1,
    AI_SMARTCHASER = 2,
    AI_HITANDRUNNER = 3,
    AI_DEFENDER = 4,
    AI_POSTGUARD = 5,
    AI_OBJECTGUARD = 6,
    AI_BOMBER = 7,
    AI_BRICKLAYER = 8,
    AI_GAUNTLETZGRUNT = 9,
    AI_GOOSUCKER = 10,
    AI_DIGGER = 11,
    AI_TIMEBOMBER = 12,
    AI_TOOLTHIEF = 13,
    AI_TOYER = 14,
    AI_MAGICWANDGRUNT = 15,
    AI_SCROLLGRUNT = 16,
    AI_BATTLEZ_PATH = 0x11
GZ_ENUM_END(EnemyAiType)

#endif // GRUNTZ_GRUNTZ_ENEMYAITYPE_H
