#ifndef GRUNTZ_GRUNTZ_ENUMS_H
#define GRUNTZ_GRUNTZ_ENUMS_H

#include <rva.h>

#include <Ints.h>

enum GruntType {
    GRUNT_NORMAL = 0,

    GRUNT_BOMB = 1,
    GRUNT_BOOMERANG = 2,
    GRUNT_BRICK = 3,
    GRUNT_CLUB = 4,
    GRUNT_GAUNTLETZ = 5,
    GRUNT_GLOVEZ = 6,
    GRUNT_GOOBER = 7,
    GRUNT_GRAVITYBOOTZ = 8,
    GRUNT_GUNHAT = 9,
    GRUNT_NERFGUN = 10,
    GRUNT_ROCK = 11,
    GRUNT_SHIELD = 12,
    GRUNT_SHOVEL = 13,
    GRUNT_SPRING = 14,
    GRUNT_SPY = 15,
    GRUNT_SWORD = 16,
    GRUNT_TIMEBOMB = 17,
    GRUNT_TOOB = 18,
    GRUNT_WAND = 19,
    GRUNT_WARPSTONE = 20,
    GRUNT_WELDER = 21,
    GRUNT_WINGZ = 22,

    GRUNT_BABYWALKER = 0x17,
    GRUNT_BEACHBALL = 0x18,
    GRUNT_BIGWHEEL = 0x19,
    GRUNT_GOKART = 0x1a,
    GRUNT_JACKINTHEBOX = 0x1b,
    GRUNT_JUMPROPE = 0x1c,
    GRUNT_POGOSTICK = 0x1d,
    GRUNT_SCROLL = 0x1e,
    GRUNT_SQUEAKTOY = 0x1f,
    GRUNT_YOYO = 0x20,

    GRUNT_GHOST = 0x36,
    GRUNT_SUPERSPEED = 0x37,
    GRUNT_INVULNERABLE = 0x38,
    GRUNT_CONVERSION = 0x39,
    GRUNT_DEATHTOUCH = 0x3a,
    GRUNT_ROIDZ = 0x3b,

    GRUNT_REACTIVEARMOR = 0x3c,
};

typedef enum GruntDeathKind {

    GRUNT_DEATH_WARPOUT = 0xc,
} GruntDeathKind;

typedef enum RezTypeTag {
    REZ_TAG_WWD = 0x575744,
    REZ_TAG_WAV = 0x574156,
    REZ_TAG_ANI = 0x414e49,
} RezTypeTag;

enum Tool {
    TOOL_BOMBZ,
    TOOL_BOOMERANGZ,
    TOOL_BRICKZ,
    TOOL_CLUBZ,
    TOOL_GAUNTLETZ,
    TOOL_GLOVEZ,
    TOOL_GOOBERZ,
    TOOL_GRAVITYBOOTZ,
    TOOL_GUNHATZ,
    TOOL_NERFGUNZ,
    TOOL_ROCKZ,
    TOOL_SHIELDZ,
    TOOL_SHOVELZ,
    TOOL_SPRINGZ,
    TOOL_SPYZ,
    TOOL_SWORDZ,
    TOOL_TIMEBOMBZ,
    TOOL_TOOBZ,
    TOOL_WANDZ,
    TOOL_WARPSTONEZ1,
    TOOL_WELDERZ,
    TOOL_WINGZ,
    TOOL_COUNT
};

enum Toy {
    TOY_BABYWALKERZ,
    TOY_BEACHBALLZ,
    TOY_BIGWHEELZ,
    TOY_GOKARTZ,
    TOY_JACKINTHEBOXZ,
    TOY_JUMPROPEZ,
    TOY_POGOSTICKZ,
    TOY_SCROLLZ,
    TOY_SQUEAKTOYZ,
    TOY_YOYOZ,
    TOY_COUNT
};

enum Warlord {
    WARLORD_KING,
    WARLORD_NAPOLEAN,
    WARLORD_PATTON,
    WARLORD_VIKING,
    WARLORD_COUNT
};

enum Powerup {
    POWERUP_COIN,
    POWERUP_GHOST,
    POWERUP_MINICAM,
    POWERUP_ROIDZ,
    POWERUP_CONVERSION,
    POWERUP_COUNT
};

enum ColorTint {
    TINT_BLACK,
    TINT_BLUE,
    TINT_CYAN,
    TINT_DKBLUE,
    TINT_DKGREEN,
    TINT_DKRED,
    TINT_DKYELLOW,
    TINT_GREEN,
    TINT_GREY,
    TINT_HOTPINK,
    TINT_ORANGE,
    TINT_PINK,
    TINT_PURPLE,
    TINT_RED,
    TINT_TURQ,
    TINT_WHITE,
    TINT_YELLOW,
    TINT_COUNT
};

enum Direction {
    DIR_NORTH,
    DIR_NORTHEAST,
    DIR_EAST,
    DIR_SOUTHEAST,
    DIR_SOUTH,
    DIR_SOUTHWEST,
    DIR_WEST,
    DIR_NORTHWEST,
    DIR_COUNT
};

enum Statez {
    STATEZ_SPLASH,
    STATEZ_MENU,
    STATEZ_HELP,
    STATEZ_CREDITZ,
    STATEZ_ATTRACT,
    STATEZ_PREVIEW,
    STATEZ_BOOTY,
    STATEZ_MULTI,
    STATEZ_COUNT
};

enum LaunchMode {
    LAUNCH_PLAY,
    LAUNCH_MULTI,
    LAUNCH_DEMO,
    LAUNCH_ATTRACT,
    LAUNCH_SELECT,
    LAUNCH_EDIT,
    LAUNCH_HOST,
    LAUNCH_JOIN,
    LAUNCH_LOAD,
    LAUNCH_LOADGAME,
    LAUNCH_NOLOGO,
    LAUNCH_NOMOVIES,
    LAUNCH_LOBBYLAUNCH,
    LAUNCH_QUICKSTART,
    LAUNCH_MODE_COUNT
};

enum LaunchModeCode {
    LAUNCHCODE_DEFAULT = 2,
    LAUNCHCODE_PLAY = 3,
    LAUNCHCODE_DEMO = 7,
    LAUNCHCODE_SELECT = 16,
    LAUNCHCODE_MULTI = 17
};

enum Resolution {
    RES_640x480 = 1,
    RES_800x600 = 2,
    RES_1024x768 = 3
};

enum Commands {

    GOTOLEVEL = 0x807F,

    LOBBYLAUNCH = 0x80B7
};

struct GruntzVolumeAttenuation {

    enum {
        kSize = 101,
        kFloor = -10000,
        kFull = 0
    };
};
SIZE_UNKNOWN();

#endif // GRUNTZ_GRUNTZ_ENUMS_H
