#ifndef GRUNTZ_GRUNTZ_FADERCONFIGKIND_H
#define GRUNTZ_GRUNTZ_FADERCONFIGKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(FaderConfigKind)
    FADER_CONFIG_UNTAGGED = 0,
    FADER_CONFIG_SHAPE = 1,
    FADER_CONFIG_LIGHT = 2,
    FADER_CONFIG_SINE = 3,
    FADER_CONFIG_RADIAL = 4,
    FADER_CONFIG_FLAT = 5,
    FADER_CONFIG_MESH = 6
GZ_ENUM_END(FaderConfigKind)

#endif // GRUNTZ_GRUNTZ_FADERCONFIGKIND_H
