#ifndef GRUNTZ_GRUNTZ_FADERKIND_H
#define GRUNTZ_GRUNTZ_FADERKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(FaderKind)
    FADERKIND_SHAPE = 0,
    FADERKIND_LIGHT = 1,
    FADERKIND_SINE = 2,
    FADERKIND_RADIAL = 3,
    FADERKIND_FLAT = 4,
    FADERKIND_MESH = 5,
    FADERKIND_COUNT = 6
GZ_ENUM_END(FaderKind)

#endif // GRUNTZ_GRUNTZ_FADERKIND_H
