#ifndef GRUNTZ_GRUNTZ_GAMESTATEID_H
#define GRUNTZ_GRUNTZ_GAMESTATEID_H

#include <Enums.h>

GZ_ENUM_BEGIN(GameStateId)
    GAMESTATE_NONE = 0,
    GAMESTATE_BASE = 1,
    GAMESTATE_ATTRACT = 2,
    GAMESTATE_PLAY = 3,
    GAMESTATE_MENU = 5,
    GAMESTATE_CREDITS = 8,
    GAMESTATE_BOOTY = 0xa,
    GAMESTATE_CREDITS_OVER_CURRENT = 0xb,
    GAMESTATE_BOOTY_OVER_CURRENT = 0xd,
    GAMESTATE_DEMO = 7,
    GAMESTATE_HELP = 9,
    GAMESTATE_SPLASH = 0xe,
    GAMESTATE_RESERVED_0F = 0xf,
    GAMESTATE_LEVEL_SELECT = 0x10,
    GAMESTATE_MULTI = 0x11,
    GAMESTATE_MULTIBOOTY = 0x12
GZ_ENUM_END(GameStateId)

#endif // GRUNTZ_GRUNTZ_GAMESTATEID_H
