#ifndef GRUNTZ_GRUNTZ_GAMESTATEID_H
#define GRUNTZ_GRUNTZ_GAMESTATEID_H

enum GameStateId {
    GAMESTATE_BASE = 1,
    GAMESTATE_ATTRACT = 2,
    GAMESTATE_PLAY = 3,
    GAMESTATE_MENU = 5,
    GAMESTATE_CREDITS = 8,
    GAMESTATE_BOOTY = 0xa,
    GAMESTATE_DEMO = 7,
    GAMESTATE_HELP = 9,
    GAMESTATE_SPLASH = 0xe,
    GAMESTATE_NONE = 0x11,
    GAMESTATE_MULTIBOOTY = 0x12
};

#endif // GRUNTZ_GRUNTZ_GAMESTATEID_H
