#ifndef GRUNTZ_GRUNTZ_GAMEICONFLASHSTATE_H
#define GRUNTZ_GRUNTZ_GAMEICONFLASHSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(GameIconFlashState)
    GAME_ICON_FLASH_IDLE = 0,
    GAME_ICON_FLASH_ACTIVE = 5
GZ_ENUM_END(GameIconFlashState)

#endif // GRUNTZ_GRUNTZ_GAMEICONFLASHSTATE_H
