#ifndef GRUNTZ_GRUNTZ_GAMEMODEID_H
#define GRUNTZ_GRUNTZ_GAMEMODEID_H

#include <Enums.h>

GZ_ENUM_BEGIN(GameModeId)
    GAMEMODE_NONE = 0,
    GAMEMODE_QUESTZ = 1,
    GAMEMODE_MULTIPLAYER = 2,
    GAMEMODE_BATTLEZ = 3
GZ_ENUM_END(GameModeId)

#endif // GRUNTZ_GRUNTZ_GAMEMODEID_H
