#ifndef GRUNTZ_GRUNTZ_GRUNTZMGRMACROS_H
#define GRUNTZ_GRUNTZ_GRUNTZMGRMACROS_H

#define IS_STANDARD_VIDEO_MODE (m_modeSize.cx == SCREEN_W_PX && m_modeSize.cy == SCREEN_H_PX)

#endif // GRUNTZ_GRUNTZ_GRUNTZMGRMACROS_H
