#ifndef GRUNTZ_GRUNTZ_GRUNTDEATHTYPE_H
#define GRUNTZ_GRUNTZ_GRUNTDEATHTYPE_H

#include <Enums.h>

GZ_ENUM_BEGIN(GruntDeathType)
    DEATH_NONE = -1,
    DEATH_DROP = 0,
    DEATH_NORMAL = 1,
    DEATH_SQUASH = 2,
    DEATH_HOLE = 3,
    DEATH_SINK = 4,
    DEATH_MELT = 5,
    DEATH_SHATTER = 6,
    DEATH_BURN = 7,
    DEATH_FALL = 8,
    DEATH_ELECTROCUTE = 9,
    DEATH_KAROKE = 10,
    DEATH_EXPLODE = 11,
    DEATH_DRAIN = 12,
    DEATH_EXIT = 13,
    DEATH_FALL2 = 14,
    DEATH_QUICKFALL = 15,

    GRUNT_DEATH_WARPOUT = DEATH_DRAIN
GZ_ENUM_END(GruntDeathType)

#endif // GRUNTZ_GRUNTZ_GRUNTDEATHTYPE_H
