#ifndef GRUNTZ_GRUNTZ_GRUNTENTRANCEMODE_H
#define GRUNTZ_GRUNTZ_GRUNTENTRANCEMODE_H

#include <Enums.h>

GZ_ENUM_BEGIN(GruntEntranceMode)
    GRUNT_ENTRANCE_NONE = 0,
    GRUNT_ENTRANCE_RESURRECT_DIRECT = 0,
    GRUNT_ENTRANCE_WORMHOLE = 1,
    GRUNT_ENTRANCE_DROP = 2,
    GRUNT_ENTRANCE_RESURRECT = 3
GZ_ENUM_END(GruntEntranceMode)

#endif // GRUNTZ_GRUNTZ_GRUNTENTRANCEMODE_H
