#ifndef GRUNTZ_GRUNTAISTATE_H
#define GRUNTZ_GRUNTAISTATE_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(GruntDwellMs)
    DWELL_REPATH_MS = 0x1f4,
    DWELL_SEEK_PATH_MS = 0x3e8,
    DWELL_STUCK_RESET_MS = 0xbb8,
    DWELL_COOLDOWN_MS = 0x1f40
GZ_ENUM_CONST_END(GruntDwellMs)

GZ_ENUM_BEGIN(GruntAiState)
    AISTATE_SEEK = 0,
    AISTATE_CHASE = 1,
    AISTATE_ATTACK = 2,
    AISTATE_RETURN = 3,
    AISTATE_COOLDOWN = 4,
    AISTATE_RETREAT = 5,
    AISTATE_BATTLEZ_ROUTE_TARGET = 6,
    AISTATE_BATTLEZ_FINAL_ROUTE = 7,
    AISTATE_PHASE_MIRROR_THEN_COOLDOWN = 0x19,
    AISTATE_PHASE_MIRROR_THEN_SEEK = 0x1a
GZ_ENUM_END(GruntAiState)

#endif // GRUNTZ_GRUNTAISTATE_H
