#ifndef GRUNTZ_GRUNTZ_GRUNTCOMBATDIRECTION_H
#define GRUNTZ_GRUNTZ_GRUNTCOMBATDIRECTION_H

#include <Enums.h>

GZ_ENUM_BEGIN(WingzKnockbackChoice)
    WINGZ_KNOCKBACK_NORTHEAST = 0,
    WINGZ_KNOCKBACK_EAST = 1,
    WINGZ_KNOCKBACK_SOUTHEAST = 2,
    WINGZ_KNOCKBACK_SOUTH = 3,
    WINGZ_KNOCKBACK_SOUTHWEST = 4,
    WINGZ_KNOCKBACK_WEST = 5,
    WINGZ_KNOCKBACK_NORTHWEST = 6
GZ_ENUM_END(WingzKnockbackChoice)

#endif // GRUNTZ_GRUNTZ_GRUNTCOMBATDIRECTION_H
