#ifndef GRUNTZ_GRUNTZ_GRUNTAREAEFFECTKIND_H
#define GRUNTZ_GRUNTZ_GRUNTAREAEFFECTKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(GruntAreaEffectKind)
    GRUNT_AREA_EFFECT_DROP = 1,
    GRUNT_AREA_EFFECT_TELEPORT = 2,
    GRUNT_AREA_EFFECT_HEAL = 3,
    GRUNT_AREA_EFFECT_FREEZE = 4,
    GRUNT_AREA_EFFECT_GIVE_TOY = 5,
    GRUNT_AREA_EFFECT_EXPLODE = 6,
    GRUNT_AREA_EFFECT_SQUASH = 7
GZ_ENUM_END(GruntAreaEffectKind)

#endif // GRUNTZ_GRUNTZ_GRUNTAREAEFFECTKIND_H
