#ifndef GRUNTZ_GRUNTZ_HEALTHPCT_H
#define GRUNTZ_GRUNTZ_HEALTHPCT_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(HealthPct)
    HEALTH_EMPTY = 0,
    HEALTH_RESPAWN = 25,
    HEALTH_FULL = 100
GZ_ENUM_CONST_END(HealthPct)

#endif // GRUNTZ_GRUNTZ_HEALTHPCT_H
