#ifndef GRUNTZ_GRUNTZ_INPUTDEVICESEL_H
#define GRUNTZ_GRUNTZ_INPUTDEVICESEL_H

#include <Enums.h>

GZ_ENUM_BEGIN(InputDeviceSel)
    INPUTDEV_NONE = 0,
    INPUTDEV_KEYBOARD = 1,
    INPUTDEV_JOYSTICK1 = 2,
    INPUTDEV_JOYSTICK2 = 3,
    INPUTDEV_JOYSTICK3 = 4,
    INPUTDEV_JOYSTICK4 = 5,
    INPUTDEV_SELECTABLE_END = 6,
    INPUTDEV_KEYBOARD_JOYSTICK1 = 6,
    INPUTDEV_KEYBOARD_MOUSE = 7,
    INPUTDEV_KEYBOARD_JOYSTICK1_MOUSE = 8
GZ_ENUM_END(InputDeviceSel)

#endif // GRUNTZ_GRUNTZ_INPUTDEVICESEL_H
