#ifndef GRUNTZ_GRUNTZ_LEVELAREA_H
#define GRUNTZ_GRUNTZ_LEVELAREA_H

#include <Enums.h>

GZ_ENUM_BEGIN(LevelArea)
    AREA_ROCKY_ROADZ = 1,
    AREA_GRUNTZICLEZ = 2,
    AREA_TROUBLE_IN_THE_TROPICZ = 3,
    AREA_HIGH_ON_SWEETZ = 4,
    AREA_HIGH_ROLLERZ = 5,
    AREA_HONEY_I_SHRUNK_THE_GRUNTZ = 6,
    AREA_MINIATURE_MASTERZ = 7,
    AREA_GRUNTZ_IN_SPACE = 8,
    AREA_LAST = AREA_GRUNTZ_IN_SPACE,
    AREA_COUNT = 8,
    AREA_TILESET_A_LAST = AREA_HIGH_ON_SWEETZ,
    AREA_TILESET_B_FIRST = AREA_HIGH_ROLLERZ
GZ_ENUM_END(LevelArea)

#endif // GRUNTZ_GRUNTZ_LEVELAREA_H
