#ifndef GRUNTZ_GRUNTZ_MAPCELLFLAGS_H
#define GRUNTZ_GRUNTZ_MAPCELLFLAGS_H

#include <Enums.h>

GZ_ENUM_FLAGS_BEGIN(MapCellFlags, u32)
    CELL_FLAG_SPECIAL = 0x2,
    CELL_FLAG_REVEALED_POWERUP = 0x40,
    CELL_FLAG_GAUNTLET_BRICK = 0x4000,
    CELL_FLAG_HIDDEN_POWERUP = 0x8000,
    CELL_FLAG_COVERED_POWERUP = 0x10000,
    CELL_FLAG_CLAIM_VISITED = 0x20000
GZ_ENUM_FLAGS_END(MapCellFlags, u32)
GZ_ENUM_FLAGS_OPS(MapCellFlags)

#endif // GRUNTZ_GRUNTZ_MAPCELLFLAGS_H
