#ifndef GRUNTZ_GRUNTZ_MENUITEMSTATE_H
#define GRUNTZ_GRUNTZ_MENUITEMSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(MenuItemState)
    MENUSTATE_NORMAL = 1,
    MENUSTATE_SELECTED = 2,
    MENUSTATE_DISABLED = 3
GZ_ENUM_END(MenuItemState)

#endif // GRUNTZ_GRUNTZ_MENUITEMSTATE_H
