#ifndef GRUNTZ_GRUNTZ_MOVIEENTRYID_H
#define GRUNTZ_GRUNTZ_MOVIEENTRYID_H

#include <Enums.h>

GZ_ENUM_BEGIN(MovieEntryId)
    MOVIE_ENTRY_LOGO = 1,
    MOVIE_ENTRY_INTRO = 2,
    MOVIE_ENTRY_ENDING = 3,
    MOVIE_ENTRY_FIRST = MOVIE_ENTRY_LOGO,
    MOVIE_ENTRY_LAST = MOVIE_ENTRY_ENDING
GZ_ENUM_END(MovieEntryId)

#endif // GRUNTZ_GRUNTZ_MOVIEENTRYID_H
