#ifndef GRUNTZ_GRUNTZ_MULTISTARTDLGCTRLID_H
#define GRUNTZ_GRUNTZ_MULTISTARTDLGCTRLID_H

#include <Enums.h>

GZ_ENUM_BEGIN(MultiStartDlgCtrlId)
    IDC_MULTI_CUSTOM_WORLD = 0x42b,
    IDC_MULTI_CHAT_INPUT = 0x42d,
    IDC_MULTI_ECHO_LATENCY = 0x4e9,
    IDC_MULTI_WORLD = 0x4ff,
    IDC_MULTI_CHAT_LOG = 0x511,
    IDC_MULTI_GAME_NAME = 0x512,
    IDC_MULTI_LATENCY = 0x527
GZ_ENUM_END(MultiStartDlgCtrlId)

#endif
