#ifndef GRUNTZ_GRUNTZ_PATHBUFFER_H
#define GRUNTZ_GRUNTZ_PATHBUFFER_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(GruntzPathBuffer)
    GRUNTZ_PATH_BUFFER_SIZE = 0x100,
    GRUNTZ_PATH_BUFFER_MAX_CHARS = GRUNTZ_PATH_BUFFER_SIZE - 1
GZ_ENUM_CONST_END(GruntzPathBuffer)

#endif // GRUNTZ_GRUNTZ_PATHBUFFER_H
