#ifndef GRUNTZ_GRUNTZ_PICKUPTYPE_H
#define GRUNTZ_GRUNTZ_PICKUPTYPE_H

enum PickupType {
    PICKUP_NONE = 0,

    PICKUP_BOMB = 1,
    PICKUP_BOOMERANG = 2,
    PICKUP_BRICK = 3,
    PICKUP_CLUB = 4,
    PICKUP_GAUNTLETZ = 5,
    PICKUP_GLOVEZ = 6,
    PICKUP_GOOBER = 7,
    PICKUP_GRAVITYBOOTZ = 8,
    PICKUP_GUNHAT = 9,
    PICKUP_NERFGUN = 10,
    PICKUP_ROCK = 11,
    PICKUP_SHIELD = 12,
    PICKUP_SHOVEL = 13,
    PICKUP_SPRING = 14,
    PICKUP_SPY = 15,
    PICKUP_SWORD = 16,
    PICKUP_TIMEBOMB = 17,
    PICKUP_TOOB = 18,
    PICKUP_WAND = 19,
    PICKUP_WARPSTONE = 20,
    PICKUP_WELDER = 21,
    PICKUP_WINGZ = 22,

    PICKUP_BABYWALKER = 23,
    PICKUP_BEACHBALL = 24,
    PICKUP_BIGWHEEL = 25,
    PICKUP_GOKART = 26,
    PICKUP_JACKINTHEBOX = 27,
    PICKUP_JUMPROPE = 28,
    PICKUP_POGOSTICK = 29,
    PICKUP_SCROLL = 30,
    PICKUP_SQUEAKTOY = 31,
    PICKUP_YOYO = 32,

    PICKUP_REDBRICK = 0x23,
    PICKUP_BLUEBRICK = 0x24,
    PICKUP_GOLDBRICK = 0x25,
    PICKUP_BLACKBRICK = 0x26,

    PICKUP_MEGAPHONE = 0x32,

    PICKUP_HEALTH1 = 0x33,
    PICKUP_HEALTH2 = 0x34,
    PICKUP_HEALTH3 = 0x35,

    PICKUP_GHOST = 0x36,
    PICKUP_SUPERSPEED = 0x37,
    PICKUP_INVULNERABILITY = 0x38,
    PICKUP_CONVERSION = 0x39,
    PICKUP_DEATHTOUCH = 0x3a,
    PICKUP_ROIDZ = 0x3b,
    PICKUP_REACTIVEARMOR = 0x3c,

    PICKUP_RANDOMCOLORZ = 0x3d,
    PICKUP_SCREENSHAKE = 0x3e,
    PICKUP_BLACKSCREEN = 0x3f,
    PICKUP_MINICAM = 0x40,
    PICKUP_STOPWATCH = 0x4b,
    PICKUP_COIN = 0x50,

    PICKUP_W = 0x5a,
    PICKUP_A = 0x5b,
    PICKUP_R = 0x5c,
    PICKUP_P = 0x5d,
    PICKUP_HELPBOX = 0x5e,

    PICKUP_COVEREDTIMEBOMB = 0x63,
};

#endif // GRUNTZ_GRUNTZ_PICKUPTYPE_H
