#ifndef GRUNTZ_GRUNTZ_PLAYINTERVALMS_H
#define GRUNTZ_GRUNTZ_PLAYINTERVALMS_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(PlayIntervalMs)
    CUE_INTERVAL_MS = 0x1f4,
    BOOTY_INTERVAL_MS = 0x2710,
    REGION_INTERVAL_MS = 0x7530,
    FIXED_SUBSTEP_MS = 0x12,
    AMBIENT_INTRO_INTERVAL_MS = 0x1f40
GZ_ENUM_CONST_END(PlayIntervalMs)

#endif // GRUNTZ_GRUNTZ_PLAYINTERVALMS_H
