#ifndef GRUNTZ_GRUNTZ_PLAYHUDLAYOUTPX_H
#define GRUNTZ_GRUNTZ_PLAYHUDLAYOUTPX_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(PlayHudLayoutPx)
    STATUSBAR_WIDTH_PX = 0xa0,
    TIMER_ORIGIN_X_PX = 0x249,
    TIMER_ORIGIN_X_STATUSBAR_RIGHT_PX = TIMER_ORIGIN_X_PX - STATUSBAR_WIDTH_PX,
    TIMER_ORIGIN_Y_PX = 0x1ca
GZ_ENUM_CONST_END(PlayHudLayoutPx)

#endif // GRUNTZ_GRUNTZ_PLAYHUDLAYOUTPX_H
