#ifndef GRUNTZ_GRUNTZ_PLAYERCOMMANDKIND_H
#define GRUNTZ_GRUNTZ_PLAYERCOMMANDKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(PlayerCommandKind)
    PLAYERCMD_PLACE_GRUNT = 0,
    PLAYERCMD_MOVE = 2,
    PLAYERCMD_USE_TOOL_AT_POINT = 3,
    PLAYERCMD_USE_TOY_AT_POINT = 4,
    PLAYERCMD_STOP = 5,
    PLAYERCMD_GUARD_BEGIN = 6,
    PLAYERCMD_GUARD_END = 7,
    PLAYERCMD_GIVE_TOOL = 8,
    PLAYERCMD_USE_TOOL_ON_GRUNT = 9,
    PLAYERCMD_USE_TOY_ON_GRUNT = 10
GZ_ENUM_END(PlayerCommandKind)

#endif // GRUNTZ_GRUNTZ_PLAYERCOMMANDKIND_H
