#ifndef GRUNTZ_GRUNTZ_PLAYVIEWMODE_H
#define GRUNTZ_GRUNTZ_PLAYVIEWMODE_H

#include <Enums.h>

GZ_ENUM_BEGIN(PlayViewMode)
    VIEW_MODE_IDLE = 0,
    VIEW_MODE_A = 1,
    VIEW_MODE_B = 2
GZ_ENUM_END(PlayViewMode)

#endif // GRUNTZ_GRUNTZ_PLAYVIEWMODE_H
