#ifndef GRUNTZ_GRUNTZ_SBICOMMANDID_H
#define GRUNTZ_GRUNTZ_SBICOMMANDID_H

#include <Enums.h>

GZ_ENUM_BEGIN(SbiCommandId)
    SBICMD_NONE = 0,
    SBICMD_TAB_STATZ = 1,
    SBICMD_TAB_FIRST = SBICMD_TAB_STATZ,
    SBICMD_TAB_GRUNTZ = 2,
    SBICMD_TAB_RESOURCE = 3,
    SBICMD_TAB_MULTIPLAYER = 4,
    SBICMD_TAB_GAME = 5,
    SBICMD_TAB_LAST = SBICMD_TAB_GAME,

    SBICMD_SIDE_TAB_FIRST = 0xb,
    SBICMD_SIDE_TAB_LAST = 0x19,

    SBICMD_GRUNT_SLOT_FIRST = 0x64,
    SBICMD_GRUNT_SLOT_LAST = 0x68,
    SBICMD_GRUNT_WELL = 0x69,
    SBICMD_GRUNT_WELL_GOO = 0x6a,
    SBICMD_GRUNT_OVENS_TEXT = 0x6b,
    SBICMD_GRUNT_WELL_TEXT = 0x6c,

    SBICMD_RESOURCE_MAIN_BACKGROUND = 0xc8,
    SBICMD_RESOURCE_UPPER_BACKGROUND = 0xc9,
    SBICMD_RESOURCE_WINDOW_BACKGROUND = 0xca,
    SBICMD_RESOURCE_BELT_TOOLS = 0xcb,
    SBICMD_RESOURCE_BELT_TOYS = 0xcc,
    SBICMD_RESOURCE_BELT_BRICKS = 0xcd,

    SBICMD_CONVEYOR_TOP = 0xce,
    SBICMD_CONVEYOR_BOTTOM = 0xd0,
    SBICMD_RESOURCE_MACHINE_BACKGROUND = 0xd1,
    SBICMD_RESOURCE_MACHINE_FOREGROUND = 0xd2,
    SBICMD_RESOURCE_CURRENT_ITEM = 0xdf,
    SBICMD_RESOURCE_FALLING_ITEM = 0xe0,

    SBICMD_MULTIPLAYER_HEAD1 = 0x190,
    SBICMD_MULTIPLAYER_HEAD_FIRST = SBICMD_MULTIPLAYER_HEAD1,
    SBICMD_MULTIPLAYER_HEAD2 = 0x191,
    SBICMD_MULTIPLAYER_HEAD3 = 0x192,
    SBICMD_MULTIPLAYER_HEAD4 = 0x193,
    SBICMD_MULTIPLAYER_HEAD_LAST = SBICMD_MULTIPLAYER_HEAD4,

    SBICMD_PAUSE = 0x1f4,
    SBICMD_LOAD_GAME = 0x1f5,
    SBICMD_SAVE_GAME = 0x1f6,
    SBICMD_SETTINGS = 0x1f7,
    SBICMD_BOOTY_STATE = 0x1f8,
    SBICMD_QUIT = 0x1f9,
    SBICMD_GAME_TAB = 0x1fa,
    SBICMD_MISSION_STATUS = 0x1fb,
    SBICMD_DESTRUCT = 0x1fc,

    SBICMD_DOCK_LEFT = 0x259,
    SBICMD_DOCK_FIRST = SBICMD_DOCK_LEFT,
    SBICMD_DOCK_RIGHT = 0x25a,
    SBICMD_HIDE = 0x25b,
    SBICMD_TAB_TITLE_TEXT = 0x25c,

    SBICMD_WARPSTONE_BASE = 0x2bc,
    SBICMD_WARPSTONE_FRAGMENT1 = 0x2bd,
    SBICMD_WARPSTONE_FRAGMENT2 = 0x2be,
    SBICMD_WARPSTONE_FRAGMENT3 = 0x2bf,
    SBICMD_WARPSTONE_FRAGMENT4 = 0x2c0,

    SBICMD_DIALOG_FRAME = 0x321,
    SBICMD_DIALOG_MISSION_STATUS = 0x322,
    SBICMD_DIALOG_PRIMARY = 0x324,
    SBICMD_DIALOG_SECONDARY = 0x325,
    SBICMD_DIALOG_REASON = 0x326,
    SBICMD_DIALOG_YES = 0x327,
    SBICMD_DIALOG_NO = 0x328,

    SBICMD_STAT_TOGGLE_FIRST = 0x12c,
    SBICMD_STAT_TOGGLE_LAST = 0x13a,
    SBICMD_CURSOR_TARGET_FIRST = 0x13b,
    SBICMD_CURSOR_TARGET_LAST = 0x149,

    SBICMD_TOOL_RESOURCE_CATEGORY = 0xd3,
    SBICMD_TOOL_RESOURCE_FIRST = SBICMD_TOOL_RESOURCE_CATEGORY,
    SBICMD_TOOL_RESOURCE_UPPER = 0xd4,
    SBICMD_TOOL_RESOURCE_MIDDLE = 0xd5,
    SBICMD_TOOL_RESOURCE_LOWER = 0xd6,
    SBICMD_TOOL_RESOURCE_LAST = SBICMD_TOOL_RESOURCE_LOWER,
    SBICMD_TOY_RESOURCE_CATEGORY = 0xd7,
    SBICMD_TOY_RESOURCE_FIRST = SBICMD_TOY_RESOURCE_CATEGORY,
    SBICMD_TOY_RESOURCE_UPPER = 0xd8,
    SBICMD_TOY_RESOURCE_MIDDLE = 0xd9,
    SBICMD_TOY_RESOURCE_LOWER = 0xda,
    SBICMD_TOY_RESOURCE_LAST = SBICMD_TOY_RESOURCE_LOWER,
    SBICMD_BRICK_RESOURCE_CATEGORY = 0xdb,
    SBICMD_BRICK_RESOURCE_FIRST = SBICMD_BRICK_RESOURCE_CATEGORY,
    SBICMD_BRICK_RESOURCE_UPPER = 0xdc,
    SBICMD_BRICK_RESOURCE_MIDDLE = 0xdd,
    SBICMD_BRICK_RESOURCE_LOWER = 0xde,
    SBICMD_BRICK_RESOURCE_LAST = SBICMD_BRICK_RESOURCE_LOWER
GZ_ENUM_END(SbiCommandId)

GZ_ENUM_STEPPED(SbiCommandId)

#endif // GRUNTZ_GRUNTZ_SBICOMMANDID_H
