#ifndef GRUNTZ_GRUNTZ_SBIFALLINGITEMSTATE_H
#define GRUNTZ_GRUNTZ_SBIFALLINGITEMSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(SbiFallingItemState)
    FALLING_ITEM_INACTIVE = 0,
    FALLING_ITEM_DESCENDING = 1,
    FALLING_ITEM_GRINDING = 2
GZ_ENUM_END(SbiFallingItemState)

#endif // GRUNTZ_GRUNTZ_SBIFALLINGITEMSTATE_H
