#ifndef GRUNTZ_GRUNTZ_SBIHLROWSTATE_H
#define GRUNTZ_GRUNTZ_SBIHLROWSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(SbiHlRowState)
    HLROW_OFF = 0,
    HLROW_IDLE_CYCLE = 1,
    HLROW_RAMP_UP_LOW = 2,
    HLROW_RAMP_DOWN_LOW = 3,
    HLROW_RAMP_UP_HIGH = 4,
    HLROW_RAMP_DOWN_HIGH = 5,
    HLROW_HOLD_HIGH = 6,
    HLROW_HOLD_LOW = 7
GZ_ENUM_END(SbiHlRowState)

#endif // GRUNTZ_GRUNTZ_SBIHLROWSTATE_H
