#ifndef GRUNTZ_GRUNTZ_SBIMENUITEMSTATE_H
#define GRUNTZ_GRUNTZ_SBIMENUITEMSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(SbiMenuItemState)
    MENUITEM_UNSET = 0,
    MENUITEM_NORMAL = 1,
    MENUITEM_HIGHLIGHT = 2,
    MENUITEM_SELECTED = 3,
    MENUITEM_DISABLED = 4
GZ_ENUM_END(SbiMenuItemState)

#endif // GRUNTZ_GRUNTZ_SBIMENUITEMSTATE_H
