#ifndef GRUNTZ_GRUNTZ_SBIMACHINESTATE_H
#define GRUNTZ_GRUNTZ_SBIMACHINESTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(SbiMachineState)
    MACHINE_STOPPED = 0,
    MACHINE_SNOOZING = 1,
    MACHINE_WAKING = 2,
    MACHINE_TURNING_WHEEL = 3,
    MACHINE_LEVER = 4,
    MACHINE_RIGHT_RUNNING = 5,
    MACHINE_RIGHT_SPEWING = 6
GZ_ENUM_END(SbiMachineState)

GZ_ENUM_CONST_BEGIN(SbiMachineFrame)
    MACHINE_LEVER_RELEASE_FRAME = 0x26
GZ_ENUM_CONST_END(SbiMachineFrame)

#endif // GRUNTZ_GRUNTZ_SBIMACHINESTATE_H
