#ifndef GRUNTZ_GRUNTZ_SCROLLEDGEFLAGS_H
#define GRUNTZ_GRUNTZ_SCROLLEDGEFLAGS_H

#include <Enums.h>

GZ_ENUM_FLAGS_BEGIN(ScrollEdgeFlags, i32)
    SCROLL_EDGE_LEFT = 0x1,
    SCROLL_EDGE_UP = 0x2,
    SCROLL_EDGE_RIGHT = 0x4,
    SCROLL_EDGE_DOWN = 0x8
GZ_ENUM_FLAGS_END(ScrollEdgeFlags, i32)
GZ_ENUM_FLAGS_OPS(ScrollEdgeFlags)

#endif // GRUNTZ_GRUNTZ_SCROLLEDGEFLAGS_H
