#ifndef GRUNTZ_GRUNTZ_SPELLID_H
#define GRUNTZ_GRUNTZ_SPELLID_H

#include <Enums.h>

GZ_ENUM_BEGIN(SpellId)
    SPELL_RANDOM = 0,
    SPELL_FREEZE = 1,
    SPELL_HEALTH = 2,
    SPELL_RESURRECTION = 3,
    SPELL_RANDOM_TOYZ = 4,
    SPELL_TELEPORT = 5,
    SPELL_ROLLING_BALLZ = 6,
    SPELL_CASTABLE_FIRST = SPELL_FREEZE,
    SPELL_CASTABLE_LAST = SPELL_ROLLING_BALLZ
GZ_ENUM_END(SpellId)

#endif // GRUNTZ_GRUNTZ_SPELLID_H
