#ifndef GRUNTZ_GRUNTZ_SPELLZEFFECT_H
#define GRUNTZ_GRUNTZ_SPELLZEFFECT_H

#include <Enums.h>

GZ_ENUM_BEGIN(SpellzEffect)
    SPELLZ_RANDOM = 0,
    SPELLZ_FREEZE = 1,
    SPELLZ_HEALTH = 2,
    SPELLZ_RESURRECTION = 3,
    SPELLZ_TOYZ = 4,
    SPELLZ_TELEPORT = 5,
    SPELLZ_ROLLINGBALL = 6
GZ_ENUM_END(SpellzEffect)

#endif // GRUNTZ_GRUNTZ_SPELLZEFFECT_H
