#ifndef GRUNTZ_GRUNTZ_SPRITETEAMCOLORVARIANT_H
#define GRUNTZ_GRUNTZ_SPRITETEAMCOLORVARIANT_H

#include <Enums.h>

GZ_ENUM_BEGIN(SpriteTeamColorVariant)
    SPRITE_TEAM_COLOR_PRIMARY = 0,
    SPRITE_TEAM_COLOR_SECONDARY = 1,
    SPRITE_TEAM_COLOR_TERTIARY = 2
GZ_ENUM_END(SpriteTeamColorVariant)

#endif // GRUNTZ_GRUNTZ_SPRITETEAMCOLORVARIANT_H
