#ifndef GRUNTZ_GRUNTZ_SPRITESTATEFLAGS_H
#define GRUNTZ_GRUNTZ_SPRITESTATEFLAGS_H

#include <Enums.h>

GZ_ENUM_FLAGS_BEGIN(SpriteStateFlags, i32)
    SPRITE_STATE_NONE = 0,
    SPRITE_STATE_HIDDEN = 0x1,
    SPRITE_STATE_MIRROR_X = 0x2,
    SPRITE_STATE_MIRROR_Y = 0x4,
    SPRITE_STATE_FLASHING = 0x8,
    SPRITE_STATE_FLASH_VISIBLE = 0x10000000
GZ_ENUM_FLAGS_END(SpriteStateFlags, i32)

#endif // GRUNTZ_GRUNTZ_SPRITESTATEFLAGS_H
