#ifndef GRUNTZ_GRUNTZ_STATUSBARDOCK_H
#define GRUNTZ_GRUNTZ_STATUSBARDOCK_H

#include <Enums.h>

GZ_ENUM_BEGIN(StatusBarDock)
    STATUSBAR_DOCK_RIGHT = 0,
    STATUSBAR_DOCK_LEFT = 1,
    STATUSBAR_HIDDEN = 2,
    STATUSBAR_NONRIGHT_FIRST = STATUSBAR_DOCK_LEFT,
    STATUSBAR_NONRIGHT_LAST = STATUSBAR_HIDDEN,
    STATUSBAR_NONRIGHT_BEFORE_FIRST = STATUSBAR_DOCK_RIGHT
GZ_ENUM_END(StatusBarDock)

#endif // GRUNTZ_GRUNTZ_STATUSBARDOCK_H
