#ifndef GRUNTZ_STATUSBARHIGHLIGHTROW_H
#define GRUNTZ_STATUSBARHIGHLIGHTROW_H

#include <Enums.h>

GZ_ENUM_BEGIN(ResourceSlotRow)
    RESOURCE_ROW_NONE = -1,
    RESOURCE_ROW_TOP = 0,
    RESOURCE_ROW_UPPER_MIDDLE = 1,
    RESOURCE_ROW_LOWER_MIDDLE = 2,
    RESOURCE_ROW_BOTTOM = 3
GZ_ENUM_END(ResourceSlotRow)

#endif // GRUNTZ_STATUSBARHIGHLIGHTROW_H
