#ifndef GRUNTZ_GRUNTZ_STATUSSAMPLEMODE_H
#define GRUNTZ_GRUNTZ_STATUSSAMPLEMODE_H

#include <Enums.h>

GZ_ENUM_BEGIN(StatusSampleMode)
    STATUS_SAMPLE_UNINITIALIZED = -1,
    STATUS_SAMPLE_NONE = 0,
    STATUS_SAMPLE_HEALTH = 1,
    STATUS_SAMPLE_TOOL = 2,
    STATUS_SAMPLE_VEHICLE = 3
GZ_ENUM_END(StatusSampleMode)

#endif // GRUNTZ_GRUNTZ_STATUSSAMPLEMODE_H
