#ifndef GRUNTZ_GRUNTZ_CTELESPRITEFACTORY_H
#define GRUNTZ_GRUNTZ_CTELESPRITEFACTORY_H

#include <DDrawMgr/DDrawChildGroup.h>

typedef CDDrawChildGroup CTeleSpriteFactory;

#endif // GRUNTZ_GRUNTZ_CTELESPRITEFACTORY_H
