#ifndef GRUNTZ_GRUNTZ_TRIGGERGRIDDIMENSIONS_H
#define GRUNTZ_GRUNTZ_TRIGGERGRIDDIMENSIONS_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(TriggerGridDimensions)
    TM_UNITS_PER_PLAYER = 15
GZ_ENUM_CONST_END(TriggerGridDimensions)

#endif // GRUNTZ_GRUNTZ_TRIGGERGRIDDIMENSIONS_H
