#ifndef GRUNTZ_GRUNTZ_VIEWPORTRESIZEMODE_H
#define GRUNTZ_GRUNTZ_VIEWPORTRESIZEMODE_H

#include <Enums.h>

GZ_ENUM_BEGIN(ViewportResizeMode)
    VIEW_RESIZE_IDLE = 0,
    VIEW_RESIZE_SHRINK = 1,
    VIEW_RESIZE_EXPAND = 2
GZ_ENUM_END(ViewportResizeMode)

#endif // GRUNTZ_GRUNTZ_VIEWPORTRESIZEMODE_H
