#include <rva.h>

#include <Gruntz/GameObjectFactory.h>

#include <DDrawMgr/DDrawSurfaceMgr.h>
#include <DDrawMgr/DDrawWorkerCache.h>
#include <Gruntz/ObjTypeRegistrars.h>

RVA(0x0000a3b0, 0x6e2)
void RegisterGameObjectTypes(CDDrawSurfaceMgr* ctx) {
    ctx->m_workerCache->CreateWorker(CreateAniCycle, "AniCycle", 2);
    CAniCycle::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateDoNothingNormal, "DoNothingNormal", 0);
    ctx->m_workerCache->CreateWorker(CreateDoNothing, "DoNothing", 2);
    ctx->m_workerCache->CreateWorker(CreateSimpleAnimation, "SimpleAnimation", 2);
    RegisterSimpleAnimLogic();
    ctx->m_workerCache->CreateWorker(CreateMenuSparkle, "MenuSparkle", 2);
    RegisterMenuSparkleActions();
    ctx->m_workerCache->CreateWorker(CreateFrontCandy, "FrontCandy", 2);
    ctx->m_workerCache->CreateWorker(CreateBehindCandy, "BehindCandy", 2);
    ctx->m_workerCache->CreateWorker(CreateFrontCandyAni, "FrontCandyAni", 2);
    CFrontCandyAni::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateBehindCandyAni, "BehindCandyAni", 2);
    CBehindCandyAni::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateEyeCandy, "EyeCandy", 2);
    ctx->m_workerCache->CreateWorker(CreateEyeCandyAni, "EyeCandyAni", 2);
    CEyeCandyAni::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGrunt, "Grunt", 4);
    RegisterGruntActions();
    ctx->m_workerCache->CreateWorker(CreateGlobalAmbientSound, "GlobalAmbientSound", 4);
    ctx->m_workerCache->CreateWorker(CreateAmbientSound, "AmbientSound", 1);
    ctx->m_workerCache->CreateWorker(CreateAmbientPosSound, "AmbientPosSound", 0);
    ctx->m_workerCache->CreateWorker(CreateSpotAmbientSound, "SpotAmbientSound", 0);
    ctx->m_workerCache->CreateWorker(CreateActionArea, "ActionArea", 4);
    CProjActObj::RegisterType();
    ctx->m_workerCache->CreateWorker(CreateStatusBarSprite, "StatusBarSprite", 2);
    CStatusBarSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateParticlez, "Particlez", 4);
    CParticlez::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateExplosion, "Explosion", 4);
    RegisterExplosionActions();
    ctx->m_workerCache->CreateWorker(CreateGruntSelectedSprite, "GruntSelectedSprite", 2);
    CGruntSelectedSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntHealthSprite, "GruntHealthSprite", 2);
    CGruntHealthSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntStaminaSprite, "GruntStaminaSprite", 2);
    CGruntHealthSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntToySprite, "GruntToySprite", 2);
    CGruntToySprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntToyTimeSprite, "GruntToyTimeSprite", 2);
    CGruntHealthSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntWingzTimeSprite, "GruntWingzTimeSprite", 2);
    CGruntHealthSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntPowerupSprite, "GruntPowerupSprite", 2);
    CGruntPowerupSprite::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateToyPeek, "ToyPeek", 4);
    RegisterIconState();
    ctx->m_workerCache->CreateWorker(CreateTileTriggerSwitch, "TileTriggerSwitch", 4);
    CTileTriggerSwitch::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateTileTrigger, "TileTrigger", 4);
    CTileTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateTileSecretTrigger, "TileSecretTrigger", 4);
    CTileTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateBrickz, "Brickz", 4);
    CBrickz::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateTileTriggerTransition, "TileTriggerTransition", 4);
    CTileTriggerTransition::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGruntStartingPoint, "GruntStartingPoint", 4);
    ActReg4RegisterType();
    ctx->m_workerCache->CreateWorker(CreateGruntCreationPoint, "GruntCreationPoint", 4);
    CGruntCreationPoint::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateFortressFlag, "FortressFlag", 4);
    CFortressFlag::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateExitTrigger, "ExitTrigger", 4);
    CExitTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGiantRock, "GiantRock", 4);
    CTileTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateCoveredPowerup, "CoveredPowerup", 4);
    CTileTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateInGameIcon, "InGameIcon", 4);
    RegisterIconActions();
    ctx->m_workerCache->CreateWorker(CreateInGameText, "InGameText", 4);
    RegisterTextLogic();
    ctx->m_workerCache->CreateWorker(CreateWormhole, "Wormhole", 4);
    RegisterWormholeLogic();
    ctx->m_workerCache->CreateWorker(CreateGruntPuddle, "GruntPuddle", 4);
    RegisterLogic();
    ctx->m_workerCache->CreateWorker(CreateRollingBall, "RollingBall", 4);
    CRollingBall::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateObjectDropper, "ObjectDropper", 4);
    CObjectDropper::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateDroppedObject, "DroppedObject", 4);
    CDroppedObject::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateDroppedObjectShadow, "DroppedObjectShadow", 4);
    CDroppedObjectShadow::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateCheckpointTrigger, "CheckpointTrigger", 4);
    CCheckpointTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateTeleporter, "Teleporter", 4);
    CTeleporter_RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateSecretTeleporterTrigger, "SecretTeleporterTrigger", 4);
    CSecretTeleporterTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateSecretLevelTrigger, "SecretLevelTrigger", 4);
    CSecretLevelTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateProjectile, "Projectile", 4);
    CProjectile::RegisterType();
    ctx->m_workerCache->CreateWorker(CreateBoomerang, "Boomerang", 4);
    CProjectile::RegisterType();
    ctx->m_workerCache->CreateWorker(CreateStaticHazard, "StaticHazard", 4);
    CStaticHazard::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateToobSpikez, "ToobSpikez", 4);
    CToobSpikez::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateTimeBomb, "TimeBomb", 4);
    CTimeBomb::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateSpotLight, "SpotLight", 4);
    RegisterSpotLightActions();
    ctx->m_workerCache->CreateWorker(CreateKitchenSlime, "KitchenSlime", 4);
    CKitchenSlime::RegisterType();
    ctx->m_workerCache->CreateWorker(CreateSingleAnimation, "SingleAnimation", 4);
    CSingleAnimation::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateWayPoint, "WayPoint", 4);
    ctx->m_workerCache->CreateWorker(CreateWarlord, "Warlord", 4);
    RegisterWarlordActions();
    ctx->m_workerCache->CreateWorker(CreatePathHazard, "PathHazard", 4);
    RegisterPathHazardActions();
    ctx->m_workerCache->CreateWorker(CreateRainCloud, "RainCloud", 4);
    RegisterPathHazardActions();
    ctx->m_workerCache->CreateWorker(CreateUFO, "UFO", 4);
    RegisterPathHazardActions();
    ctx->m_workerCache->CreateWorker(CreateGruntVoice, "GruntVoice", 4);
    RegisterGruntVoiceActions();
    ctx->m_workerCache->CreateWorker(CreateWarpStonePad, "WarpStonePad", 4);
    CWarpStonePad::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateGuardPoint, "GuardPoint", 4);
    ctx->m_workerCache->CreateWorker(CreateVoiceTrigger, "VoiceTrigger", 4);
    CVoiceTrigger::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateLevelTime, "LevelTime", 4);
    ctx->m_workerCache->CreateWorker(CreateCursorSnapSprite, "CursorSnapSprite", 1);
    RegisterCursorSnapActions();
    ctx->m_workerCache->CreateWorker(CreateLightFx, "LightFx", 4);
    CLightFx::RegisterActs();
    ctx->m_workerCache->CreateWorker(CreateDemoMover, "DemoMover", 0);
    ctx->m_workerCache->CreateWorker(CreateDemoSign, "DemoSign", 0);
}
