// GameObjectFactory.cpp - RegisterGameObjectTypes (RVA 0x000a3b0).
//
// The level/object-type factory registrar: walks one uniform list registering
// each named game-object type with the type registry (ctx->m_14, virtual slot
// +0x24) under a class-id flag, and (for most types) calls a per-type follow-up
// registration helper. Frameless __cdecl. Only offsets + code bytes are
// load-bearing; every create-fn / follow-up helper is a reloc-masked external
// (an unnamed ILT jmp-thunk to the real ctor/helper).
#include <rva.h>

typedef void* (*ObjCreateFn)();

// The object-type registry reached through ctx->m_14. RegisterType is virtual
// slot 9 (+0x24): record one named type + its create-fn under a class-id flag.
struct GameObjTypeRegistry {
    virtual void v0();
    virtual void v1();
    virtual void v2();
    virtual void v3();
    virtual void v4();
    virtual void v5();
    virtual void v6();
    virtual void v7();
    virtual void v8();
    virtual void RegisterType(ObjCreateFn create, const char* name, i32 flags); // +0x24
};
struct GameObjFactoryCtx {
    char m_pad00[0x14];
    GameObjTypeRegistry* m_14; // +0x14
};

// Reloc-masked externals: per-type object create-fns (ILT thunks to the real
// ctors) and the per-type follow-up registration helpers (by ILT-thunk RVA).
extern "C" {
    void* CreateAniCycle();
    void* CreateDoNothingNormal();
    void* CreateDoNothing();
    void* CreateSimpleAnimation();
    void* CreateMenuSparkle();
    void* CreateFrontCandy();
    void* CreateBehindCandy();
    void* CreateFrontCandyAni();
    void* CreateBehindCandyAni();
    void* CreateEyeCandy();
    void* CreateEyeCandyAni();
    void* CreateGrunt();
    void* CreateGlobalAmbientSound();
    void* CreateAmbientSound();
    void* CreateAmbientPosSound();
    void* CreateSpotAmbientSound();
    void* CreateActionArea();
    void* CreateStatusBarSprite();
    void* CreateParticlez();
    void* CreateExplosion();
    void* CreateGruntSelectedSprite();
    void* CreateGruntHealthSprite();
    void* CreateGruntStaminaSprite();
    void* CreateGruntToySprite();
    void* CreateGruntToyTimeSprite();
    void* CreateGruntWingzTimeSprite();
    void* CreateGruntPowerupSprite();
    void* CreateToyPeek();
    void* CreateTileTriggerSwitch();
    void* CreateTileTrigger();
    void* CreateTileSecretTrigger();
    void* CreateBrickz();
    void* CreateTileTriggerTransition();
    void* CreateGruntStartingPoint();
    void* CreateGruntCreationPoint();
    void* CreateFortressFlag();
    void* CreateExitTrigger();
    void* CreateGiantRock();
    void* CreateCoveredPowerup();
    void* CreateInGameIcon();
    void* CreateInGameText();
    void* CreateWormhole();
    void* CreateGruntPuddle();
    void* CreateRollingBall();
    void* CreateObjectDropper();
    void* CreateDroppedObject();
    void* CreateDroppedObjectShadow();
    void* CreateCheckpointTrigger();
    void* CreateTeleporter();
    void* CreateSecretTeleporterTrigger();
    void* CreateSecretLevelTrigger();
    void* CreateProjectile();
    void* CreateBoomerang();
    void* CreateStaticHazard();
    void* CreateToobSpikez();
    void* CreateTimeBomb();
    void* CreateSpotLight();
    void* CreateKitchenSlime();
    void* CreateSingleAnimation();
    void* CreateWayPoint();
    void* CreateWarlord();
    void* CreatePathHazard();
    void* CreateRainCloud();
    void* CreateUFO();
    void* CreateGruntVoice();
    void* CreateWarpStonePad();
    void* CreateGuardPoint();
    void* CreateVoiceTrigger();
    void* CreateLevelTime();
    void* CreateCursorSnapSprite();
    void* CreateLightFx();
    void* CreateDemoMover();
    void* CreateDemoSign();
    void RegHelper_10a5();
    void RegHelper_10f0();
    void RegHelper_1113();
    void RegHelper_1140();
    void RegHelper_1181();
    void RegHelper_1244();
    void RegHelper_1370();
    void RegHelper_137f();
    void RegHelper_1389();
    void RegHelper_13f7();
    void RegHelper_1424();
    void RegHelper_146f();
    void RegHelper_150f();
    void RegHelper_157d();
    void RegHelper_1587();
    void RegHelper_1631();
    void RegHelper_16d6();
    void RegHelper_17e9();
    void RegHelper_18cf();
    void RegHelper_1afa();
    void RegHelper_1d4d();
    void RegHelper_1d66();
    void RegHelper_1e15();
    void RegHelper_1e65();
    void RegHelper_1eec();
    void RegHelper_1f7d();
    void RegHelper_1faa();
    void RegHelper_23bf();
    void RegHelper_2400();
    void RegHelper_272a();
    void RegHelper_2874();
    void RegHelper_2cd4();
    void RegHelper_2f63();
    void RegHelper_314d();
    void RegHelper_3189();
    void RegHelper_318e();
    void RegHelper_3274();
    void RegHelper_33b9();
    void RegHelper_33f5();
    void RegHelper_35a3();
    void RegHelper_380a();
    void RegHelper_394f();
    void RegHelper_3b3e();
    void RegHelper_3b89();
    void RegHelper_3e1d();
    void RegHelper_3f2b();
    void RegHelper_40b6();
    void RegHelper_4101();
    void RegHelper_41a6();
    void RegHelper_4241();
}

// @source: string-xref
RVA(0x0000a3b0, 0x6e2)
void RegisterGameObjectTypes(GameObjFactoryCtx* ctx) {
    ctx->m_14->RegisterType(CreateAniCycle, "AniCycle", 2);
    RegHelper_4101();
    ctx->m_14->RegisterType(CreateDoNothingNormal, "DoNothingNormal", 0);
    ctx->m_14->RegisterType(CreateDoNothing, "DoNothing", 2);
    ctx->m_14->RegisterType(CreateSimpleAnimation, "SimpleAnimation", 2);
    RegHelper_35a3();
    ctx->m_14->RegisterType(CreateMenuSparkle, "MenuSparkle", 2);
    RegHelper_1631();
    ctx->m_14->RegisterType(CreateFrontCandy, "FrontCandy", 2);
    ctx->m_14->RegisterType(CreateBehindCandy, "BehindCandy", 2);
    ctx->m_14->RegisterType(CreateFrontCandyAni, "FrontCandyAni", 2);
    RegHelper_1587();
    ctx->m_14->RegisterType(CreateBehindCandyAni, "BehindCandyAni", 2);
    RegHelper_1afa();
    ctx->m_14->RegisterType(CreateEyeCandy, "EyeCandy", 2);
    ctx->m_14->RegisterType(CreateEyeCandyAni, "EyeCandyAni", 2);
    RegHelper_3274();
    ctx->m_14->RegisterType(CreateGrunt, "Grunt", 4);
    RegHelper_16d6();
    ctx->m_14->RegisterType(CreateGlobalAmbientSound, "GlobalAmbientSound", 4);
    ctx->m_14->RegisterType(CreateAmbientSound, "AmbientSound", 1);
    ctx->m_14->RegisterType(CreateAmbientPosSound, "AmbientPosSound", 0);
    ctx->m_14->RegisterType(CreateSpotAmbientSound, "SpotAmbientSound", 0);
    ctx->m_14->RegisterType(CreateActionArea, "ActionArea", 4);
    RegHelper_1e65();
    ctx->m_14->RegisterType(CreateStatusBarSprite, "StatusBarSprite", 2);
    RegHelper_2874();
    ctx->m_14->RegisterType(CreateParticlez, "Particlez", 4);
    RegHelper_314d();
    ctx->m_14->RegisterType(CreateExplosion, "Explosion", 4);
    RegHelper_157d();
    ctx->m_14->RegisterType(CreateGruntSelectedSprite, "GruntSelectedSprite", 2);
    RegHelper_13f7();
    ctx->m_14->RegisterType(CreateGruntHealthSprite, "GruntHealthSprite", 2);
    RegHelper_4241();
    ctx->m_14->RegisterType(CreateGruntStaminaSprite, "GruntStaminaSprite", 2);
    RegHelper_4241();
    ctx->m_14->RegisterType(CreateGruntToySprite, "GruntToySprite", 2);
    RegHelper_33b9();
    ctx->m_14->RegisterType(CreateGruntToyTimeSprite, "GruntToyTimeSprite", 2);
    RegHelper_4241();
    ctx->m_14->RegisterType(CreateGruntWingzTimeSprite, "GruntWingzTimeSprite", 2);
    RegHelper_4241();
    ctx->m_14->RegisterType(CreateGruntPowerupSprite, "GruntPowerupSprite", 2);
    RegHelper_1113();
    ctx->m_14->RegisterType(CreateToyPeek, "ToyPeek", 4);
    RegHelper_1faa();
    ctx->m_14->RegisterType(CreateTileTriggerSwitch, "TileTriggerSwitch", 4);
    RegHelper_1181();
    ctx->m_14->RegisterType(CreateTileTrigger, "TileTrigger", 4);
    RegHelper_1140();
    ctx->m_14->RegisterType(CreateTileSecretTrigger, "TileSecretTrigger", 4);
    RegHelper_1140();
    ctx->m_14->RegisterType(CreateBrickz, "Brickz", 4);
    RegHelper_10f0();
    ctx->m_14->RegisterType(CreateTileTriggerTransition, "TileTriggerTransition", 4);
    RegHelper_272a();
    ctx->m_14->RegisterType(CreateGruntStartingPoint, "GruntStartingPoint", 4);
    RegHelper_1370();
    ctx->m_14->RegisterType(CreateGruntCreationPoint, "GruntCreationPoint", 4);
    RegHelper_40b6();
    ctx->m_14->RegisterType(CreateFortressFlag, "FortressFlag", 4);
    RegHelper_23bf();
    ctx->m_14->RegisterType(CreateExitTrigger, "ExitTrigger", 4);
    RegHelper_2cd4();
    ctx->m_14->RegisterType(CreateGiantRock, "GiantRock", 4);
    RegHelper_1140();
    ctx->m_14->RegisterType(CreateCoveredPowerup, "CoveredPowerup", 4);
    RegHelper_1140();
    ctx->m_14->RegisterType(CreateInGameIcon, "InGameIcon", 4);
    RegHelper_1eec();
    ctx->m_14->RegisterType(CreateInGameText, "InGameText", 4);
    RegHelper_18cf();
    ctx->m_14->RegisterType(CreateWormhole, "Wormhole", 4);
    RegHelper_1d66();
    ctx->m_14->RegisterType(CreateGruntPuddle, "GruntPuddle", 4);
    RegHelper_1424();
    ctx->m_14->RegisterType(CreateRollingBall, "RollingBall", 4);
    RegHelper_3b3e();
    ctx->m_14->RegisterType(CreateObjectDropper, "ObjectDropper", 4);
    RegHelper_3189();
    ctx->m_14->RegisterType(CreateDroppedObject, "DroppedObject", 4);
    RegHelper_1389();
    ctx->m_14->RegisterType(CreateDroppedObjectShadow, "DroppedObjectShadow", 4);
    RegHelper_41a6();
    ctx->m_14->RegisterType(CreateCheckpointTrigger, "CheckpointTrigger", 4);
    RegHelper_150f();
    ctx->m_14->RegisterType(CreateTeleporter, "Teleporter", 4);
    RegHelper_1f7d();
    ctx->m_14->RegisterType(CreateSecretTeleporterTrigger, "SecretTeleporterTrigger", 4);
    RegHelper_1e15();
    ctx->m_14->RegisterType(CreateSecretLevelTrigger, "SecretLevelTrigger", 4);
    RegHelper_394f();
    ctx->m_14->RegisterType(CreateProjectile, "Projectile", 4);
    RegHelper_1244();
    ctx->m_14->RegisterType(CreateBoomerang, "Boomerang", 4);
    RegHelper_1244();
    ctx->m_14->RegisterType(CreateStaticHazard, "StaticHazard", 4);
    RegHelper_3e1d();
    ctx->m_14->RegisterType(CreateToobSpikez, "ToobSpikez", 4);
    RegHelper_10a5();
    ctx->m_14->RegisterType(CreateTimeBomb, "TimeBomb", 4);
    RegHelper_146f();
    ctx->m_14->RegisterType(CreateSpotLight, "SpotLight", 4);
    RegHelper_318e();
    ctx->m_14->RegisterType(CreateKitchenSlime, "KitchenSlime", 4);
    RegHelper_2f63();
    ctx->m_14->RegisterType(CreateSingleAnimation, "SingleAnimation", 4);
    RegHelper_3b89();
    ctx->m_14->RegisterType(CreateWayPoint, "WayPoint", 4);
    ctx->m_14->RegisterType(CreateWarlord, "Warlord", 4);
    RegHelper_33f5();
    ctx->m_14->RegisterType(CreatePathHazard, "PathHazard", 4);
    RegHelper_1d4d();
    ctx->m_14->RegisterType(CreateRainCloud, "RainCloud", 4);
    RegHelper_1d4d();
    ctx->m_14->RegisterType(CreateUFO, "UFO", 4);
    RegHelper_1d4d();
    ctx->m_14->RegisterType(CreateGruntVoice, "GruntVoice", 4);
    RegHelper_3f2b();
    ctx->m_14->RegisterType(CreateWarpStonePad, "WarpStonePad", 4);
    RegHelper_137f();
    ctx->m_14->RegisterType(CreateGuardPoint, "GuardPoint", 4);
    ctx->m_14->RegisterType(CreateVoiceTrigger, "VoiceTrigger", 4);
    RegHelper_2400();
    ctx->m_14->RegisterType(CreateLevelTime, "LevelTime", 4);
    ctx->m_14->RegisterType(CreateCursorSnapSprite, "CursorSnapSprite", 1);
    RegHelper_380a();
    ctx->m_14->RegisterType(CreateLightFx, "LightFx", 4);
    RegHelper_17e9();
    ctx->m_14->RegisterType(CreateDemoMover, "DemoMover", 0);
    ctx->m_14->RegisterType(CreateDemoSign, "DemoSign", 0);
}

SIZE_UNKNOWN(GameObjFactoryCtx);
SIZE_UNKNOWN(GameObjTypeRegistry);
