#ifndef GRUNTZ_WWD_LOGICRECORDEVENT_H
#define GRUNTZ_WWD_LOGICRECORDEVENT_H

#include <Enums.h>

GZ_ENUM_BEGIN_SPLIT(LogicRecordEvent, u32)
    ACT_UNINITIALISED = 0,
    ACT_LIVE = 0x3e8,
    ACT_NONE = 0x3e9,
    ACT_HEALTH_DEPLETED = 0x1c,
    ACT_OBJECT_REMOVED = 0x1d,
    ACT_LEAVE_ACTIVE_REGION = 0x1e,
    ACT_PREPARE_SAVE = 0x50,
    ACT_AFTER_SAVE = 0x51,
    ACT_AFTER_LOAD = 0x52,
    ACT_AFTER_LOAD_REFERENCES = 0x53
GZ_ENUM_END_SPLIT(LogicRecordEvent, u32)

#endif // GRUNTZ_WWD_LOGICRECORDEVENT_H
