#ifndef GRUNTZ_WWD_WWDANIDRAWVALUE_H
#define GRUNTZ_WWD_WWDANIDRAWVALUE_H

#include <Enums.h>

GZ_ENUM_BEGIN(WwdAniDrawValue)
    WWDDRAW_NO_ANIMATION = -1,
    WWDDRAW_NONE = 0,
    WWDDRAW_ANIMATION_COMPLETE = 1,
    WWDDRAW_EFFECT_FRAME = 2,
    WWDDRAW_TOOL_APPLIES = 0x63
GZ_ENUM_END(WwdAniDrawValue)

#endif // GRUNTZ_WWD_WWDANIDRAWVALUE_H
