#ifndef GRUNTZ_WWD_WWDANIMSTEPMODE_H
#define GRUNTZ_WWD_WWDANIMSTEPMODE_H

#include <Enums.h>

GZ_ENUM_BEGIN(WwdAnimStepMode)
    WWDSTEP_HOLD = 0,
    WWDSTEP_NEXT = 1,
    WWDSTEP_PREV = 2,
    WWDSTEP_SET = 3,
    WWDSTEP_FIRST = 4,
    WWDSTEP_LAST = 5,
    WWDSTEP_FORWARD_BY = 6,
    WWDSTEP_BACK_BY = 7
GZ_ENUM_END(WwdAnimStepMode)

GZ_ENUM_BEGIN(WwdAnimPositionMode)
    WWDPOS_NONE = 0,
    WWDPOS_PLOT_OFFSET = 1,
    WWDPOS_MOVE_RELATIVE = 2,
    WWDPOS_MOVE_ABSOLUTE = 3
GZ_ENUM_END(WwdAnimPositionMode)

GZ_ENUM_BEGIN(WwdAnimLoopMode)
    WWDLOOP_NEXT = 0,
    WWDLOOP_AT_PARAM = 1,
    WWDLOOP_AT_FIRST = 2,
    WWDLOOP_AT_LAST = 3,
    WWDLOOP_AFTER_FIRST = 4,
    WWDLOOP_BEFORE_LAST = 5,
    WWDLOOP_RESTART_AT_SECOND = 7,
    WWDLOOP_RESET_ANIMATION = 8,
    WWDLOOP_FINISH = 9,
    WWDLOOP_INVALID = 0xffff
GZ_ENUM_END(WwdAnimLoopMode)

#endif // GRUNTZ_WWD_WWDANIMSTEPMODE_H
