#ifndef GRUNTZ_WWD_WWDANIDRAWVALUE_H
#define GRUNTZ_WWD_WWDANIDRAWVALUE_H

#include <Enums.h>

GZ_ENUM_BEGIN(AnimationEventCode)
    ANIM_EVENT_NO_ANIMATION = -1,
    ANIM_EVENT_NONE = 0,
    ANIM_EVENT_COMPLETE = 1,
    ANIM_EVENT_EFFECT_FRAME = 2,
    ANIM_EVENT_TOOL_APPLIES = 0x63
GZ_ENUM_END(AnimationEventCode)

#endif // GRUNTZ_WWD_WWDANIDRAWVALUE_H
