#ifndef GRUNTZ_WWD_WWDOBJECTTYPE_H
#define GRUNTZ_WWD_WWDOBJECTTYPE_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(WwdObjectType)
    WWD_OBJECT_TYPE_PLATFORM = 0x80,
    WWD_OBJECT_TYPE_GRUNT = 0x1000
GZ_ENUM_CONST_END(WwdObjectType)

#endif // GRUNTZ_WWD_WWDOBJECTTYPE_H
