#ifndef GRUNTZ_WWD_WWDOBJECTTYPE_H
#define GRUNTZ_WWD_WWDOBJECTTYPE_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(WwdObjectType)
    WWD_OBJECT_TYPE_PLATFORM = 0x80,
    WWD_OBJECT_TYPE_GRUNT = 0x1000,
    WWD_GRUNT_HIT_TYPE_FLAGS = 0x3d1,
    WWD_GRUNT_COLLISION_MASK = 0x103f,
    WWD_GRUNT_ATTACK_TYPE_MASK = 0x1
GZ_ENUM_CONST_END(WwdObjectType)

#endif // GRUNTZ_WWD_WWDOBJECTTYPE_H
