#ifndef GRUNTZ_WWD_WWDPLANEFLAGS_H
#define GRUNTZ_WWD_WWDPLANEFLAGS_H

#include <Enums.h>
#include <Ints.h>

GZ_ENUM_FLAGS_BEGIN(WwdPlaneFlags, u32)
    WWD_PLANE_FLAG_MAIN = 0x1,
    WWD_PLANE_FLAG_NO_DRAW = 0x2,
    WWD_PLANE_FLAG_WRAP_X = 0x4,
    WWD_PLANE_FLAG_WRAP_Y = 0x8,
    WWD_PLANE_FLAG_AUTO_TILE_SIZE = 0x10
GZ_ENUM_FLAGS_END(WwdPlaneFlags, u32)
GZ_ENUM_FLAGS_OPS(WwdPlaneFlags)

#endif // GRUNTZ_WWD_WWDPLANEFLAGS_H
