// All.cpp - aggregate TU for the src/Stub/ @stub backlog.
//
// These are LABELED-BUT-UNMATCHED placeholders (empty `{}` bodies). They are
// compiled so the symbols exist and the TU stays valid, but objdiff does NOT
// diff them and their RVA() is NOT delink-verified against GRUNTZ.EXE.
// Why: this file #includes the per-class stubs, so their RVA() annotations DO
// surface in All.cpp's LLVM IR - but labels.py SKIPS the `engine_label_stubs`
// unit (this TU) entirely, so none of those annotations reach
// build/gen/symbol_names.csv and none are delinked. Consequences:
//   * the `engine_label_stubs` objdiff unit shows a trivial 100% with 0 funcs;
//   * RVA()/@stub here are DOCUMENTARY only (verify_stub_labels.py + the
//     "vs full engine" comprehension denominator), not load-bearing for matching;
//   * the labels.py duplicate-RVA guard does NOT cover anything here.
//
// The plan is to MOVE each stub into its real class's TU (as already done for
// CGrunt -> Grunt, CBootyState/CCreditsState -> GameMode, CGameMgr -> GameApp,
// CMultiStartDlg -> Dialogs). Once a stub lives in a real (non-skipped) TU,
// labels.py reads its RVA() from IR -> symbol_names row -> delink -> objdiff
// diffs it (initially ~0%, so it surfaces in the matching worklist). src/Stub/
// shrinks toward empty as classes are reconstructed; do not treat anything here
// as binary-verified.

#include "../rva.h"   // RVA()/RVAU() label macros the included stub files use

#include "ImplementedLabels.cpp"
#include "Backlog.cpp"
#include "CActionArea.cpp"
#include "CAmbientPosSound.cpp"
#include "CAmbientSound.cpp"
#include "CAniCycle.cpp"
#include "CAttract.cpp"
#include "CBehindCandy.cpp"
#include "CBehindCandyAni.cpp"
#include "CBoomerang.cpp"
#include "CBrickz.cpp"
#include "CCheckpointDlg.cpp"
#include "CCheckpointTrigger.cpp"
#include "CCheckpointTriggerSwitchLogic.cpp"
#include "CCoveredPowerup.cpp"
#include "CCoveredPowerupLogic.cpp"
#include "CCursorSnapSprite.cpp"
#include "CDirectDrawMgr.cpp"
#include "CDoNothing.cpp"
#include "CDoNothingNormal.cpp"
#include "CDroppedObject.cpp"
#include "CDroppedObjectShadow.cpp"
#include "CExitTrigger.cpp"
#include "CExplosion.cpp"
#include "CEyeCandy.cpp"
#include "CEyeCandyAni.cpp"
#include "CFortressFlag.cpp"
#include "CFrontCandy.cpp"
#include "CFrontCandyAni.cpp"
#include "CGameMgrDerived.cpp"
#include "CGiantRock.cpp"
#include "CGiantRockLogic.cpp"
#include "CGruntCreationPoint.cpp"
#include "CGruntHealthSprite.cpp"
#include "CGruntPowerupSprite.cpp"
#include "CGruntPuddle.cpp"
#include "CGruntSelectedSprite.cpp"
#include "CGruntStaminaSprite.cpp"
#include "CGruntStartingPoint.cpp"
#include "CGruntToySprite.cpp"
#include "CGruntToyTimeSprite.cpp"
#include "CGruntVoice.cpp"
#include "CGruntWingzTimeSprite.cpp"
#include "CGruntzCommand.cpp"
#include "CGruntzMapMgr.cpp"
#include "CGruntzMgr.cpp"
#include "CGruntzMultiCommand.cpp"
#include "CGruntzSingleCommand.cpp"
#include "CGuardPoint.cpp"
#include "CInGameIcon.cpp"
#include "CInGameText.cpp"
#include "CKitchenSlime.cpp"
#include "CLevelTime.cpp"
#include "CLightFx.cpp"
#include "CMenuSparkle.cpp"
#include "CMovingLogic.cpp"
#include "CObjectDropper.cpp"
#include "CParticlez.cpp"
#include "CPathHazard.cpp"
#include "CProjectile.cpp"
#include "CRainCloud.cpp"
#include "CRandomAmbientSound.cpp"
#include "CRollingBall.cpp"
#include "CSBI_Image.cpp"
#include "CSBI_ImageSet.cpp"
#include "CSBI_SideTab.cpp"
#include "CSecretLevelTrigger.cpp"
#include "CSecretTeleporterTrigger.cpp"
#include "CSimpleAnimation.cpp"
#include "CSingleAnimation.cpp"
#include "CSingleFrameMessage.cpp"
#include "CSplashState.cpp"
#include "CSpotLight.cpp"
#include "CStaticHazard.cpp"
#include "CStatusBarSprite.cpp"
#include "CTeleporter.cpp"
#include "CTileExclusiveTriggerSwitchLogic.cpp"
#include "CTileMultiTriggerSwitchLogic.cpp"
#include "CTileSecretTrigger.cpp"
#include "CTileSecretTriggerLogic.cpp"
#include "CTileSecretTriggerSwitchLogic.cpp"
#include "CTileTimeTriggerLogic.cpp"
#include "CTileTimeTriggerSwitchLogic.cpp"
#include "CTileTrigger.cpp"
#include "CTileTriggerSwitch.cpp"
#include "CTileTriggerSwitchLogic.cpp"
#include "CTileTriggerTransition.cpp"
#include "CTimeBomb.cpp"
#include "CToobSpikez.cpp"
#include "CToyPeek.cpp"
#include "CUFO.cpp"
#include "CUserLogic.cpp"
#include "CVoiceTrigger.cpp"
#include "CWarlord.cpp"
#include "CWarpStonePad.cpp"
#include "CWayPoint.cpp"
#include "DirectInputMgr2.cpp"
#include "DirectSoundMgr.cpp"
#include "RezSync.cpp"
#include "UnknownCGruntzMgrHogwarts.cpp"
#include "UnknownCGruntzMgrLucius.cpp"
#include "UnknownClassArrays.cpp"
#include "UnknownClassCGruntzMgrHarryPotter.cpp"
#include "UnknownClassInCGruntzMgr.cpp"
#include "UnknownFilch.cpp"
#include "UnknownMinerva.cpp"
#include "UnknownPettigrew.cpp"
#include "UnknownSalazar.cpp"
#include "UnknownSirius.cpp"
#include "UnknownVoldemort.cpp"
#include "Wwd/WwdFile.cpp"
