// All.cpp - aggregate TU for the src/Stub/ @stub backlog.
//
// These are LABELED-BUT-UNMATCHED functions (empty `{}` bodies, each with a real
// RVA()+size). This file #includes the per-class stubs, so their RVA()
// annotations surface in All.cpp's LLVM IR; labels.py reads them like any unit ->
// build/gen/symbol_names.csv -> the delinker carves the retail bytes at each RVA
// -> objdiff diffs them. So the `engine_label_stubs` objdiff unit lists all of
// them (initially ~0%), they ARE binary-verified (delinked against GRUNTZ.EXE),
// they count in the started-units denominator like any unmatched function, and
// they are covered by the labels.py duplicate-RVA guard + verify_stub_labels.py's
// stub-vs-matched cross-check.
//
// This unit IS the matching worklist for the backlog: pick a stub off it in
// objdiff and reconstruct it. The plan is to MOVE each stub into its real class's
// TU (as already done for CGrunt -> Grunt, CBootyState/CCreditsState -> GameMode,
// CGameMgr -> GameApp, CMultiStartDlg -> Dialogs); src/Stub/ shrinks toward empty
// as classes are reconstructed.

#include "../rva.h"   // RVA()/RVAU() label macros the included stub files use

#include "ImplementedLabels.cpp"
#include "Backlog.cpp"
#include "CActionArea.cpp"
#include "CAmbientPosSound.cpp"
#include "CAmbientSound.cpp"
#include "CAniCycle.cpp"
#include "CAttract.cpp"
#include "CBehindCandy.cpp"
#include "CBehindCandyAni.cpp"
#include "CBoomerang.cpp"
#include "CBrickz.cpp"
#include "CCheckpointDlg.cpp"
#include "CCheckpointTrigger.cpp"
#include "CCheckpointTriggerSwitchLogic.cpp"
#include "CCoveredPowerup.cpp"
#include "CCoveredPowerupLogic.cpp"
#include "CCursorSnapSprite.cpp"
#include "CDirectDrawMgr.cpp"
#include "CDoNothing.cpp"
#include "CDoNothingNormal.cpp"
#include "CDroppedObject.cpp"
#include "CDroppedObjectShadow.cpp"
#include "CExitTrigger.cpp"
#include "CExplosion.cpp"
#include "CEyeCandy.cpp"
#include "CEyeCandyAni.cpp"
#include "CFortressFlag.cpp"
#include "CFrontCandy.cpp"
#include "CFrontCandyAni.cpp"
#include "CGameMgrDerived.cpp"
#include "CGiantRock.cpp"
#include "CGiantRockLogic.cpp"
#include "CGruntCreationPoint.cpp"
#include "CGruntHealthSprite.cpp"
#include "CGruntPowerupSprite.cpp"
#include "CGruntPuddle.cpp"
#include "CGruntSelectedSprite.cpp"
#include "CGruntStaminaSprite.cpp"
#include "CGruntStartingPoint.cpp"
#include "CGruntToySprite.cpp"
#include "CGruntToyTimeSprite.cpp"
#include "CGruntVoice.cpp"
#include "CGruntWingzTimeSprite.cpp"
#include "CGruntzCommand.cpp"
#include "CGruntzMapMgr.cpp"
#include "CGruntzMgr.cpp"
#include "CGruntzMultiCommand.cpp"
#include "CGruntzSingleCommand.cpp"
#include "CGuardPoint.cpp"
#include "CInGameIcon.cpp"
#include "CInGameText.cpp"
#include "CKitchenSlime.cpp"
#include "CLevelTime.cpp"
#include "CLightFx.cpp"
#include "CMenuSparkle.cpp"
#include "CMovingLogic.cpp"
#include "CObjectDropper.cpp"
#include "CParticlez.cpp"
#include "CPathHazard.cpp"
#include "CProjectile.cpp"
#include "CRainCloud.cpp"
#include "CRandomAmbientSound.cpp"
#include "CRollingBall.cpp"
#include "CSBI_Image.cpp"
#include "CSBI_ImageSet.cpp"
#include "CSBI_SideTab.cpp"
#include "CSecretLevelTrigger.cpp"
#include "CSecretTeleporterTrigger.cpp"
#include "CSimpleAnimation.cpp"
#include "CSingleAnimation.cpp"
#include "CSingleFrameMessage.cpp"
#include "CSplashState.cpp"
#include "CSpotLight.cpp"
#include "CStaticHazard.cpp"
#include "CStatusBarSprite.cpp"
#include "CTeleporter.cpp"
#include "CTileExclusiveTriggerSwitchLogic.cpp"
#include "CTileMultiTriggerSwitchLogic.cpp"
#include "CTileSecretTrigger.cpp"
#include "CTileSecretTriggerLogic.cpp"
#include "CTileSecretTriggerSwitchLogic.cpp"
#include "CTileTimeTriggerLogic.cpp"
#include "CTileTimeTriggerSwitchLogic.cpp"
#include "CTileTrigger.cpp"
#include "CTileTriggerSwitch.cpp"
#include "CTileTriggerSwitchLogic.cpp"
#include "CTileTriggerTransition.cpp"
#include "CTimeBomb.cpp"
#include "CToobSpikez.cpp"
#include "CToyPeek.cpp"
#include "CUFO.cpp"
#include "CUserLogic.cpp"
#include "CVoiceTrigger.cpp"
#include "CWarlord.cpp"
#include "CWarpStonePad.cpp"
#include "CWayPoint.cpp"
#include "DirectInputMgr2.cpp"
#include "DirectSoundMgr.cpp"
#include "RezSync.cpp"
#include "UnknownCGruntzMgrHogwarts.cpp"
#include "UnknownCGruntzMgrLucius.cpp"
#include "UnknownClassArrays.cpp"
#include "UnknownClassCGruntzMgrHarryPotter.cpp"
#include "UnknownClassInCGruntzMgr.cpp"
#include "UnknownFilch.cpp"
#include "UnknownMinerva.cpp"
#include "UnknownPettigrew.cpp"
#include "UnknownSalazar.cpp"
#include "UnknownSirius.cpp"
#include "UnknownVoldemort.cpp"
#include "Wwd/WwdFile.cpp"
