// All.cpp - aggregate TU for the src/Stub/ @stub backlog.
//
// These are LABELED-BUT-UNMATCHED functions (empty `{}` bodies, each with a real
// RVA()+size). This file #includes the per-class stubs, so their RVA()
// annotations surface in All.cpp's LLVM IR; labels.py reads them like any unit ->
// build/gen/symbol_names.csv -> the delinker carves the retail bytes at each RVA
// -> objdiff diffs them. So the `engine_label_stubs` objdiff unit lists all of
// them (initially ~0%), they ARE binary-verified (delinked against GRUNTZ.EXE),
// they count in the started-units denominator like any unmatched function, and
// they are covered by the labels.py duplicate-RVA guard + verify_stub_labels.py's
// stub-vs-matched cross-check.
//
// This unit IS the matching worklist for the backlog: pick a stub off it in
// objdiff and reconstruct it. The plan is to MOVE each stub into its real class's
// TU (as already done for CGrunt -> Grunt, CBootyState/CCreditsState -> GameMode,
// CGameMgr -> GameApp, CMultiStartDlg -> Dialogs); src/Stub/ shrinks toward empty
// as classes are reconstructed.

#include <rva.h> // RVA()/RVAU() label macros the included stub files use

#include "ImplementedLabels.cpp"
#include "Backlog.cpp"
#include "ApiCallers.cpp"
// CButeTree defines CButeTree + g_buteTree, shared by the game-object ctors that
// remain here (and by GameObjectCtors.cpp / UserLogic.cpp) -> include early.
#include "CButeTree.cpp"
#include "CActionArea.cpp"
#include "CAmbientPosSound.cpp"
#include "CAmbientSound.cpp"
#include "CAttract.cpp"
#include "CBehindCandy.cpp"
#include "CBehindCandyAni.cpp"
#include "CBoomerang.cpp"
#include "CBrickz.cpp"
// reloc-correlation extern stubs (split from GenExterns):
#include "CButeMgrHelper.cpp"
#include "CButeNodeBase.cpp"
#include "CFileIO.cpp"
#include "CFileImageDecode.cpp"
#include "CGMMenuUI.cpp"
#include "CGameModeBase.cpp"
#include "CGruntzCmdList.cpp"
#include "CGruntzSoundInnerZ.cpp"
#include "CGruntzSoundZ.cpp"
#include "CImageBlit.cpp"
#include "CNetMgr.cpp"
#include "CNetSession.cpp"
#include "CPlay.cpp"
#include "CRegSink.cpp"
#include "CStatusBarItem2.cpp"
#include "CStatusBarMgr.cpp"
#include "EngineExternFns.cpp"
#include "HelperHost.cpp"
#include "MinervaInner.cpp"
#include "RemusParseSource.cpp"
#include "RezColl.cpp"
#include "RezMgr.cpp"
#include "RezNode.cpp"
#include "VoldemortObj.cpp"
#include "CCheckpointTrigger.cpp"
#include "CCheckpointTriggerSwitchLogic.cpp"
#include "CCoveredPowerup.cpp"
#include "CCoveredPowerupLogic.cpp"
#include "CCursorSnapSprite.cpp"
#include "CDirectDrawMgr.cpp"
#include "CDoNothing.cpp"
#include "CDoNothingNormal.cpp"
#include "CDroppedObject.cpp"
#include "CDroppedObjectShadow.cpp"
#include "CExitTrigger.cpp"
#include "CExplosion.cpp"
#include "CEyeCandy.cpp"
#include "CEyeCandyAni.cpp"
#include "CFortressFlag.cpp"
#include "CFrontCandy.cpp"
#include "CFrontCandyAni.cpp"
#include "CGameMgrDerived.cpp"
#include "CGiantRock.cpp"
#include "CGiantRockLogic.cpp"
#include "CGruntCreationPoint.cpp"
#include "CGruntHealthSprite.cpp"
#include "CGruntPowerupSprite.cpp"
#include "CGruntPuddle.cpp"
#include "CGruntSelectedSprite.cpp"
#include "CGruntStartingPoint.cpp"
#include "CGruntToySprite.cpp"
#include "CGruntVoice.cpp"
#include "CGruntzCommand.cpp"
#include "CGruntzMapMgr.cpp"
#include "CGruntzMgr.cpp"
#include "CGuardPoint.cpp"
#include "CInGameIcon.cpp"
#include "CInGameText.cpp"
#include "CKitchenSlime.cpp"
#include "CLevelTime.cpp"
#include "CLightFx.cpp"
#include "CMenuSparkle.cpp"
#include "CMovingLogic.cpp"
#include "CObjectDropper.cpp"
#include "CPathHazard.cpp"
#include "CProjectile.cpp"
#include "CRandomAmbientSound.cpp"
#include "CRollingBall.cpp"
#include "CSBI_Image.cpp"
#include "CSBI_ImageSet.cpp"
#include "CSBI_SideTab.cpp"
#include "CSimpleAnimation.cpp"
#include "CSingleFrameMessage.cpp"
#include "CSplashState.cpp"
#include "CSpotLight.cpp"
#include "CStaticHazard.cpp"
#include "CStatusBarSprite.cpp"
#include "CTeleporter.cpp"
#include "CTileExclusiveTriggerSwitchLogic.cpp"
#include "CTileMultiTriggerSwitchLogic.cpp"
#include "CTileSecretTrigger.cpp"
#include "CTileSecretTriggerLogic.cpp"
#include "CTileSecretTriggerSwitchLogic.cpp"
#include "CTileTimeTriggerLogic.cpp"
#include "CTileTimeTriggerSwitchLogic.cpp"
#include "CTimeBomb.cpp"
#include "CToyPeek.cpp"
#include "CUserLogic.cpp"
#include "CVoiceTrigger.cpp"
#include "CWarlord.cpp"
#include "CWayPoint.cpp"
#include "DirectSoundMgr.cpp"
#include "RezSync.cpp"
#include "UnknownClassInCGruntzMgr.cpp"
#include "UnknownVoldemort.cpp"
