// AUTO-GENERATED by gruntz.analysis.gen_attributed_stubs - do not hand-edit.
// Empty __thiscall stubs at each proximity-attributed RVA; the class is the
// static-layout bracket assignment (conf in the trailing comment). @stub
// backlog -> reconstruct from objdiff; a matcher moves it if the class was off.
#include <rva.h>
#include <Stub/attributed.h>

// ---- CChatBoxOwner ----
RVA(0x000205c0, 0x741) void CChatBoxOwner::CChatBoxOwner_0205c0() {}  // high

// ---- CNetMgr ----
RVA(0x000b86c0, 0x206) void CNetMgr::CNetMgr_0b86c0() {}  // high; large /GX EH func, final-sweep
// b8960: WRONG CLASS - this is a CDialog-derived dtor (base ~CDialog @1ba51d
// vtbl 0x5eb174; CString member @+0x70; CStringList member @+0x74 via
// ~CObject-based dtor @1b5d78). CNetMgr+0x70/+0x74 are i32 selection latches
// (ReadGroupSel/ReadPlayerSel, matched), so this is NOT a CNetMgr method -
// re-attribute (likely CMultiStartDlg or a sibling multiplayer dialog).
RVA(0x000b8fc0, 0x151) void CNetMgr::CNetMgr_0b8fc0() {}  // high; /GX cond-temp EH wall, final-sweep
// b93a0/b9410/b9500/b9570/b95f0/ba170/ba1a0/ba3b0 reconstructed in src/Net/NetMgr.cpp
RVA(0x000bbc90, 0x1b8) void CNetMgr::CNetMgr_0bbc90() {}  // high
RVA(0x000bbec0, 0x81) void CNetMgr::CNetMgr_0bbec0() {}  // high
RVA(0x000bbf80, 0xb7) void CNetMgr::CNetMgr_0bbf80() {}  // high
RVA(0x000bc750, 0x151) void CNetMgr::CNetMgr_0bc750() {}  // high
RVA(0x000bccd0, 0x141) void CNetMgr::CNetMgr_0bccd0() {}  // high

// ---- CShadeTableCache ----
RVA(0x0014df40, 0x5f4) void CShadeTableCache::CShadeTableCache_14df40() {}  // high

// ---- CTileTriggerTransition ----
RVA(0x0010fe70, 0x18d) void CTileTriggerTransition::CTileTriggerTransition_10fe70() {}  // med

// ---- CTriggerMgr ----
RVA(0x0007abc0, 0x4b6) void CTriggerMgr::CTriggerMgr_07abc0() {}  // high

// ---- CWarlord ----
RVA(0x000447a0, 0x333) void CWarlord::CWarlord_0447a0() {}  // med

// ---- CWwdObjMgr ----
RVA(0x0015ad30, 0x2be) void CWwdObjMgr::CWwdObjMgr_15ad30() {}  // high

// ---- FontRenderer ----
RVA(0x0017b120, 0x3c6) void FontRenderer::FontRenderer_17b120() {}  // high

// ---- UnknownClassArrays ----
RVA(0x0002b950, 0x513) void UnknownClassArrays::UnknownClassArrays_02b950() {}  // high
RVA(0x000302c0, 0x1ec) void UnknownClassArrays::UnknownClassArrays_0302c0() {}  // high

// ---- istream ----
RVA(0x0016a490, 0x7a) void istream::istream_16a490() {}  // med

// ---- streambuf ----
RVA(0x0016b340, 0x20) void streambuf::streambuf_16b340() {}  // high
RVA(0x0016b360, 0x31) void streambuf::streambuf_16b360() {}  // high

// ---- strstreambuf ----
RVA(0x001692c0, 0x129) void strstreambuf::strstreambuf_1692c0() {}  // high
RVA(0x001693f0, 0x10) void strstreambuf::strstreambuf_1693f0() {}  // high
RVA(0x00169400, 0x8a) void strstreambuf::strstreambuf_169400() {}  // high
