// AUTO-GENERATED by gruntz.analysis.gen_boundary_stubs - do not hand-edit.
// Unnamed FUN_ bodies that sit AT a class boundary: the two matched neighbours
// are different classes, so single-class proximity abstains (~58% exact). Each
// stub is named neutrally; the trailing comment records the two candidate
// classes (below | above) a matcher should pick between. The `engine_boundary`
// unit; delinked + objdiff'd like any backlog stub.
#include <rva.h>

// (drained) 0x13ab00 -> CSymParser 3-arg ctor (src/Bute/SymParser.cpp);
//          0x1493b0 -> CImageOwned::Rebuild   (src/Image/CImageOwned.cpp).
