#ifndef GRUNTZ_STUB_CBehindCandyAni_H
#define GRUNTZ_STUB_CBehindCandyAni_H
// CBehindCandyAni - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e838c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CBehindCandyAni : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x0100c0
    virtual void slot_01() OVERRIDE;   // 0x010050
    virtual void slot_02() OVERRIDE;   // 0x010030
    virtual void slot_04() OVERRIDE;   // 0x0ad850
};
#endif  // GRUNTZ_STUB_CBehindCandyAni_H
