#ifndef GRUNTZ_STUB_CBootyState_H
#define GRUNTZ_STUB_CBootyState_H
// CBootyState - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e9cec; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CState.h"

class CBootyState : public CState {
public:
    virtual void slot_00() OVERRIDE;   // 0x08d410
    virtual void slot_01() OVERRIDE;   // 0x018830  ?LoadBootyCheatState@EngineLabelBacklog@@YAXXZ
    virtual void slot_02() OVERRIDE;   // 0x018c90
    virtual void slot_04() OVERRIDE;   // 0x08d3f0  ?Update@CBootyState@@UAEHXZ
    virtual void slot_05() OVERRIDE;   // 0x01c210  ?CheckWarpLetterBonus@EngineLabelBacklog@@YAXXZ
    virtual void slot_06() OVERRIDE;   // 0x01ce10
    virtual void slot_07() OVERRIDE;   // 0x01ce30
    virtual void slot_08() OVERRIDE;   // 0x01c8a0  ?BootyState_OnActivate2_vfunc8@EngineLabelBacklog@@YAXXZ
    virtual void slot_09() OVERRIDE;   // 0x018d30  ?vfunc_9@BootyState@@QAEXXZ
    virtual void slot_0a() OVERRIDE;   // 0x018e40
    virtual void slot_0c() OVERRIDE;   // 0x01d420
    virtual void slot_0e() OVERRIDE;   // 0x01d3e0
    virtual void slot_11() OVERRIDE;   // 0x01d400
};
#endif  // GRUNTZ_STUB_CBootyState_H
