#ifndef GRUNTZ_STUB_CCheckpointTriggerSwitchLogic_H
#define GRUNTZ_STUB_CCheckpointTriggerSwitchLogic_H
// CCheckpointTriggerSwitchLogic - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eaf54; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CTileTriggerSwitchLogic.h"

class CCheckpointTriggerSwitchLogic : public CTileTriggerSwitchLogic {
public:
    virtual void slot_01() OVERRIDE;   // 0x112a50  ?BuildStatzTabSmall_vfunc1@EngineLabelBacklog@@YAXXZ
    virtual void slot_02() OVERRIDE;   // 0x112b70
    virtual void slot_03() OVERRIDE;   // 0x112bf0
};
#endif  // GRUNTZ_STUB_CCheckpointTriggerSwitchLogic_H
