#ifndef GRUNTZ_STUB_CCmdUI_H
#define GRUNTZ_STUB_CCmdUI_H
// CCmdUI - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eb834; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)

class CCmdUI {
public:
    virtual void slot_00();   // 0x1bebe1
    virtual void slot_01();   // 0x1bec71
    virtual void slot_02();   // 0x1becd3
    virtual void slot_03();   // 0x1bed25
};
#endif  // GRUNTZ_STUB_CCmdUI_H
