#ifndef GRUNTZ_STUB_CCoveredPowerupLogic_H
#define GRUNTZ_STUB_CCoveredPowerupLogic_H
// CCoveredPowerupLogic - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eaef4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CTileTriggerLogic.h"

class CCoveredPowerupLogic : public CTileTriggerLogic {
public:
};
#endif  // GRUNTZ_STUB_CCoveredPowerupLogic_H
