#ifndef GRUNTZ_STUB_CCreditsState_H
#define GRUNTZ_STUB_CCreditsState_H
// CCreditsState - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e9c64; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CState.h"

class CCreditsState : public CState {
public:
    virtual void slot_00() OVERRIDE;   // 0x08d5b0
    virtual void slot_01() OVERRIDE;   // 0x038d20  ?LoadCreditzStateAssets@EngineLabelBacklog@@YAXXZ
    virtual void slot_02() OVERRIDE;   // 0x038f00
    virtual void slot_04() OVERRIDE;   // 0x08d590  ?Update@CCreditsState@@UAEHXZ
    virtual void slot_05() OVERRIDE;   // 0x0391d0  ?Render@CCreditsState@@UAEHXZ
    virtual void slot_06() OVERRIDE;   // 0x039400
    virtual void slot_08() OVERRIDE;   // 0x0393b0
    virtual void slot_09() OVERRIDE;   // 0x039120
    virtual void slot_0a() OVERRIDE;   // 0x039160  ?vfunc_10@CAttract@@QAEXXZ
    virtual void slot_0c() OVERRIDE;   // 0x039440
    virtual void slot_0e() OVERRIDE;   // 0x0394b0
};
#endif  // GRUNTZ_STUB_CCreditsState_H
