#ifndef GRUNTZ_STUB_CDoNothing_H
#define GRUNTZ_STUB_CDoNothing_H
// CDoNothing - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e85f4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CDoNothing : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x00f740
    virtual void slot_01() OVERRIDE;   // 0x00f6d0
    virtual void slot_02() OVERRIDE;   // 0x00f6b0
};
#endif  // GRUNTZ_STUB_CDoNothing_H
