#ifndef GRUNTZ_STUB_CDroppedObject_H
#define GRUNTZ_STUB_CDroppedObject_H
// CDroppedObject - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e78d4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CDroppedObject : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x012580
    virtual void slot_01() OVERRIDE;   // 0x0c73a0
    virtual void slot_02() OVERRIDE;   // 0x012560
    virtual void slot_04() OVERRIDE;   // 0x0c6bd0
    virtual void slot_07() OVERRIDE;   // 0x0c7350
};
#endif  // GRUNTZ_STUB_CDroppedObject_H
