#ifndef GRUNTZ_STUB_CDroppedObjectShadow_H
#define GRUNTZ_STUB_CDroppedObjectShadow_H
// CDroppedObjectShadow - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e787c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CDroppedObjectShadow : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x012640
    virtual void slot_01() OVERRIDE;   // 0x0c7b40
    virtual void slot_02() OVERRIDE;   // 0x012620
    virtual void slot_04() OVERRIDE;   // 0x0c7750
};
#endif  // GRUNTZ_STUB_CDroppedObjectShadow_H
