#ifndef GRUNTZ_STUB_CEyeCandyAni_H
#define GRUNTZ_STUB_CEyeCandyAni_H
// CEyeCandyAni - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e8334; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CEyeCandyAni : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x00ff90
    virtual void slot_01() OVERRIDE;   // 0x00ff20
    virtual void slot_02() OVERRIDE;   // 0x00ff00
    virtual void slot_04() OVERRIDE;   // 0x0acbb0
};
#endif  // GRUNTZ_STUB_CEyeCandyAni_H
