#ifndef GRUNTZ_STUB_CFrontCandyAni_H
#define GRUNTZ_STUB_CFrontCandyAni_H
// CFrontCandyAni - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e83e4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CFrontCandyAni : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x00fe60
    virtual void slot_01() OVERRIDE;   // 0x00fdf0
    virtual void slot_02() OVERRIDE;   // 0x00fdd0
    virtual void slot_04() OVERRIDE;   // 0x0ad1b0
};
#endif  // GRUNTZ_STUB_CFrontCandyAni_H
