#ifndef GRUNTZ_STUB_CGruntzMapMgr_H
#define GRUNTZ_STUB_CGruntzMapMgr_H
// CGruntzMapMgr - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e9bb4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CMapMgr.h"

class CGruntzMapMgr : public CMapMgr {
public:
    virtual void slot_00() OVERRIDE;   // 0x085480
    virtual void slot_01() OVERRIDE;   // 0x082430
};
#endif  // GRUNTZ_STUB_CGruntzMapMgr_H
