#ifndef GRUNTZ_STUB_CGruntzMgr_H
#define GRUNTZ_STUB_CGruntzMgr_H
// CGruntzMgr - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e9b64; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CGameMgr.h"

class CGruntzMgr : public CGameMgr {
public:
    virtual void slot_00() OVERRIDE;   // 0x083330  ?vector_deleting_destructor@CGruntzMgr@@QAEXXZ
    virtual void slot_01() OVERRIDE;   // 0x083450  ?Init@RezSync@@QAEXXZ
    virtual void slot_02() OVERRIDE;   // 0x0855e0  ?UnknownClose@CGruntzMgr@@QAEXXZ
    virtual void slot_03() OVERRIDE;   // 0x083300
    virtual void slot_04() OVERRIDE;   // 0x08b740  ?PerFrameTick@RezMgr@@UAEHXZ
    virtual void slot_05() OVERRIDE;   // 0x0862f0
};
#endif  // GRUNTZ_STUB_CGruntzMgr_H
