#ifndef GRUNTZ_STUB_CGruntStartingPoint_H
#define GRUNTZ_STUB_CGruntStartingPoint_H
// CGruntStartingPoint - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e8284; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CGruntStartingPoint : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x010640
    virtual void slot_01() OVERRIDE;   // 0x0105d0
    virtual void slot_02() OVERRIDE;   // 0x0105b0
    virtual void slot_04() OVERRIDE;   // 0x03e1a0
};
#endif  // GRUNTZ_STUB_CGruntStartingPoint_H
