#ifndef GRUNTZ_STUB_CGruntzWnd_H
#define GRUNTZ_STUB_CGruntzWnd_H
// CGruntzWnd - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1ea2d4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CGameWnd.h"

class CGruntzWnd : public CGameWnd {
public:
    virtual void slot_00() OVERRIDE;   // 0x094670  ?Stub_094670@CGruntzWnd@@QAEXXZ
    virtual void slot_01() OVERRIDE;   // 0x094790
    virtual void slot_02() OVERRIDE;   // 0x094770
    virtual void slot_04() OVERRIDE;   // 0x094b90
    virtual void slot_07() OVERRIDE;   // 0x094bc0
    virtual void slot_08() OVERRIDE;   // 0x0948a0
    virtual void slot_09() OVERRIDE;   // 0x0948e0
    virtual void slot_0a() OVERRIDE;   // 0x094920
    virtual void slot_0c() OVERRIDE;   // 0x094b20
    virtual void slot_0e() OVERRIDE;   // 0x094960
    virtual void slot_0f() OVERRIDE;   // 0x094a20
    virtual void slot_10() OVERRIDE;   // 0x0949a0
    virtual void slot_11() OVERRIDE;   // 0x094a60
    virtual void slot_12() OVERRIDE;   // 0x0949e0
    virtual void slot_13() OVERRIDE;   // 0x094aa0
    virtual void slot_14() OVERRIDE;   // 0x094ae0
};
#endif  // GRUNTZ_STUB_CGruntzWnd_H
