#ifndef GRUNTZ_STUB_CGruntHealthSprite_H
#define GRUNTZ_STUB_CGruntHealthSprite_H
// CGruntHealthSprite - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7ba4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CGruntHealthSprite : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x011f80
    virtual void slot_01() OVERRIDE;   // 0x07f270
    virtual void slot_02() OVERRIDE;   // 0x011f60
    virtual void slot_04() OVERRIDE;   // 0x07ed70
    virtual void slot_10();   // 0x07f160
};
#endif  // GRUNTZ_STUB_CGruntHealthSprite_H
