#ifndef GRUNTZ_STUB_CGruntWingzTimeSprite_H
#define GRUNTZ_STUB_CGruntWingzTimeSprite_H
// CGruntWingzTimeSprite - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e77cc; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CGruntHealthSprite.h"

class CGruntWingzTimeSprite : public CGruntHealthSprite {
public:
    virtual void slot_00() OVERRIDE;   // 0x0121c0
    virtual void slot_02() OVERRIDE;   // 0x0121a0
    virtual void slot_10() OVERRIDE;   // 0x07fd90
};
#endif  // GRUNTZ_STUB_CGruntWingzTimeSprite_H
