#ifndef GRUNTZ_STUB_CGruntVoice_H
#define GRUNTZ_STUB_CGruntVoice_H
// CGruntVoice - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eaf6c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CGruntVoice : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x119ab0
    virtual void slot_04() OVERRIDE;   // 0x119e40
};
#endif  // GRUNTZ_STUB_CGruntVoice_H
