#ifndef GRUNTZ_STUB_CGruntToySprite_H
#define GRUNTZ_STUB_CGruntToySprite_H
// CGruntToySprite - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7b4c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CGruntToySprite : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x012280
    virtual void slot_01() OVERRIDE;   // 0x07fa20
    virtual void slot_02() OVERRIDE;   // 0x012260
    virtual void slot_04() OVERRIDE;   // 0x07f5c0
};
#endif  // GRUNTZ_STUB_CGruntToySprite_H
