#ifndef GRUNTZ_STUB_CGuardPoint_H
#define GRUNTZ_STUB_CGuardPoint_H
// CGuardPoint - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7154; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CGuardPoint : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x0103e0
    virtual void slot_01() OVERRIDE;   // 0x010370
    virtual void slot_02() OVERRIDE;   // 0x010350
};
#endif  // GRUNTZ_STUB_CGuardPoint_H
