#ifndef GRUNTZ_STUB_CHotKeyCtrl_H
#define GRUNTZ_STUB_CHotKeyCtrl_H
// CHotKeyCtrl - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1ecda4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CWnd.h"

class CHotKeyCtrl : public CWnd {
public:
    virtual void slot_00();   // 0x1d37c5
    virtual void slot_01();   // 0x11e7fc
};
#endif  // GRUNTZ_STUB_CHotKeyCtrl_H
