#ifndef GRUNTZ_STUB_CInGameText_H
#define GRUNTZ_STUB_CInGameText_H
// CInGameText - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7cac; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CInGameText : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x011d90
    virtual void slot_01() OVERRIDE;   // 0x099a30
    virtual void slot_02() OVERRIDE;   // 0x011d70
    virtual void slot_04() OVERRIDE;   // 0x099460
};
#endif  // GRUNTZ_STUB_CInGameText_H
