#ifndef GRUNTZ_STUB_CMirrorFile_H
#define GRUNTZ_STUB_CMirrorFile_H
// CMirrorFile - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1ee54c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CFile.h"

class CMirrorFile : public CFile {
public:
    virtual void slot_01();   // 0x1c9eb8
    virtual void slot_0a();   // 0x1c9c08
    virtual void slot_13();   // 0x1c9dcf
    virtual void slot_15();   // 0x1c9de8
};
#endif  // GRUNTZ_STUB_CMirrorFile_H
