#ifndef GRUNTZ_STUB_CMultiBootyState_H
#define GRUNTZ_STUB_CMultiBootyState_H
// CMultiBootyState - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e9bdc; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CState.h"

class CMultiBootyState : public CState {
public:
    virtual void slot_00() OVERRIDE;   // 0x08d4e0
    virtual void slot_01() OVERRIDE;   // 0x01d440  ?vfunc_1@CBootyState@@QAEXXZ
    virtual void slot_02() OVERRIDE;   // 0x01e520
    virtual void slot_04() OVERRIDE;   // 0x08d4c0
    virtual void slot_05() OVERRIDE;   // 0x01f480
    virtual void slot_06() OVERRIDE;   // 0x01f850
    virtual void slot_07() OVERRIDE;   // 0x01f870
    virtual void slot_08() OVERRIDE;   // 0x01f6f0  ?OnActivate_vfunc8@BootyState@@QAEXXZ
    virtual void slot_09() OVERRIDE;   // 0x01e570
    virtual void slot_0a() OVERRIDE;   // 0x01e660
    virtual void slot_0c() OVERRIDE;   // 0x01f920
    virtual void slot_0e() OVERRIDE;   // 0x01f8e0
    virtual void slot_11() OVERRIDE;   // 0x01f900
};
#endif  // GRUNTZ_STUB_CMultiBootyState_H
