#ifndef GRUNTZ_STUB_CNetMgr_H
#define GRUNTZ_STUB_CNetMgr_H
// CNetMgr - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1ea42c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CObject.h"

class CNetMgr : public CObject {
public:
    virtual void slot_01();   // 0x0b5fd0
};
#endif  // GRUNTZ_STUB_CNetMgr_H
