#ifndef GRUNTZ_STUB_CPathHazard_H
#define GRUNTZ_STUB_CPathHazard_H
// CPathHazard - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7394; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CPathHazard : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x013250
    virtual void slot_01() OVERRIDE;   // 0x0b4d30
    virtual void slot_02() OVERRIDE;   // 0x013210
    virtual void slot_04() OVERRIDE;   // 0x0b3b60
    virtual void slot_10();   // 0x0b4020
    virtual void slot_11();   // 0x0b43f0
    virtual void slot_12();   // 0x0b47a0
    virtual void slot_13();   // 0x0b47e0
    virtual void slot_14();   // 0x013230
};
#endif  // GRUNTZ_STUB_CPathHazard_H
