#ifndef GRUNTZ_STUB_CProjectile_H
#define GRUNTZ_STUB_CProjectile_H
// CProjectile - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e798c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CMovingLogic.h"
#include "CWapX.h"

class CProjectile : public CMovingLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x012980
    virtual void slot_01() OVERRIDE;   // 0x0e0d40
    virtual void slot_02() OVERRIDE;   // 0x012960
    virtual void slot_04() OVERRIDE;   // 0x0df9a0
    virtual void slot_10() OVERRIDE;   // 0x0dfd00  ?LoadProjectileEffects@EngineLabelBacklog@@YAXXZ
    virtual void slot_11();   // 0x0df050  ?LoadProjectileSprites@CProjectile@@QAEXXZ
};
#endif  // GRUNTZ_STUB_CProjectile_H
