#ifndef GRUNTZ_STUB_CRandomAmbientSound_H
#define GRUNTZ_STUB_CRandomAmbientSound_H
// CRandomAmbientSound - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e713c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CAmbientSound.h"

class CRandomAmbientSound : public CAmbientSound {
public:
    virtual void slot_00() OVERRIDE;   // 0x00bb10
    virtual void slot_03() OVERRIDE;   // 0x00cb30
};
#endif  // GRUNTZ_STUB_CRandomAmbientSound_H
