#ifndef GRUNTZ_STUB_CSBI_GruntMachine_H
#define GRUNTZ_STUB_CSBI_GruntMachine_H
// CSBI_GruntMachine - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eadbc; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CStatusBarItem.h"

class CSBI_GruntMachine : public CStatusBarItem {
public:
    virtual void slot_00() OVERRIDE;   // 0x104cb0
    virtual void slot_01() OVERRIDE;   // 0x0e8e00
    virtual void slot_03() OVERRIDE;   // 0x0e8c70
    virtual void slot_04() OVERRIDE;   // 0x0e8c90
    virtual void slot_05() OVERRIDE;   // 0x0e8cb0
};
#endif  // GRUNTZ_STUB_CSBI_GruntMachine_H
