#ifndef GRUNTZ_STUB_CSBI_MenuItem_H
#define GRUNTZ_STUB_CSBI_MenuItem_H
// CSBI_MenuItem - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eab4c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CSBI_Image.h"

class CSBI_MenuItem : public CSBI_Image {
public:
    virtual void slot_00() OVERRIDE;   // 0x1007a0
    virtual void slot_01() OVERRIDE;   // 0x0e8520
    virtual void slot_03() OVERRIDE;   // 0x0e81a0
    virtual void slot_04() OVERRIDE;   // 0x0e81c0
    virtual void slot_05() OVERRIDE;   // 0x0e82a0
    virtual void slot_0b() OVERRIDE;   // 0x0e80e0
};
#endif  // GRUNTZ_STUB_CSBI_MenuItem_H
