#ifndef GRUNTZ_STUB_CSecretTeleporterTrigger_H
#define GRUNTZ_STUB_CSecretTeleporterTrigger_H
// CSecretTeleporterTrigger - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7564; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CSecretTeleporterTrigger : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x010a80
    virtual void slot_01() OVERRIDE;   // 0x010a10
    virtual void slot_02() OVERRIDE;   // 0x0109f0
    virtual void slot_04() OVERRIDE;   // 0x042150
};
#endif  // GRUNTZ_STUB_CSecretTeleporterTrigger_H
