#ifndef GRUNTZ_STUB_CSingleFrameMessage_H
#define GRUNTZ_STUB_CSingleFrameMessage_H
// CSingleFrameMessage - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e864c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CSingleFrameMessage : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x00f610
    virtual void slot_01() OVERRIDE;   // 0x00f5a0
    virtual void slot_02() OVERRIDE;   // 0x00f580
    virtual void slot_04() OVERRIDE;   // 0x0ab5b0
};
#endif  // GRUNTZ_STUB_CSingleFrameMessage_H
