#ifndef GRUNTZ_STUB_CSingleAnimation_H
#define GRUNTZ_STUB_CSingleAnimation_H
// CSingleAnimation - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e745c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CSingleAnimation : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x010510
    virtual void slot_01() OVERRIDE;   // 0x0104a0
    virtual void slot_02() OVERRIDE;   // 0x010480
    virtual void slot_04() OVERRIDE;   // 0x0aea20
};
#endif  // GRUNTZ_STUB_CSingleAnimation_H
