#ifndef GRUNTZ_STUB_CStatusBarSprite_H
#define GRUNTZ_STUB_CStatusBarSprite_H
// CStatusBarSprite - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e7fc4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CStatusBarSprite : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x011b50
    virtual void slot_01() OVERRIDE;   // 0x011ae0
    virtual void slot_02() OVERRIDE;   // 0x011ac0
    virtual void slot_04() OVERRIDE;   // 0x10c4b0
};
#endif  // GRUNTZ_STUB_CStatusBarSprite_H
