#ifndef GRUNTZ_STUB_CThreadData_H
#define GRUNTZ_STUB_CThreadData_H
// CThreadData - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1ed6ec; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CNoTrackObject.h"

class CThreadData : public CNoTrackObject {
public:
    virtual void slot_00();   // 0x1d4707
};
#endif  // GRUNTZ_STUB_CThreadData_H
