#ifndef GRUNTZ_STUB_CTileSecretTriggerLogic_H
#define GRUNTZ_STUB_CTileSecretTriggerLogic_H
// CTileSecretTriggerLogic - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eaf14; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CTileTriggerLogic.h"

class CTileSecretTriggerLogic : public CTileTriggerLogic {
public:
    virtual void slot_00() OVERRIDE;   // 0x1128b0
};
#endif  // GRUNTZ_STUB_CTileSecretTriggerLogic_H
