#ifndef GRUNTZ_STUB_CTileTriggerSwitchLogic_H
#define GRUNTZ_STUB_CTileTriggerSwitchLogic_H
// CTileTriggerSwitchLogic - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eae8c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)

class CTileTriggerSwitchLogic {
public:
    virtual void slot_00();   // 0x1104f0
    virtual void slot_01();   // 0x110460
    virtual void slot_02();   // 0x110570  ?LoadSwitchDownSprite@EngineLabelBacklog@@YAXXZ
    virtual void slot_03();   // 0x1106b0  ?LoadSwitchUpSprite@EngineLabelBacklog@@YAXXZ
};
#endif  // GRUNTZ_STUB_CTileTriggerSwitchLogic_H
