#ifndef GRUNTZ_STUB_CTileTriggerLogic_H
#define GRUNTZ_STUB_CTileTriggerLogic_H
// CTileTriggerLogic - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1eaea4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)

class CTileTriggerLogic {
public:
    virtual void slot_00();   // 0x110c10  ?LoadPyramidBridgeSprites@EngineLabelBacklog@@YAXXZ
};
#endif  // GRUNTZ_STUB_CTileTriggerLogic_H
