#ifndef GRUNTZ_STUB_CUFO_H
#define GRUNTZ_STUB_CUFO_H
// CUFO - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e72b4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CPathHazard.h"

class CUFO : public CPathHazard {
public:
    virtual void slot_00() OVERRIDE;   // 0x0133d0
    virtual void slot_01() OVERRIDE;   // 0x0b4c40
    virtual void slot_02() OVERRIDE;   // 0x0133b0
    virtual void slot_10() OVERRIDE;   // 0x0b4330
};
#endif  // GRUNTZ_STUB_CUFO_H
