#ifndef GRUNTZ_STUB_CVoiceTrigger_H
#define GRUNTZ_STUB_CVoiceTrigger_H
// CVoiceTrigger - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e885c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CVoiceTrigger : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x013570
    virtual void slot_01() OVERRIDE;   // 0x0134e0
    virtual void slot_02() OVERRIDE;   // 0x013550
    virtual void slot_04() OVERRIDE;   // 0x11a3a0
};
#endif  // GRUNTZ_STUB_CVoiceTrigger_H
