#ifndef GRUNTZ_STUB_CWarpStonePad_H
#define GRUNTZ_STUB_CWarpStonePad_H
// CWarpStonePad - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e71ac; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CWarpStonePad : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x010f90
    virtual void slot_01() OVERRIDE;   // 0x010f20
    virtual void slot_02() OVERRIDE;   // 0x010f00
    virtual void slot_04() OVERRIDE;   // 0x10d8c0
};
#endif  // GRUNTZ_STUB_CWarpStonePad_H
