#ifndef GRUNTZ_STUB_CWayPoint_H
#define GRUNTZ_STUB_CWayPoint_H
// CWayPoint - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e74b4; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CWayPoint : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x0102b0
    virtual void slot_01() OVERRIDE;   // 0x010240
    virtual void slot_02() OVERRIDE;   // 0x010220
};
#endif  // GRUNTZ_STUB_CWayPoint_H
