#ifndef GRUNTZ_STUB_CWormhole_H
#define GRUNTZ_STUB_CWormhole_H
// CWormhole - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e817c; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "CUserLogic.h"
#include "CWapX.h"

class CWormhole : public CUserLogic, public CWapX {
public:
    virtual void slot_00() OVERRIDE;   // 0x010950
    virtual void slot_01() OVERRIDE;   // 0x03fed0  ?Stub_03fed0@CWormhole@@QAEXXZ
    virtual void slot_02() OVERRIDE;   // 0x010930
    virtual void slot_04() OVERRIDE;   // 0x040050
};
#endif  // GRUNTZ_STUB_CWormhole_H
