// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.
// Empty __thiscall stubs at each trace-discovered RVA; the class is the trace's
// (inheritance-aware) assignment. @stub backlog -> reconstruct from objdiff.
#include <rva.h>
#include <Stub/discovered.h>

// ---- CBattlezDlgColors ----
RVA(0x00017ac0, 0x6)
void CBattlezDlgColors::CBattlezDlgColors_017ac0() {}

// ---- CBehindCandy ----
RVA(0x0000fb70, 0x6)
void CBehindCandy::CBehindCandy_00fb70() {}
RVA(0x0000fc30, 0x44)
void CBehindCandy::CBehindCandy_00fc30() {}

// ---- CBehindCandyAni ----
RVA(0x000100f0, 0x44)
void CBehindCandyAni::CBehindCandyAni_0100f0() {}
RVA(0x000adbb0, 0x17)
void CBehindCandyAni::CBehindCandyAni_0adbb0() {}

// ---- CBrickz ---- (trace placeholder) two distinct classes were grouped here:
//  (1) the CUserLogic-derived terrain/influence grid leaf "CMapLogic" - its clean
//      serializer methods (~CMapLogic 0x113c0, float-curve serializer 0xec230,
//      polymorphic Visit 0x9f7f0, FreeNodes tear-down 0x85480) are reconstructed
//      BYTE-EXACT in src/Gruntz/MapLogic.cpp.
//  (2) the matched CBrickz container itself (src/Gruntz/Brickz.cpp): its A*-style
//      grid search driver Search (0x9eca0) and neighbour-relax Expand (0x9f010)
//      are reconstructed there - they call CBrickz::Insert/Find/Unlink/CellPop.
// The remaining CMapLogic grid/serializer methods (0x77790 jump-table flag compute,
// 0x81e10/0x82030 terrain-flag grid walks, 0x82430 node serializer, 0x9356c the
// thin ec230+fd3f0 wrapper) are large/entangled and deferred to the final sweep.
// They are NOT CBrickz members - they belong to CMapLogic (different this-shape).
RVA(0x00077790, 0x37d)
void CBrickz::CBrickz_077790() {}
RVA(0x00081e10, 0x1a7)
void CBrickz::CBrickz_081e10() {}
RVA(0x00082030, 0x1a1)
void CBrickz::CBrickz_082030() {}
RVA(0x00082430, 0x161)
void CBrickz::CBrickz_082430() {}
RVA(0x0009356c, 0x38)
void CBrickz::CBrickz_09356c() {}

// ---- CButeMgr ---- lexer cluster migrated to src/Bute/ButeMgr.cpp; only the
// EH-frame scalar destructor remains here (deferred to the final sweep).
RVA(0x000213c0, 0x14c)
void CButeMgr::CButeMgr_0213c0() {}

// ---- CButeMgrHelper ---- ctor/dtor + vbase vtable-init thunks migrated to
// src/Bute/ButeMgr.cpp (CButeMgrHelper, the +0x14 sub-object).

// ---- CButeTree ----
RVA(0x0016e070, 0x7b)
void CButeTree::CButeTree_16e070() {}

// ---- CCheckpointDlg ----
RVA(0x00023570, 0x6)
void CCheckpointDlg::CCheckpointDlg_023570() {}

// ---- CCheckpointTrigger ----
RVA(0x00011480, 0x44)
void CCheckpointTrigger::CCheckpointTrigger_011480() {}

// ---- CCreditsState ----
RVA(0x00038f00, 0x87)
void CCreditsState::CCreditsState_038f00() {}
RVA(0x00039c40, 0x10)
void CCreditsState::CCreditsState_039c40() {}
RVA(0x00039c60, 0x7a)
void CCreditsState::CCreditsState_039c60() {}
RVA(0x00039d00, 0x8c)
void CCreditsState::CCreditsState_039d00() {}

// ---- CCursorSnapSprite ----
RVA(0x00011880, 0x47)
void CCursorSnapSprite::CCursorSnapSprite_011880() {}
RVA(0x00011920, 0x44)
void CCursorSnapSprite::CCursorSnapSprite_011920() {}

// ---- CDDPalette ----
RVA(0x001474d0, 0x60)
void CDDPalette::CDDPalette_1474d0() {}
RVA(0x00147530, 0x54)
void CDDPalette::CDDPalette_147530() {}

// ---- CDDSurface ----
RVA(0x00142a40, 0x53)
void CDDSurface::CDDSurface_142a40() {}

// ---- CDDrawSubMgr ----
// NOTE: this discovery cluster is a DISTINCT class from the matched small
// CDDrawSubMgr (different field layout / vtable).  The clean self-contained
// methods (158b40..158ee0, 159ef0, 15c290/2c0/2d0) plus the whole CMap/CList
// collection family (159e40, 15aa90..15b1d0 = CWwdObjMgr) and the blit-param
// serializer/dispatcher (15c900/15c970) were reconstructed into
// src/Gruntz/CDDrawSubMgr.cpp (CWwdObjMgr / CDDrawBlitParam).  Three remain:
//   - 0x031250: a NON-MEMBER (iterates a +0x68 list, vtable+0x20==5 probe; a
//     different class entirely) — left stubbed.
//   - 0x159600: the CWwdObject factory (EH frame + 0x1dc heap construct +
//     vtable stamps; tail-calls the matched 159e40) — deferred to final sweep.
//   - 0x15c360: the 0x555-byte blit-param step/advance megafunction (two jump
//     tables, EH) — deferred to final sweep.
RVA(0x00031250, 0x33)
void CDDrawSubMgr::CDDrawSubMgr_031250() {}
RVA(0x00159600, 0x1ab)
void CDDrawSubMgr::CDDrawSubMgr_159600() {}
RVA(0x0015c360, 0x555)
void CDDrawSubMgr::CDDrawSubMgr_15c360() {}

// ---- CDDrawSubMgrLeaf ----
RVA(0x0005b7e0, 0x23)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_05b7e0() {}
RVA(0x00114120, 0x70)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_114120() {}
RVA(0x00157570, 0x68)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_157570() {}
RVA(0x00157c70, 0xf8)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_157c70() {}
RVA(0x00157d70, 0x90)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_157d70() {}
RVA(0x00157ee0, 0x1c6)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_157ee0() {}
RVA(0x001583c0, 0xdc)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_1583c0() {}
RVA(0x001584f0, 0x80)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_1584f0() {}
RVA(0x00158570, 0xd4)
void CDDrawSubMgrLeaf::CDDrawSubMgrLeaf_158570() {}

// ---- CDDrawSurfaceMgr ----
RVA(0x001558b0, 0x46)
void CDDrawSurfaceMgr::CDDrawSurfaceMgr_1558b0() {}
RVA(0x00155e20, 0xd1)
void CDDrawSurfaceMgr::CDDrawSurfaceMgr_155e20() {}
RVA(0x00156020, 0x505)
void CDDrawSurfaceMgr::CDDrawSurfaceMgr_156020() {}

// ---- CDDrawWorkerList ----
RVA(0x00163bc0, 0x2c)
void CDDrawWorkerList::CDDrawWorkerList_163bc0() {}

// ---- CDDrawWorkerMapSmall ----
RVA(0x00156d20, 0x82)
void CDDrawWorkerMapSmall::CDDrawWorkerMapSmall_156d20() {}
RVA(0x00165810, 0xa9)
void CDDrawWorkerMapSmall::CDDrawWorkerMapSmall_165810() {}

// ---- CSeverusWorker ----
// MISATTRIBUTION CORRECTED: 0x151f00 / 0x15cc30 are methods of the *worker*
// object (vtable g_severusWorkerVtbl @ RVA 0x1efbe8: 0x151f00 is slot +0x38),
// NOT of CDDrawWorkerRegistry. They iterate the worker's own CByteArray (m_pData
// at this+0x14, m_nSize at this+0x18) and track min/max at this+0x64/+0x68 - the
// SeverusWorkerObj layout, not the registry's CMapStringToOb. Left stubbed for a
// dedicated worker TU. The other four (0x155360/550/630, 0x165360) were genuine
// map-holder methods and now live reconstructed in src/Gruntz/CDDrawWorkerRegistry.cpp.
RVA(0x00151f00, 0xa4)
void CSeverusWorker::CSeverusWorker_151f00() {}
RVA(0x0015cc30, 0x1e)
void CSeverusWorker::CSeverusWorker_15cc30() {}

// ---- CDoNothing ----
RVA(0x0000f6b0, 0x6)
void CDoNothing::CDoNothing_00f6b0() {}
RVA(0x0000f770, 0x44)
void CDoNothing::CDoNothing_00f770() {}

// ---- CDroppedObject ----
RVA(0x000125b0, 0x44)
void CDroppedObject::CDroppedObject_0125b0() {}
RVA(0x000c6bd0, 0x102)
void CDroppedObject::CDroppedObject_0c6bd0() {}

// ---- CDroppedObjectShadow ----
RVA(0x00012670, 0x44)
void CDroppedObjectShadow::CDroppedObjectShadow_012670() {}

// ---- CExitTrigger ----
RVA(0x00010870, 0x6)
void CExitTrigger::CExitTrigger_010870() {}
RVA(0x000108c0, 0x44)
void CExitTrigger::CExitTrigger_0108c0() {}

// ---- CExplosion ----
RVA(0x00012ec0, 0x44)
void CExplosion::CExplosion_012ec0() {}

// ---- CEyeCandy ----
RVA(0x0000fca0, 0x6)
void CEyeCandy::CEyeCandy_00fca0() {}
RVA(0x0000fd60, 0x44)
void CEyeCandy::CEyeCandy_00fd60() {}

// ---- CFortressFlag ----
RVA(0x00010e90, 0x44)
void CFortressFlag::CFortressFlag_010e90() {}
RVA(0x00046410, 0x92)
void CFortressFlag::CFortressFlag_046410() {}

// ---- CGrunt ----
RVA(0x00057c40, 0x71)
void CGrunt::CGrunt_057c40() {}

// ---- CGruntAnimPlayer ----
RVA(0x00150610, 0x41)
void CGruntAnimPlayer::CGruntAnimPlayer_150610() {}

// ---- CGruntCreationPoint ----
RVA(0x00010730, 0x44)
void CGruntCreationPoint::CGruntCreationPoint_010730() {}
RVA(0x0003ecc0, 0x17)
void CGruntCreationPoint::CGruntCreationPoint_03ecc0() {}

// ---- CGruntHealthSprite ----
RVA(0x00011fb0, 0x44)
void CGruntHealthSprite::CGruntHealthSprite_011fb0() {}
RVA(0x0007f0d0, 0x6e)
void CGruntHealthSprite::CGruntHealthSprite_07f0d0() {}

// ---- CGruntPowerupSprite ----
RVA(0x00012370, 0x44)
void CGruntPowerupSprite::CGruntPowerupSprite_012370() {}
RVA(0x00080380, 0x6c)
void CGruntPowerupSprite::CGruntPowerupSprite_080380() {}
RVA(0x00080410, 0x51)
void CGruntPowerupSprite::CGruntPowerupSprite_080410() {}

// ---- CGruntPuddle ---- migrated to src/Gruntz/CGruntPuddle.cpp (all 4 methods).

// ---- CGruntSelectedSprite ----
RVA(0x00011e80, 0x44)
void CGruntSelectedSprite::CGruntSelectedSprite_011e80() {}
RVA(0x0007e9c0, 0x16)
void CGruntSelectedSprite::CGruntSelectedSprite_07e9c0() {}
RVA(0x0007e9f0, 0x5f)
void CGruntSelectedSprite::CGruntSelectedSprite_07e9f0() {}

// ---- CGruntStartingPoint ----
RVA(0x00010670, 0x44)
void CGruntStartingPoint::CGruntStartingPoint_010670() {}

// ---- CGruntToySprite ----
RVA(0x000122b0, 0x44)
void CGruntToySprite::CGruntToySprite_0122b0() {}
RVA(0x0007f920, 0x21)
void CGruntToySprite::CGruntToySprite_07f920() {}
RVA(0x0007f960, 0x85)
void CGruntToySprite::CGruntToySprite_07f960() {}

// ---- CGruntToyTimeSprite ----
RVA(0x00012130, 0x44)
void CGruntToyTimeSprite::CGruntToyTimeSprite_012130() {}

// ---- CGruntzMgr ---- (43 methods migrated to src/Gruntz/GruntzMgr.cpp, incl.
// SyncOptionsState @0x093170, now @early-stop at 92.95%). The one remaining big
// method stays stubbed for the final sweep (per matcher doctrine: don't half-do a
// big EH/switch state-factory - a partial under-counts AND diverges its regalloc;
// redo leaf-first once the ~11 state classes are modeled):
//   0x08b960 (1988 B) - the state-FACTORY/switch method: /GX EH frame + a 0x11-case
//     switch (jump table switchdataD_0048c124 @0x48c124) that `new`s a distinct
//     game-state object per case, each with its own vftable (PTR_LAB_005ea21c ..
//     PTR_LAB_005e9bdc - 11 distinct, none yet named to a class) + CString/CByteArray
//     members (out-of-line NAFXCW ctors FUN_0051f5a0 etc.) + a scalar-deleting dtor.
//     Tearing down m_curState (vtbl 0x10/0x28) then installing+entering the new state
//     (vtbl 0x4). Blocked on modelling all ~11 state-class layouts + their vtable
//     contents; reconstruct those leaves FIRST, then this dispatcher.
RVA(0x0008b960, 0x7c4)
void CGruntzMgr::CGruntzMgr_08b960() {}

// ---- CGruntzSoundZ ---- migrated to src/Dsndmgr/CGruntzSoundZ.cpp (all 8 methods).

// ---- CGuardPoint ----
RVA(0x00010410, 0x44)
void CGuardPoint::CGuardPoint_010410() {}

// ---- CInGameIcon ---- migrated to src/Gruntz/CInGameIcon.cpp (all 5 methods).

// ---- CInGameText ----
RVA(0x00011dc0, 0x44)
void CInGameText::CInGameText_011dc0() {}
RVA(0x00099460, 0x102)
void CInGameText::CInGameText_099460() {}
RVA(0x00099a30, 0xaa)
void CInGameText::CInGameText_099a30() {}

// ---- CKitchenSlime ----
RVA(0x00013100, 0x44)
void CKitchenSlime::CKitchenSlime_013100() {}
RVA(0x000b2940, 0x102)
void CKitchenSlime::CKitchenSlime_0b2940() {}

// ---- CLightFx ----
RVA(0x00012430, 0x44)
void CLightFx::CLightFx_012430() {}
RVA(0x0009d520, 0xfd)
void CLightFx::CLightFx_09d520() {}
RVA(0x0009d770, 0x25)
void CLightFx::CLightFx_09d770() {}

// ---- CMapArrayA ----
RVA(0x0009e740, 0x76)
void CMapArrayA::CMapArrayA_09e740() {}

// ---- CMapArrayB ----
RVA(0x0009e860, 0x7a)
void CMapArrayB::CMapArrayB_09e860() {}

// ---- CMenuState ----
RVA(0x000a0d40, 0x24)
void CMenuState::CMenuState_0a0d40() {}

// ---- NetUnattributed ----
// Trace-discovered near the NetMgr DirectPlay body but NOT CNetMgr methods (the
// 0x178xxx CNetMgr cluster moved to src/Net/NetMgr.cpp). Each verified non-member:
//   0x007c20 __cdecl/__stdcall callback-iterator (ret 0x10, no `this`)
//   0x024450 __cdecl teardown of a .data global object (no `this`)
//   0x099d10 __thiscall on a .data global (ecx = &g_0x6459b0, not CNetMgr)
//   0x0b89e0 free function taking the net-mgr as a parameter (no `mov reg,ecx`)
//   0x0f93b0 __cdecl format/log helper (esp args, no `this`)
//   0x11f618 SEH cleanup funclet (ebp-relative; not a function start)
//   0x18c022 CRT libm routine (fyl2x/fstcw == pow/log; not a method)
RVA(0x00007c20, 0x2a)
void NetUnattributed::NetUnattributed_007c20() {}
RVA(0x00024450, 0x29)
void NetUnattributed::NetUnattributed_024450() {}
RVA(0x00099d10, 0x20)
void NetUnattributed::NetUnattributed_099d10() {}
RVA(0x000b89e0, 0xc8)
void NetUnattributed::NetUnattributed_0b89e0() {}
RVA(0x000f93b0, 0x41)
void NetUnattributed::NetUnattributed_0f93b0() {}
RVA(0x0011f618, 0x14)
void NetUnattributed::NetUnattributed_11f618() {}
RVA(0x0018c022, 0x1d3)
void NetUnattributed::NetUnattributed_18c022() {}

// ---- CObjectDropper ----
RVA(0x000124f0, 0x44)
void CObjectDropper::CObjectDropper_0124f0() {}

// ---- CParticlez ----
RVA(0x00012d90, 0x44)
void CParticlez::CParticlez_012d90() {}
RVA(0x00046d30, 0x102)
void CParticlez::CParticlez_046d30() {}

// ---- CPlay ---- HandleDragMove (0xd0db0) reconstructed in src/Gruntz/CPlay.cpp.
// The 0x08d270 / 0x0b6110-0x0bc420 cluster was MIS-ATTRIBUTED to CPlay: RTTI
// (.?AVCMulti@@) recovered the real class CMulti (the multiplayer/lobby game-
// state, `CMulti : public CPlay, public CState`), now reconstructed in
// src/Gruntz/CMulti.cpp (the EH-frame dtor at 0x08d270 + the 10 lobby methods).
// 0x0d1b60 (3119 B) IS a genuine CPlay method (offsets <=0x464, uses g_64556c/
// g_644c54/g_buteMgr, strings GAME_BADSELECT/PlayerDefenderRadius/Grunt) - the big
// selection/command dispatcher built on a jump table (switchdataD_004d2790, 40
// calls, 104 branches). Too large/entangled to converge in breadth-first mode;
// deferred to the final sweep (leaf-first redo) - do NOT half-reconstruct.
RVA(0x000d1b60, 0xc2f)
void CPlay::CPlay_0d1b60() {}

// ---- CRollingBall ----
RVA(0x00012f80, 0x44)
void CRollingBall::CRollingBall_012f80() {}
RVA(0x000b0fe0, 0x1ab)
void CRollingBall::CRollingBall_0b0fe0() {}

// ---- CSBI_RectOnly ----
RVA(0x000c8980, 0x64)
void CSBI_RectOnly::CSBI_RectOnly_0c8980() {}
RVA(0x000ebd70, 0x366)
void CSBI_RectOnly::CSBI_RectOnly_0ebd70() {}
RVA(0x00105800, 0x9e)
void CSBI_RectOnly::CSBI_RectOnly_105800() {}
RVA(0x001084d0, 0x96c)
void CSBI_RectOnly::CSBI_RectOnly_1084d0() {}

// ---- CSecretLevelTrigger ----
RVA(0x00010c50, 0x44)
void CSecretLevelTrigger::CSecretLevelTrigger_010c50() {}
RVA(0x00042ac0, 0x90)
void CSecretLevelTrigger::CSecretLevelTrigger_042ac0() {}

// ---- CSimpleAnimation ----
RVA(0x0000f9d0, 0x44)
void CSimpleAnimation::CSimpleAnimation_00f9d0() {}
RVA(0x000abf70, 0x17)
void CSimpleAnimation::CSimpleAnimation_0abf70() {}

// ---- CSingleAnimation ----
RVA(0x00010540, 0x44)
void CSingleAnimation::CSingleAnimation_010540() {}

// ---- CState ---- migrated to src/Gruntz/GameMode.cpp (its real class TU): the
// two leaf `??1` destructors + slot-2 release virtuals (CMenuState/CBootyState)
// and the CMenuState per-frame poll methods, plus the two switch dispatchers.

// ---- CStaticHazard ----
RVA(0x00012b30, 0x44)
void CStaticHazard::CStaticHazard_012b30() {}
RVA(0x000fbbf0, 0x102)
void CStaticHazard::CStaticHazard_0fbbf0() {}

// ---- CStatusBarItem ----
RVA(0x000e6d90, 0x8)
void CStatusBarItem::CStatusBarItem_0e6d90() {}
RVA(0x000e6e40, 0x17c)
void CStatusBarItem::CStatusBarItem_0e6e40() {}
RVA(0x000e80e0, 0x8c)
void CStatusBarItem::CStatusBarItem_0e80e0() {}
RVA(0x000e81a0, 0x8)
void CStatusBarItem::CStatusBarItem_0e81a0() {}
RVA(0x000e81e0, 0x8b)
void CStatusBarItem::CStatusBarItem_0e81e0() {}
RVA(0x000e82a0, 0x45)
void CStatusBarItem::CStatusBarItem_0e82a0() {}
RVA(0x000e8310, 0x112)
void CStatusBarItem::CStatusBarItem_0e8310() {}
RVA(0x000e8480, 0x4a)
void CStatusBarItem::CStatusBarItem_0e8480() {}
RVA(0x000e84f0, 0x16)
void CStatusBarItem::CStatusBarItem_0e84f0() {}
RVA(0x000e8520, 0x152)
void CStatusBarItem::CStatusBarItem_0e8520() {}
RVA(0x001005b0, 0x8)
void CStatusBarItem::CStatusBarItem_1005b0() {}
RVA(0x001007d0, 0x7f)
void CStatusBarItem::CStatusBarItem_1007d0() {}
RVA(0x0010bfc0, 0xe8)
void CStatusBarItem::CStatusBarItem_10bfc0() {}

// ---- CTeleporter ----
RVA(0x00010dd0, 0x44)
void CTeleporter::CTeleporter_010dd0() {}
RVA(0x000419e0, 0x81)
void CTeleporter::CTeleporter_0419e0() {}

// ---- CTileTriggerSwitch ----
RVA(0x000110f0, 0x44)
void CTileTriggerSwitch::CTileTriggerSwitch_0110f0() {}

// ---- CTileTriggerSwitchLogic ---- (leftover misattributed cluster) The block
// was 3 conflated classes; 9 of the 12 RVAs are now reconstructed in their real
// homes:
//   container (CTileTriggerContainer, src/Gruntz/TileTriggerContainer.cpp):
//     0xc8640 (~dtor, 100%), 116fa0 (RemoveAll, 100%), 117f60 (SetCell, ~78%),
//     116a40/116cf0 (AddTo* /GX-new walls, ~43/29%), 117630/117710
//     (SerializeApplyA/B switch-table walls, ~57/63%).
//   command   (CTileGridCommand, src/Gruntz/TileGridCommand.cpp):
//     112970 (Classify, ~96%), 112b70 (BumpCell, ~73%), 112590 (ApplyMove, ~70%).
// Two RVAs remain stubbed below (see each note).
// The remaining conflated outlier (a tile-trigger/switch object whose this+0x24
// is a CTileTriggerContainer back-pointer, walked then queried for grid commands)
// stays stubbed for the final sweep: it is NEITHER the command (its +0x24 is a
// game clock) NOR the container (its lists are at +0x1c/+0x38/+0x54, not +0x24).
RVA(0x00112c70, 0xc4)
void CTileTriggerSwitchLogic::CTileTriggerSwitchLogic_112c70() {}

// CTileTriggerContainer::SerializeWalk (0x117280, 748 B, /GX): the big serialize
// driver that walks all three lists, streams each element's count, and applies
// SerializeApplyA/B per element (its tag-dispatched helpers 117630/117710 ARE
// reconstructed in src/Gruntz/TileTriggerContainer.cpp).  Deferred for the final
// sweep (>512 B EH; would under-count + diverge its regalloc if half-reconstructed).
RVA(0x00117280, 0x2ec)
void CTileTriggerSwitchLogic::CTileTriggerSwitchLogic_117280() {}

// ---- CTileTriggerTransition ----
RVA(0x00011730, 0x6)
void CTileTriggerTransition::CTileTriggerTransition_011730() {}
RVA(0x000117f0, 0x44)
void CTileTriggerTransition::CTileTriggerTransition_0117f0() {}
RVA(0x00110070, 0x71)
void CTileTriggerTransition::CTileTriggerTransition_110070() {}

// ---- CToobSpikez ----
RVA(0x00012c60, 0x44)
void CToobSpikez::CToobSpikez_012c60() {}
RVA(0x00114860, 0x102)
void CToobSpikez::CToobSpikez_114860() {}

// ---- CGrunt (migration in progress; see src/Gruntz/Grunt.cpp) ----
RVA(0x0000f2f0, 0xc8)
void CUserLogic::CUserLogic_00f2f0() {}
// 0x04ac10 -> CGrunt::PlaySound (src/Gruntz/Grunt.cpp)
// 0x04b370 -> CGrunt::StepArrivalDrop (src/Gruntz/Grunt.cpp)
// 0x04c170 -> CGrunt::StepGruntMovement (src/Gruntz/Grunt.cpp)
// 0x051850 -> CGrunt::RectContains (src/Gruntz/Grunt.cpp)
// 0x051a20 -> CGrunt::RectContainsGated (src/Gruntz/Grunt.cpp)
// 0x052fb0 -> CGrunt::StepAnimDispatchA (src/Gruntz/Grunt.cpp)
RVA(0x00053b80, 0x340)
void CUserLogic::CUserLogic_053b80() {}
RVA(0x00059230, 0x40d)
void CUserLogic::CUserLogic_059230() {}
RVA(0x0005caa0, 0x5e4)
void CUserLogic::CUserLogic_05caa0() {}
// 0x05f310 -> CGrunt::StepCoordResolve (src/Gruntz/Grunt.cpp)
RVA(0x00062110, 0x5bc)
void CUserLogic::CUserLogic_062110() {}
RVA(0x000637a0, 0x2f8)
void CUserLogic::CUserLogic_0637a0() {}
RVA(0x00067850, 0x214)
void CUserLogic::CUserLogic_067850() {}
// 0x06a6d0 -> CGrunt::StepAnimDispatchB (src/Gruntz/Grunt.cpp)
RVA(0x0016e7f0, 0x1cf)
void CUserLogic::CUserLogic_16e7f0() {}
RVA(0x0016ea90, 0x234)
void CUserLogic::CUserLogic_16ea90() {}

// ---- CVoiceTrigger ----
RVA(0x000135a0, 0x44)
void CVoiceTrigger::CVoiceTrigger_0135a0() {}
RVA(0x0011a700, 0xae)
void CVoiceTrigger::CVoiceTrigger_11a700() {}

// ---- CWayPoint ----
RVA(0x000102e0, 0x44)
void CWayPoint::CWayPoint_0102e0() {}

// ---- CWormhole ----
RVA(0x00010980, 0x44)
void CWormhole::CWormhole_010980() {}
RVA(0x000403b0, 0xa5)
void CWormhole::CWormhole_0403b0() {}

// ---- ClassUnknown_1 ----
RVA(0x00134be0, 0x7e)
void ClassUnknown_1::ClassUnknown_1_134be0() {}
RVA(0x00134c60, 0x14)
void ClassUnknown_1::ClassUnknown_1_134c60() {}
RVA(0x00134c80, 0x24)
void ClassUnknown_1::ClassUnknown_1_134c80() {}

// ---- ClassUnknown_10 ----
RVA(0x000e2250, 0x26)
void ClassUnknown_10::ClassUnknown_10_0e2250() {}
RVA(0x000e2290, 0x2a)
void ClassUnknown_10::ClassUnknown_10_0e2290() {}
RVA(0x000e22d0, 0x6e)
void ClassUnknown_10::ClassUnknown_10_0e22d0() {}
RVA(0x000e2360, 0x15)
void ClassUnknown_10::ClassUnknown_10_0e2360() {}
RVA(0x000e2390, 0x15)
void ClassUnknown_10::ClassUnknown_10_0e2390() {}
RVA(0x000e23c0, 0x2d)
void ClassUnknown_10::ClassUnknown_10_0e23c0() {}
RVA(0x000e2890, 0xb6)
void ClassUnknown_10::ClassUnknown_10_0e2890() {}

// ---- ClassUnknown_100 ----
RVA(0x00109bb0, 0xb)
void ClassUnknown_100::ClassUnknown_100_109bb0() {}
RVA(0x0010a0f0, 0x184)
void ClassUnknown_100::ClassUnknown_100_10a0f0() {}
RVA(0x0010a2f0, 0x35)
void ClassUnknown_100::ClassUnknown_100_10a2f0() {}

// ---- ClassUnknown_101 ----
RVA(0x0011f6b9, 0x17)
void ClassUnknown_101::ClassUnknown_101_11f6b9() {}

// ---- ClassUnknown_102 ----
RVA(0x0006b2e0, 0x39)
void ClassUnknown_102::ClassUnknown_102_06b2e0() {}

// ---- ClassUnknown_103 ----
RVA(0x00148d10, 0x25)
void ClassUnknown_103::ClassUnknown_103_148d10() {}

// ---- ClassUnknown_104 ----
RVA(0x00152e30, 0x53)
void ClassUnknown_104::ClassUnknown_104_152e30() {}
RVA(0x00165730, 0x4c)
void ClassUnknown_104::ClassUnknown_104_165730() {}

// ---- ClassUnknown_105 ----
RVA(0x001657a0, 0x66)
void ClassUnknown_105::ClassUnknown_105_1657a0() {}

// ---- ClassUnknown_106 ----
RVA(0x000af0a0, 0xf4)
void ClassUnknown_106::ClassUnknown_106_0af0a0() {}

// ---- ClassUnknown_107 ----
RVA(0x0010d3d0, 0xf1)
void ClassUnknown_107::ClassUnknown_107_10d3d0() {}

// ---- ClassUnknown_108 ----
RVA(0x00112d80, 0xa)
void ClassUnknown_108::ClassUnknown_108_112d80() {}
RVA(0x00112da0, 0x9e)
void ClassUnknown_108::ClassUnknown_108_112da0() {}
RVA(0x00112ee0, 0x35e)
void ClassUnknown_108::ClassUnknown_108_112ee0() {}
RVA(0x00113f10, 0x3b)
void ClassUnknown_108::ClassUnknown_108_113f10() {}
RVA(0x00113f60, 0xa2)
void ClassUnknown_108::ClassUnknown_108_113f60() {}

// ---- ClassUnknown_109 ----
RVA(0x000aa960, 0xf1)
void ClassUnknown_109::ClassUnknown_109_0aa960() {}

// ---- ClassUnknown_11 ----
RVA(0x0013abc0, 0x13f)
void ClassUnknown_11::ClassUnknown_11_13abc0() {}
RVA(0x0013b850, 0xa8)
void ClassUnknown_11::ClassUnknown_11_13b850() {}
RVA(0x0013bff0, 0x19)
void ClassUnknown_11::ClassUnknown_11_13bff0() {}
RVA(0x0013c030, 0x14)
void ClassUnknown_11::ClassUnknown_11_13c030() {}
RVA(0x0013c210, 0x1a)
void ClassUnknown_11::ClassUnknown_11_13c210() {}

// ---- ClassUnknown_110 ----
RVA(0x000fb660, 0xf1)
void ClassUnknown_110::ClassUnknown_110_0fb660() {}

// ---- ClassUnknown_111 ----
RVA(0x00029a80, 0x29)
void ClassUnknown_111::ClassUnknown_111_029a80() {}

// ---- ClassUnknown_112 ----
RVA(0x00021c40, 0x8)
void ClassUnknown_112::ClassUnknown_112_021c40() {}

// ---- ClassUnknown_113 ----
RVA(0x00114480, 0xf1)
void ClassUnknown_113::ClassUnknown_113_114480() {}

// ---- ClassUnknown_114 ----
RVA(0x000e6380, 0xf9)
void ClassUnknown_114::ClassUnknown_114_0e6380() {}
RVA(0x00104bb0, 0x94)
void ClassUnknown_114::ClassUnknown_114_104bb0() {}

// ---- ClassUnknown_115 ----
RVA(0x000e8c70, 0xc)
void ClassUnknown_115::ClassUnknown_115_0e8c70() {}
RVA(0x000e8cb0, 0xc4)
void ClassUnknown_115::ClassUnknown_115_0e8cb0() {}
RVA(0x000e8dc0, 0x22)
void ClassUnknown_115::ClassUnknown_115_0e8dc0() {}
RVA(0x00104ce0, 0x55)
void ClassUnknown_115::ClassUnknown_115_104ce0() {}

// ---- ClassUnknown_116 ----
RVA(0x000e7980, 0x109)
void ClassUnknown_116::ClassUnknown_116_0e7980() {}
RVA(0x000e7b00, 0xe1)
void ClassUnknown_116::ClassUnknown_116_0e7b00() {}
RVA(0x000ea0f0, 0x5c)
void ClassUnknown_116::ClassUnknown_116_0ea0f0() {}
RVA(0x001047f0, 0x94)
void ClassUnknown_116::ClassUnknown_116_1047f0() {}
RVA(0x001048f0, 0xa9)
void ClassUnknown_116::ClassUnknown_116_1048f0() {}

// ---- ClassUnknown_117 ----
RVA(0x000ea470, 0x24)
void ClassUnknown_117::ClassUnknown_117_0ea470() {}
RVA(0x000ea4b0, 0x1c)
void ClassUnknown_117::ClassUnknown_117_0ea4b0() {}
RVA(0x000ea6c0, 0x237)
void ClassUnknown_117::ClassUnknown_117_0ea6c0() {}
RVA(0x00104b00, 0x55)
void ClassUnknown_117::ClassUnknown_117_104b00() {}

// ---- ClassUnknown_118 ----
RVA(0x000eb6b0, 0x67)
void ClassUnknown_118::ClassUnknown_118_0eb6b0() {}
RVA(0x000eb740, 0xb3)
void ClassUnknown_118::ClassUnknown_118_0eb740() {}
RVA(0x000eb830, 0x31)
void ClassUnknown_118::ClassUnknown_118_0eb830() {}
RVA(0x000eb880, 0xbd)
void ClassUnknown_118::ClassUnknown_118_0eb880() {}
RVA(0x00104a00, 0x94)
void ClassUnknown_118::ClassUnknown_118_104a00() {}

// ---- ClassUnknown_119 ----
RVA(0x001591b0, 0x19)
void ClassUnknown_119::ClassUnknown_119_1591b0() {}

// ---- ClassUnknown_12 ----
RVA(0x00139ee0, 0x11e)
void ClassUnknown_12::ClassUnknown_12_139ee0() {}
RVA(0x0013a230, 0x29)
void ClassUnknown_12::ClassUnknown_12_13a230() {}
RVA(0x0013bae0, 0x1b9)
void ClassUnknown_12::ClassUnknown_12_13bae0() {}
RVA(0x0013be40, 0x1ac)
void ClassUnknown_12::ClassUnknown_12_13be40() {}

// ---- ClassUnknown_120 ----
RVA(0x001852e0, 0x35)
void ClassUnknown_120::ClassUnknown_120_1852e0() {}

// ---- ClassUnknown_121 ----
RVA(0x00139cf0, 0xd7)
void ClassUnknown_121::ClassUnknown_121_139cf0() {}

// ---- ClassUnknown_122 ----
RVA(0x001397a0, 0x57)
void ClassUnknown_122::ClassUnknown_122_1397a0() {}

// ---- ClassUnknown_123 ----
RVA(0x0016dfc0, 0x7)
void ClassUnknown_123::ClassUnknown_123_16dfc0() {}

// ---- ClassUnknown_124 ----
RVA(0x0011eaf5, 0x7)
void ClassUnknown_124::ClassUnknown_124_11eaf5() {}

// ---- ClassUnknown_125 ----
RVA(0x0011eaa8, 0x7)
void ClassUnknown_125::ClassUnknown_125_11eaa8() {}

// ---- ClassUnknown_126 ----
RVA(0x0011cf30, 0x7)
void ClassUnknown_126::ClassUnknown_126_11cf30() {}

// ---- ClassUnknown_127 ----
RVA(0x0011cee3, 0x7)
void ClassUnknown_127::ClassUnknown_127_11cee3() {}

// ---- ClassUnknown_128 ----
RVA(0x00174d70, 0x70)
void ClassUnknown_128::ClassUnknown_128_174d70() {}

// ---- ClassUnknown_129 ----
RVA(0x00016460, 0x46)
void ClassUnknown_129::ClassUnknown_129_016460() {}

// ---- ClassUnknown_13 ----
RVA(0x0013c240, 0x29)
void ClassUnknown_13::ClassUnknown_13_13c240() {}
RVA(0x0013c270, 0xca)
void ClassUnknown_13::ClassUnknown_13_13c270() {}
RVA(0x0013c350, 0xd)
void ClassUnknown_13::ClassUnknown_13_13c350() {}
RVA(0x0013c360, 0x47)
void ClassUnknown_13::ClassUnknown_13_13c360() {}
RVA(0x0013c3c0, 0x29)
void ClassUnknown_13::ClassUnknown_13_13c3c0() {}
RVA(0x0013c3f0, 0xca)
void ClassUnknown_13::ClassUnknown_13_13c3f0() {}
RVA(0x00184a40, 0x27)
void ClassUnknown_13::ClassUnknown_13_184a40() {}
RVA(0x00184ab0, 0x25)
void ClassUnknown_13::ClassUnknown_13_184ab0() {}
RVA(0x00184b40, 0x1d)
void ClassUnknown_13::ClassUnknown_13_184b40() {}

// ---- ClassUnknown_14 ----
RVA(0x0013a000, 0x37)
void ClassUnknown_14::ClassUnknown_14_13a000() {}

// ---- ClassUnknown_15 ----
RVA(0x0013c520, 0xe)
void ClassUnknown_15::ClassUnknown_15_13c520() {}
RVA(0x0013c590, 0x66)
void ClassUnknown_15::ClassUnknown_15_13c590() {}
RVA(0x0013c600, 0xbd)
void ClassUnknown_15::ClassUnknown_15_13c600() {}
RVA(0x0013c830, 0x63)
void ClassUnknown_15::ClassUnknown_15_13c830() {}

// ---- ClassUnknown_16 ----
RVA(0x00021280, 0x10)
void ClassUnknown_16::ClassUnknown_16_021280() {}
RVA(0x00169160, 0xbc)
void ClassUnknown_16::ClassUnknown_16_169160() {}
RVA(0x00169220, 0x6c)
void ClassUnknown_16::ClassUnknown_16_169220() {}
RVA(0x001692b0, 0xb)
void ClassUnknown_16::ClassUnknown_16_1692b0() {}
RVA(0x00169490, 0x49)
void ClassUnknown_16::ClassUnknown_16_169490() {}
RVA(0x0016b070, 0x42)
void ClassUnknown_16::ClassUnknown_16_16b070() {}
RVA(0x0016b150, 0x35)
void ClassUnknown_16::ClassUnknown_16_16b150() {}
RVA(0x0016b1d0, 0x58)
void ClassUnknown_16::ClassUnknown_16_16b1d0() {}
RVA(0x0016b320, 0x1b)
void ClassUnknown_16::ClassUnknown_16_16b320() {}
RVA(0x0016b3a0, 0x33)
void ClassUnknown_16::ClassUnknown_16_16b3a0() {}
RVA(0x0016cd00, 0x4b)
void ClassUnknown_16::ClassUnknown_16_16cd00() {}

// ---- ClassUnknown_17 ----
RVA(0x0016f6c0, 0x12)
void ClassUnknown_17::ClassUnknown_17_16f6c0() {}
RVA(0x0016f760, 0x82)
void ClassUnknown_17::ClassUnknown_17_16f760() {}
RVA(0x00170100, 0x104)
void ClassUnknown_17::ClassUnknown_17_170100() {}

// ---- ClassUnknown_18 ----
RVA(0x0016f7f0, 0x47b)
void ClassUnknown_18::ClassUnknown_18_16f7f0() {}

// ---- ClassUnknown_19 ----
RVA(0x0016fc70, 0x48e)
void ClassUnknown_19::ClassUnknown_19_16fc70() {}

// ---- ClassUnknown_2 ---- reconstructed as the DDrawMgr color/shade lookup-
// table cache CShadeTableCache in src/DDrawMgr/ShadeTableCache.cpp (a CGruntzMgr
// member). The ctor/dtor/Init/FreeNodes/FindRemove + two integer-loop builders
// (GreyTable 0x14eef0, AlphaTable 0x14f5b0) are reconstructed there. The two
// remaining builders below are large float-curve generators (__ftol + nested
// fcom/fnstsw-clamped loops on a /GX EH frame this recompile can't emit -
// rezalloc-placement-new-no-eh-frame.md); deferred to the final sweep.
RVA(0x0014f080, 0x283)
void ClassUnknown_2::ClassUnknown_2_14f080() {}
RVA(0x0014f310, 0x297)
void ClassUnknown_2::ClassUnknown_2_14f310() {}

// ---- ClassUnknown_20 ----
RVA(0x0016df70, 0x22)
void ClassUnknown_20::ClassUnknown_20_16df70() {}

// ---- ClassUnknown_21 ----
RVA(0x0016e480, 0x3e)
void ClassUnknown_21::ClassUnknown_21_16e480() {}

// ---- ClassUnknown_22 ----
RVA(0x00022b00, 0xaf)
void ClassUnknown_22::ClassUnknown_22_022b00() {}
RVA(0x00022be0, 0x71)
void ClassUnknown_22::ClassUnknown_22_022be0() {}
RVA(0x00022c80, 0x173)
void ClassUnknown_22::ClassUnknown_22_022c80() {}
RVA(0x00085e60, 0x4a)
void ClassUnknown_22::ClassUnknown_22_085e60() {}

// ---- ClassUnknown_24 ----
RVA(0x00085df0, 0x4a)
void ClassUnknown_24::ClassUnknown_24_085df0() {}
RVA(0x0011adc0, 0x44)
void ClassUnknown_24::ClassUnknown_24_11adc0() {}
RVA(0x0011ae30, 0x95)
void ClassUnknown_24::ClassUnknown_24_11ae30() {}
RVA(0x0011af00, 0x62)
void ClassUnknown_24::ClassUnknown_24_11af00() {}
RVA(0x0011af90, 0xb)
void ClassUnknown_24::ClassUnknown_24_11af90() {}
RVA(0x0011bba0, 0x1f4)
void ClassUnknown_24::ClassUnknown_24_11bba0() {}
RVA(0x0011bee0, 0x230)
void ClassUnknown_24::ClassUnknown_24_11bee0() {}
RVA(0x0011c1a0, 0x46)
void ClassUnknown_24::ClassUnknown_24_11c1a0() {}
RVA(0x0011c7b0, 0x2d)
void ClassUnknown_24::ClassUnknown_24_11c7b0() {}
RVA(0x0011c830, 0x12)
void ClassUnknown_24::ClassUnknown_24_11c830() {}

// ---- ClassUnknown_25 ----
RVA(0x00099ca0, 0x49)
void ClassUnknown_25::ClassUnknown_25_099ca0() {}
RVA(0x0009a450, 0x36)
void ClassUnknown_25::ClassUnknown_25_09a450() {}
RVA(0x0011c560, 0x91)
void ClassUnknown_25::ClassUnknown_25_11c560() {}

// ---- ClassUnknown_26 ----
RVA(0x0011c630, 0x6e)
void ClassUnknown_26::ClassUnknown_26_11c630() {}

// ---- ClassUnknown_27 ----
RVA(0x0013a260, 0x11)
void ClassUnknown_27::ClassUnknown_27_13a260() {}
RVA(0x0013a280, 0x19)
void ClassUnknown_27::ClassUnknown_27_13a280() {}
RVA(0x0013a2b0, 0x11)
void ClassUnknown_27::ClassUnknown_27_13a2b0() {}
RVA(0x0013a2d0, 0x19)
void ClassUnknown_27::ClassUnknown_27_13a2d0() {}
RVA(0x0013a2f0, 0x19)
void ClassUnknown_27::ClassUnknown_27_13a2f0() {}
RVA(0x0013a310, 0x19)
void ClassUnknown_27::ClassUnknown_27_13a310() {}

// ---- ClassUnknown_28 ----
RVA(0x0001f940, 0x4c)
void ClassUnknown_28::ClassUnknown_28_01f940() {}
RVA(0x00158760, 0x59)
void ClassUnknown_28::ClassUnknown_28_158760() {}

// ---- ClassUnknown_29 ----
RVA(0x00137110, 0x8d)
void ClassUnknown_29::ClassUnknown_29_137110() {}

// ---- ClassUnknown_3 ----
RVA(0x0009dad0, 0x14a)
void ClassUnknown_3::ClassUnknown_3_09dad0() {}
RVA(0x0009dc80, 0x1d)
void ClassUnknown_3::ClassUnknown_3_09dc80() {}
RVA(0x0009dcb0, 0x41)
void ClassUnknown_3::ClassUnknown_3_09dcb0() {}

// ---- ClassUnknown_30 ----
RVA(0x00136f60, 0x74)
void ClassUnknown_30::ClassUnknown_30_136f60() {}
RVA(0x001390e0, 0x25)
void ClassUnknown_30::ClassUnknown_30_1390e0() {}
RVA(0x00139110, 0x27)
void ClassUnknown_30::ClassUnknown_30_139110() {}
RVA(0x001391e0, 0x30)
void ClassUnknown_30::ClassUnknown_30_1391e0() {}

// ---- ClassUnknown_31 ----
RVA(0x00152f20, 0x86)
void ClassUnknown_31::ClassUnknown_31_152f20() {}
RVA(0x00152fb0, 0x123)
void ClassUnknown_31::ClassUnknown_31_152fb0() {}
RVA(0x00153810, 0x95)
void ClassUnknown_31::ClassUnknown_31_153810() {}

// ---- ClassUnknown_32 ----
RVA(0x00141d50, 0x6f)
void ClassUnknown_32::ClassUnknown_32_141d50() {}
RVA(0x00142060, 0x9d)
void ClassUnknown_32::ClassUnknown_32_142060() {}
RVA(0x00142100, 0x18)
void ClassUnknown_32::ClassUnknown_32_142100() {}
RVA(0x00142120, 0x31)
void ClassUnknown_32::ClassUnknown_32_142120() {}
RVA(0x00142160, 0x24)
void ClassUnknown_32::ClassUnknown_32_142160() {}
RVA(0x00142260, 0xd2)
void ClassUnknown_32::ClassUnknown_32_142260() {}
RVA(0x001423c0, 0xd2)
void ClassUnknown_32::ClassUnknown_32_1423c0() {}
RVA(0x00142e60, 0x27)
void ClassUnknown_32::ClassUnknown_32_142e60() {}
RVA(0x00142eb0, 0x17)
void ClassUnknown_32::ClassUnknown_32_142eb0() {}
RVA(0x00142ed0, 0x3d)
void ClassUnknown_32::ClassUnknown_32_142ed0() {}
RVA(0x00142f10, 0x2b)
void ClassUnknown_32::ClassUnknown_32_142f10() {}
RVA(0x00142fc0, 0x7c)
void ClassUnknown_32::ClassUnknown_32_142fc0() {}

// ---- ClassUnknown_33 ----
RVA(0x00153180, 0xda)
void ClassUnknown_33::ClassUnknown_33_153180() {}

// ---- ClassUnknown_34 ----
RVA(0x00148ce0, 0x2f)
void ClassUnknown_34::ClassUnknown_34_148ce0() {}
RVA(0x001490d0, 0x173)
void ClassUnknown_34::ClassUnknown_34_1490d0() {}

// ---- ClassUnknown_35 ----
RVA(0x00151eb0, 0x43)
void ClassUnknown_35::ClassUnknown_35_151eb0() {}
RVA(0x001557a0, 0x68)
void ClassUnknown_35::ClassUnknown_35_1557a0() {}

// ---- ClassUnknown_36 ----
RVA(0x0014dd90, 0x74)
void ClassUnknown_36::ClassUnknown_36_14dd90() {}

// ---- ClassUnknown_37 ----
RVA(0x0006b2a0, 0x23)
void ClassUnknown_37::ClassUnknown_37_06b2a0() {}
RVA(0x00152720, 0xa2)
void ClassUnknown_37::ClassUnknown_37_152720() {}
RVA(0x001527d0, 0xf8)
void ClassUnknown_37::ClassUnknown_37_1527d0() {}
RVA(0x001528d0, 0xdd)
void ClassUnknown_37::ClassUnknown_37_1528d0() {}
RVA(0x00152ad0, 0x17f)
void ClassUnknown_37::ClassUnknown_37_152ad0() {}
RVA(0x00152c50, 0xdc)
void ClassUnknown_37::ClassUnknown_37_152c50() {}
RVA(0x00152d30, 0xd4)
void ClassUnknown_37::ClassUnknown_37_152d30() {}
RVA(0x001577e0, 0x68)
void ClassUnknown_37::ClassUnknown_37_1577e0() {}

// ---- ClassUnknown_38 ----
RVA(0x0006b270, 0x1b)
void ClassUnknown_38::ClassUnknown_38_06b270() {}
RVA(0x00165460, 0x156)
void ClassUnknown_38::ClassUnknown_38_165460() {}
RVA(0x001655c0, 0x53)
void ClassUnknown_38::ClassUnknown_38_1655c0() {}

// ---- ClassUnknown_39 ----
RVA(0x00168c60, 0xa0)
void ClassUnknown_39::ClassUnknown_39_168c60() {}
RVA(0x00168e50, 0x1e)
void ClassUnknown_39::ClassUnknown_39_168e50() {}

// ---- ClassUnknown_4 ----
RVA(0x00150180, 0xd)
void ClassUnknown_4::ClassUnknown_4_150180() {}
RVA(0x00150190, 0xb)
void ClassUnknown_4::ClassUnknown_4_150190() {}
RVA(0x001501a0, 0x44)
void ClassUnknown_4::ClassUnknown_4_1501a0() {}
RVA(0x001503c0, 0x2e)
void ClassUnknown_4::ClassUnknown_4_1503c0() {}

// ---- ClassUnknown_40 ----
RVA(0x00168d00, 0x14c)
void ClassUnknown_40::ClassUnknown_40_168d00() {}

// ---- ClassUnknown_41 ----
RVA(0x00165dd0, 0x5b)
void ClassUnknown_41::ClassUnknown_41_165dd0() {}
RVA(0x00168ee0, 0x40)
void ClassUnknown_41::ClassUnknown_41_168ee0() {}
RVA(0x00168fb0, 0x1f)
void ClassUnknown_41::ClassUnknown_41_168fb0() {}

// ---- ClassUnknown_42 ----
RVA(0x000e2df0, 0x39f)
void ClassUnknown_42::ClassUnknown_42_0e2df0() {}
RVA(0x000e32e0, 0x25)
void ClassUnknown_42::ClassUnknown_42_0e32e0() {}

// ---- ClassUnknown_43 ----
RVA(0x0013e4d0, 0x7e)
void ClassUnknown_43::ClassUnknown_43_13e4d0() {}
RVA(0x0013edb0, 0x78)
void ClassUnknown_43::ClassUnknown_43_13edb0() {}
RVA(0x0013f910, 0x4a)
void ClassUnknown_43::ClassUnknown_43_13f910() {}
RVA(0x00142360, 0x53)
void ClassUnknown_43::ClassUnknown_43_142360() {}
RVA(0x00144350, 0x5f)
void ClassUnknown_43::ClassUnknown_43_144350() {}
RVA(0x00144640, 0x2be)
void ClassUnknown_43::ClassUnknown_43_144640() {}
RVA(0x00148840, 0x47)
void ClassUnknown_43::ClassUnknown_43_148840() {}

// ---- ClassUnknown_44 ----
RVA(0x00158680, 0x5b)
void ClassUnknown_44::ClassUnknown_44_158680() {}
RVA(0x001587c0, 0x23)
void ClassUnknown_44::ClassUnknown_44_1587c0() {}

// ---- ClassUnknown_45 ----  RECOVERED -> CMenuPage (src/Gruntz/MenuPage.cpp).
// The named menu/list page node (3 CStrings + a CPtrList of child items + focus
// navigation), built by the main-menu builder (0xa11d0) and driven by the menu
// host (0x182ab0). All 22 methods reconstructed in MenuPage.cpp. The child-item
// class recovered -> CMenuItem (src/Gruntz/MenuItem.cpp).

// ---- ClassUnknown_47 ----
RVA(0x000f9280, 0xe4)
void ClassUnknown_47::ClassUnknown_47_0f9280() {}
RVA(0x0017e7b0, 0x9)
void ClassUnknown_47::ClassUnknown_47_17e7b0() {}
RVA(0x0017e880, 0x28)
void ClassUnknown_47::ClassUnknown_47_17e880() {}

// ---- ClassUnknown_48 ----
RVA(0x0017d910, 0x65)
void ClassUnknown_48::ClassUnknown_48_17d910() {}
RVA(0x0017d9a0, 0x11)
void ClassUnknown_48::ClassUnknown_48_17d9a0() {}
RVA(0x0017d9c0, 0x786)
void ClassUnknown_48::ClassUnknown_48_17d9c0() {}
RVA(0x0017e170, 0x5b)
void ClassUnknown_48::ClassUnknown_48_17e170() {}
RVA(0x0017e1d0, 0x4d)
void ClassUnknown_48::ClassUnknown_48_17e1d0() {}

// ---- ClassUnknown_49 ----
RVA(0x00182940, 0x13c)
void ClassUnknown_49::ClassUnknown_49_182940() {}
RVA(0x00182a80, 0x2e)
void ClassUnknown_49::ClassUnknown_49_182a80() {}

// ---- ClassUnknown_5 ----
RVA(0x00150040, 0x136)
void ClassUnknown_5::ClassUnknown_5_150040() {}

// ---- ClassUnknown_50 ----
RVA(0x000d5e80, 0x5b)
void ClassUnknown_50::ClassUnknown_50_0d5e80() {}
RVA(0x00153260, 0x41)
void ClassUnknown_50::ClassUnknown_50_153260() {}
RVA(0x00153790, 0x6a)
void ClassUnknown_50::ClassUnknown_50_153790() {}

// ---- ClassUnknown_51 ----
RVA(0x001154b0, 0x45)
void ClassUnknown_51::ClassUnknown_51_1154b0() {}

// ---- ClassUnknown_52 (== FontRenderer, see src/Font/Font.cpp) ----
// ---- ClassUnknown_53 ----
RVA(0x00029ac0, 0x20)
void ClassUnknown_53::ClassUnknown_53_029ac0() {}

// ---- ClassUnknown_54 ----
RVA(0x00135110, 0x8e)
void ClassUnknown_54::ClassUnknown_54_135110() {}

// ---- ClassUnknown_55 ----
RVA(0x00137060, 0x6b)
void ClassUnknown_55::ClassUnknown_55_137060() {}
RVA(0x001370d0, 0x38)
void ClassUnknown_55::ClassUnknown_55_1370d0() {}

// ---- ClassUnknown_56 ----
RVA(0x0008c3b0, 0x10)
void ClassUnknown_56::ClassUnknown_56_08c3b0() {}

// ---- ClassUnknown_57 ----
RVA(0x0003a1d0, 0x1d)
void ClassUnknown_57::ClassUnknown_57_03a1d0() {}
RVA(0x001590f0, 0x56)
void ClassUnknown_57::ClassUnknown_57_1590f0() {}
RVA(0x00163e20, 0x2d)
void ClassUnknown_57::ClassUnknown_57_163e20() {}
RVA(0x00163f40, 0x23e)
void ClassUnknown_57::ClassUnknown_57_163f40() {}

// ---- ClassUnknown_58 ----
RVA(0x000204e0, 0x19)
void ClassUnknown_58::ClassUnknown_58_0204e0() {}
RVA(0x00020510, 0x8)
void ClassUnknown_58::ClassUnknown_58_020510() {}
RVA(0x00020530, 0x61)
void ClassUnknown_58::ClassUnknown_58_020530() {}
RVA(0x00021140, 0xda)
void ClassUnknown_58::ClassUnknown_58_021140() {}

// ---- ClassUnknown_59 ----
RVA(0x000e6c80, 0xc3)
void ClassUnknown_59::ClassUnknown_59_0e6c80() {}
RVA(0x000e74f0, 0x152)
void ClassUnknown_59::ClassUnknown_59_0e74f0() {}
RVA(0x000e86e0, 0x53)
void ClassUnknown_59::ClassUnknown_59_0e86e0() {}
RVA(0x000e9800, 0x9)
void ClassUnknown_59::ClassUnknown_59_0e9800() {}
RVA(0x000e9820, 0x11)
void ClassUnknown_59::ClassUnknown_59_0e9820() {}
RVA(0x000e99c0, 0x4c)
void ClassUnknown_59::ClassUnknown_59_0e99c0() {}
RVA(0x00100700, 0x55)
void ClassUnknown_59::ClassUnknown_59_100700() {}
RVA(0x00100870, 0x6a)
void ClassUnknown_59::ClassUnknown_59_100870() {}
RVA(0x00105200, 0x55)
void ClassUnknown_59::ClassUnknown_59_105200() {}

// ---- ClassUnknown_6 ----
RVA(0x0014dcf0, 0x69)
void ClassUnknown_6::ClassUnknown_6_14dcf0() {}

// ---- ClassUnknown_60 ----
RVA(0x000ebd30, 0x21)
void ClassUnknown_60::ClassUnknown_60_0ebd30() {}

// ---- ClassUnknown_61 ----
RVA(0x00120120, 0xbc)
void ClassUnknown_61::ClassUnknown_61_120120() {}
RVA(0x0017b500, 0x8)
void ClassUnknown_61::ClassUnknown_61_17b500() {}

// ---- ClassUnknown_62 ----
RVA(0x00099c20, 0x5f)
void ClassUnknown_62::ClassUnknown_62_099c20() {}
RVA(0x00099d40, 0x21c)
void ClassUnknown_62::ClassUnknown_62_099d40() {}
RVA(0x0009a0b0, 0x7)
void ClassUnknown_62::ClassUnknown_62_09a0b0() {}
RVA(0x0009b430, 0x49)
void ClassUnknown_62::ClassUnknown_62_09b430() {}

// ---- ClassUnknown_63 ----
RVA(0x001682f0, 0x4a)
void ClassUnknown_63::ClassUnknown_63_1682f0() {}
RVA(0x00168340, 0xe1)
void ClassUnknown_63::ClassUnknown_63_168340() {}
RVA(0x00168430, 0x2e)
void ClassUnknown_63::ClassUnknown_63_168430() {}
RVA(0x00168460, 0x95)
void ClassUnknown_63::ClassUnknown_63_168460() {}
RVA(0x00168500, 0x3af)
void ClassUnknown_63::ClassUnknown_63_168500() {}
RVA(0x001688b0, 0x40)
void ClassUnknown_63::ClassUnknown_63_1688b0() {}
RVA(0x001688f0, 0x6d)
void ClassUnknown_63::ClassUnknown_63_1688f0() {}

// ---- ClassUnknown_64 ----
RVA(0x001682a0, 0x46)
void ClassUnknown_64::ClassUnknown_64_1682a0() {}
RVA(0x001915c0, 0x15d)
void ClassUnknown_64::ClassUnknown_64_1915c0() {}
RVA(0x00191800, 0x39)
void ClassUnknown_64::ClassUnknown_64_191800() {}
RVA(0x00191840, 0x48)
void ClassUnknown_64::ClassUnknown_64_191840() {}
RVA(0x00191890, 0x24)
void ClassUnknown_64::ClassUnknown_64_191890() {}
RVA(0x001918c0, 0x1a2)
void ClassUnknown_64::ClassUnknown_64_1918c0() {}
RVA(0x00191a70, 0x57)
void ClassUnknown_64::ClassUnknown_64_191a70() {}

// ---- ClassUnknown_65 ----
RVA(0x00095750, 0xf4)
void ClassUnknown_65::ClassUnknown_65_095750() {}
RVA(0x00095890, 0xf1)
void ClassUnknown_65::ClassUnknown_65_095890() {}
RVA(0x000aa6e0, 0xf1)
void ClassUnknown_65::ClassUnknown_65_0aa6e0() {}
RVA(0x00151da0, 0x80)
void ClassUnknown_65::ClassUnknown_65_151da0() {}
RVA(0x00151e20, 0x46)
void ClassUnknown_65::ClassUnknown_65_151e20() {}
RVA(0x0015b340, 0x2b)
void ClassUnknown_65::ClassUnknown_65_15b340() {}
RVA(0x00164830, 0xd3)
void ClassUnknown_65::ClassUnknown_65_164830() {}
RVA(0x00164960, 0x41a)
void ClassUnknown_65::ClassUnknown_65_164960() {}

// ---- ClassUnknown_66 ----
RVA(0x00161370, 0x7)
void ClassUnknown_66::ClassUnknown_66_161370() {}
RVA(0x00166d40, 0x24)
void ClassUnknown_66::ClassUnknown_66_166d40() {}

// ---- ClassUnknown_67 ----
RVA(0x00191ad0, 0x34)
void ClassUnknown_67::ClassUnknown_67_191ad0() {}
RVA(0x00191b10, 0x111)
void ClassUnknown_67::ClassUnknown_67_191b10() {}
RVA(0x00191c30, 0xcc)
void ClassUnknown_67::ClassUnknown_67_191c30() {}

// ---- ClassUnknown_68 ----  (recovered: CLightFxRender, src/Gruntz/CLightFxRender.cpp)
// 0xa3b50 DrawBorder reconstructed in src/Gruntz/CLightFxRender.cpp.
// 0xa3460 Resize / 0xa3820 ComputeRect remain for the final sweep (per-pixel
// palette blit + idiv scale-clamp; coupled to BltEx/Lock surface layout).
RVA(0x000a3460, 0x2f3)
void ClassUnknown_68::ClassUnknown_68_0a3460() {}
RVA(0x000a3820, 0x18e)
void ClassUnknown_68::ClassUnknown_68_0a3820() {}

// ---- ClassUnknown_69 ----
RVA(0x00058b60, 0x2d)
void ClassUnknown_69::ClassUnknown_69_058b60() {}
RVA(0x0010d150, 0xf1)
void ClassUnknown_69::ClassUnknown_69_10d150() {}
RVA(0x001504d0, 0x6c)
void ClassUnknown_69::ClassUnknown_69_1504d0() {}
RVA(0x0015b2c0, 0x3d)
void ClassUnknown_69::ClassUnknown_69_15b2c0() {}

// ---- ClassUnknown_7 ----
RVA(0x000fc9c0, 0x17)
void ClassUnknown_7::ClassUnknown_7_0fc9c0() {}
RVA(0x000fca10, 0x8a)
void ClassUnknown_7::ClassUnknown_7_0fca10() {}
RVA(0x000fcad0, 0x53)
void ClassUnknown_7::ClassUnknown_7_0fcad0() {}
RVA(0x000fcb50, 0x2b)
void ClassUnknown_7::ClassUnknown_7_0fcb50() {}
RVA(0x000fcb90, 0x12)
void ClassUnknown_7::ClassUnknown_7_0fcb90() {}
RVA(0x000fcbc0, 0x3a)
void ClassUnknown_7::ClassUnknown_7_0fcbc0() {}
RVA(0x000fcc10, 0x2f)
void ClassUnknown_7::ClassUnknown_7_0fcc10() {}
RVA(0x000fcc50, 0x2a)
void ClassUnknown_7::ClassUnknown_7_0fcc50() {}
RVA(0x000fcc90, 0xf)
void ClassUnknown_7::ClassUnknown_7_0fcc90() {}
RVA(0x000fccb0, 0x21)
void ClassUnknown_7::ClassUnknown_7_0fccb0() {}
RVA(0x000fcd70, 0x61)
void ClassUnknown_7::ClassUnknown_7_0fcd70() {}
RVA(0x000fced0, 0x31)
void ClassUnknown_7::ClassUnknown_7_0fced0() {}
RVA(0x000fd330, 0x84)
void ClassUnknown_7::ClassUnknown_7_0fd330() {}
RVA(0x000fd3f0, 0x425)
void ClassUnknown_7::ClassUnknown_7_0fd3f0() {}

// ---- ClassUnknown_70 ----
RVA(0x0015b2b0, 0xe)
void ClassUnknown_70::ClassUnknown_70_15b2b0() {}

// ---- ClassUnknown_71 ----
RVA(0x0015b270, 0x11)
void ClassUnknown_71::ClassUnknown_71_15b270() {}

// ---- ClassUnknown_72 ----
RVA(0x0003d670, 0xf1)
void ClassUnknown_72::ClassUnknown_72_03d670() {}
RVA(0x0007db20, 0xf1)
void ClassUnknown_72::ClassUnknown_72_07db20() {}
RVA(0x0007dda0, 0xf1)
void ClassUnknown_72::ClassUnknown_72_07dda0() {}
RVA(0x0015b300, 0x40)
void ClassUnknown_72::ClassUnknown_72_15b300() {}

// ---- ClassUnknown_73 ----
RVA(0x0015b730, 0x2b)
void ClassUnknown_73::ClassUnknown_73_15b730() {}

// ---- ClassUnknown_74 ----
RVA(0x0016e360, 0x11a)
void ClassUnknown_74::ClassUnknown_74_16e360() {}

// ---- ClassUnknown_75 ----
RVA(0x000a9cc0, 0xf1)
void ClassUnknown_75::ClassUnknown_75_0a9cc0() {}

// ---- ClassUnknown_76 ----
RVA(0x000aa5a0, 0xf1)
void ClassUnknown_76::ClassUnknown_76_0aa5a0() {}

// ---- ClassUnknown_77 ----
// Recovered: CMotionState (the 3-axis kinematic subobject at CMovingLogic+0x38).
// The ctor/SetParams/SetZ are reconstructed in src/Gruntz/MotionState.cpp; only
// the big per-frame easing integrator Step (0x16ecd0) remains stubbed - a 1766 B
// hand-scheduled x87 routine, deferred to the final sweep (big-FP wall).
RVA(0x0016ecd0, 0x6e6)
void ClassUnknown_77::ClassUnknown_77_16ecd0() {}

// ---- ClassUnknown_78 ----
RVA(0x00008750, 0x15)
void ClassUnknown_78::ClassUnknown_78_008750() {}
RVA(0x000310f0, 0x8d)
void ClassUnknown_78::ClassUnknown_78_0310f0() {}
RVA(0x000312a0, 0x74)
void ClassUnknown_78::ClassUnknown_78_0312a0() {}
RVA(0x0016da80, 0x10b)
void ClassUnknown_78::ClassUnknown_78_16da80() {}
RVA(0x0016df40, 0x22)
void ClassUnknown_78::ClassUnknown_78_16df40() {}

// ---- ClassUnknown_8 ----
RVA(0x000382c0, 0x52)
void ClassUnknown_8::ClassUnknown_8_0382c0() {}
RVA(0x00038340, 0x46)
void ClassUnknown_8::ClassUnknown_8_038340() {}
RVA(0x000383b0, 0x19c)
void ClassUnknown_8::ClassUnknown_8_0383b0() {}
RVA(0x000385e0, 0x9f)
void ClassUnknown_8::ClassUnknown_8_0385e0() {}
RVA(0x000386b0, 0x5d)
void ClassUnknown_8::ClassUnknown_8_0386b0() {}

// ---- ClassUnknown_81 ----
RVA(0x0000b790, 0xf)
void ClassUnknown_81::ClassUnknown_81_00b790() {}
RVA(0x0000c090, 0x118)
void ClassUnknown_81::ClassUnknown_81_00c090() {}
RVA(0x0000c200, 0x7e)
void ClassUnknown_81::ClassUnknown_81_00c200() {}

// ---- ClassUnknown_82 ----
RVA(0x00115520, 0x45)
void ClassUnknown_82::ClassUnknown_82_115520() {}

// ---- ClassUnknown_83 ----
RVA(0x00029a30, 0x10)
void ClassUnknown_83::ClassUnknown_83_029a30() {}

// ---- ClassUnknown_84 ----
RVA(0x0009a260, 0x1d)
void ClassUnknown_84::ClassUnknown_84_09a260() {}

// ---- ClassUnknown_85 ----
RVA(0x00139ae0, 0xf)
void ClassUnknown_85::ClassUnknown_85_139ae0() {}
RVA(0x00139af0, 0xcc)
void ClassUnknown_85::ClassUnknown_85_139af0() {}

// ---- ClassUnknown_86 ---- reconstructed in src/Gruntz/CDDrawShadeBlit.cpp
// (CDDrawShadeBlit, the DDrawMgr software shaded-sprite blitter).

// ---- ClassUnknown_87 ----
RVA(0x00152480, 0x4e)
void ClassUnknown_87::ClassUnknown_87_152480() {}
RVA(0x00152520, 0x4b)
void ClassUnknown_87::ClassUnknown_87_152520() {}
RVA(0x001525c0, 0x76)
void ClassUnknown_87::ClassUnknown_87_1525c0() {}

// ---- ClassUnknown_88 ----
RVA(0x000311b0, 0x14)
void ClassUnknown_88::ClassUnknown_88_0311b0() {}

// ---- ClassUnknown_89 ----
RVA(0x0014c9f0, 0x5a6)
void ClassUnknown_89::ClassUnknown_89_14c9f0() {}

// ---- ClassUnknown_9 ----
RVA(0x000239d0, 0xf)
void ClassUnknown_9::ClassUnknown_9_0239d0() {}
RVA(0x000239f0, 0xc)
void ClassUnknown_9::ClassUnknown_9_0239f0() {}
RVA(0x00023a10, 0xe7)
void ClassUnknown_9::ClassUnknown_9_023a10() {}
RVA(0x00023bc0, 0x25)
void ClassUnknown_9::ClassUnknown_9_023bc0() {}
RVA(0x00023c00, 0x1c)
void ClassUnknown_9::ClassUnknown_9_023c00() {}
RVA(0x00023c30, 0x47)
void ClassUnknown_9::ClassUnknown_9_023c30() {}
RVA(0x00023ca0, 0x47)
void ClassUnknown_9::ClassUnknown_9_023ca0() {}
RVA(0x00023d10, 0x5a)
void ClassUnknown_9::ClassUnknown_9_023d10() {}
RVA(0x00024890, 0x18d)
void ClassUnknown_9::ClassUnknown_9_024890() {}
RVA(0x00024a90, 0x20)
void ClassUnknown_9::ClassUnknown_9_024a90() {}
RVA(0x00085bd0, 0x56)
void ClassUnknown_9::ClassUnknown_9_085bd0() {}

// ---- ClassUnknown_90 ----
RVA(0x001d38a1, 0x9)
void ClassUnknown_90::ClassUnknown_90_1d38a1() {}

// ---- ClassUnknown_91 ----
RVA(0x001d496b, 0x1e)
void ClassUnknown_91::ClassUnknown_91_1d496b() {}

// ---- ClassUnknown_92 ----
RVA(0x000e3c60, 0x1a3)
void ClassUnknown_92::ClassUnknown_92_0e3c60() {}

// ---- ClassUnknown_93 ----
RVA(0x0000d170, 0x74)
void ClassUnknown_93::ClassUnknown_93_00d170() {}

// ---- ClassUnknown_94 ----
RVA(0x00157850, 0x54)
void ClassUnknown_94::ClassUnknown_94_157850() {}
RVA(0x00157980, 0x74)
void ClassUnknown_94::ClassUnknown_94_157980() {}
RVA(0x00157a40, 0x10)
void ClassUnknown_94::ClassUnknown_94_157a40() {}
RVA(0x00157a50, 0x16)
void ClassUnknown_94::ClassUnknown_94_157a50() {}
RVA(0x00165e30, 0x27)
void ClassUnknown_94::ClassUnknown_94_165e30() {}
RVA(0x00165e60, 0x82)
void ClassUnknown_94::ClassUnknown_94_165e60() {}
RVA(0x00165ef0, 0xf)
void ClassUnknown_94::ClassUnknown_94_165ef0() {}
RVA(0x00165f50, 0x45)
void ClassUnknown_94::ClassUnknown_94_165f50() {}

// ---- ClassUnknown_95 ----
RVA(0x00008c00, 0x152)
void ClassUnknown_95::ClassUnknown_95_008c00() {}

// ---- ClassUnknown_96 ----
RVA(0x0003c8f0, 0x76)
void ClassUnknown_96::ClassUnknown_96_03c8f0() {}

// ---- ClassUnknown_97 ----
RVA(0x00058ee0, 0x5c)
void ClassUnknown_97::ClassUnknown_97_058ee0() {}

// ---- ClassUnknown_98 ----
RVA(0x00056da0, 0xc7)
void ClassUnknown_98::ClassUnknown_98_056da0() {}

// ---- ClassUnknown_99 ----
RVA(0x00046850, 0xf1)
void ClassUnknown_99::ClassUnknown_99_046850() {}

// ---- CmdHost_0953f0 ----
RVA(0x0008cf30, 0x55)
void CmdHost_0953f0::CmdHost_0953f0_08cf30() {}
RVA(0x00095140, 0x6e)
void CmdHost_0953f0::CmdHost_0953f0_095140() {}

// ---- EngStr ----
RVA(0x00115440, 0x45)
void EngStr::EngStr_115440() {}
RVA(0x0016da60, 0x12)
void EngStr::EngStr_16da60() {}
RVA(0x0016e100, 0x7f)
void EngStr::EngStr_16e100() {}
RVA(0x00193080, 0xb5)
void EngStr::EngStr_193080() {}

// ---- HelperHost ----
RVA(0x001549d0, 0x29)
void HelperHost::HelperHost_1549d0() {}
RVA(0x00154a50, 0x23)
void HelperHost::HelperHost_154a50() {}
RVA(0x001647e0, 0x48)
void HelperHost::HelperHost_1647e0() {}

// ---- InterfaceObject ----
RVA(0x00179300, 0x20)
void InterfaceObject::InterfaceObject_179300() {}
RVA(0x00179340, 0x48)
void InterfaceObject::InterfaceObject_179340() {}

// ---- MallocCtor_136230 ----
RVA(0x001359a0, 0x18)
void MallocCtor_136230::MallocCtor_136230_1359a0() {}

// ---- MallocCtor_1375b0 ----
RVA(0x00136370, 0xcc)
void MallocCtor_1375b0::MallocCtor_1375b0_136370() {}
RVA(0x001374c0, 0x5d)
void MallocCtor_1375b0::MallocCtor_1375b0_1374c0() {}
RVA(0x00137520, 0x6e)
void MallocCtor_1375b0::MallocCtor_1375b0_137520() {}
RVA(0x00137590, 0x18)
void MallocCtor_1375b0::MallocCtor_1375b0_137590() {}
RVA(0x00137650, 0x64)
void MallocCtor_1375b0::MallocCtor_1375b0_137650() {}

// ---- MallocCtor_1615a0 ----
RVA(0x000311e0, 0x4c)
void MallocCtor_1615a0::MallocCtor_1615a0_0311e0() {}

// ---- MallocCtor_16b510 ----
RVA(0x0016a410, 0x7b)
void MallocCtor_16b510::MallocCtor_16b510_16a410() {}
RVA(0x0016a510, 0x7d)
void MallocCtor_16b510::MallocCtor_16b510_16a510() {}
RVA(0x0016b720, 0xfb)
void MallocCtor_16b510::MallocCtor_16b510_16b720() {}

// ---- MallocCtor_16bfa0 ----
RVA(0x0016ab20, 0x49)
void MallocCtor_16bfa0::MallocCtor_16bfa0_16ab20() {}
RVA(0x0016bd10, 0x7f)
void MallocCtor_16bfa0::MallocCtor_16bfa0_16bd10() {}
RVA(0x0016bd90, 0xca)
void MallocCtor_16bfa0::MallocCtor_16bfa0_16bd90() {}
RVA(0x00192060, 0xb5)
void MallocCtor_16bfa0::MallocCtor_16bfa0_192060() {}

// ---- MallocCtor_17fdb0 ----
RVA(0x0017e450, 0x23)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17e450() {}
RVA(0x0017e4a0, 0x69)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17e4a0() {}
RVA(0x0017e510, 0x23)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17e510() {}
RVA(0x0017e760, 0x11)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17e760() {}
RVA(0x0017e780, 0xa)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17e780() {}
RVA(0x0017fdf0, 0xb)
void MallocCtor_17fdb0::MallocCtor_17fdb0_17fdf0() {}

// ---- MinervaInner ---- (== the DirectSound *device* manager, DSNDMGR.CPP,
// vtable 0x5ef6c4; trace conflated it with the buffer-wrapper DirectSoundMgr).
// The lifecycle/teardown run (~dtor 0x136500, Shutdown 0x136690, RemoveBuffer
// 0x136d80, StopAll 0x136de0) is reconstructed in src/Dsndmgr/SoundDevice.cpp.
// FreeSamples (0x136ed0) + SetPrimaryFormat (0x1371a0) also reconstructed in
// src/Dsndmgr/SoundDevice.cpp. The *derived* streaming class (DSndMgSR.cpp,
// vtable 0x5ef6ec: 0x137710/0x137780/0x137900/0x1379d0/0x137b70) is
// reconstructed in src/Dsndmgr/SoundStream.cpp. The remaining device methods
// (CreateBuffer 0x1366f0, Acquire 0x136910) are left here for a follow-up.
RVA(0x001366f0, 0x168)
void MinervaInner::MinervaInner_1366f0() {}
RVA(0x00136910, 0x119)
void MinervaInner::MinervaInner_136910() {}

// ---- PaintHost_0fac70 ----
RVA(0x000140d0, 0x33)
void PaintHost_0fac70::PaintHost_0fac70_0140d0() {}
RVA(0x00014340, 0x71)
void PaintHost_0fac70::PaintHost_0fac70_014340() {}
RVA(0x000147b0, 0x6a)
void PaintHost_0fac70::PaintHost_0fac70_0147b0() {}
RVA(0x0008c610, 0x5)
void PaintHost_0fac70::PaintHost_0fac70_08c610() {}
RVA(0x0008cd90, 0x55)
void PaintHost_0fac70::PaintHost_0fac70_08cd90() {}
RVA(0x000fa300, 0x3a)
void PaintHost_0fac70::PaintHost_0fac70_0fa300() {}

// ---- RegistryHelper ----
RVA(0x00114fa0, 0x3e)
void RegistryHelper::RegistryHelper_114fa0() {}

// ---- RemusParseSource ----
RVA(0x00139800, 0x6)
void RemusParseSource::RemusParseSource_139800() {}

// ---- RngBox_00cd70 ----
RVA(0x0000bb40, 0xf)
void RngBox_00cd70::RngBox_00cd70_00bb40() {}
RVA(0x0000be50, 0x8f)
void RngBox_00cd70::RngBox_00cd70_00be50() {}
RVA(0x0000c2a0, 0x19e)
void RngBox_00cd70::RngBox_00cd70_00c2a0() {}
RVA(0x0000cb30, 0x168)
void RngBox_00cd70::RngBox_00cd70_00cb30() {}

// ---- StatusBarItem ----
RVA(0x000d1b30, 0x20)
void StatusBarItem::StatusBarItem_0d1b30() {}
RVA(0x000d6560, 0x45)
void StatusBarItem::StatusBarItem_0d6560() {}
RVA(0x000d9290, 0x2a7)
void StatusBarItem::StatusBarItem_0d9290() {}
RVA(0x000da030, 0x169)
void StatusBarItem::StatusBarItem_0da030() {}

// ---- Timer_1380d0 ---- (reconstructed as StreamFeeder in src/Dsndmgr/StreamFeeder.cpp)

// ---- UnknownClassArrays ---- (all 9 moved into the real class TU
// src/Gruntz/UnknownClassArrays.cpp: 4 reconstructed [025d90/026470/0300c0/034460],
// 5 @early-stop placeholders [029b40/02d800/02edb0/02f620/030b20] for the final sweep)

// ---- UnknownClassInCGruntzMgr ----
RVA(0x0001f450, 0x20)
void UnknownClassInCGruntzMgr::UnknownClassInCGruntzMgr_01f450() {}
RVA(0x000da870, 0xb8)
void UnknownClassInCGruntzMgr::UnknownClassInCGruntzMgr_0da870() {}
RVA(0x000da960, 0x5b)
void UnknownClassInCGruntzMgr::UnknownClassInCGruntzMgr_0da960() {}
RVA(0x000dace0, 0x239)
void UnknownClassInCGruntzMgr::UnknownClassInCGruntzMgr_0dace0() {}
RVA(0x000dafb0, 0x71)
void UnknownClassInCGruntzMgr::UnknownClassInCGruntzMgr_0dafb0() {}

// ---- WndHolder_13d4c0 ----
RVA(0x000946a0, 0x5f)
void WndHolder_13d4c0::WndHolder_13d4c0_0946a0() {}
RVA(0x00094920, 0x21)
void WndHolder_13d4c0::WndHolder_13d4c0_094920() {}
RVA(0x00094a20, 0x26)
void WndHolder_13d4c0::WndHolder_13d4c0_094a20() {}
RVA(0x00094a60, 0x26)
void WndHolder_13d4c0::WndHolder_13d4c0_094a60() {}
RVA(0x00094ae0, 0x26)
void WndHolder_13d4c0::WndHolder_13d4c0_094ae0() {}
RVA(0x00094b20, 0x49)
void WndHolder_13d4c0::WndHolder_13d4c0_094b20() {}
RVA(0x00094b90, 0x1b)
void WndHolder_13d4c0::WndHolder_13d4c0_094b90() {}
RVA(0x0013d470, 0x12)
void WndHolder_13d4c0::WndHolder_13d4c0_13d470() {}
RVA(0x0013d4e0, 0x43)
void WndHolder_13d4c0::WndHolder_13d4c0_13d4e0() {}
