// AUTO-GENERATED by gruntz.analysis.gen_class_stubs - do not hand-edit.
// Empty __thiscall stubs at each trace-discovered RVA; the class is the trace's
// (inheritance-aware) assignment. @stub backlog -> reconstruct from objdiff.
#include <rva.h>
#include <Stub/discovered.h>

// Base vtable restored by ~CWapObject-derived dtors (0x5e8cb4); these 7-byte
// `mov [ecx],&vtbl; ret` thunks are the still-manual vtable stamps for those
// classes (kept as the manual stamp, not yet modelled as real virtuals).
extern void* g_wapObjectDtorVtbl;
// scalar-deleting-destructor vtable at 0x5f04d8 stamped by ClassUnknown_50.
extern void* g_vtbl5f04d8;

// ---- CGruntzSingleCommand ----
// 0x11f618 and 0x18c022 were stub-attributed here off a stale ecx; both are CRT
// library, not game methods, so they are FID-carved (config/library_labels.csv,
// manual-stub-reclass) and no longer stubbed here:
//   0x11f618 - the compiler-generated EH unwind funclet for the CRT `__ehvec_ctor`
//              vector-constructor iterator at 0x11f5a0 (borrows the parent ebp
//              frame; forwards to the partial-destruct helper only on unwind).
//   0x18c022 - the CRT `pow`/`_CIpow` FP power routine (fstcw + 0x27f cw-guard,
//              2^(y*log2 x) via fyl2x, 0x7ff00000 NaN/Inf classification).

// ---- ClassUnknown_13 ----
// Two __cdecl forwarder twins (trace mis-attributed as __thiscall methods): read a
// handler off p->m_4 (at +0x18 / +0x14), and if non-null forward all 9 stack args
// to a 10-arg __cdecl callee (0x115930 via the 0x1262 ILT), inserting the handler's
// m_2c as the 4th argument. The argument is `p` (a stack arg, NOT this).
// Owning class is NOT resolvable: these are free __cdecl forwarders (the callee
// 0x115930 is winapi_115930_CopyRect_OffsetRect, a Win32-rect helper); ClassUnknown_13
// is a stale-ecx trace artifact. No real class TU exists -> left here per the re-home
// rule (re-home only when the owning class is resolvable).
SIZE_UNKNOWN(U13Handler);
struct U13Handler {
    char m_pad00[0x2c];
    i32 m_2c; // +0x2c
};
SIZE_UNKNOWN(U13Inner);
struct U13Inner {
    char m_pad00[0x14];
    U13Handler* m_14; // +0x14
    U13Handler* m_18; // +0x18
};
SIZE_UNKNOWN(U13Obj);
struct U13Obj {
    char m_pad00[4];
    U13Inner* m_4; // +0x04
};
extern "C" void U13Callee(
    U13Obj* p,
    i32 a2,
    i32 a3,
    i32 m,
    i32 a4,
    i32 a5,
    i32 a6,
    i32 a7,
    i32 a8,
    i32 a9
); // 0x115930
// @early-stop
// tail-merge / block-layout wall (~94.3%, topic:wall topic:scheduling): the handler
// load + the 10-arg `[esp+0x24]`-reload forwarding push chain + the call/`add esp`
// are byte-IDENTICAL; the sole residual is the null guard, where retail emits
// `jne body; ret` (a separate early ret, no tail-merge) but cl tail-merges the two
// rets to `je <shared end ret>`. An MSVC5 block-ordering coin-flip; not
// source-steerable (early-return / explicit-return-in-body both still tail-merge).
RVA(0x001154b0, 0x45)
void U13Forward1154b0(U13Obj* p, i32 a2, i32 a3, i32 a4, i32 a5, i32 a6, i32 a7, i32 a8, i32 a9) {
    U13Handler* h = p->m_4->m_18;
    if (h == 0) {
        return;
    }
    U13Callee(p, a2, a3, h->m_2c, a4, a5, a6, a7, a8, a9);
}
// @early-stop
// same tail-merge wall as U13Forward1154b0 (twin; inner offset +0x14 vs +0x18).
RVA(0x00115520, 0x45)
void U13Forward115520(U13Obj* p, i32 a2, i32 a3, i32 a4, i32 a5, i32 a6, i32 a7, i32 a8, i32 a9) {
    U13Handler* h = p->m_4->m_14;
    if (h == 0) {
        return;
    }
    U13Callee(p, a2, a3, h->m_2c, a4, a5, a6, a7, a8, a9);
}

// ---- ClassUnknown_15 ----
// A bare ctor: stamp the class vtable (0x5ed36c) and return this. Reconstructed.
DATA(0x005ed36c)
extern void* g_vtbl5ed36c;
RVA(0x001d38a1, 0x9)
ClassUnknown_15::ClassUnknown_15() {
    *(void**)this = &g_vtbl5ed36c;
}

// ---- ClassUnknown_16 ----
RVA(0x001d496b, 0x1e)
void ClassUnknown_16::ClassUnknown_16_1d496b() {}

// ---- ClassUnknown_33 ----
RVA(0x0011f6b9, 0x17)
void ClassUnknown_33::ClassUnknown_33_11f6b9() {}

// ---- ClassUnknown_45 ----
// A ctor: zero m_4, stamp the class vtable (0x5ea2a4), return this. Reconstructed.
DATA(0x005ea2a4)
extern void* g_vtbl5ea2a4;
RVA(0x0008c3b0, 0x10)
ClassUnknown_45::ClassUnknown_45() {
    m_4 = 0;
    *(void**)this = &g_vtbl5ea2a4;
}

// ---- ClassUnknown_50 ----
RVA(0x0016dfc0, 0x7)
void ClassUnknown_50::ClassUnknown_50_16dfc0() {
    *(void**)this = &g_vtbl5f04d8;
}

// ---- ClassUnknown_51 ----
RVA(0x0011eaf5, 0x7)
void ClassUnknown_51::ClassUnknown_51_11eaf5() {
    *(void**)this = &g_wapObjectDtorVtbl;
}

// ---- ClassUnknown_52 ----
RVA(0x0011eaa8, 0x7)
void ClassUnknown_52::ClassUnknown_52_11eaa8() {
    *(void**)this = &g_wapObjectDtorVtbl;
}

// ---- ClassUnknown_53 ----
RVA(0x0011cf30, 0x7)
void ClassUnknown_53::ClassUnknown_53_11cf30() {
    *(void**)this = &g_wapObjectDtorVtbl;
}

// ---- ClassUnknown_54 ----
RVA(0x0011cee3, 0x7)
void ClassUnknown_54::ClassUnknown_54_11cee3() {
    *(void**)this = &g_wapObjectDtorVtbl;
}
