// GapFunctions.cpp - GENERATED by `python -m gruntz.analysis.discover_gaps
// --emit`. DO NOT EDIT BY HAND; re-run the tool to refresh.
//
// Functions Ghidra never carved, recovered by .text coverage-gap analysis
// (real prologue + terminator, >=32B, not FID). Each is an RVA()+size stub so
// the delinker extracts its retail bytes and objdiff tracks it (initially ~0%).
// These are the matching worklist: reconstruct each and RE-HOME it into its
// real class TU, deleting the row here. See gruntz.analysis.discover_gaps.
#include <rva.h>

RVA(0x00007c60, 0xf1)
i32 Gap_007c60(void) {
    return 0;
} // @stub
RVA(0x00008580, 0x5e)
i32 Gap_008580(void) {
    return 0;
} // @stub
RVA(0x0000ba00, 0xc6)
i32 Gap_00ba00(void) {
    return 0;
} // @stub
RVA(0x0000f5a0, 0x47)
i32 Gap_00f5a0(void) {
    return 0;
} // @stub
RVA(0x0000f6d0, 0x47)
i32 Gap_00f6d0(void) {
    return 0;
} // @stub
RVA(0x0000f800, 0x47)
i32 Gap_00f800(void) {
    return 0;
} // @stub
RVA(0x0000f930, 0x47)
i32 Gap_00f930(void) {
    return 0;
} // @stub
RVA(0x0000fa60, 0x47)
i32 Gap_00fa60(void) {
    return 0;
} // @stub
RVA(0x00010bb0, 0x47)
i32 Gap_010bb0(void) {
    return 0;
} // @stub
RVA(0x00010f20, 0x47)
i32 Gap_010f20(void) {
    return 0;
} // @stub
RVA(0x00011050, 0x47)
i32 Gap_011050(void) {
    return 0;
} // @stub
RVA(0x000111f0, 0x47)
i32 Gap_0111f0(void) {
    return 0;
} // @stub
RVA(0x00011750, 0x47)
i32 Gap_011750(void) {
    return 0;
} // @stub
RVA(0x000119b0, 0x47)
i32 Gap_0119b0(void) {
    return 0;
} // @stub
RVA(0x00011ae0, 0x47)
i32 Gap_011ae0(void) {
    return 0;
} // @stub
RVA(0x00012cf0, 0x47)
i32 Gap_012cf0(void) {
    return 0;
} // @stub
RVA(0x00012e20, 0x47)
i32 Gap_012e20(void) {
    return 0;
} // @stub
RVA(0x000134e0, 0x47)
i32 Gap_0134e0(void) {
    return 0;
} // @stub
RVA(0x00013610, 0x8c)
i32 Gap_013610(void) {
    return 0;
} // @stub
RVA(0x00014120, 0x1a9)
i32 Gap_014120(void) {
    return 0;
} // @stub
RVA(0x00015a10, 0x70)
i32 Gap_015a10(void) {
    return 0;
} // @stub
RVA(0x00017560, 0x28)
i32 Gap_017560(void) {
    return 0;
} // @stub
RVA(0x000175a0, 0x28)
i32 Gap_0175a0(void) {
    return 0;
} // @stub
RVA(0x000175e0, 0x28)
i32 Gap_0175e0(void) {
    return 0;
} // @stub
RVA(0x00017620, 0x28)
i32 Gap_017620(void) {
    return 0;
} // @stub
RVA(0x000179b0, 0xcb)
i32 Gap_0179b0(void) {
    return 0;
} // @stub
RVA(0x00017ae0, 0x20)
i32 Gap_017ae0(void) {
    return 0;
} // @stub
RVA(0x00018e40, 0x81)
i32 Gap_018e40(void) {
    return 0;
} // @stub
RVA(0x0001e660, 0x81)
i32 Gap_01e660(void) {
    return 0;
} // @stub
RVA(0x0001f480, 0x1e9)
i32 Gap_01f480(void) {
    return 0;
} // @stub
RVA(0x00022770, 0x7d)
i32 Gap_022770(void) {
    return 0;
} // @stub
RVA(0x00023520, 0x3e)
i32 Gap_023520(void) {
    return 0;
} // @stub
RVA(0x00023590, 0x31)
i32 Gap_023590(void) {
    return 0;
} // @stub
RVA(0x00023f90, 0x48)
i32 Gap_023f90(void) {
    return 0;
} // @stub
RVA(0x00024000, 0x3e)
i32 Gap_024000(void) {
    return 0;
} // @stub
RVA(0x000244d0, 0x3b)
i32 Gap_0244d0(void) {
    return 0;
} // @stub
RVA(0x000246c0, 0x3b)
i32 Gap_0246c0(void) {
    return 0;
} // @stub
RVA(0x00024710, 0x8b)
i32 Gap_024710(void) {
    return 0;
} // @stub
RVA(0x00035210, 0x4f)
i32 Gap_035210(void) {
    return 0;
} // @stub
RVA(0x00035550, 0x52)
i32 Gap_035550(void) {
    return 0;
} // @stub
RVA(0x00036410, 0x366)
i32 Gap_036410(void) {
    return 0;
} // @stub
RVA(0x00036e50, 0x43)
i32 Gap_036e50(void) {
    return 0;
} // @stub
RVA(0x000377e0, 0x6a)
i32 Gap_0377e0(void) {
    return 0;
} // @stub
RVA(0x00038730, 0x2e)
i32 Gap_038730(void) {
    return 0;
} // @stub
RVA(0x00038770, 0x40)
i32 Gap_038770(void) {
    return 0;
} // @stub
RVA(0x000388e0, 0x112)
i32 Gap_0388e0(void) {
    return 0;
} // @stub
RVA(0x00039120, 0x2c)
i32 Gap_039120(void) {
    return 0;
} // @stub
RVA(0x00039400, 0x2f)
i32 Gap_039400(void) {
    return 0;
} // @stub
RVA(0x0003a5b0, 0x102)
i32 Gap_03a5b0(void) {
    return 0;
} // @stub
RVA(0x0003ae60, 0xec)
i32 Gap_03ae60(void) {
    return 0;
} // @stub
RVA(0x0003b600, 0x15f)
i32 Gap_03b600(void) {
    return 0;
} // @stub
RVA(0x0003bfa0, 0x42)
i32 Gap_03bfa0(void) {
    return 0;
} // @stub
RVA(0x0003c030, 0x22)
i32 Gap_03c030(void) {
    return 0;
} // @stub
RVA(0x0003c300, 0x183)
i32 Gap_03c300(void) {
    return 0;
} // @stub
RVA(0x0003c850, 0x38)
i32 Gap_03c850(void) {
    return 0;
} // @stub
RVA(0x0003c8a0, 0x38)
i32 Gap_03c8a0(void) {
    return 0;
} // @stub
RVA(0x0003c990, 0x1bc)
i32 Gap_03c990(void) {
    return 0;
} // @stub
RVA(0x0003cdd0, 0x19f)
i32 Gap_03cdd0(void) {
    return 0;
} // @stub
RVA(0x0003e1a0, 0x102)
i32 Gap_03e1a0(void) {
    return 0;
} // @stub
RVA(0x0003f040, 0x147)
i32 Gap_03f040(void) {
    return 0;
} // @stub
RVA(0x00040750, 0x102)
i32 Gap_040750(void) {
    return 0;
} // @stub
RVA(0x00041350, 0xee)
i32 Gap_041350(void) {
    return 0;
} // @stub
RVA(0x00043670, 0xc20)
i32 Gap_043670(void) {
    return 0;
} // @stub
RVA(0x00044e70, 0x87)
i32 Gap_044e70(void) {
    return 0;
} // @stub
RVA(0x00044f30, 0x38)
i32 Gap_044f30(void) {
    return 0;
} // @stub
RVA(0x00047350, 0x102)
i32 Gap_047350(void) {
    return 0;
} // @stub
RVA(0x000476b0, 0x69)
i32 Gap_0476b0(void) {
    return 0;
} // @stub
RVA(0x0004a780, 0x1ec)
i32 Gap_04a780(void) {
    return 0;
} // @stub
RVA(0x00057d10, 0x4e)
i32 Gap_057d10(void) {
    return 0;
} // @stub
RVA(0x0005baf0, 0xf4)
i32 Gap_05baf0(void) {
    return 0;
} // @stub
RVA(0x0005bcd0, 0x102)
i32 Gap_05bcd0(void) {
    return 0;
} // @stub
RVA(0x0005ecd0, 0x4f3)
i32 Gap_05ecd0(void) {
    return 0;
} // @stub
RVA(0x00062840, 0x25d)
i32 Gap_062840(void) {
    return 0;
} // @stub
RVA(0x00063b60, 0x1cf)
i32 Gap_063b60(void) {
    return 0;
} // @stub
RVA(0x00065300, 0x148)
i32 Gap_065300(void) {
    return 0;
} // @stub
RVA(0x000654b0, 0x130)
i32 Gap_0654b0(void) {
    return 0;
} // @stub
RVA(0x00065c20, 0x1d5)
i32 Gap_065c20(void) {
    return 0;
} // @stub
RVA(0x0006bc20, 0x6f)
i32 Gap_06bc20(void) {
    return 0;
} // @stub
RVA(0x0007ea70, 0x6f)
i32 Gap_07ea70(void) {
    return 0;
} // @stub
RVA(0x00080d20, 0x24)
i32 Gap_080d20(void) {
    return 0;
} // @stub
RVA(0x00082250, 0x17c)
i32 Gap_082250(void) {
    return 0;
} // @stub
RVA(0x00082ff0, 0x2f)
i32 Gap_082ff0(void) {
    return 0;
} // @stub
RVA(0x000853f0, 0x46)
i32 Gap_0853f0(void) {
    return 0;
} // @stub
RVA(0x0008b8c0, 0x76)
i32 Gap_08b8c0(void) {
    return 0;
} // @stub
RVA(0x0008dc20, 0x2b)
i32 Gap_08dc20(void) {
    return 0;
} // @stub
RVA(0x0008dc90, 0xb1)
i32 Gap_08dc90(void) {
    return 0;
} // @stub
RVA(0x0008e780, 0x2a)
i32 Gap_08e780(void) {
    return 0;
} // @stub
RVA(0x0008f980, 0x21)
i32 Gap_08f980(void) {
    return 0;
} // @stub
RVA(0x000907c0, 0x77)
i32 Gap_0907c0(void) {
    return 0;
} // @stub
RVA(0x00092060, 0x3c)
i32 Gap_092060(void) {
    return 0;
} // @stub
RVA(0x000920e0, 0x32)
i32 Gap_0920e0(void) {
    return 0;
} // @stub
RVA(0x00092130, 0x32)
i32 Gap_092130(void) {
    return 0;
} // @stub
RVA(0x00092a30, 0x52)
i32 Gap_092a30(void) {
    return 0;
} // @stub
RVA(0x00092da0, 0x3a)
i32 Gap_092da0(void) {
    return 0;
} // @stub
RVA(0x00092df0, 0x24)
i32 Gap_092df0(void) {
    return 0;
} // @stub
RVA(0x00094790, 0xcd)
i32 Gap_094790(void) {
    return 0;
} // @stub
RVA(0x000948a0, 0x21)
i32 Gap_0948a0(void) {
    return 0;
} // @stub
RVA(0x000948e0, 0x21)
i32 Gap_0948e0(void) {
    return 0;
} // @stub
RVA(0x00094960, 0x26)
i32 Gap_094960(void) {
    return 0;
} // @stub
RVA(0x000949a0, 0x26)
i32 Gap_0949a0(void) {
    return 0;
} // @stub
RVA(0x000949e0, 0x26)
i32 Gap_0949e0(void) {
    return 0;
} // @stub
RVA(0x00094aa0, 0x26)
i32 Gap_094aa0(void) {
    return 0;
} // @stub
RVA(0x000951f0, 0xeb)
i32 Gap_0951f0(void) {
    return 0;
} // @stub
RVA(0x00095320, 0x56)
i32 Gap_095320(void) {
    return 0;
} // @stub
RVA(0x000953a0, 0x3c)
i32 Gap_0953a0(void) {
    return 0;
} // @stub
RVA(0x00095440, 0x24)
i32 Gap_095440(void) {
    return 0;
} // @stub
RVA(0x0009a4c0, 0x3e)
i32 Gap_09a4c0(void) {
    return 0;
} // @stub
RVA(0x0009cdc0, 0xf1)
i32 Gap_09cdc0(void) {
    return 0;
} // @stub
RVA(0x0009d1c0, 0x102)
i32 Gap_09d1c0(void) {
    return 0;
} // @stub
RVA(0x0009d660, 0xc8)
i32 Gap_09d660(void) {
    return 0;
} // @stub
RVA(0x0009d7b0, 0x40)
i32 Gap_09d7b0(void) {
    return 0;
} // @stub
RVA(0x0009f540, 0x40)
i32 Gap_09f540(void) {
    return 0;
} // @stub
RVA(0x0009f840, 0x110)
i32 Gap_09f840(void) {
    return 0;
} // @stub
RVA(0x0009f9a0, 0x12e)
i32 Gap_09f9a0(void) {
    return 0;
} // @stub
RVA(0x0009fe10, 0x29)
i32 Gap_09fe10(void) {
    return 0;
} // @stub
RVA(0x000a0b90, 0xc7)
i32 Gap_0a0b90(void) {
    return 0;
} // @stub
RVA(0x000a0ca0, 0x21)
i32 Gap_0a0ca0(void) {
    return 0;
} // @stub
RVA(0x000a0ce0, 0x21)
i32 Gap_0a0ce0(void) {
    return 0;
} // @stub
RVA(0x000a1190, 0x29)
i32 Gap_0a1190(void) {
    return 0;
} // @stub
RVA(0x000a3a20, 0xe2)
i32 Gap_0a3a20(void) {
    return 0;
} // @stub
RVA(0x000ae360, 0x6f)
i32 Gap_0ae360(void) {
    return 0;
} // @stub
RVA(0x000aed80, 0x39)
i32 Gap_0aed80(void) {
    return 0;
} // @stub
RVA(0x000b47a0, 0x27)
i32 Gap_0b47a0(void) {
    return 0;
} // @stub
RVA(0x000b6330, 0x89)
i32 Gap_0b6330(void) {
    return 0;
} // @stub
RVA(0x000b63f0, 0x11b)
i32 Gap_0b63f0(void) {
    return 0;
} // @stub
RVA(0x000b8020, 0x22f)
i32 Gap_0b8020(void) {
    return 0;
} // @stub
RVA(0x000b9180, 0x4a)
i32 Gap_0b9180(void) {
    return 0;
} // @stub
RVA(0x000b9490, 0x42)
i32 Gap_0b9490(void) {
    return 0;
} // @stub
RVA(0x000bc910, 0xf6)
i32 Gap_0bc910(void) {
    return 0;
} // @stub
RVA(0x000bd210, 0x14d)
i32 Gap_0bd210(void) {
    return 0;
} // @stub
RVA(0x000bd850, 0x141)
i32 Gap_0bd850(void) {
    return 0;
} // @stub
RVA(0x000bda70, 0xda)
i32 Gap_0bda70(void) {
    return 0;
} // @stub
RVA(0x000bddd0, 0x193)
i32 Gap_0bddd0(void) {
    return 0;
} // @stub
RVA(0x000be550, 0x193)
i32 Gap_0be550(void) {
    return 0;
} // @stub
RVA(0x000c0320, 0x37)
i32 Gap_0c0320(void) {
    return 0;
} // @stub
RVA(0x000c0370, 0x28)
i32 Gap_0c0370(void) {
    return 0;
} // @stub
RVA(0x000c03b0, 0x28)
i32 Gap_0c03b0(void) {
    return 0;
} // @stub
RVA(0x000c10d0, 0x7c)
i32 Gap_0c10d0(void) {
    return 0;
} // @stub
RVA(0x000c1a10, 0x70)
i32 Gap_0c1a10(void) {
    return 0;
} // @stub
RVA(0x000c28c0, 0x27)
i32 Gap_0c28c0(void) {
    return 0;
} // @stub
RVA(0x000c2900, 0x2a)
i32 Gap_0c2900(void) {
    return 0;
} // @stub
RVA(0x000c2940, 0x2b)
i32 Gap_0c2940(void) {
    return 0;
} // @stub
RVA(0x000c52f0, 0x43)
i32 Gap_0c52f0(void) {
    return 0;
} // @stub
RVA(0x000c7350, 0x39)
i32 Gap_0c7350(void) {
    return 0;
} // @stub
RVA(0x000c7ab0, 0x67)
i32 Gap_0c7ab0(void) {
    return 0;
} // @stub
RVA(0x000c7b40, 0x76)
i32 Gap_0c7b40(void) {
    return 0;
} // @stub
RVA(0x000c8b80, 0x11b)
i32 Gap_0c8b80(void) {
    return 0;
} // @stub
RVA(0x000cf0a0, 0x567)
i32 Gap_0cf0a0(void) {
    return 0;
} // @stub
RVA(0x000cfc90, 0x1d1)
i32 Gap_0cfc90(void) {
    return 0;
} // @stub
RVA(0x000cfef0, 0xbc)
i32 Gap_0cfef0(void) {
    return 0;
} // @stub
RVA(0x000d0050, 0x3a)
i32 Gap_0d0050(void) {
    return 0;
} // @stub
RVA(0x000d1650, 0x90)
i32 Gap_0d1650(void) {
    return 0;
} // @stub
RVA(0x000d5c10, 0x10d)
i32 Gap_0d5c10(void) {
    return 0;
} // @stub
RVA(0x000daa60, 0x24)
i32 Gap_0daa60(void) {
    return 0;
} // @stub
RVA(0x000daaa0, 0xd3)
i32 Gap_0daaa0(void) {
    return 0;
} // @stub
RVA(0x000dabc0, 0xd3)
i32 Gap_0dabc0(void) {
    return 0;
} // @stub
RVA(0x000de190, 0x35)
i32 Gap_0de190(void) {
    return 0;
} // @stub
RVA(0x000de2c0, 0x5c)
i32 Gap_0de2c0(void) {
    return 0;
} // @stub
RVA(0x000de340, 0x56)
i32 Gap_0de340(void) {
    return 0;
} // @stub
RVA(0x000de3c0, 0x2d)
i32 Gap_0de3c0(void) {
    return 0;
} // @stub
RVA(0x000de8a0, 0xf4)
i32 Gap_0de8a0(void) {
    return 0;
} // @stub
RVA(0x000e3690, 0x2ec)
i32 Gap_0e3690(void) {
    return 0;
} // @stub
RVA(0x000e5520, 0x20)
i32 Gap_0e5520(void) {
    return 0;
} // @stub
RVA(0x000e5b90, 0x51)
i32 Gap_0e5b90(void) {
    return 0;
} // @stub
RVA(0x000e5c10, 0x54)
i32 Gap_0e5c10(void) {
    return 0;
} // @stub
RVA(0x000e64c0, 0x3e7)
i32 Gap_0e64c0(void) {
    return 0;
} // @stub
RVA(0x000e6dd0, 0x45)
i32 Gap_0e6dd0(void) {
    return 0;
} // @stub
RVA(0x000e7440, 0x5e)
i32 Gap_0e7440(void) {
    return 0;
} // @stub
RVA(0x000e7c30, 0x7d)
i32 Gap_0e7c30(void) {
    return 0;
} // @stub
RVA(0x000e8e00, 0x41a)
i32 Gap_0e8e00(void) {
    return 0;
} // @stub
RVA(0x000e9a30, 0x31e)
i32 Gap_0e9a30(void) {
    return 0;
} // @stub
RVA(0x000ea4e0, 0x172)
i32 Gap_0ea4e0(void) {
    return 0;
} // @stub
RVA(0x000f9920, 0x108)
i32 Gap_0f9920(void) {
    return 0;
} // @stub
RVA(0x000f9a80, 0x44)
i32 Gap_0f9a80(void) {
    return 0;
} // @stub
RVA(0x000f9af0, 0x3e)
i32 Gap_0f9af0(void) {
    return 0;
} // @stub
RVA(0x000f9b40, 0x37)
i32 Gap_0f9b40(void) {
    return 0;
} // @stub
RVA(0x000f9b90, 0x24)
i32 Gap_0f9b90(void) {
    return 0;
} // @stub
RVA(0x000fa6b0, 0xa7)
i32 Gap_0fa6b0(void) {
    return 0;
} // @stub
RVA(0x000faf50, 0x31)
i32 Gap_0faf50(void) {
    return 0;
} // @stub
RVA(0x000fc5b0, 0xf5)
i32 Gap_0fc5b0(void) {
    return 0;
} // @stub
RVA(0x00100660, 0x50)
i32 Gap_100660(void) {
    return 0;
} // @stub
RVA(0x00106af0, 0x37)
i32 Gap_106af0(void) {
    return 0;
} // @stub
RVA(0x0010c0f0, 0xf1)
i32 Gap_10c0f0(void) {
    return 0;
} // @stub
RVA(0x0010c4b0, 0x102)
i32 Gap_10c4b0(void) {
    return 0;
} // @stub
RVA(0x0010cb10, 0xf1)
i32 Gap_10cb10(void) {
    return 0;
} // @stub
RVA(0x0010cc50, 0xf1)
i32 Gap_10cc50(void) {
    return 0;
} // @stub
RVA(0x0010cd90, 0xf1)
i32 Gap_10cd90(void) {
    return 0;
} // @stub
RVA(0x0010ced0, 0xf1)
i32 Gap_10ced0(void) {
    return 0;
} // @stub
RVA(0x0010d010, 0xf1)
i32 Gap_10d010(void) {
    return 0;
} // @stub
RVA(0x0010d290, 0xf4)
i32 Gap_10d290(void) {
    return 0;
} // @stub
RVA(0x0010d510, 0xf1)
i32 Gap_10d510(void) {
    return 0;
} // @stub
RVA(0x0010dea0, 0x102)
i32 Gap_10dea0(void) {
    return 0;
} // @stub
RVA(0x0010e4a0, 0x102)
i32 Gap_10e4a0(void) {
    return 0;
} // @stub
RVA(0x0010ea80, 0x102)
i32 Gap_10ea80(void) {
    return 0;
} // @stub
RVA(0x0010f1e0, 0x102)
i32 Gap_10f1e0(void) {
    return 0;
} // @stub
RVA(0x0010f6a0, 0x235)
i32 Gap_10f6a0(void) {
    return 0;
} // @stub
RVA(0x0010f9a0, 0x8f)
i32 Gap_10f9a0(void) {
    return 0;
} // @stub
RVA(0x0010fd10, 0x102)
i32 Gap_10fd10(void) {
    return 0;
} // @stub
RVA(0x00110110, 0x39)
i32 Gap_110110(void) {
    return 0;
} // @stub
RVA(0x00114f50, 0x3e)
i32 Gap_114f50(void) {
    return 0;
} // @stub
RVA(0x00115b60, 0x97)
i32 Gap_115b60(void) {
    return 0;
} // @stub
RVA(0x001164a0, 0x116)
i32 Gap_1164a0(void) {
    return 0;
} // @stub
RVA(0x00118130, 0x44)
i32 Gap_118130(void) {
    return 0;
} // @stub
RVA(0x00118960, 0x20)
i32 Gap_118960(void) {
    return 0;
} // @stub
RVA(0x00118990, 0x20)
i32 Gap_118990(void) {
    return 0;
} // @stub
RVA(0x00118bf0, 0xb4)
i32 Gap_118bf0(void) {
    return 0;
} // @stub
RVA(0x00119620, 0xf1)
i32 Gap_119620(void) {
    return 0;
} // @stub
RVA(0x00119760, 0xf1)
i32 Gap_119760(void) {
    return 0;
} // @stub
RVA(0x0011a3a0, 0x102)
i32 Gap_11a3a0(void) {
    return 0;
} // @stub
RVA(0x0011a8e0, 0x198)
i32 Gap_11a8e0(void) {
    return 0;
} // @stub
RVA(0x0011c6c0, 0x27)
i32 Gap_11c6c0(void) {
    return 0;
} // @stub
RVA(0x0011c700, 0x20)
i32 Gap_11c700(void) {
    return 0;
} // @stub
RVA(0x00132fc0, 0xb8)
i32 Gap_132fc0(void) {
    return 0;
} // @stub
RVA(0x00133560, 0x27)
i32 Gap_133560(void) {
    return 0;
} // @stub
RVA(0x00134df0, 0x33)
i32 Gap_134df0(void) {
    return 0;
} // @stub
RVA(0x00134e30, 0x36)
i32 Gap_134e30(void) {
    return 0;
} // @stub
RVA(0x00134e70, 0x3f)
i32 Gap_134e70(void) {
    return 0;
} // @stub
RVA(0x00135000, 0x3b)
i32 Gap_135000(void) {
    return 0;
} // @stub
RVA(0x00135490, 0x73)
i32 Gap_135490(void) {
    return 0;
} // @stub
RVA(0x00135840, 0x3b)
i32 Gap_135840(void) {
    return 0;
} // @stub
RVA(0x00135e10, 0x124)
i32 Gap_135e10(void) {
    return 0;
} // @stub
RVA(0x00136650, 0x37)
i32 Gap_136650(void) {
    return 0;
} // @stub
RVA(0x00136b00, 0xc2)
i32 Gap_136b00(void) {
    return 0;
} // @stub
RVA(0x00137a30, 0x4b)
i32 Gap_137a30(void) {
    return 0;
} // @stub
RVA(0x00138120, 0x27)
i32 Gap_138120(void) {
    return 0;
} // @stub
RVA(0x00138d50, 0x74)
i32 Gap_138d50(void) {
    return 0;
} // @stub
RVA(0x00139140, 0x41)
i32 Gap_139140(void) {
    return 0;
} // @stub
RVA(0x00139190, 0x44)
i32 Gap_139190(void) {
    return 0;
} // @stub
RVA(0x00139410, 0x45)
i32 Gap_139410(void) {
    return 0;
} // @stub
RVA(0x00139620, 0x28)
i32 Gap_139620(void) {
    return 0;
} // @stub
RVA(0x00139810, 0x146)
i32 Gap_139810(void) {
    return 0;
} // @stub
RVA(0x0013ba20, 0x27)
i32 Gap_13ba20(void) {
    return 0;
} // @stub
RVA(0x0013ba80, 0x57)
i32 Gap_13ba80(void) {
    return 0;
} // @stub
RVA(0x0013d3a0, 0x6a)
i32 Gap_13d3a0(void) {
    return 0;
} // @stub
RVA(0x0013d530, 0x55)
i32 Gap_13d530(void) {
    return 0;
} // @stub
RVA(0x0013df00, 0x25)
i32 Gap_13df00(void) {
    return 0;
} // @stub
RVA(0x0013e010, 0x32)
i32 Gap_13e010(void) {
    return 0;
} // @stub
RVA(0x0013e8f0, 0xb0)
i32 Gap_13e8f0(void) {
    return 0;
} // @stub
RVA(0x0013ea70, 0x21)
i32 Gap_13ea70(void) {
    return 0;
} // @stub
RVA(0x0013eae0, 0x24)
i32 Gap_13eae0(void) {
    return 0;
} // @stub
RVA(0x0013eb10, 0x28)
i32 Gap_13eb10(void) {
    return 0;
} // @stub
RVA(0x0013eb80, 0x21)
i32 Gap_13eb80(void) {
    return 0;
} // @stub
RVA(0x0013f020, 0x43f)
i32 Gap_13f020(void) {
    return 0;
} // @stub
RVA(0x0013f960, 0x22)
i32 Gap_13f960(void) {
    return 0;
} // @stub
RVA(0x00141040, 0x36)
i32 Gap_141040(void) {
    return 0;
} // @stub
RVA(0x00141080, 0x174)
i32 Gap_141080(void) {
    return 0;
} // @stub
RVA(0x00141200, 0x39)
i32 Gap_141200(void) {
    return 0;
} // @stub
RVA(0x00141240, 0x39)
i32 Gap_141240(void) {
    return 0;
} // @stub
RVA(0x001412d0, 0x24)
i32 Gap_1412d0(void) {
    return 0;
} // @stub
RVA(0x001413d0, 0x27)
i32 Gap_1413d0(void) {
    return 0;
} // @stub
RVA(0x00141ff0, 0x6c)
i32 Gap_141ff0(void) {
    return 0;
} // @stub
RVA(0x00143390, 0x35)
i32 Gap_143390(void) {
    return 0;
} // @stub
RVA(0x00143420, 0x4b)
i32 Gap_143420(void) {
    return 0;
} // @stub
RVA(0x00143810, 0x2b)
i32 Gap_143810(void) {
    return 0;
} // @stub
RVA(0x00143840, 0x32)
i32 Gap_143840(void) {
    return 0;
} // @stub
RVA(0x00143880, 0x3b)
i32 Gap_143880(void) {
    return 0;
} // @stub
RVA(0x001438c0, 0x31)
i32 Gap_1438c0(void) {
    return 0;
} // @stub
RVA(0x00143900, 0x4d)
i32 Gap_143900(void) {
    return 0;
} // @stub
RVA(0x001439b0, 0x75)
i32 Gap_1439b0(void) {
    return 0;
} // @stub
RVA(0x00145e30, 0x125)
i32 Gap_145e30(void) {
    return 0;
} // @stub
RVA(0x00147b10, 0x8b)
i32 Gap_147b10(void) {
    return 0;
} // @stub
RVA(0x00147ba0, 0x82)
i32 Gap_147ba0(void) {
    return 0;
} // @stub
RVA(0x00147d50, 0x1d2)
i32 Gap_147d50(void) {
    return 0;
} // @stub
RVA(0x001482c0, 0x2e9)
i32 Gap_1482c0(void) {
    return 0;
} // @stub
RVA(0x00148720, 0x117)
i32 Gap_148720(void) {
    return 0;
} // @stub
RVA(0x00148ac0, 0x2b)
i32 Gap_148ac0(void) {
    return 0;
} // @stub
RVA(0x00148b80, 0xb5)
i32 Gap_148b80(void) {
    return 0;
} // @stub
RVA(0x00148f50, 0x61)
i32 Gap_148f50(void) {
    return 0;
} // @stub
RVA(0x001494b0, 0x11a)
i32 Gap_1494b0(void) {
    return 0;
} // @stub
RVA(0x00149780, 0x69)
i32 Gap_149780(void) {
    return 0;
} // @stub
RVA(0x0014ed10, 0xcc)
i32 Gap_14ed10(void) {
    return 0;
} // @stub
RVA(0x0014fb40, 0x3e)
i32 Gap_14fb40(void) {
    return 0;
} // @stub
RVA(0x0014fe90, 0x188)
i32 Gap_14fe90(void) {
    return 0;
} // @stub
RVA(0x00150660, 0x49)
i32 Gap_150660(void) {
    return 0;
} // @stub
RVA(0x001506b0, 0x1ec)
i32 Gap_1506b0(void) {
    return 0;
} // @stub
RVA(0x001508a0, 0x117)
i32 Gap_1508a0(void) {
    return 0;
} // @stub
RVA(0x00151b90, 0x70)
i32 Gap_151b90(void) {
    return 0;
} // @stub
RVA(0x001521c0, 0x2b)
i32 Gap_1521c0(void) {
    return 0;
} // @stub
RVA(0x001521f0, 0xbc)
i32 Gap_1521f0(void) {
    return 0;
} // @stub
RVA(0x001522b0, 0xf7)
i32 Gap_1522b0(void) {
    return 0;
} // @stub
RVA(0x001523b0, 0x3b)
i32 Gap_1523b0(void) {
    return 0;
} // @stub
RVA(0x00152570, 0x24)
i32 Gap_152570(void) {
    return 0;
} // @stub
RVA(0x00153330, 0x36)
i32 Gap_153330(void) {
    return 0;
} // @stub
RVA(0x00153470, 0x31a)
i32 Gap_153470(void) {
    return 0;
} // @stub
RVA(0x00155ff0, 0x22)
i32 Gap_155ff0(void) {
    return 0;
} // @stub
RVA(0x00156ad0, 0x1d2)
i32 Gap_156ad0(void) {
    return 0;
} // @stub
RVA(0x00157920, 0x24)
i32 Gap_157920(void) {
    return 0;
} // @stub
RVA(0x00157e90, 0x23)
i32 Gap_157e90(void) {
    return 0;
} // @stub
RVA(0x00157ec0, 0x20)
i32 Gap_157ec0(void) {
    return 0;
} // @stub
RVA(0x001581b0, 0x5b)
i32 Gap_1581b0(void) {
    return 0;
} // @stub
RVA(0x001582c0, 0xf6)
i32 Gap_1582c0(void) {
    return 0;
} // @stub
RVA(0x00158b10, 0x2c)
i32 Gap_158b10(void) {
    return 0;
} // @stub
RVA(0x00158fd0, 0x41)
i32 Gap_158fd0(void) {
    return 0;
} // @stub
RVA(0x00159020, 0x55)
i32 Gap_159020(void) {
    return 0;
} // @stub
RVA(0x00159090, 0x24)
i32 Gap_159090(void) {
    return 0;
} // @stub
RVA(0x00159150, 0x24)
i32 Gap_159150(void) {
    return 0;
} // @stub
RVA(0x001593e0, 0x53)
i32 Gap_1593e0(void) {
    return 0;
} // @stub
RVA(0x001595b0, 0x44)
i32 Gap_1595b0(void) {
    return 0;
} // @stub
RVA(0x00159a10, 0x57)
i32 Gap_159a10(void) {
    return 0;
} // @stub
RVA(0x00159db0, 0x5e)
i32 Gap_159db0(void) {
    return 0;
} // @stub
RVA(0x00159e10, 0x2e)
i32 Gap_159e10(void) {
    return 0;
} // @stub
RVA(0x00159f00, 0x22e)
i32 Gap_159f00(void) {
    return 0;
} // @stub
RVA(0x0015a210, 0x432)
i32 Gap_15a210(void) {
    return 0;
} // @stub
RVA(0x0015a650, 0x12c)
i32 Gap_15a650(void) {
    return 0;
} // @stub
RVA(0x0015a780, 0xd2)
i32 Gap_15a780(void) {
    return 0;
} // @stub
RVA(0x0015a8c0, 0x7d)
i32 Gap_15a8c0(void) {
    return 0;
} // @stub
RVA(0x0015a9a0, 0x23)
i32 Gap_15a9a0(void) {
    return 0;
} // @stub
RVA(0x0015a9d0, 0x45)
i32 Gap_15a9d0(void) {
    return 0;
} // @stub
RVA(0x0015aa20, 0x3c)
i32 Gap_15aa20(void) {
    return 0;
} // @stub
RVA(0x0015aa60, 0x23)
i32 Gap_15aa60(void) {
    return 0;
} // @stub
RVA(0x0015aaf0, 0x35)
i32 Gap_15aaf0(void) {
    return 0;
} // @stub
RVA(0x0015dbe0, 0xa3)
i32 Gap_15dbe0(void) {
    return 0;
} // @stub
RVA(0x0015f470, 0x193)
i32 Gap_15f470(void) {
    return 0;
} // @stub
RVA(0x00160450, 0xd6)
i32 Gap_160450(void) {
    return 0;
} // @stub
RVA(0x00160870, 0x43)
i32 Gap_160870(void) {
    return 0;
} // @stub
RVA(0x001608c0, 0xc0)
i32 Gap_1608c0(void) {
    return 0;
} // @stub
RVA(0x00160ef0, 0x42)
i32 Gap_160ef0(void) {
    return 0;
} // @stub
RVA(0x001610a0, 0xd4)
i32 Gap_1610a0(void) {
    return 0;
} // @stub
RVA(0x00161470, 0x2c)
i32 Gap_161470(void) {
    return 0;
} // @stub
RVA(0x00161640, 0x3a2)
i32 Gap_161640(void) {
    return 0;
} // @stub
RVA(0x001619f0, 0x1f7)
i32 Gap_1619f0(void) {
    return 0;
} // @stub
RVA(0x00161c50, 0x3f)
i32 Gap_161c50(void) {
    return 0;
} // @stub
RVA(0x00161fa0, 0x6c)
i32 Gap_161fa0(void) {
    return 0;
} // @stub
RVA(0x00163db0, 0x64)
i32 Gap_163db0(void) {
    return 0;
} // @stub
RVA(0x00164920, 0x35)
i32 Gap_164920(void) {
    return 0;
} // @stub
RVA(0x001651b0, 0x5d)
i32 Gap_1651b0(void) {
    return 0;
} // @stub
RVA(0x00165d30, 0x6b)
i32 Gap_165d30(void) {
    return 0;
} // @stub
RVA(0x001660b0, 0x33)
i32 Gap_1660b0(void) {
    return 0;
} // @stub
RVA(0x00166780, 0x57)
i32 Gap_166780(void) {
    return 0;
} // @stub
RVA(0x001667e0, 0x2f)
i32 Gap_1667e0(void) {
    return 0;
} // @stub
RVA(0x00166850, 0x29)
i32 Gap_166850(void) {
    return 0;
} // @stub
RVA(0x00166880, 0x29)
i32 Gap_166880(void) {
    return 0;
} // @stub
RVA(0x001668b0, 0x26)
i32 Gap_1668b0(void) {
    return 0;
} // @stub
RVA(0x001668e0, 0x2d)
i32 Gap_1668e0(void) {
    return 0;
} // @stub
RVA(0x00166910, 0x34)
i32 Gap_166910(void) {
    return 0;
} // @stub
RVA(0x00166950, 0x34)
i32 Gap_166950(void) {
    return 0;
} // @stub
RVA(0x00168a20, 0x46)
i32 Gap_168a20(void) {
    return 0;
} // @stub
RVA(0x00168f20, 0x40)
i32 Gap_168f20(void) {
    return 0;
} // @stub
RVA(0x00168fd0, 0x24)
i32 Gap_168fd0(void) {
    return 0;
} // @stub
RVA(0x001694f0, 0x11e)
i32 Gap_1694f0(void) {
    return 0;
} // @stub
RVA(0x001696d0, 0x2d)
i32 Gap_1696d0(void) {
    return 0;
} // @stub
RVA(0x00169890, 0x2d)
i32 Gap_169890(void) {
    return 0;
} // @stub
RVA(0x00169aa0, 0x2d)
i32 Gap_169aa0(void) {
    return 0;
} // @stub
RVA(0x00169c90, 0x72)
i32 Gap_169c90(void) {
    return 0;
} // @stub
RVA(0x00169e50, 0x45)
i32 Gap_169e50(void) {
    return 0;
} // @stub
RVA(0x00169ea0, 0x2d)
i32 Gap_169ea0(void) {
    return 0;
} // @stub
RVA(0x00169f80, 0x2d)
i32 Gap_169f80(void) {
    return 0;
} // @stub
RVA(0x0016a2e0, 0x57)
i32 Gap_16a2e0(void) {
    return 0;
} // @stub
RVA(0x0016a640, 0x2d)
i32 Gap_16a640(void) {
    return 0;
} // @stub
RVA(0x0016a980, 0x57)
i32 Gap_16a980(void) {
    return 0;
} // @stub
RVA(0x0016ade0, 0xb2)
i32 Gap_16ade0(void) {
    return 0;
} // @stub
RVA(0x0016aea0, 0x4e)
i32 Gap_16aea0(void) {
    return 0;
} // @stub
RVA(0x0016b0e0, 0x6b)
i32 Gap_16b0e0(void) {
    return 0;
} // @stub
RVA(0x0016b190, 0x3a)
i32 Gap_16b190(void) {
    return 0;
} // @stub
RVA(0x0016b230, 0xe1)
i32 Gap_16b230(void) {
    return 0;
} // @stub
RVA(0x0016b4e0, 0x2d)
i32 Gap_16b4e0(void) {
    return 0;
} // @stub
RVA(0x0016b660, 0xb3)
i32 Gap_16b660(void) {
    return 0;
} // @stub
RVA(0x0016bc40, 0x2d)
i32 Gap_16bc40(void) {
    return 0;
} // @stub
RVA(0x0016bf70, 0x2d)
i32 Gap_16bf70(void) {
    return 0;
} // @stub
RVA(0x0016c0d0, 0xa6)
i32 Gap_16c0d0(void) {
    return 0;
} // @stub
RVA(0x0016c200, 0x2d)
i32 Gap_16c200(void) {
    return 0;
} // @stub
RVA(0x0016c7d0, 0x2d)
i32 Gap_16c7d0(void) {
    return 0;
} // @stub
RVA(0x0016cc20, 0x74)
i32 Gap_16cc20(void) {
    return 0;
} // @stub
RVA(0x0016e220, 0x139)
i32 Gap_16e220(void) {
    return 0;
} // @stub
RVA(0x0016e6e0, 0x3e)
i32 Gap_16e6e0(void) {
    return 0;
} // @stub
RVA(0x0016e7a0, 0x48)
i32 Gap_16e7a0(void) {
    return 0;
} // @stub
RVA(0x0016ea20, 0x51)
i32 Gap_16ea20(void) {
    return 0;
} // @stub
RVA(0x001714e0, 0x66)
i32 Gap_1714e0(void) {
    return 0;
} // @stub
RVA(0x00171640, 0x3f2)
i32 Gap_171640(void) {
    return 0;
} // @stub
RVA(0x001726c0, 0x6b)
i32 Gap_1726c0(void) {
    return 0;
} // @stub
RVA(0x00172bd0, 0x6c)
i32 Gap_172bd0(void) {
    return 0;
} // @stub
RVA(0x00173720, 0x4e)
i32 Gap_173720(void) {
    return 0;
} // @stub
RVA(0x00173cb0, 0x4e)
i32 Gap_173cb0(void) {
    return 0;
} // @stub
RVA(0x00173dd0, 0x38f)
i32 Gap_173dd0(void) {
    return 0;
} // @stub
RVA(0x001741b0, 0x39)
i32 Gap_1741b0(void) {
    return 0;
} // @stub
RVA(0x001741f0, 0x4e)
i32 Gap_1741f0(void) {
    return 0;
} // @stub
RVA(0x00174770, 0x4e)
i32 Gap_174770(void) {
    return 0;
} // @stub
RVA(0x00175710, 0x69)
i32 Gap_175710(void) {
    return 0;
} // @stub
RVA(0x00176840, 0x288)
i32 Gap_176840(void) {
    return 0;
} // @stub
RVA(0x00176b00, 0x2c)
i32 Gap_176b00(void) {
    return 0;
} // @stub
RVA(0x00176da0, 0x4b)
i32 Gap_176da0(void) {
    return 0;
} // @stub
RVA(0x00176ec0, 0x64)
i32 Gap_176ec0(void) {
    return 0;
} // @stub
RVA(0x00176f30, 0x51)
i32 Gap_176f30(void) {
    return 0;
} // @stub
RVA(0x00177670, 0x27)
i32 Gap_177670(void) {
    return 0;
} // @stub
RVA(0x001786a0, 0x2a)
i32 Gap_1786a0(void) {
    return 0;
} // @stub
RVA(0x00178b00, 0x30)
i32 Gap_178b00(void) {
    return 0;
} // @stub
RVA(0x00178e60, 0x23)
i32 Gap_178e60(void) {
    return 0;
} // @stub
RVA(0x00178f50, 0x63)
i32 Gap_178f50(void) {
    return 0;
} // @stub
RVA(0x00179010, 0x78)
i32 Gap_179010(void) {
    return 0;
} // @stub
RVA(0x001790e0, 0x4f)
i32 Gap_1790e0(void) {
    return 0;
} // @stub
RVA(0x00179190, 0x84)
i32 Gap_179190(void) {
    return 0;
} // @stub
RVA(0x00179240, 0x22)
i32 Gap_179240(void) {
    return 0;
} // @stub
RVA(0x0017b950, 0x60b)
i32 Gap_17b950(void) {
    return 0;
} // @stub
RVA(0x0017f660, 0x2e6)
i32 Gap_17f660(void) {
    return 0;
} // @stub
RVA(0x0017f950, 0x24)
i32 Gap_17f950(void) {
    return 0;
} // @stub
RVA(0x0017ff30, 0x4c2)
i32 Gap_17ff30(void) {
    return 0;
} // @stub
RVA(0x00180640, 0x96c)
i32 Gap_180640(void) {
    return 0;
} // @stub
RVA(0x00181b00, 0x34f)
i32 Gap_181b00(void) {
    return 0;
} // @stub
RVA(0x00182900, 0x35)
i32 Gap_182900(void) {
    return 0;
} // @stub
RVA(0x00183170, 0x24)
i32 Gap_183170(void) {
    return 0;
} // @stub
RVA(0x001833f0, 0x38)
i32 Gap_1833f0(void) {
    return 0;
} // @stub
RVA(0x00184900, 0x43)
i32 Gap_184900(void) {
    return 0;
} // @stub
RVA(0x001849d0, 0x5b)
i32 Gap_1849d0(void) {
    return 0;
} // @stub
RVA(0x00184b10, 0x29)
i32 Gap_184b10(void) {
    return 0;
} // @stub
RVA(0x00184d50, 0x88)
i32 Gap_184d50(void) {
    return 0;
} // @stub
RVA(0x00184e60, 0x6d)
i32 Gap_184e60(void) {
    return 0;
} // @stub
RVA(0x00184ed0, 0x5b)
i32 Gap_184ed0(void) {
    return 0;
} // @stub
RVA(0x00184f30, 0x73)
i32 Gap_184f30(void) {
    return 0;
} // @stub
RVA(0x001851b0, 0x23)
i32 Gap_1851b0(void) {
    return 0;
} // @stub
RVA(0x00185240, 0x48)
i32 Gap_185240(void) {
    return 0;
} // @stub
RVA(0x00185290, 0x48)
i32 Gap_185290(void) {
    return 0;
} // @stub
RVA(0x00185520, 0x2c)
i32 Gap_185520(void) {
    return 0;
} // @stub
RVA(0x00185550, 0x2c)
i32 Gap_185550(void) {
    return 0;
} // @stub
RVA(0x00185690, 0x25)
i32 Gap_185690(void) {
    return 0;
} // @stub
RVA(0x001858a0, 0x2b)
i32 Gap_1858a0(void) {
    return 0;
} // @stub
RVA(0x001863d0, 0xf8)
i32 Gap_1863d0(void) {
    return 0;
} // @stub
RVA(0x00186550, 0xc6)
i32 Gap_186550(void) {
    return 0;
} // @stub
RVA(0x00191720, 0xdd)
i32 Gap_191720(void) {
    return 0;
} // @stub
RVA(0x00192360, 0x2d)
i32 Gap_192360(void) {
    return 0;
} // @stub
RVA(0x00193680, 0x5e)
i32 Gap_193680(void) {
    return 0;
} // @stub
