// AUTO-GENERATED by gruntz.analysis.gen_unmatched_stubs - do not hand-edit.
// engine_unmatched WORKLIST: real reconstruction targets that still need matching.
// Each is a genuine game/engine function body - reconstruct it into its real class
// TU (see docs/HANDOFF-unmatched.md for the doctrine + workflow). The CRT/MFC/zlib
// library implementations have been split out into UnmatchedLibrary.cpp (do NOT
// hand-reconstruct those - use the library / FID-tag them).
#include <rva.h>
