#ifndef GRUNTZ_STUB_zPTree_H
#define GRUNTZ_STUB_zPTree_H
// zPTree - RTTI inheritance + vtable carcass (no fields/bodies yet).
// vtable @0x1e94ac; generated by scripts/analysis/gen_class_skeletons.py.
#include "../rva.h"   // OVERRIDE (no-op under MSVC 5.0)
#include "zErrHandling.h"
#include "zPtrColl.h"

class zPTree : public zErrHandling, public zPtrColl {
public:
    virtual void slot_00();   // 0x0212e0
};
#endif  // GRUNTZ_STUB_zPTree_H
