// UnknownVTables.h - AUTO-GENERATED catalog of the discovered non-RTTI vtables
// (no Complete Object Locator => no recoverable class name). We DO know every
// address: each vtable is named by its src g_*Vtbl name when one exists, else by
// its RVA (Vtbl_<rva>); each slot is a named member carrying its target RVA + the
// function name where known (scalar/vector-deleting dtor, __purecall, or a matched
// fn) or sub_<rva> for the still-un-reconstructed engine virtuals. Slots are typed
// UnkVfn (void(void)) - TRACKING ONLY; this header emits no code, is not #included,
// and is matching-neutral. Generated by gruntz.analysis.vtable_scan from retail
// GRUNTZ.EXE. Sizes exact (reloc-run cut at every RTTI/code-referenced start).
#ifndef GRUNTZ_UNKNOWN_VTABLES_H
#define GRUNTZ_UNKNOWN_VTABLES_H

typedef void (*UnkVfn)(void);

// ClassWithUnknownVTable1  @ 0x005ef628  (6 slots)  refs x2  src:g_deviceConfigVtblA
// CATALOGED as ??_7CInputDevice@@6B@ via VTBL() in src/DinMgr2/DirectInputMgr2.cpp.
// Kept a manual stamp: CInputDevice is non-polymorphic (explicit m_vptr) and its /GX
// deleting-dtor chain re-stamps a 3-level base-subobject vtable sequence
// (0x5ef628/0x5ef680/0x5ef670); a real-virtual model needs the multilevel polymorphic
// base chain (eh-dtor-multilevel-polymorphic-chain.md) - deferred to the final sweep.
struct DeviceConfigVtblA {
    UnkVfn _scalar_deleting_destructor_; // [0] -> 0x1332e0 `scalar_deleting_destructor'
    UnkVfn CreateDeviceWrap;             // [1] -> 0x134260 CreateDeviceWrap
    UnkVfn Teardown;                     // [2] -> 0x133bf0 Teardown
    UnkVfn slot3_1332b0;                 // [3] -> 0x1332b0 sub_1332b0
    UnkVfn Poll;                         // [4] -> 0x133d00 Poll
    UnkVfn slot5_1332c0;                 // [5] -> 0x1332c0 sub_1332c0
};

// ClassWithUnknownVTable2  @ 0x005ef640  (6 slots)  refs x2  src:g_deviceConfigVtblB2
// CATALOGED as ??_7CDeviceConfigB@@6B@ via VTBL() in src/DinMgr2/DirectInputMgr2.cpp
// (device-B/mouse config). Non-polymorphic (explicit m_vptr, ctor-stamped); kept.
struct Vtbl_1ef640 {
    UnkVfn _scalar_deleting_destructor_; // [0] -> 0x1334d0 `scalar_deleting_destructor'
    UnkVfn CreateDeviceWrap;             // [1] -> 0x134260 CreateDeviceWrap
    UnkVfn FUN_00534360;                 // [2] -> 0x134360 FUN_00534360
    UnkVfn slot3_1332b0;                 // [3] -> 0x1332b0 sub_1332b0
    UnkVfn FUN_005343b0;                 // [4] -> 0x1343b0 FUN_005343b0
    UnkVfn slot5_1332c0;                 // [5] -> 0x1332c0 sub_1332c0
};

// ClassWithUnknownVTable3  @ 0x005ef658  (6 slots)  refs x2
struct Vtbl_1ef658 {
    UnkVfn _scalar_deleting_destructor_; // [0] -> 0x133440 `scalar_deleting_destructor'
    UnkVfn CreateDeviceWrap;             // [1] -> 0x134260 CreateDeviceWrap
    UnkVfn FUN_005346d0;                 // [2] -> 0x1346d0 FUN_005346d0
    UnkVfn slot3_1332b0;                 // [3] -> 0x1332b0 sub_1332b0
    UnkVfn FUN_005347d0;                 // [4] -> 0x1347d0 FUN_005347d0
    UnkVfn slot5_1332c0;                 // [5] -> 0x1332c0 sub_1332c0
};

// ClassWithUnknownVTable4  @ 0x005ef670  (4 slots)  refs x6  src:g_deviceConfigVtblC
struct DeviceConfigVtblC {
    UnkVfn vector_deleting_destructor; // [0] -> 0x133380 vector_deleting_destructor
    UnkVfn Create;                     // [1] -> 0x134cb0 Create
    UnkVfn ReleaseDevices;             // [2] -> 0x134d50 ReleaseDevices
    UnkVfn slot3_1332b0;               // [3] -> 0x1332b0 sub_1332b0
};

// ClassWithUnknownVTable5  @ 0x005ef680  (6 slots)  refs x4  src:g_deviceConfigVtblB
struct DeviceConfigVtblB {
    UnkVfn _scalar_deleting_destructor_; // [0] -> 0x133420 `scalar_deleting_destructor'
    UnkVfn CreateDeviceWrap;             // [1] -> 0x134260 CreateDeviceWrap
    UnkVfn ReleaseDevices;               // [2] -> 0x1342b0 ReleaseDevices
    UnkVfn slot3_1332b0;                 // [3] -> 0x1332b0 sub_1332b0
    UnkVfn slot4_133410;                 // [4] -> 0x133410 sub_133410
    UnkVfn slot5_1332c0;                 // [5] -> 0x1332c0 sub_1332c0
};

// ClassWithUnknownVTable6  @ 0x005ef6c8  (2 slots)  refs x4  src:g_PureVtbl
// The all-__purecall vtable of a 2-method ABSTRACT sound-element base (both slots ->
// 0x11fec0 __purecall).  It is never a live object's vtable: the Dsndmgr list helpers
// (SoundVoiceList.cpp RemoveMatching, SoundDevice.cpp FreeSamples) stamp it into a
// reaped element right before RezFree - the inlined trivial base-dtor vptr restamp, a
// reloc-masked DIR32 store.  Its ??_7 is emitted by the OWNING concrete element class's
// ctor (DSoundVoice / the sample node, in an as-yet-unmodeled TU), NOT by these helper
// TUs, so it cannot be auto-emitted where it is referenced; kept as the g_PureVtbl DATA
// extern (bound at 0x1ef6c8) until the element class is modeled real-polymorphic.
// Placeholder struct removed.

// ClassWithUnknownVTable7  @ 0x005ef6d0  (3 slots)  refs x1
// CATALOGED as ??_7DSoundVoice@@6B@ via VTBL() in src/Dsndmgr/DSoundVoice.cpp (the
// 0x28-byte playing-voice node). Non-polymorphic (explicit m_vtbl; its ctor 0x136fe0
// lives in another TU and hand-stamps the vtable, so cl cannot auto-emit it); kept.
struct Vtbl_1ef6d0 {
    UnkVfn Tick_137060;  // [0] -> 0x137060 DSoundVoice::Tick
    UnkVfn Stop_1370d0;  // [1] -> 0x1370d0 DSoundVoice::Stop
    UnkVfn slot2_137630; // [2] -> 0x137630 sub_137630
};

// ClassWithUnknownVTable8  @ 0x005ef6e0  (3 slots)  refs x1  src:g_StreamVoiceFeederVtbl
// REALIZED as ??_7StreamVoiceFeeder@@6B@ (real StreamFeeder-derived voice feeder in
// src/Dsndmgr/StreamFeeder.h; cl auto-emits). Placeholder removed.

// ClassWithUnknownVTable9  @ 0x005ef6f0  (3 slots)  refs x2  src:g_StreamFeederVtbl
// REALIZED as ??_7StreamFeeder@@6B@ (real polymorphic StreamFeeder base in
// src/Dsndmgr/StreamFeeder.h; cl auto-emits). Placeholder removed.

// ClassWithUnknownVTable10  @ 0x005ef700  (16 slots)  refs x3  src:g_innerSoundVtbl
// REALIZED as ??_7CGruntzSoundInnerZ@@6B@ (real polymorphic CGruntzSoundInnerZ in
// src/Dsndmgr/CGruntzSoundZ.cpp; cl auto-emits the vtable). Placeholder removed.

// ClassWithUnknownVTable11  @ 0x005ef750
// REALIZED as ??_7CSymParser@@6B@ (real polymorphic CSymParser in
// src/Bute/SymParser.cpp; 3-slot primary vtable, non-virtual dtor). Placeholder
// removed.

// ClassWithUnknownVTable12  @ 0x005ef768 - REALIZED as ??_7CRezItmBase@@6B@ (the shared
// resource-tree node base, real polymorphic with 6 pure virtuals + virtual dtor in
// include/Rez/RezMgr.h; cl auto-emits). Cataloged via VTBL(CRezItmBase, 0x001ef768) in
// src/Rez/RezMgr.cpp. Placeholder removed.

// ClassWithUnknownVTable13  @ 0x005ef788 - REALIZED as ??_7CRezItm@@6B@ (the leaf
// resource/file node CRezItm : CRezItmBase overriding the dtor + Read/Close stream
// slots; cl auto-emits). Cataloged via VTBL(CRezItm, 0x001ef788) in src/Rez/RezMgr.cpp.
// Placeholder removed.

// ClassWithUnknownVTable14  @ 0x005ef7a8
// REALIZED as ??_7CRezDir@@6B@ (real polymorphic CRezDir : CRezItmBase in
// include/Rez/RezMgr.h; its ctor 0x13c940 cl-auto-stamps the derived vtable).
// Cataloged via VTBL(CRezDir, 0x001ef7a8). Placeholder removed.

// ClassWithUnknownVTable15  @ 0x005ef7d0  (8 slots)  refs x2
struct Vtbl_1ef7d0 {
    UnkVfn slot0_13cef0;                 // [0] -> 0x13cef0 sub_13cef0
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x13cb60 `scalar_deleting_destructor'
    UnkVfn FUN_0053cc00;                 // [2] -> 0x13cc00 FUN_0053cc00
    UnkVfn FUN_0053cca0;                 // [3] -> 0x13cca0 FUN_0053cca0
    UnkVfn slot4_13cd40;                 // [4] -> 0x13cd40 sub_13cd40
    UnkVfn slot5_13cd50;                 // [5] -> 0x13cd50 sub_13cd50
    UnkVfn FUN_0053cd60;                 // [6] -> 0x13cd60 FUN_0053cd60
    UnkVfn slot7_13cdb0;                 // [7] -> 0x13cdb0 sub_13cdb0
};

// ClassWithUnknownVTable16 @ 0x005ef7f0 (was src:g_fileImageVtbl) - CONVERTED to
// real polymorphic: CFileImage / CFileImageSurface / CImageSurfaceItemInit now
// carry the virtuals and cl emits their ??_7 (see src/Image/Image.cpp). Catalog
// entry removed per the all-vtables mandate.

// ClassWithUnknownVTable17-20 @ 0x005efa58 / a88 / ab8 / ae8 - REALIZED as the pool-A
// surface-item family in src/Gruntz/CDDrawPtrCollections.cpp.  GENUINE C++ VTABLES
// (verified against the retail .rdata, NOT a pointer-to-member table): a 9-slot
// polymorphic base (0x5ef7f0, modeled as CPoolItemBase; the base vtable datum itself is
// bound in CDirectDrawMgr.cpp as g_poolItemVtbl) plus four derived subclasses that each
// override {virtual dtor slot 0, the slot-2 init, the slot-6 surface op} and add their
// own init tail slots.  cl now auto-emits each ??_7 (VTBL-bound):
//   0x5efa58  CPoolItemA    (12 slots; dtor 0x142820, tail 9=0x148890/10=0x148940/11=0x148840)
//   0x5efa88  CPoolItemA88  (11 slots; tail 9=0x148a50/10=0x148ac0)
//   0x5efab8  CPoolItemAB8  (11 slots; slot 2=0x148b50; tail 9=0x148af0/10=0x148b80)
//   0x5efae8  CPoolItemAE8  (10 slots; dtor 0x142d40, slot 2=0x148cc0; tail 9=0x148c40)
// Placeholder structs removed.  (The init slots are invoked with per-subclass-varying
// arities; a single C++ virtual signature serves the common arity - the odd 3-arg ab8
// call site over-pushes two zeros, an accepted residual of the honest polymorphic
// model.  All slot fns live in Image.cpp / boundary so the emitted vtable slots
// reloc-mask against the retail RVAs.)

// ClassWithUnknownVTable21  @ 0x005efb28  (5 slots)  refs x3  src:g_shadeArrayVtbl
// REALIZED as ??_7CShadeTableArray@@6B@ (real CObject-derived array in
// src/DDrawMgr/ShadeTableCache.{h,cpp}; cl auto-emits it + the CObject-masking
// ??_7CShadeArrayBase). Placeholder removed.

// ClassWithUnknownVTable22  @ 0x005efb80  (10 slots)  refs x7  src:g_siriusWorkerVtbl
// REALIZED as ??_7SiriusWorkerObj@@6B@ (real polymorphic SiriusWorkerObj built via
// `new` in src/Gruntz/CDDrawWorkerCache.cpp; cl auto-emits the vtable; VTBL(SiriusWorkerObj,
// 0x001efb80)). Placeholder removed.

// ClassWithUnknownVTable23  @ 0x005efba8  (5 slots)  src:g_aniElemVtbl
// REALIZED as ??_7CAniElementObj@@6B@ (real polymorphic CAniElementObj in
// src/Gruntz/CDDrawSubMgrAni.cpp; cl auto-emits the vtable). Placeholder removed.

// ClassWithUnknownVTable24  @ 0x005efbc0  (10 slots)  refs x4  src:g_remusNodeVtbl
// REALIZED as ??_7CRemusNode@@6B@ (real polymorphic CRemusNode : CRemusNodeBase in
// src/Gruntz/CRemusNode.cpp; cl auto-emits the vtable). Placeholder removed.

// ClassWithUnknownVTable25  @ 0x005efbe8  (17 slots)  refs x6  src:g_severusWorkerVtbl
// REALIZED as ??_7SeverusWorkerObj@@6B@ (real polymorphic SeverusWorkerObj built via
// `new` in src/Gruntz/CDDrawWorkerRegistry.cpp; cl auto-emits the 17-slot vtable;
// VTBL(SeverusWorkerObj, 0x001efbe8)). Same retail class as CSeverusEntryList
// (its dtor 0x1557a0 = slot[1] ??_G phase). Placeholder removed.

// ClassWithUnknownVTable26  @ 0x005efc30  (9 slots)  refs x12  src:g_severusWorkerBaseVtbl
// REALIZED as ??_7SeverusWorkerBase@@6B@ (real polymorphic base of SeverusWorkerObj in
// src/Gruntz/CDDrawWorkerRegistry.cpp; cl auto-emits the 9-slot base vtable;
// VTBL(SeverusWorkerBase, 0x001efc30)). Placeholder removed.

// ClassWithUnknownVTable27  @ 0x005efc58  (8 slots)  refs x2
struct Vtbl_1efc58 {
    UnkVfn slot0_1bef01;                 // [0] -> 0x1bef01 sub_1bef01
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x155890 `scalar_deleting_destructor'
    UnkVfn slot2_0028ec;                 // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;                 // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;                 // [4] -> 0x004034 sub_004034
    UnkVfn UnknownVirtualMethod14;       // [5] -> 0x155f00 UnknownVirtualMethod14
    UnkVfn UnknownVirtualMethod18;       // [6] -> 0x155900 UnknownVirtualMethod18
    UnkVfn Cleanup_155e20;               // [7] -> 0x155e20 Cleanup_155e20
};

// ClassWithUnknownVTable28  @ 0x005efc78  (9 slots)  refs x2  src:g_catalogVtbl
// REALIZED as ??_7CDDrawSubMgrLeaf@@6B@ (real polymorphic CDDrawSubMgrLeaf in
// src/Gruntz/CDDrawSubMgrLeaf.cpp; cl auto-emits the 9-slot vtable;
// VTBL(CDDrawSubMgrLeaf, 0x001efc78)). Placeholder removed.

// ClassWithUnknownVTable29  @ 0x005efca0  (9 slots)  refs x2  src:g_leafScanVtbl
// REALIZED as ??_7CDDrawSubMgrLeafScan@@6B@ (real polymorphic CDDrawSubMgrLeafScan in
// src/Gruntz/CDDrawSubMgrLeafScan.cpp; cl auto-emits the 9-slot vtable;
// VTBL(CDDrawSubMgrLeafScan, 0x001efca0)). Placeholder removed.

// ClassWithUnknownVTable30  @ 0x005efcc8  (13 slots)  refs x2  src:g_albusClassVtbl
// REALIZED as ??_7CDDrawWorkerMapSmall@@6B@ (real polymorphic CDDrawWorkerMapSmall in
// src/Gruntz/CDDrawWorkerMapSmall.cpp; cl auto-emits the 13-slot vtable;
// VTBL(CDDrawWorkerMapSmall, 0x001efcc8)). Placeholder removed.

// ClassWithUnknownVTable31  @ 0x005efd00  (10 slots)  refs x2
// REALIZED as ??_7CDDrawWorkerCache@@6B@ (real polymorphic CDDrawWorkerCache in
// src/Gruntz/CDDrawWorkerCache.cpp; dtor 0x157700 / VirtualMethodUnknown20 0x1576f0 /
// VirtualMethodUnknown24 0x1652c0 cl-auto-emit the 10-slot vtable;
// VTBL(CDDrawWorkerCache, 0x001efd00)). Placeholder removed.

// ClassWithUnknownVTable32  @ 0x005efd28  (23 slots)  refs x2
struct Vtbl_1efd28 {
    UnkVfn slot0_1bef01;           // [0] -> 0x1bef01 sub_1bef01
    UnkVfn Stub_156df0;            // [1] -> 0x156df0 Stub_156df0
    UnkVfn slot2_0028ec;           // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;           // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;           // [4] -> 0x004034 sub_004034
    UnkVfn slot5_156dc0;           // [5] -> 0x156dc0 sub_156dc0
    UnkVfn VirtualMethodUnknown18; // [6] -> 0x154aa0 VirtualMethodUnknown18
    UnkVfn VirtualMethodUnknown1C; // [7] -> 0x154ac0 VirtualMethodUnknown1C
    UnkVfn VirtualMethodUnknown20; // [8] -> 0x156de0 VirtualMethodUnknown20
    UnkVfn VirtualMethodUnknown24; // [9] -> 0x154df0 VirtualMethodUnknown24
    UnkVfn VirtualMethodUnknown28; // [10] -> 0x154f60 VirtualMethodUnknown28
    UnkVfn VirtualMethodUnknown2C; // [11] -> 0x154f40 VirtualMethodUnknown2C
    UnkVfn VirtualMethodUnknown30; // [12] -> 0x154ce0 VirtualMethodUnknown30
    UnkVfn VirtualMethodUnknown34; // [13] -> 0x154f20 VirtualMethodUnknown34
    UnkVfn VirtualMethodUnknown38; // [14] -> 0x154ae0 VirtualMethodUnknown38
    UnkVfn VirtualMethodUnknown3C; // [15] -> 0x154f00 VirtualMethodUnknown3C
    UnkVfn VirtualMethodUnknown40; // [16] -> 0x154be0 VirtualMethodUnknown40
    UnkVfn Stub_156e80;            // [17] -> 0x156e80 Stub_156e80
    UnkVfn Stub_154f80;            // [18] -> 0x154f80 Stub_154f80
    UnkVfn Stub_155160;            // [19] -> 0x155160 Stub_155160
    UnkVfn VirtualMethodUnknown50; // [20] -> 0x155280 VirtualMethodUnknown50
    UnkVfn VirtualMethodUnknown54; // [21] -> 0x156ec0 VirtualMethodUnknown54
    UnkVfn MapTeardown_1552b0;     // [22] -> 0x1552b0 MapTeardown_1552b0
};

// ClassWithUnknownVTable33  @ 0x005efd88  (14 slots)  refs x2
struct Vtbl_1efd88 {
    UnkVfn slot0_1bef01;                 // [0] -> 0x1bef01 sub_1bef01
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x156f30 `scalar_deleting_destructor'
    UnkVfn slot2_0028ec;                 // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;                 // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;                 // [4] -> 0x004034 sub_004034
    UnkVfn VirtualMethodUnknown14;       // [5] -> 0x156f00 VirtualMethodUnknown14
    UnkVfn Stub_156fc0;                  // [6] -> 0x156fc0 Stub_156fc0
    UnkVfn CDDrawWorkerList_163bc0;      // [7] -> 0x163bc0 CDDrawWorkerList_163bc0
    UnkVfn VirtualMethodUnknown20;       // [8] -> 0x156f20 VirtualMethodUnknown20
    UnkVfn VirtualMethodUnknown24;       // [9] -> 0x156fd0 VirtualMethodUnknown24
    UnkVfn VirtualMethodUnknown28;       // [10] -> 0x1573e0 VirtualMethodUnknown28
    UnkVfn VirtualMethodUnknown2C;       // [11] -> 0x157330 VirtualMethodUnknown2C
    UnkVfn VirtualMethodUnknown30;       // [12] -> 0x157150 VirtualMethodUnknown30
    UnkVfn VirtualMethodUnknown34;       // [13] -> 0x163bf0 VirtualMethodUnknown34
};

// ClassWithUnknownVTable34  @ 0x005efdc0  (17 slots)  refs x2
struct Vtbl_1efdc0 {
    UnkVfn slot0_1bef01;             // [0] -> 0x1bef01 sub_1bef01
    UnkVfn Stub_157610;              // [1] -> 0x157610 Stub_157610
    UnkVfn slot2_0028ec;             // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;             // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;             // [4] -> 0x004034 sub_004034
    UnkVfn VirtualMethodUnknown14;   // [5] -> 0x1575e0 VirtualMethodUnknown14
    UnkVfn VirtualMethodUnknown1C;   // [6] -> 0x1576c0 VirtualMethodUnknown1C
    UnkVfn VirtualMethodUnknown1C_7; // [7] -> 0x1591e0 VirtualMethodUnknown1C
    UnkVfn VirtualMethodUnknown20;   // [8] -> 0x157600 VirtualMethodUnknown20
    UnkVfn Stub_159a70;              // [9] -> 0x159a70 Stub_159a70
    UnkVfn VirtualMethodUnknown28;   // [10] -> 0x159c90 VirtualMethodUnknown28
    UnkVfn VirtualMethodUnknown2C;   // [11] -> 0x159cc0 VirtualMethodUnknown2C
    UnkVfn VirtualMethodUnknown30;   // [12] -> 0x159cf0 VirtualMethodUnknown30
    UnkVfn VirtualMethodUnknown34;   // [13] -> 0x159d40 VirtualMethodUnknown34
    UnkVfn VirtualMethodUnknown38;   // [14] -> 0x159d90 VirtualMethodUnknown38
    UnkVfn Stub_1591f0;              // [15] -> 0x1591f0 Stub_1591f0
    UnkVfn slot16_159f00;            // [16] -> 0x159f00 sub_159f00
};

// ClassWithUnknownVTable35  @ 0x005efe08  (10 slots)  refs x2
// REALIZED as ??_7CDDrawSubMgrDraco@@6B@ (real polymorphic CDDrawSubMgrDraco in
// src/Gruntz/CDDrawSubMgrDraco.cpp; dtor 0x1574b0 / VirtualMethodUnknown14 0x157480 /
// VirtualMethodUnknown1C 0x158ac0 cl-auto-emit the 10-slot vtable;
// VTBL(CDDrawSubMgrDraco, 0x001efe08)). Placeholder removed.

// ClassWithUnknownVTable36  @ 0x005efe30  src:g_fileMemVtbl
// REALIZED as ??_7CFileMem@@6B@ (real polymorphic CFileMem in src/Io/FileMem.cpp;
// 13-slot CFile-style vtable, scanner-split here at +0xc). Placeholder removed.

// ClassWithUnknownVTable37  @ 0x005efe3c  (10 slots)  refs x28
// SPLIT-VIEW ARTIFACT of ??_7CFileMem@@6B@ (0x005efe30): the scanner cut CFileMem's
// one 13-slot CFile-style vtable at +0xc (0x5efe30 -> 0x5efe3c). Already realized as
// the real polymorphic CFileMem in src/Io/FileMem.cpp (VTBL(CFileMem, 0x005efe30));
// this is not a separate class. Placeholder removed.

// ClassWithUnknownVTable38  @ 0x005efe68  src:g_fileMemBaseVtbl
// REALIZED as ??_7CFileMemBase@@6B@ (abstract base of CFileMem in
// src/Io/FileMem.cpp; 13-slot vtable, scanner-split here at +0xc). Placeholder
// removed.

// ClassWithUnknownVTable39  @ 0x005efe74  (10 slots)  refs x4
// SPLIT-VIEW ARTIFACT of ??_7CFileMemBase@@6B@ (0x005efe68): the scanner cut
// CFileMemBase's one 13-slot vtable at +0xc (0x5efe68 -> 0x5efe74). Already realized
// as the real abstract CFileMemBase in src/Io/FileMem.cpp (VTBL(CFileMemBase,
// 0x005efe68); __purecall in the pure slots); not a separate class. Placeholder removed.

// ClassWithUnknownVTable40  @ 0x005efea0  (12 slots)  refs x1  src:g_hagridWorkerVtblA
// REALIZED as ??_7HagridWorkerA@@6B@ (real polymorphic HagridWorkerA in
// src/Gruntz/CDDrawWorkerList.cpp, built via `new`; vtable_names.csv 0x1efea0/0x30).
// Placeholder removed.

// ClassWithUnknownVTable41  @ 0x005efed0  (14 slots)  refs x3  src:g_hagridWorkerVtblB
// REALIZED as ??_7HagridWorkerB@@6B@ (real polymorphic HagridWorkerB in
// src/Gruntz/CDDrawWorkerList.cpp, built via `new`; vtable_names.csv 0x1efed0/0x38).
// Placeholder removed.

// ClassWithUnknownVTable42  @ 0x005eff08  (9 slots)  refs x3  src:g_leafElemVtbl
// REALIZED as ??_7LeafElementObj@@6B@ (real polymorphic 0x1c-byte cache element in
// src/Gruntz/CDDrawSubMgrLeafScan.cpp; ctor/dtor cl-auto-stamp; 5 grand-base slots +
// 4 leaf virtuals; VTBL(LeafElementObj, 0x001eff08)). The grand-base dtor vtable
// (0x5e8cb4) is the cl-emitted ??_7LeafElementBase - manual g_remusBaseDtorVtbl stamp
// removed. Placeholder removed.

// ClassWithUnknownVTable43  @ 0x005eff30  (15 slots)  refs x3
struct Vtbl_1eff30 {
    UnkVfn slot0_1bef01;                 // [0] -> 0x1bef01 sub_1bef01
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x1590d0 `scalar_deleting_destructor'
    UnkVfn slot2_0028ec;                 // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;                 // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;                 // [4] -> 0x004034 sub_004034
    UnkVfn slot5_159090;                 // [5] -> 0x159090 sub_159090
    UnkVfn slot6_001c08;                 // [6] -> 0x001c08 sub_001c08
    UnkVfn TeardownSurface;              // [7] -> 0x163e20 TeardownSurface
    UnkVfn slot8_1590c0;                 // [8] -> 0x1590c0 sub_1590c0
    UnkVfn slot9_158fd0;                 // [9] -> 0x158fd0 sub_158fd0
    UnkVfn slot10_164250;                // [10] -> 0x164250 sub_164250
    UnkVfn slot11_163db0;                // [11] -> 0x163db0 sub_163db0
    UnkVfn FUN_00563c90;                 // [12] -> 0x163c90 FUN_00563c90
    UnkVfn slot13_163e50;                // [13] -> 0x163e50 sub_163e50
    UnkVfn slot14_163ee0;                // [14] -> 0x163ee0 sub_163ee0
};

// ClassWithUnknownVTable44  @ 0x005eff70  (11 slots)  refs x1
struct Vtbl_1eff70 {
    UnkVfn slot0_1bef01;                 // [0] -> 0x1bef01 sub_1bef01
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x159190 `scalar_deleting_destructor'
    UnkVfn slot2_0028ec;                 // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;                 // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;                 // [4] -> 0x004034 sub_004034
    UnkVfn slot5_159150;                 // [5] -> 0x159150 sub_159150
    UnkVfn slot6_001c08;                 // [6] -> 0x001c08 sub_001c08
    UnkVfn slot7_1591d0;                 // [7] -> 0x1591d0 sub_1591d0
    UnkVfn slot8_159180;                 // [8] -> 0x159180 sub_159180
    UnkVfn
        directx_wrapper_caller_1644a0_DirectDrawCreate_DirectDrawEnumerateA; // [9] -> 0x1644a0 directx_wrapper_caller_1644a0_DirectDrawCreate_DirectDrawEnumerateA
    UnkVfn slot10_1646b0; // [10] -> 0x1646b0 sub_1646b0
};

// ClassWithUnknownVTable45  @ 0x005effa0  (11 slots)  refs x1  src:g_severusWorker3Vtbl
// REALIZED as ??_7CSeverusWorker3@@6B@ (real polymorphic leaf-worker whose 3-arg
// ctor 0x158f30 cl-auto-stamps the vptr in src/Gruntz/CDDrawSubMgr.cpp;
// VTBL(CSeverusWorker3, 0x001effa0)). Placeholder removed.

// ClassWithUnknownVTable46  @ 0x005effd0  (19 slots)  refs x2
struct Vtbl_1effd0 {
    UnkVfn slot0_1bef01;                 // [0] -> 0x1bef01 sub_1bef01
    UnkVfn _scalar_deleting_destructor_; // [1] -> 0x15c050 `scalar_deleting_destructor'
    UnkVfn slot2_0028ec;                 // [2] -> 0x0028ec sub_0028ec
    UnkVfn slot3_00106e;                 // [3] -> 0x00106e sub_00106e
    UnkVfn slot4_004034;                 // [4] -> 0x004034 sub_004034
    UnkVfn slot5_15c000;                 // [5] -> 0x15c000 sub_15c000
    UnkVfn slot6_001c08;                 // [6] -> 0x001c08 sub_001c08
    UnkVfn FUN_0055c200;                 // [7] -> 0x15c200 FUN_0055c200
    UnkVfn slot8_15c020;                 // [8] -> 0x15c020 sub_15c020
    UnkVfn Helper_164790;                // [9] -> 0x164790 Helper_164790
    UnkVfn Setup;                        // [10] -> 0x150d60 Setup
    UnkVfn FUN_005660f0;                 // [11] -> 0x1660f0 FUN_005660f0
    UnkVfn slot12_1661d0;                // [12] -> 0x1661d0 sub_1661d0
    UnkVfn slot13_1662a0;                // [13] -> 0x1662a0 sub_1662a0
    UnkVfn slot14_1664a0;                // [14] -> 0x1664a0 sub_1664a0
    UnkVfn Play;                         // [15] -> 0x151150 Play
    UnkVfn FUN_0055c1d0;                 // [16] -> 0x15c1d0 FUN_0055c1d0
    UnkVfn slot17_15c030;                // [17] -> 0x15c030 sub_15c030
    UnkVfn slot18_15c040;                // [18] -> 0x15c040 sub_15c040
};

// ClassWithUnknownVTable47  @ 0x005f0020  (16 slots)  refs x9  src:g_wwdGameObjectVtbl
// REALIZED as ??_7CWwdGameObjectE@@6B@ (the "Mid" base game object in
// src/Gruntz/WwdGameObjectEh.cpp; cl auto-emits it). ORPHAN: the delinked 0x5f0020
// datum stays named g_wwdGameObjectVtbl because the CWwdObjMgrFactories factories
// MANUAL-stamp it (`*(void**)obj = &g_wwdGameObjectVtbl`) and cannot reference the
// compiler ??_7 without a `new`-based ctor rewrite -> NO VTBL (would dup-DATA the
// bound g_wwdGameObjectVtbl). Placeholder removed.

// ClassWithUnknownVTable48  @ 0x005f0060  (17 slots)  refs x2
// REALIZED as ??_7CWwdGameObjectF@@6B@ (the 0x159440-final variant in
// src/Gruntz/WwdGameObjectEh.cpp; the 0x18c-byte object). ORPHAN (same reason as
// VTable47: bound to g_wwd159440FinalVtbl via the factory manual stamp). NO VTBL.

// ClassWithUnknownVTable49  @ 0x005f00a8  (16 slots)  refs x6  src:g_wwdObjVtbl
// REALIZED as ??_7CWwdGameObjectA@@6B@ (the 0x166640-final variant in
// src/Gruntz/WwdGameObjectEh.cpp; the 0x1dc-byte object). ORPHAN (bound to
// g_wwdObjVtbl via the factory manual stamp). NO VTBL. Placeholder removed.

// ClassWithUnknownVTable50  @ 0x005f00e8  (16 slots)  refs x2
// REALIZED as ??_7CWwdGameObjectB@@6B@ (the 0x1598d0-final 0x1fc-byte object). The
// flat manual-restamp dtor is now a REAL 4-level polymorphic chain in
// src/Gruntz/WwdGameObjectEh.cpp (CWwdGameObjectB : WwdBLevel2 : WwdBMid : WwdBRemus);
// cl auto-emits the four per-level ??_7 (orphans, since the factory in
// CWwdObjMgrFactories.cpp still manual-stamps g_wwd1598d0FinalVtbl @0x5f00e8) and the
// multi-phase vptr-restamp dtor chain. NO VTBL (would dup-DATA the factory's bound
// g_wwd1598d0FinalVtbl). Placeholder removed.

// ClassWithUnknownVTable51  @ 0x005f0128  src:g_wwdSubVtbl
// REALIZED as ??_7CAniAdvanceCursor@@6B@ (real polymorphic CAniAdvanceCursor, the
// WWD sub-object class, in src/Wwd/CAniAdvanceCursor.cpp; cl auto-emits the 9-slot
// vtable). WwdFile.cpp's +0x1A0 sub-object stamp reloc-masks against it.
// Placeholder removed.

// ClassWithUnknownVTable52  @ 0x005f0150  (18 slots)  refs x2  src:g_gameLevelVtbl
// REALIZED as ??_7CGameLevel@@6B@ (real polymorphic CGameLevel : CSeverusWorker in
// src/Gruntz/GameLevel.cpp; cl auto-emits the 18-slot vtable + the two-phase vptr
// stamp - base ??_7CSeverusWorker orphan then derived @0x5f0150). The matched slots
// (ScalarDtor/IsLoaded/Unload/GetClassId + SetCoordsAndLoad38/3C/40/SetCoords/
// SetCoordExtents/LoadWwd/LoadFromSource/LoadFromFile/ReleaseChildren) point at the
// real methods; the base-thunk slots (0/2/3/4/6) reloc-mask.
// VTBL(CGameLevel, 0x001f0150). Placeholder removed.

// ClassWithUnknownVTable53  @ 0x005f0198  (18 slots)  refs x1  src:g_imageSet1Vtbl
// REALIZED as ??_7CImageSet1@@6B@ (flat 18-slot CImageSet1 in src/Gruntz/GameLevel.cpp;
// cl auto-emits it; the INLINE ctor auto-stamps the vptr for `new CImageSet1`). Slot 5
// (+0x14 Parse @0x166d40) is the matched body; the rest reloc-mask.
// VTBL(CImageSet1, 0x001f0198). Placeholder removed.

// ClassWithUnknownVTable54  @ 0x005f01e0  (18 slots)  refs x1  src:g_imageSet2Vtbl
// REALIZED as ??_7CImageSet2@@6B@ (flat 18-slot CImageSet2 in src/Gruntz/GameLevel.cpp;
// cl auto-emits it). Slot 5 (+0x14 Parse @0x166990) matched; the rest reloc-mask.
// VTBL(CImageSet2, 0x001f01e0). Placeholder removed.

// ClassWithUnknownVTable55  @ 0x005f0228  (18 slots)  refs x2  src:g_imageSet3Vtbl
// REALIZED as ??_7CImageSet3@@6B@ (flat 18-slot CImageSet3 factory variant in
// src/Gruntz/GameLevel.cpp; cl auto-emits it). Slot 5 (+0x14 Parse @0x166d70)
// matched; the rest reloc-mask. VTBL(CImageSet3, 0x001f0228). Placeholder removed.
// (Distinct from the 0xb0-byte collection CImageSet3 in CImageSet3.cpp - same name,
// different class; that one owns no cl-emitted vtable.)

// ClassWithUnknownVTable56  @ 0x005f0270  (12 slots)  refs x2  src:g_severusWorkerHostVtbl
// REALIZED as ??_7CSeverusWorkerHost@@6B@ (real polymorphic CSeverusBase-derived host
// in src/Gruntz/CSeverusWorkerHost.cpp; ctor 0x1615a0 / dtor 0x163af0 cl-auto-stamp;
// VTBL(CSeverusWorkerHost, 0x001f0270)). Placeholder removed.

// ClassWithUnknownVTable57  @ 0x005f02a8  (5 slots)  refs x4  src:g_wwdGridIterVtbl
// REALIZED as ??_7CWwdGridIter@@6B@ (real polymorphic 5-slot CObject-style cursor in
// src/Gruntz/WwdSpatialMgr.cpp; cl auto-emits the vtable + implicit vptr-first stamp).
// NO VTBL: 0x5f02a8 is SHARED (also g_planeRenderVtbl in wwdfile), so the emitted
// ??_7CWwdGridIter is an orphan (unpaired, matching-neutral). Placeholder removed.

// ClassWithUnknownVTable58  @ 0x005f02c0  (5 slots)  refs x2  src:g_aniRecordVtbl
// REALIZED as ??_7CAniRecordPrimary@@6B@ (real polymorphic primary base of CAniRecord in
// src/Gruntz/CAniRecord.cpp; cl auto-emits the 5-slot vtable;
// VTBL(CAniRecordPrimary, 0x001f02c0)). Placeholder removed.

// ClassWithUnknownVTable59  @ 0x005f02d8  (14 slots)  refs x5  src:g_albusWorkerVtbl
// REALIZED as ??_7CAniRecordBase2@@6B@ (real polymorphic secondary base of CAniRecord in
// src/Gruntz/CAniRecord.cpp; cl auto-emits the 14-slot vtable;
// VTBL(CAniRecordBase2, 0x001f02d8)). Also modeled (truncated 12-slot view) as
// AlbusWorkerObj in CDDrawWorkerMapSmall.cpp. Placeholder removed.

// ClassWithUnknownVTable60  @ 0x005f0310  (6 slots)  refs x3
// REALIZED as ??_7SubWidget_168080@@6B@ (flat 6-slot polymorphic SubWidget_168080 in
// src/Gruntz/ApiHiCallers.cpp - the compound-widget's sub-widget; cl auto-emits the
// vtable + the INLINE-ctor vptr stamp for `new SubWidget_168080`). All 6 slots are
// engine (base-thunk / 0x168280 scalar dtor / 0x168060) declared-only -> reloc-mask.
// VTBL(SubWidget_168080, 0x001f0310). Placeholder removed.

// ClassWithUnknownVTable61  @ 0x005f0328  (6 slots)  refs x2  src:g_wwdGridVtbl
// REALIZED as ??_7CWwdGrid@@6B@ (real polymorphic abstract CWwdGrid : CRemusBase in
// include/Gruntz/WwdGrid.h; cl auto-emits the 6-slot vtable with __purecall @slot5).
// VTBL(CWwdGrid, 0x001f0328) pairs it (RVA was unbound). Placeholder removed.

// ClassWithUnknownVTable62  @ 0x005f0748
// REALIZED as ??_7InterfaceObject@@6B@ (real polymorphic InterfaceObject :
// InterfaceObjectBase in src/Net/InterfaceObject.cpp; cl auto-emits it). Cataloged
// via VTBL(InterfaceObject, 0x005f0748). Placeholder removed.

// ClassWithUnknownVTable63  @ 0x005f0760
// REALIZED as ??_7CNetPlayerListNode@@6B@ (real polymorphic CNetPlayerListNode :
// CNetNodeBase in src/Net/NetSessionNode.cpp; cl auto-emits it). Cataloged via
// VTBL(CNetPlayerListNode, 0x005f0760). Placeholder removed.

// ClassWithUnknownVTable64  @ 0x005f0778
// REALIZED as ??_7CNetSessionNode@@6B@ (real polymorphic CNetSessionNode :
// CNetNodeBase in src/Net/NetSessionNode.cpp; cl auto-emits it). Cataloged via
// VTBL(CNetSessionNode, 0x005f0778). Placeholder removed.

// ClassWithUnknownVTable65  @ 0x005f0790  (5 slots)  refs x3  src:g_faderArrayVtbl
// The vtable of CFaderArray - the CFaderMgr's growable CFader* element array (base
// vtable @ manager +0x10, referenced in include/Gruntz/CFaderMgr.h as g_faderArrayVtbl).
// This is a real MFC CObject-derived array: slots [0]/[3]/[4] are ILT jmp-thunks into
// the CObject base (0x1bef01 GetRuntimeClass, 0x106e / 0x4034 AssertValid / Dump), slot
// [1] is the scalar-deleting dtor (0x17e430) and slot [2] the Serialize override
// (0x17e2a0).  Its ctor + dtor are INLINED into CFaderMgr's ctor (matched, 0x17d8f0) and
// dtor (early-stopped, 0x17d910); a real CObject-derived model needs the MFC base's exact
// 5-slot vtable AND an external ~CFaderArray, and would perturb that matched cluster, so
// it is kept as the g_faderArrayVtbl DATA extern (bound at 0x1f0790) + manual stamp until
// the CFaderMgr cluster is re-attacked with the real MFC base.  Placeholder struct removed.

// ClassWithUnknownVTable66-73 (0x5f07a8..0x5f0890) - REALIZED as the CFader family
// in src/Gruntz/CFader.cpp (+ include/Gruntz/CFader.h), now real C++ polymorphic
// classes with VTBL() catalog bindings (cl auto-emits ??_7 + the implicit vptr
// stamp). The retail slot RVAs formerly documented by these placeholder structs:
//   0x5f07a8 CFader           dtor 0x17e480 / __purecall x2 (slots 1/2, pure) / 0x17e790 / 0x17e7a0
//   0x5f07c0 CFader17e940     dtor 0x17e970 / 0x17ef00 / 0x17f120 / 0x17e790 / 0x17e7a0
//   0x5f07d8 CFader17e940Sub  0x1bef01 / dtor 0x17f310 / 0x17f130 / 0x106e(ILT) / 0x4034(ILT)
//            (this datum is also VTBL-bound as ??_7CSeverusWorkerX@@6B@ via the real
//             ~CSeverusWorkerX 0x17f330 in src/Gruntz/SeverusWorkerDtor.cpp - same class)
//   0x5f07f8 CFaderFlat       dtor 0x17f550 / 0x17f660 / 0x17f950 / 0x17e790 / 0x17e7a0
//   0x5f0810 CFader17f9a0     dtor 0x17f9d0 / 0x17fc60 / 0x17fda0 / 0x17e790 / 0x17e7a0
//   0x5f0848 CFaderSine       dtor 0x17fdd0 / 0x17ff30 / 0x180400 / 0x17e790 / 0x17e7a0
//   0x5f0870 CFader180410     dtor 0x180430 / 0x180640 / 0x1814f0 / 0x181660 / 0x1816a0
//   0x5f0890 CFader1816c0     dtor 0x181700 / 0x181b00 / 0x182900 / 0x17e790 / 0x17e7a0
// Slots 1/2 are the base's two pure virtuals (v1/v2); each subtype overrides them,
// so the slot NAMES are C++-mandated shared names (not FUN_<rva>-nameable).

// ClassWithUnknownVTable74 (@0x5f08c0, 14 slots) / ClassWithUnknownVTable75
// (@0x5f08f8, 15 slots) - REALIZED as the polymorphic CMenuItem / CMenuItem2 in
// include/Gruntz/MenuItem.h + MenuItem2.h (+ VTBL() catalog rows in MenuItem.cpp);
// cl now emits ??_7CMenuItem@@6B@ / ??_7CMenuItem2@@6B@ + the scalar-deleting-dtor
// thunks + the implicit vptr stamps. The former placeholder slot map:
//   0x5f08c0: ??_G 0x184670 / Init 0x185460 / Dispatch0c 0x185510 / Reset 0x184730 /
//             GetWidth 0x185550 / Vf5 0x185520 / Vf6 0x184650 / Detach 0x1855d0 /
//             Notify 0x1855e0 / Place 0x1855f0 / Configure 0x185690 / Release 0x1856c0 /
//             Trigger 0x1856d0 / OnInit 0x184660
//   0x5f08f8: ??_G 0x1847c0 / Init 0x185750 / Dispatch0c 0x185510 / Reset 0x184890 /
//             GetWidth 0x185890 / Vf5 0x185880 / Vf6 0x184780 / Detach 0x1855d0 /
//             Notify 0x1858a0 / Place(draw) 0x1858d0 / Configure 0x185690 /
//             Release 0x1856c0 / Trigger 0x1856d0 / OnInit 0x1847b0 / SetFrame 0x1847a0

#endif // GRUNTZ_UNKNOWN_VTABLES_H
