#!/usr/bin/env python3
"""gruntz.match.fingerprints - per-function source fingerprints for match.status.

gruntz.match.status gates "is this fuzzy% drop a real regression?" on whether the
function's SOURCE changed. Hashing a whole .cpp is too coarse: editing one
function would reset the high-water mark of every sibling in the unit, hiding
collateral regressions. This computes a fingerprint per FUNCTION instead, by
asking clangd for each function's source extent (textDocument/documentSymbol,
hierarchical) and hashing that range's text.

Bridge from the report's MANGLED names to clangd's source-level qualified names:
  * C++ (?...):  llvm-undname -> "Class::Method" -> clangd qualified symbol.
  * C   (_name): strip the cdecl leading underscore -> clangd source name
                 (report `_init_block` -> `init_block`, `__tr_tally` -> `_tr_tally`).
clangd returns BOTH the zlib-style forward-declaration prototypes (single line)
and the real definitions (multi-line body); we keep the multi-line range(s) as
the body (union for genuine overloads) and drop single-line prototypes.

Output is a DERIVED cache, build/clangd/func_fingerprints.tsv (gitignored, not
committed). Regenerated incrementally - only units whose .cpp content hash
changed get re-parsed - so the common edit-one-file rebuild re-runs clangd on a
single TU. `gruntz build` refreshes it before `python -m gruntz.match.status check`.

A function clangd can't resolve (a compiler-generated `scalar deleting dtor', a
parse failure, a name clangd spells differently) simply gets NO entry, and
match_status falls back to the unit's whole-.cpp hash for it - coarser but safe.

  nix develop --command python3 -m gruntz.match.fingerprints [--all] [-v]
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path

REPO = next((p for p in Path(__file__).resolve().parents if (p / "flake.nix").exists()),
            Path(__file__).resolve().parents[3])
MANIFEST = REPO / "config" / "units.toml"
# matched rva->name->unit map, regenerated every build from src @address comments
NAMES = REPO / "build" / "gen" / "symbol_names.csv"
CACHE = REPO / "build" / "clangd" / "func_fingerprints.tsv"


def cpp_hash(source: str) -> str:
    """12-hex sha1 of a unit's whole source file (the unit-level fallback hash)."""
    p = REPO / source
    return hashlib.sha1(p.read_bytes()).hexdigest()[:12] if p.is_file() else "nosrc"


def _sha12(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()[:12]


def load_manifest() -> dict[str, str]:
    from gruntz.core import manifest
    return {u["unit"]: u.get("source", "") for u in manifest.units()}


def unit_mangled() -> dict[str, set]:
    """unit -> {mangled names}, from build/gen/symbol_names.csv (rva,name,unit).
    Empty if it hasn't been generated yet (then nothing is fingerprinted and
    match_status falls back to the whole-.cpp hash)."""
    out: dict[str, set] = {}
    if not NAMES.is_file():
        return out
    for line in NAMES.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("rva,"):
            continue
        cols = line.split(",")
        if len(cols) >= 3:
            out.setdefault(cols[2], set()).add(cols[1])
    return out


# --------------------------------------------------------------------------- #
# cache I/O                                                                    #
# --------------------------------------------------------------------------- #
def load_cache() -> tuple[dict[str, dict], dict[tuple[str, str], str]]:
    """Return (units{unit:{cpp_hash,source}}, funcs{(unit,mangled): src_hash})."""
    units: dict[str, dict] = {}
    funcs: dict[tuple[str, str], str] = {}
    if not CACHE.is_file():
        return units, funcs
    section = None
    for line in CACHE.read_text().splitlines():
        if line.startswith("# [units]"):
            section = "u"
            continue
        if line.startswith("# [functions]"):
            section = "f"
            continue
        if not line or line.startswith("#"):
            continue
        c = line.split("\t")
        if section == "u" and len(c) >= 3:
            units[c[0]] = {"cpp_hash": c[1], "source": c[2]}
        elif section == "f" and len(c) >= 3:
            funcs[(c[0], c[1])] = c[2]
    return units, funcs


def write_cache(units: dict[str, dict], funcs: dict[tuple[str, str], str]) -> None:
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    out = ["# func source fingerprints - generated by gruntz.match.fingerprints.\n",
           "# Derived cache (gitignored). Consumed by gruntz.match.status.\n",
           "# [units]\tunit\tcpp_hash\tsource\n"]
    for u in sorted(units):
        out.append(f"{u}\t{units[u]['cpp_hash']}\t{units[u]['source']}\n")
    out.append("# [functions]\tunit\tmangled\tsrc_hash\n")
    for k in sorted(funcs):
        out.append(f"{k[0]}\t{k[1]}\t{funcs[k]}\n")
    CACHE.write_text("".join(out))


# --------------------------------------------------------------------------- #
# mangled -> qualified source name bridge                                      #
# --------------------------------------------------------------------------- #
def demangle_map(names: set) -> dict[str, str]:
    """C++ mangled -> 'Class::Method' qualified key, via one batched llvm-undname.

    llvm-undname echoes each input then its demangling, blank-line separated:
        ?Open@CFileIO@@QAEHPBDIPAX@Z
        public: int __thiscall CFileIO::Open(char const *, ...)
    """
    cpp = sorted(n for n in names if n.startswith("?"))
    if not cpp:
        return {}
    # NOTE the trailing newline: without it llvm-undname drops the final name.
    proc = subprocess.run(["llvm-undname"], input="\n".join(cpp) + "\n",
                          capture_output=True, text=True)
    out: dict[str, str] = {}
    for block in proc.stdout.split("\n\n"):
        lines = block.splitlines()
        if len(lines) >= 2 and lines[0] in names:
            q = _qualified_of(lines[1])
            if q:
                out[lines[0]] = q
    return out


def _qualified_of(demangled: str) -> str | None:
    """'public: int __thiscall CFileIO::Open(char const *,...)' -> 'CFileIO::Open'."""
    head = demangled.split("(", 1)[0].strip()        # drop the parameter list
    if not head:
        return None
    tok = head.split()[-1]                            # name follows retty/callconv
    if "`" in tok or "'" in tok:                      # compiler-generated -> no source
        return None
    return tok


# --------------------------------------------------------------------------- #
# clangd documentSymbol -> per-function source extent                          #
# --------------------------------------------------------------------------- #
def body_ranges(symbols: list) -> dict[str, list]:
    """Hierarchical DocumentSymbol[] -> {qualified_name: [(startline, endline)]}.

    Keep the multi-line range(s) (the definition body); if a name only has
    single-line ranges (a tiny fn, or just a prototype) keep those. Genuine
    overloads (>1 multi-line def of one name) are unioned.
    """
    acc: dict[str, list] = {}

    def walk(syms, prefix):
        for s in syms:
            k = s.get("kind")
            nm = s.get("name", "")
            if k in (6, 9, 12):  # Method / Constructor / Function (dtor -> Method)
                r = s["range"]
                acc.setdefault(prefix + nm, []).append(
                    (r["start"]["line"], r["end"]["line"]))
            # prefix through Namespace(3)/Class(5)/Interface(11)/Struct(23) nodes
            # so a method clangd lists as 'RegistryHelper::Open' under namespace
            # 'Utils' becomes 'Utils::RegistryHelper::Open' (== llvm-undname).
            child_prefix = prefix + nm + "::" if k in (3, 5, 11, 23) else prefix
            walk(s.get("children") or [], child_prefix)

    walk(symbols, "")
    chosen: dict[str, list] = {}
    for name, ranges in acc.items():
        multi = [r for r in ranges if r[1] > r[0]]
        chosen[name] = sorted(multi or ranges)
    return chosen


def _hash_ranges(lines: list, ranges: list) -> str:
    chunks = ["\n".join(lines[a:b + 1]) for (a, b) in ranges]
    return _sha12("\n--\n".join(chunks))


def _candidates(mangled: str) -> list:
    """Source-name candidates for a C symbol, undoing the cdecl/stdcall decoration:
    a leading `_` (both conventions) and a trailing `@N` (stdcall arg-byte count),
    e.g. `_WwdFile_InflateMainBlock@12` -> `WwdFile_InflateMainBlock`.
    """
    cands = []
    for n in (mangled, mangled.split("@", 1)[0]):
        cands += [n, n[1:] if n.startswith("_") else n, n.lstrip("_")]
    return list(dict.fromkeys(cands))  # dedup, preserve order


# --------------------------------------------------------------------------- #
# regenerate (incremental)                                                     #
# --------------------------------------------------------------------------- #
def regenerate(force_all: bool = False, verbose: bool = False) -> int:
    manifest = load_manifest()
    umang = unit_mangled()
    cache_units, cache_funcs = load_cache()

    cur_cpp: dict[str, str] = {}
    todo: list[str] = []
    for unit, source in manifest.items():
        if not source:
            continue
        cur_cpp[unit] = cpp_hash(source)
        if force_all or cache_units.get(unit, {}).get("cpp_hash") != cur_cpp[unit]:
            todo.append(unit)

    new_units: dict[str, dict] = {}
    new_funcs: dict[tuple[str, str], str] = {}
    # carry over units whose source is unchanged
    for unit, source in manifest.items():
        if unit not in cur_cpp or unit in todo:
            continue
        new_units[unit] = {"cpp_hash": cur_cpp[unit], "source": source}
        for k, v in cache_funcs.items():
            if k[0] == unit:
                new_funcs[k] = v

    if todo:
        # record cpp-hashes for stale units up front, so they're cached even if we
        # don't fingerprint them (and don't get re-parsed every run).
        for unit in todo:
            new_units[unit] = {"cpp_hash": cur_cpp[unit], "source": manifest[unit]}
        allm: set = set()
        for u in todo:
            allm |= umang.get(u, set())

        if allm:  # nothing to map (no build/gen/symbol_names.csv yet) -> skip clangd
            m2q = demangle_map(allm)
            from gruntz.core.clangd_query import Clangd  # heavy; only when there are names to map
            lsp = Clangd()
            try:
                for unit in todo:
                    path = (REPO / manifest[unit]).resolve()
                    if not path.is_file():
                        continue
                    chosen = body_ranges(lsp.document_symbols(path))
                    lines = path.read_text(errors="replace").splitlines()
                    qhash = {q: _hash_ranges(lines, rs) for q, rs in chosen.items()}
                    n = 0
                    for m in umang.get(unit, set()):
                        q = m2q.get(m) if m.startswith("?") else next(
                            (c for c in _candidates(m) if c in qhash), None)
                        if q and q in qhash:
                            new_funcs[(unit, m)] = qhash[q]
                            n += 1
                    if verbose:
                        print(f"  {unit}: {n}/{len(umang.get(unit, set()))} fingerprinted "
                              f"({len(chosen)} defs in clangd)")
            finally:
                lsp.close()

    write_cache(new_units, new_funcs)
    print(f"func fingerprints: {len(new_funcs)} functions  "
          f"({len(todo)} unit(s) re-parsed, {len(new_units) - len(todo)} cached)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--all", action="store_true", help="re-parse every unit (ignore cache)")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()
    return regenerate(force_all=args.all, verbose=args.verbose)


if __name__ == "__main__":
    raise SystemExit(main())
