#ifndef NET_DPLAYSESSIONFLAGS_H
#define NET_DPLAYSESSIONFLAGS_H

#include <Win32.h>

#include <dplay.h>

#ifndef DPSESSION_MIGRATEHOST
#define DPSESSION_MIGRATEHOST 0x00000004
#endif
#ifndef DPSESSION_KEEPALIVE
#define DPSESSION_KEEPALIVE 0x00000040
#endif
#ifndef DPSESSION_OPTIMIZELATENCY
#define DPSESSION_OPTIMIZELATENCY 0x00008000
#endif
#ifndef DPSESSION_DIRECTPLAYPROTOCOL
#define DPSESSION_DIRECTPLAYPROTOCOL 0x00002000
#endif

#endif // NET_DPLAYSESSIONFLAGS_H
