#ifndef GRUNTZ_NET_NETMSGID_H
#define GRUNTZ_NET_NETMSGID_H

#include <Enums.h>

GZ_ENUM_FLAGS_BEGIN(NetPacketFlags, u8)
    NET_PACKET_APPLICATION = 0x80
GZ_ENUM_FLAGS_END(NetPacketFlags, u8)
GZ_ENUM_FLAGS_OPS(NetPacketFlags)

GZ_ENUM_BEGIN(NetMsgId)
    NETMSG_ALL_PLAYERS_READY = 0x3e8,
    NETMSG_PLAYER_LEFT = 0x3ea,
    NETMSG_PLAYER_READY = 0x3ed,
    NETMSG_CHAT_LINE = 0x3f0,
    NETMSG_KEEP_ALIVE = 0x3f6,
    NETMSG_REQUEST_PLAYER_TABLE = 0x3f7,
    NETMSG_PLAYER_TABLE = 0x3f8,
    NETMSG_REGISTER_PLAYER = 0x3f9,
    NETMSG_UPDATE_PLAYER = 0x3fa,
    NETMSG_REMOVED_BY_HOST = 0x3fb,
    NETMSG_VERIFY_CUSTOM_LEVEL = 0x3fc,
    NETMSG_GAME_CLOSED = 0x3fd,
    NETMSG_GAME_FULL = 0x3fe,
    NETMSG_WAIT_DIALOG_REPLY = 0x402,
    NETMSG_OUT_OF_SYNC_REPORT = 0x403,
    NETMSG_OUT_OF_SYNC = 0x404,
    NETMSG_PAUSE = 0x407,
    NETMSG_DROP_TIMEOUT = 0x40c,
    NETMSG_APPLY_PLAYER_DROP = 0x410,
    NETMSG_YOU_WERE_DROPPED = 0x411,
    NETMSG_REQUEST_CONFIG = 0x415,
    NETMSG_CONFIG = 0x416,
    NETMSG_VERSION_CHECK = 0x417,
    NETMSG_VERSION_MISMATCH = 0x418,
    NETMSG_COLOR_REJECTED = 0x419,
    NETMSG_LEVEL_CHECKSUM = 0x41c,
    NETMSG_VERIFY_OK = 0x41d,
    NETMSG_VERIFY_FAILED = 0x41e,
    NETMSG_LATENCY_PROBE = 0x41f,
    NETMSG_LATENCY_REPLY = 0x420,
    NETMSG_ACK_LATENCY_REPORT = 0x421,
    NETMSG_OPTIONS_OPENED = 0x422,
    NETMSG_OPTIONS_CLOSED = 0x423,

    STAT_ALL_PLAYERS_READY = NETMSG_ALL_PLAYERS_READY,
    STAT_CHAT = NETMSG_CHAT_LINE,
    STAT_PLAYER_TABLE = NETMSG_PLAYER_TABLE,
    STAT_REGISTER_PLAYER = NETMSG_REGISTER_PLAYER,
    STAT_PLAYER_UPDATE = NETMSG_UPDATE_PLAYER,
    STAT_REMOVED_BY_HOST = NETMSG_REMOVED_BY_HOST,
    STAT_PAUSE = NETMSG_PAUSE,
    STAT_APPLY_PLAYER_DROP = NETMSG_APPLY_PLAYER_DROP,
    STAT_YOU_WERE_DROPPED = NETMSG_YOU_WERE_DROPPED,
    STAT_REQUEST_CONFIG = NETMSG_REQUEST_CONFIG,
    STAT_CONFIG = NETMSG_CONFIG,
    STAT_VERSION_CHECK = NETMSG_VERSION_CHECK,
    STAT_VERSION_MISMATCH = NETMSG_VERSION_MISMATCH,
    STAT_ACK_LATENCY_REPORT = NETMSG_ACK_LATENCY_REPORT,
    STAT_LEVEL_CHECKSUM = NETMSG_LEVEL_CHECKSUM,
    STAT_VERIFY_AGREE = NETMSG_VERIFY_OK,
    STAT_VERIFY_DISAGREE = NETMSG_VERIFY_FAILED
GZ_ENUM_END(NetMsgId)

#endif
