#ifndef GRUNTZ_NET_NETPACKETLAYOUT_H
#define GRUNTZ_NET_NETPACKETLAYOUT_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(NetPacketLayout)
    NET_COMMAND_WIRE_BUFFER_BYTES = 0x400,
    NET_COMMAND_RECORD_PAYLOAD_BYTES = 0x400,
    NET_RECEIVE_BUFFER_BYTES = 0x800
GZ_ENUM_CONST_END(NetPacketLayout)

#endif // GRUNTZ_NET_NETPACKETLAYOUT_H
