#ifndef NET_NETSLOTSTATE_H
#define NET_NETSLOTSTATE_H

#include <Enums.h>

GZ_ENUM_BEGIN(NetSlotState)
    NETSLOT_EMPTY = 0,
    NETSLOT_INACTIVE = 1,
    NETSLOT_DONE = NETSLOT_INACTIVE,
    NETSLOT_LOCAL = 2,
    NETSLOT_REMOTE = 3,
    NETSLOT_ACTIVE = NETSLOT_REMOTE
GZ_ENUM_END(NetSlotState)

GZ_ENUM_CONST_BEGIN(NetSlotCount)
    NET_SLOT_COUNT = 4
GZ_ENUM_CONST_END(NetSlotCount)

#endif // NET_NETSLOTSTATE_H
