#ifndef GRUNTZ_DDRAWMGR_DDRAWCHILDGROUPFLAGS_H
#define GRUNTZ_DDRAWMGR_DDRAWCHILDGROUPFLAGS_H

#include <Enums.h>
#include <Ints.h>

GZ_ENUM_FLAGS_BEGIN(DDrawChildGroupFlags, i32)
    DDRAW_CHILD_GROUP_FLAG_DEBUG_HIT_RECT = 0x00010000,
    DDRAW_CHILD_GROUP_FLAG_DEBUG_ATTACK_RECT = 0x00020000,
    DDRAW_CHILD_GROUP_FLAG_DEBUG_MOVE_RECT = 0x00040000,
    DDRAW_CHILD_GROUP_FLAG_DEBUG_ORIGIN = 0x00100000,
    DDRAW_CHILD_GROUP_FLAG_DEBUG_SORT_KEY = 0x00200000,
    DDRAW_CHILD_GROUP_FLAG_DEBUG_SURFACE_MEMORY = 0x01000000
GZ_ENUM_FLAGS_END(DDrawChildGroupFlags, i32)
GZ_ENUM_FLAGS_OPS(DDrawChildGroupFlags)

#endif // GRUNTZ_DDRAWMGR_DDRAWCHILDGROUPFLAGS_H
