#ifndef GRUNTZ_DDRAWMGR_LOGICRECORDFLAGS_H
#define GRUNTZ_DDRAWMGR_LOGICRECORDFLAGS_H

#include <Enums.h>
#include <Ints.h>

GZ_ENUM_FLAGS_BEGIN(LogicRecordFlags, i32)
    LOGIC_RECORD_FLAG_LARGE_ACTIVE_REGION = 0x1,
    LOGIC_RECORD_FLAG_SMALL_ACTIVE_REGION = 0x2,
    LOGIC_RECORD_FLAG_KEEP_ACTIVE = 0x4
GZ_ENUM_FLAGS_END(LogicRecordFlags, i32)
GZ_ENUM_FLAGS_OPS(LogicRecordFlags)

#endif // GRUNTZ_DDRAWMGR_LOGICRECORDFLAGS_H
