#ifndef DDRAWMGR_PALETTESIZE_H
#define DDRAWMGR_PALETTESIZE_H

#include <Enums.h>

GZ_ENUM_CONST_BEGIN(PaletteSize)
    PALETTE_ENTRY_COUNT = 256,
    PALETTE_INDEX_BITS = 8,
    PALETTE_RGB_BYTE_COUNT = PALETTE_ENTRY_COUNT * 3,
    LOGICAL_PALETTE_VERSION = 0x300
GZ_ENUM_CONST_END(PaletteSize)

#endif // DDRAWMGR_PALETTESIZE_H
