#ifndef DDRAWMGR_RASTERROWORDER_H
#define DDRAWMGR_RASTERROWORDER_H

#include <Enums.h>

GZ_ENUM_BEGIN(RasterRowOrder)
    RASTER_ROWS_TOP_DOWN = 1,
    RASTER_ROWS_BOTTOM_UP = 2
GZ_ENUM_END(RasterRowOrder)

#endif // DDRAWMGR_RASTERROWORDER_H
